/**
 * Kid avatar catalog (DiceBear · avataaars set generated by scripts/gen-avatars.mjs).
 * The chosen one is stored on `profile.avatarId` and shown as the profile photo.
 */
export const AVATAR_IDS = Array.from({ length: 12 }, (_, i) => `avatar-${String(i + 1).padStart(2, '0')}`);

export const DEFAULT_AVATAR_ID = 'avatar-01';

/** True for the new picture avatars (avatar-01..12), false for legacy ids. */
export function isPictureAvatar(id) {
  return typeof id === 'string' && /^avatar-\d{2}$/.test(id) && AVATAR_IDS.includes(id);
}

/**
 * Resolve an avatarId to an asset path (relative — wrap with assetUrl()).
 * Legacy ids (e.g. 'avatar-unicorn') fall back to the duo mascot.
 */
export function avatarSrc(id) {
  if (isPictureAvatar(id)) return `assets/characters/avatars/${id}.svg`;
  return 'assets/characters/mascot-pair.svg';
}
