import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade5Modules = [
  createModule({
    id: 'math-g5-large-numbers',
    subjectId: 'mathematics',
    gradeId: 'P5',
    domainId: 'place-value',
    domainLabel: 'Grands nombres',
    title: 'Lire et ecrire les grands nombres',
    summary: 'Manipuler des nombres jusqu\'a 1 000 000.',
    goal: 'Maitriser la numeration en millions.',
    demo: 'Demo sur la decomposition des grands nombres.',
    guidedActivityIds: ['generated-place-value-p5'],
    independentActivityIds: ['generated-place-value-p5'],
    challengeActivityId: 'generated-place-value-p5',
    examActivityId: 'generated-place-value-p5',
    missionTitle: 'Mission Grands Nombres P5',
    levelTitles: { 'generated-place-value-p5': 'Nombres jusqu\'a 1 million' },
  }),
  createModule({
    id: 'math-g5-decimals',
    subjectId: 'mathematics',
    gradeId: 'P5',
    domainId: 'decimals',
    domainLabel: 'Nombres decimaux',
    title: 'Les nombres decimaux',
    summary: 'Calculer et comprendre les nombres a virgule.',
    goal: 'Etendre la numeration au dela de l\'unite.',
    demo: 'Demo sur les dixiemes et centiemes.',
    guidedActivityIds: ['generated-decimals-p5'],
    independentActivityIds: ['generated-decimals-p5'],
    challengeActivityId: 'generated-decimals-p5',
    examActivityId: 'generated-decimals-p5',
    missionTitle: 'Mission Decimaux P5',
    levelTitles: { 'generated-decimals-p5': 'Dixiemes et centiemes' },
  }),
  createModule({
    id: 'math-g5-fractions-percentages',
    subjectId: 'mathematics',
    gradeId: 'P5',
    domainId: 'fractions-percentages',
    domainLabel: 'Fractions et Pourcentages',
    title: 'Fractions et pourcentages',
    summary: 'Additionner des fractions et calculer des pourcentages simples.',
    goal: 'Relier fractions, decimaux et pourcentages.',
    demo: 'Demo 50% = 1/2 = 0,5.',
    guidedActivityIds: ['generated-fractions-p5'],
    independentActivityIds: ['generated-percentages-p5'],
    challengeActivityId: 'generated-fractions-p5',
    examActivityId: 'generated-percentages-p5',
    missionTitle: 'Mission Fractions P5',
    levelTitles: {
      'generated-fractions-p5': 'Operations sur fractions',
      'generated-percentages-p5': 'Pourcentages 10%, 25%, 50%',
    },
  }),
  createModule({
    id: 'math-g5-geometry-area',
    subjectId: 'mathematics',
    gradeId: 'P5',
    domainId: 'geometry',
    domainLabel: 'Geometrie',
    title: 'Aires et figures',
    summary: 'Calculer l\'aire de figures simples.',
    goal: 'Distinguer perimetre et aire.',
    demo: 'Demo aire = longueur x largeur.',
    guidedActivityIds: ['generated-geometry-p5'],
    independentActivityIds: ['generated-geometry-p5'],
    challengeActivityId: 'generated-geometry-p5',
    examActivityId: 'generated-geometry-p5',
    missionTitle: 'Mission Geometrie P5',
    levelTitles: { 'generated-geometry-p5': 'Calcul d\'aires' },
  }),
];
