import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade6Modules = [
  createModule({
    id: 'math-g6-fractions-advanced',
    subjectId: 'mathematics',
    gradeId: 'P6',
    domainId: 'fractions',
    domainLabel: 'Fractions avancees',
    title: 'Comparer et simplifier les fractions',
    summary: 'Simplifier, ordonner et comparer des fractions avec denominateurs differents.',
    goal: 'Maitriser les fractions equivalentes.',
    demo: 'Demo simplification et PGCD.',
    guidedActivityIds: ['generated-fractions-p6'],
    independentActivityIds: ['generated-fractions-p6'],
    challengeActivityId: 'generated-fractions-p6',
    examActivityId: 'generated-fractions-p6',
    missionTitle: 'Mission Fractions Avancees P6',
    levelTitles: { 'generated-fractions-p6': 'Fractions et equivalences' },
  }),
  createModule({
    id: 'math-g6-percentages',
    subjectId: 'mathematics',
    gradeId: 'P6',
    domainId: 'percentages',
    domainLabel: 'Pourcentages',
    title: 'Problemes avec pourcentages',
    summary: 'Calculer des remises, des augmentations et des proportions.',
    goal: 'Appliquer les pourcentages dans la vie quotidienne.',
    demo: 'Demo: -20% sur un prix.',
    guidedActivityIds: ['generated-percentages-p6'],
    independentActivityIds: ['generated-percentages-p6'],
    challengeActivityId: 'generated-percentages-p6',
    examActivityId: 'generated-percentages-p6',
    missionTitle: 'Mission Pourcentages P6',
    levelTitles: { 'generated-percentages-p6': 'Pourcentages appliques' },
  }),
  createModule({
    id: 'math-g6-geometry-volume',
    subjectId: 'mathematics',
    gradeId: 'P6',
    domainId: 'geometry',
    domainLabel: 'Volumes',
    title: 'Volumes et solides',
    summary: 'Calculer le volume de cubes, paves et cylindres simples.',
    goal: 'Passer de la surface au volume.',
    demo: 'Demo volume = L x l x h.',
    guidedActivityIds: ['generated-geometry-p6'],
    independentActivityIds: ['generated-geometry-p6'],
    challengeActivityId: 'generated-geometry-p6',
    examActivityId: 'generated-geometry-p6',
    missionTitle: 'Mission Volumes P6',
    levelTitles: { 'generated-geometry-p6': 'Volumes et solides' },
  }),
  createModule({
    id: 'math-g6-mixed',
    subjectId: 'mathematics',
    gradeId: 'P6',
    domainId: 'mixed-operations',
    domainLabel: 'Operations mixtes',
    title: 'Grand defi final',
    summary: 'Combiner toutes les operations dans des defis complexes.',
    goal: 'Respecter l\'ordre des operations.',
    demo: 'Demo calculs enchaenes.',
    guidedActivityIds: ['generated-mixed-operations-p6'],
    independentActivityIds: ['generated-statistics-p6'],
    challengeActivityId: 'generated-statistics-p6',
    examActivityId: 'generated-mixed-operations-p6',
    missionTitle: 'Mission Grand Defi P6',
    levelTitles: {
      'generated-mixed-operations-p6': 'Operations enchainees',
      'generated-statistics-p6': 'Statistiques et graphiques',
    },
  }),
];
