// ── FILL-IN-THE-BLANK (Univers 1) ─────────────────────────────────────────
// All 4 options are the SAME type. Correct option is contextually fitting.
export const MOT_MANQUANT = [
  // Géographie/Culture générale
  { sentence: 'La ___ est un pays qui se situe en Asie.', answer: 'Chine', options: ['Chine','France','Belgique','Espagne'], type: 'nom_propre' },
  { sentence: 'Bruxelles est la ___ de la Belgique.', answer: 'capitale', options: ['capitale','ville','region','quartier'], type: 'nom_commun' },
  { sentence: 'Le ___ est le roi des animaux.', answer: 'lion', options: ['lion','chien','lapin','oiseau'], type: 'nom_commun' },
  { sentence: 'L\'___ est l\'instrument de la musique classique.', answer: 'orchestre', options: ['orchestre','accordeon','guitare','batterie'], type: 'nom_commun' },
  // Nature
  { sentence: 'Au printemps, les ___ fleurissent dans les jardins.', answer: 'fleurs', options: ['fleurs','arbres','rochers','nuages'], type: 'nom_commun' },
  { sentence: 'En hiver, la ___ tombe sur les toits.', answer: 'neige', options: ['neige','pluie','grele','rosee'], type: 'nom_commun' },
  { sentence: 'Le soleil se ___ a l\'ouest chaque soir.', answer: 'couche', options: ['couche','leve','cache','montre'], type: 'verbe' },
  { sentence: 'Les abeilles ___ le miel dans la ruche.', answer: 'fabriquent', options: ['fabriquent','mangent','cherchent','trouvent'], type: 'verbe' },
  { sentence: 'La ___ est un insecte qui vole de fleur en fleur.', answer: 'abeille', options: ['abeille','araignee','fourmi','coccinelle'], type: 'nom_commun' },
  { sentence: 'Les ecureuils ___ des noisettes pour l\'hiver.', answer: 'cachent', options: ['cachent','mangent','vendent','donnent'], type: 'verbe' },
  // Ecole
  { sentence: 'L\'institutrice ___ les exercices au tableau.', answer: 'ecrit', options: ['ecrit','mange','court','chante'], type: 'verbe' },
  { sentence: 'Les eleves ___ attentivement la lecon.', answer: 'ecoutent', options: ['ecoutent','oublient','lancent','cassent'], type: 'verbe' },
  { sentence: 'Le ___ contient les livres et les cahiers.', answer: 'cartable', options: ['cartable','bureau','tableau','couloir'], type: 'nom_commun' },
  { sentence: 'La recreation ___ a 10 heures du matin.', answer: 'commence', options: ['commence','finit','dure','passe'], type: 'verbe' },
  // Animaux
  { sentence: 'Le ___ aboie quand un etranger arrive.', answer: 'chien', options: ['chien','chat','lapin','hamster'], type: 'nom_commun' },
  { sentence: 'La grenouille ___ dans la mare.', answer: 'saute', options: ['saute','vole','nage','dort'], type: 'verbe' },
  { sentence: 'L\'___ barrit dans la savane.', answer: 'elephant', options: ['elephant','hippopotame','rhinoceros','gorille'], type: 'nom_commun' },
  { sentence: 'Les oiseaux ___ vers le sud en automne.', answer: 'migrent', options: ['migrent','restent','dorment','chantent'], type: 'verbe' },
  // Famille
  { sentence: 'Ma ___ prepare un delicieux gateau au chocolat.', answer: 'grand-mere', options: ['grand-mere','voisine','institutrice','amie'], type: 'nom_commun' },
  { sentence: 'Mon ___ lit le journal le dimanche matin.', answer: 'papa', options: ['papa','frere','cousin','oncle'], type: 'nom_commun' },
  // Adjectifs
  { sentence: 'Lena porte une robe ___ pour la fete.', answer: 'belle', options: ['belle','laide','sale','mouilee'], type: 'adjectif' },
  { sentence: 'Le ___ chat dort sur le canape.', answer: 'gros', options: ['gros','petit','maigre','jeune'], type: 'adjectif' },
  { sentence: 'L\'eau de la mer est ___ en ete.', answer: 'chaude', options: ['chaude','froide','tiede','glacee'], type: 'adjectif' },
  { sentence: 'Les montagnes sont tres ___ en hiver.', answer: 'enneigees', options: ['enneigees','fleuries','seches','vertes'], type: 'adjectif' },
  // Contes
  { sentence: 'Le Petit Chaperon ___ apporte une galette a sa grand-mere.', answer: 'Rouge', options: ['Rouge','Bleu','Vert','Noir'], type: 'nom_propre' },
  { sentence: 'Cendrillon perdit son ___ de verre a minuit.', answer: 'soulier', options: ['soulier','chapeau','manteau','bijou'], type: 'nom_commun' },
  { sentence: 'Les trois ___ construisent leurs maisons.', answer: 'cochons', options: ['cochons','ours','loups','renards'], type: 'nom_commun' },
  { sentence: 'Blanche-Neige mange une pomme ___.', answer: 'empoisonnee', options: ['empoisonnee','sucree','rouge','verte'], type: 'adjectif' },
  // Saisons
  { sentence: 'En ___, les feuilles tombent des arbres.', answer: 'automne', options: ['automne','ete','printemps','hiver'], type: 'nom_commun' },
  { sentence: 'Les enfants font des bonhommes de ___ en hiver.', answer: 'neige', options: ['neige','sable','boue','glace'], type: 'nom_commun' },
  // Nourriture
  { sentence: 'La boulangere ___ le pain dans le four.', answer: 'cuit', options: ['cuit','vend','mange','achete'], type: 'verbe' },
  { sentence: 'Les enfants ___ du jus d\'orange au petit-dejeuner.', answer: 'boivent', options: ['boivent','mangent','cuisinent','versent'], type: 'verbe' },
  { sentence: 'Le ___ est fait avec du lait de vache.', answer: 'fromage', options: ['fromage','beurre','yaourt','creme'], type: 'nom_commun' },
  // Sports
  { sentence: 'Les footballeurs ___ le ballon dans le but.', answer: 'envoient', options: ['envoient','portent','lancent','tapent'], type: 'verbe' },
  { sentence: 'La nageuse ___ vite dans la piscine.', answer: 'avance', options: ['avance','court','vole','saute'], type: 'verbe' },
  // Divers
  { sentence: 'La ___ sonne a 8 heures du matin.', answer: 'cloche', options: ['cloche','sirene','trompette','sonnette'], type: 'nom_commun' },
  { sentence: 'Les pompiers ___ les incendies.', answer: 'eteignent', options: ['eteignent','allument','regardent','signalent'], type: 'verbe' },
  { sentence: 'Le medecin ___ les malades a l\'hopital.', answer: 'soigne', options: ['soigne','voit','appelle','cherche'], type: 'verbe' },
  { sentence: 'Les astronautes ___ dans l\'espace.', answer: 'voyagent', options: ['voyagent','nagent','courent','dorment'], type: 'verbe' },
  { sentence: 'La ___ pousse tres haut vers le ciel.', answer: 'fusee', options: ['fusee','avion','montgolfiere','helicoptere'], type: 'nom_commun' },
  // More sentences
  { sentence: 'Le ___ jaune tourne autour de la Terre.', answer: 'soleil', options: ['soleil','lune','etoile','nuage'], type: 'nom_commun' },
  { sentence: 'Les enfants ___ des cadeaux a Noel.', answer: 'recoivent', options: ['recoivent','ouvrent','cachent','cherchent'], type: 'verbe' },
  { sentence: 'La bibliotheque est pleine de ___.', answer: 'livres', options: ['livres','journaux','revues','albums'], type: 'nom_commun' },
  { sentence: 'Mon chien ___ sa queue quand il est content.', answer: 'remue', options: ['remue','cache','montre','leve'], type: 'verbe' },
  { sentence: 'Le ___ siffle dans la nuit.', answer: 'vent', options: ['vent','oiseau','train','cricket'], type: 'nom_commun' },
  { sentence: 'La riviere ___ vers la mer.', answer: 'coule', options: ['coule','monte','tombe','jaillit'], type: 'verbe' },
  { sentence: 'Les papillons sont des insectes tres ___.', answer: 'colores', options: ['colores','rapides','lourds','forts'], type: 'adjectif' },
  { sentence: 'La girafe est l\'animal le plus ___ du monde.', answer: 'grand', options: ['grand','gros','lourd','rapide'], type: 'adjectif' },
  { sentence: 'Le boulanger se ___ tres tot le matin.', answer: 'leve', options: ['leve','couche','prepare','lave'], type: 'verbe' },
  { sentence: 'Les etoiles ___ dans le ciel nocturne.', answer: 'brillent', options: ['brillent','tombent','montent','disparaissent'], type: 'verbe' },
  { sentence: 'Le lapin ___ tres vite dans le pre.', answer: 'court', options: ['court','saute','nage','vole'], type: 'verbe' },
  { sentence: 'Ma soeur ___ la guitare depuis deux ans.', answer: 'joue', options: ['joue','apprend','chante','ecoute'], type: 'verbe' },
  { sentence: 'Le chateau fort a de hautes ___.', answer: 'tours', options: ['tours','murailles','portes','fenetres'], type: 'nom_commun' },
  { sentence: 'Les fourmis ___ en colonne vers leur fourmiliere.', answer: 'marchent', options: ['marchent','courent','nagent','sautent'], type: 'verbe' },
  { sentence: 'La neige est ___ et froide.', answer: 'blanche', options: ['blanche','grise','jaune','verte'], type: 'adjectif' },
  { sentence: 'Les poissons ___ dans les oceans et les rivieres.', answer: 'vivent', options: ['vivent','nagent','sautent','dorment'], type: 'verbe' },
  { sentence: 'Le fermier ___ ses vaches chaque matin.', answer: 'trait', options: ['trait','nourrit','soigne','appelle'], type: 'verbe' },
  { sentence: 'Le ___ est un oiseau qui chante la nuit.', answer: 'rossignol', options: ['rossignol','corbeau','pigeon','moineau'], type: 'nom_commun' },
  { sentence: 'Les ___ de la foret sont tres hauts.', answer: 'arbres', options: ['arbres','buissons','champignons','fleurs'], type: 'nom_commun' },
  { sentence: 'Lena ___ son livre avant de dormir.', answer: 'lit', options: ['lit','ferme','pose','range'], type: 'verbe' },
  { sentence: 'Le ciel est ___ apres la pluie.', answer: 'bleu', options: ['bleu','gris','sombre','nuageux'], type: 'adjectif' },
  { sentence: 'Les enfants ___ des chansons en choeur.', answer: 'chantent', options: ['chantent','crient','murmurent','repetent'], type: 'verbe' },
  { sentence: 'Mon ___ prefere est le chocolat.', answer: 'dessert', options: ['dessert','repas','gouter','petit-dejeuner'], type: 'nom_commun' },
  { sentence: 'La mer est ___ en temps de tempete.', answer: 'dechainee', options: ['dechainee','calme','froide','bleue'], type: 'adjectif' },
  { sentence: 'Le jardinier ___ les mauvaises herbes.', answer: 'arrache', options: ['arrache','plante','coupe','ramasse'], type: 'verbe' },
  { sentence: 'Les pingouins ___ dans les mers froides.', answer: 'nagent', options: ['nagent','vivent','chassent','dorment'], type: 'verbe' },
  { sentence: 'La ___ apporte les lettres chaque matin.', answer: 'factrice', options: ['factrice','boulangere','infirmiere','institutrice'], type: 'nom_commun' },
  { sentence: 'Mon livre ___ est "Le Petit Prince".', answer: 'prefere', options: ['prefere','nouveau','vieux','grand'], type: 'adjectif' },
  { sentence: 'Le train ___ a grande vitesse sur les rails.', answer: 'roule', options: ['roule','vole','glisse','avance'], type: 'verbe' },
  { sentence: 'Les Vikings ___ les mers du Nord.', answer: 'parcouraient', options: ['parcouraient','traversaient','naviguaient','exploraient'], type: 'verbe' },
  { sentence: 'La ___ hulule dans la nuit.', answer: 'chouette', options: ['chouette','chauve-souris','grenouille','cigale'], type: 'nom_commun' },
  { sentence: 'En automne, les feuilles ___ de couleur.', answer: 'changent', options: ['changent','tombent','poussent','brillent'], type: 'verbe' },
  { sentence: 'Le soleil ___ derriere les nuages.', answer: 'disparait', options: ['disparait','brille','monte','chauffe'], type: 'verbe' },
  { sentence: 'Les enfants ___ des chateaux de sable sur la plage.', answer: 'construisent', options: ['construisent','detruisent','regardent','dessinent'], type: 'verbe' },
  { sentence: 'Mon ecole est un ___ batiment rouge.', answer: 'grand', options: ['grand','petit','vieux','nouveau'], type: 'adjectif' },
  { sentence: 'Les chats ___ dans les arbres.', answer: 'grimpent', options: ['grimpent','sautent','courent','dorment'], type: 'verbe' },
  { sentence: 'La lune ___ la nuit sur la terre.', answer: 'eclaire', options: ['eclaire','chauffe','regarde','guide'], type: 'verbe' },
  { sentence: 'Les ___ construisent des barrages dans les rivieres.', answer: 'castors', options: ['castors','loutres','grenouilles','poissons'], type: 'nom_commun' },
  { sentence: 'Le ___ est le roi de la foret.', answer: 'cerf', options: ['cerf','loup','renard','sanglier'], type: 'nom_commun' },
  { sentence: 'Emma ___ son anniversaire avec ses amis.', answer: 'fete', options: ['fete','passe','oublie','prepare'], type: 'verbe' },

  // ── DIFFICILE : homophones + accords + conjugaisons complexes ──
  { sentence: 'Le chien ___ a son maitre depuis la fenetre.', answer: 'obeit', options: ['obeit','appartient','ressemble','repond'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Il ___ beaucoup de courage pour traverser ce pont.', answer: 'faut', options: ['faut','fait','faisait','fallait'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Les eleves ont ___ leurs cahiers de brouillon.', answer: 'rempli', options: ['rempli','remplis','remplies','remplir'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'La chaleur ___ sur la ville comme une couverture.', answer: 'pesait', options: ['pesait','tombait','planait','reposait'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Mon grand-pere ___ toujours les memes histoires.', answer: 'raconte', options: ['raconte','repete','rappelle','retient'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Les voyageurs ___ leurs valises avec soin.', answer: 'preparent', options: ['preparent','remplissent','ferment','glissent'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'La foret ___ sous le poids de la neige.', answer: 'ploie', options: ['ploie','plie','tombe','gémit'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Cette histoire ___ a une belle lecon de vie.', answer: 'aboutit', options: ['aboutit','conduit','mene','finit'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Le capitaine ___ ses matelots d\'un regard severe.', answer: 'surveille', options: ['surveille','observe','regarde','examine'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'L\'odeur du pain ___ tout le quartier.', answer: 'envahit', options: ['envahit','parfume','emplit','traverse'], type: 'verbe', difficulty: 'difficile' },
  // Homophones comme distracteurs
  { sentence: 'Le maitre ___ une question difficile au tableau.', answer: 'pose', options: ['pose','pause','paux','pauze'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Ma tante ___ arrive hier soir de voyage.', answer: 'est', options: ['est','et','ai','a'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Le renard ___ cache derriere un rocher.', answer: 's\'est', options: ['s\'est','c\'est','sait','ces'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Les enfants ___ bien sages ce matin.', answer: 'sont', options: ['sont','son','s\'ont','son\'t'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'Le chat mange ___ croquettes avec appetit.', answer: 'ses', options: ['ses','ces','c\'est','s\'est'], type: 'adjectif', difficulty: 'difficile' },
  { sentence: 'Je ne sais pas ___ il va venir.', answer: 'si', options: ['si','s\'il','sy','ci'], type: 'mot_outil', difficulty: 'difficile' },
  { sentence: 'Tu peux prendre ce livre ___ tu veux.', answer: 'ou', options: ['ou','ou','ou bien','ni'], type: 'mot_outil', difficulty: 'difficile' },
  { sentence: 'Il ___ tres froid dehors ce matin.', answer: 'fait', options: ['fait','fais','faisait','fera'], type: 'verbe', difficulty: 'difficile' },
  // Adjectifs difficiles (accords)
  { sentence: 'Les feuilles mortes sont ___ et fragiles.', answer: 'seches', options: ['seches','secs','sec','seche'], type: 'adjectif', difficulty: 'difficile' },
  { sentence: 'La tornade ___ a tout detruit sur son passage.', answer: 'destructrice', options: ['destructrice','destructeur','destructrice','destruite'], type: 'adjectif', difficulty: 'difficile' },
  { sentence: 'Les athletes ___ ont gagne la medaille d\'or.', answer: 'belges', options: ['belges','belge','belgique','belgo'], type: 'adjectif', difficulty: 'difficile' },
  { sentence: 'Une reponse ___ s\'impose dans cette situation.', answer: 'precise', options: ['precise','precis','precises','precisee'], type: 'adjectif', difficulty: 'difficile' },
  // Vocabulaire recherche
  { sentence: 'Le ___ du poème evoque la melancolie de l\'automne.', answer: 'rythme', options: ['rythme','ton','style','sens'], type: 'nom_commun', difficulty: 'difficile' },
  { sentence: 'L\'___ de la foret attire de nombreux touristes.', answer: 'etendue', options: ['etendue','espace','grandeur','superficie'], type: 'nom_commun', difficulty: 'difficile' },
  { sentence: 'Le ___ du soleil rechauffait les pierres du chateau.', answer: 'rayonnement', options: ['rayonnement','eclat','reflet','brillance'], type: 'nom_commun', difficulty: 'difficile' },
  { sentence: 'La ___ de l\'eau en vapeur s\'appelle l\'evaporation.', answer: 'transformation', options: ['transformation','conversion','changement','passage'], type: 'nom_commun', difficulty: 'difficile' },
  { sentence: 'Les ___ du vent faisaient danser les branches.', answer: 'rafales', options: ['rafales','souffles','bourrasques','courants'], type: 'nom_commun', difficulty: 'difficile' },
  { sentence: 'Le vieux sage ___ ses connaissances aux jeunes villageois.', answer: 'transmettait', options: ['transmettait','enseignait','expliquait','racontait'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'La ___ de cette legende remonte au Moyen Age.', answer: 'origine', options: ['origine','naissance','creation','invention'], type: 'nom_commun', difficulty: 'difficile' },
  { sentence: 'Les navigateurs ___ les etoiles pour s\'orienter.', answer: 'observaient', options: ['observaient','contemplaient','regardaient','suivaient'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'L\'enfant ___ avec curiosite le vieux grimoire.', answer: 'feuilleta', options: ['feuilleta','parcourut','lut','consulta'], type: 'verbe', difficulty: 'difficile' },
  { sentence: 'La ___ des oiseaux au printemps annonce le beau temps.', answer: 'migration', options: ['migration','arrivee','retour','presence'], type: 'nom_commun', difficulty: 'difficile' },
];

// ── MOTS CACHES (Univers 2) ──────────────────────────────────────────────
export const MOTS_CACHES = [
  { word: 'abeille', hint: 'Elle fait du miel et vole de fleur en fleur.', emoji: '🐝', letters: 7 },
  { word: 'ecureuil', hint: 'Il grimpe aux arbres et mange des noisettes.', emoji: '🐿️', letters: 8 },
  { word: 'jonquille', hint: 'Une fleur jaune qui pousse au printemps.', emoji: '🌼', letters: 9 },
  { word: 'grenouille', hint: 'Elle saute et coasse pres des marres.', emoji: '🐸', letters: 10 },
  { word: 'citrouille', hint: 'Un legume orange de Halloween.', emoji: '🎃', letters: 9 },
  { word: 'papillon', hint: 'Un insecte qui vole avec ses ailes colorees.', emoji: '🦋', letters: 8 },
  { word: 'crocodile', hint: 'Un reptile avec des grandes dents.', emoji: '🐊', letters: 9 },
  { word: 'hibou', hint: 'Un oiseau de nuit qui tourne la tete.', emoji: '🦉', letters: 5 },
  { word: 'chameau', hint: 'Un animal du desert avec une bosse.', emoji: '🐪', letters: 7 },
  { word: 'hippopotame', hint: 'Un gros animal qui vit dans l\'eau en Afrique.', emoji: '🦛', letters: 11 },
  { word: 'arc-en-ciel', hint: 'De belles couleurs dans le ciel apres la pluie.', emoji: '🌈', letters: 10 },
  { word: 'parapluie', hint: 'On l\'ouvre quand il pleut.', emoji: '☂️', letters: 9 },
  { word: 'chocolat', hint: 'Un dessert delicieux fait avec du cacao.', emoji: '🍫', letters: 8 },
  { word: 'bibliotheque', hint: 'Un endroit plein de livres.', emoji: '📚', letters: 12 },
  { word: 'anniversaire', hint: 'Le jour ou l\'on est ne. On souffle des bougies.', emoji: '🎂', letters: 12 },
  { word: 'astronaute', hint: 'Il voyage dans l\'espace a bord d\'une fusee.', emoji: '👨‍🚀', letters: 10 },
  { word: 'dinosaure', hint: 'Un tres grand animal disparu il y a longtemps.', emoji: '🦕', letters: 9 },
  { word: 'baleine', hint: 'Le plus grand animal de la mer.', emoji: '🐋', letters: 7 },
  { word: 'perroquet', hint: 'Un oiseau tropical qui repete les mots.', emoji: '🦜', letters: 9 },
  { word: 'escalier', hint: 'On monte dessus pour aller a l\'etage.', emoji: '🪜', letters: 8 },
  { word: 'ambulance', hint: 'Un vehicule rapide pour transporter les malades.', emoji: '🚑', letters: 9 },
  { word: 'tigre', hint: 'Un grand chat sauvage avec des rayures.', emoji: '🐯', letters: 5 },
  { word: 'tortue', hint: 'Un animal lent avec une carapace.', emoji: '🐢', letters: 6 },
  { word: 'champignon', hint: 'Il pousse dans la foret apres la pluie.', emoji: '🍄', letters: 10 },
  { word: 'chouette', hint: 'Un oiseau de nuit qui hulule.', emoji: '🦉', letters: 8 },
  { word: 'maternelle', hint: 'La premiere ecole pour les petits enfants.', emoji: '🏫', letters: 10 },
  { word: 'fontaine', hint: 'De l\'eau qui jaillit dans une place.', emoji: '⛲', letters: 8 },
  { word: 'trampoline', hint: 'On saute dessus pour s\'amuser.', emoji: '🤸', letters: 10 },
  { word: 'tournesol', hint: 'Une grande fleur jaune qui suit le soleil.', emoji: '🌻', letters: 9 },
  { word: 'citronnelle', hint: 'Une plante qui repousse les moustiques.', emoji: '🌿', letters: 11 },

  // ── DIFFICILE : mots longs + indices vagues ──
  { word: 'chrysantheme', hint: 'Une fleur souvent deposee au cimetiere.', emoji: '🌸', letters: 12, difficulty: 'difficile' },
  { word: 'prestidigitateur', hint: 'Il fait des tours de magie avec ses mains.', emoji: '🎩', letters: 16, difficulty: 'difficile' },
  { word: 'encyclopedie', hint: 'Un grand livre qui contient tout le savoir.', emoji: '📖', letters: 12, difficulty: 'difficile' },
  { word: 'extraterrestre', hint: 'Il vient d\'une autre planete.', emoji: '👽', letters: 14, difficulty: 'difficile' },
  { word: 'thermometre', hint: 'Il mesure la temperature.', emoji: '🌡️', letters: 11, difficulty: 'difficile' },
  { word: 'photographe', hint: 'Il prend des photos avec son appareil.', emoji: '📷', letters: 11, difficulty: 'difficile' },
  { word: 'kaleidoscope', hint: 'Un tube magique avec des formes colorees.', emoji: '🔭', letters: 12, difficulty: 'difficile' },
  { word: 'imperméable', hint: 'Un vetement qu\'on porte sous la pluie.', emoji: '🧥', letters: 11, difficulty: 'difficile' },
  { word: 'microbiologiste', hint: 'Un scientifique qui etudie les bacteries.', emoji: '🔬', letters: 15, difficulty: 'difficile' },
  { word: 'metamorphose', hint: 'La transformation d\'une chenille en papillon.', emoji: '🦋', letters: 12, difficulty: 'difficile' },
  { word: 'paleontologue', hint: 'Il etudie les fossiles et les dinosaures.', emoji: '🦕', letters: 13, difficulty: 'difficile' },
  { word: 'velocipede', hint: 'L\'ancetre de la bicyclette.', emoji: '🚲', letters: 10, difficulty: 'difficile' },
  { word: 'philanthrope', hint: 'Quelqu\'un qui aime les autres et aide les pauvres.', emoji: '❤️', letters: 12, difficulty: 'difficile' },
  { word: 'constellation', hint: 'Un groupe d\'etoiles qui forment une figure.', emoji: '⭐', letters: 13, difficulty: 'difficile' },
  { word: 'volcanologie', hint: 'La science qui etudie les volcans.', emoji: '🌋', letters: 12, difficulty: 'difficile' },
];

// ── PHRASE RECONSTRUCTION (Univers 4) ─────────────────────────────────────
export const RECONSTRUCTIONS = [
  { words: ['L\'','abeille','se','pose','sur','la','jonquille','.'], answer: 'L\'abeille se pose sur la jonquille.' },
  { words: ['Le','chat','dort','sur','le','canape','.'], answer: 'Le chat dort sur le canape.' },
  { words: ['Lena','mange','une','pomme','rouge','.'], answer: 'Lena mange une pomme rouge.' },
  { words: ['Les','enfants','jouent','dans','le','jardin','.'], answer: 'Les enfants jouent dans le jardin.' },
  { words: ['Mon','chien','court','tres','vite','.'], answer: 'Mon chien court tres vite.' },
  { words: ['La','petite','fille','chante','une','chanson','.'], answer: 'La petite fille chante une chanson.' },
  { words: ['Il','fait','beau','aujourd\'hui','.'], answer: 'Il fait beau aujourd\'hui.' },
  { words: ['Papa','lit','le','journal','le','matin','.'], answer: 'Papa lit le journal le matin.' },
  { words: ['Les','oiseaux','chantent','dans','les','arbres','.'], answer: 'Les oiseaux chantent dans les arbres.' },
  { words: ['La','neige','tombe','en','hiver','.'], answer: 'La neige tombe en hiver.' },
  { words: ['Emma','aime','les','glaces','au','chocolat','.'], answer: 'Emma aime les glaces au chocolat.' },
  { words: ['Le','soleil','brille','dans','le','ciel','bleu','.'], answer: 'Le soleil brille dans le ciel bleu.' },
  { words: ['Mon','frere','joue','au','football','avec','ses','amis','.'], answer: 'Mon frere joue au football avec ses amis.' },
  { words: ['La','tortue','marche','lentement','dans','le','jardin','.'], answer: 'La tortue marche lentement dans le jardin.' },
  { words: ['Hugo','range','ses','jouets','dans','sa','chambre','.'], answer: 'Hugo range ses jouets dans sa chambre.' },
  { words: ['Les','etoiles','brillent','dans','le','ciel','nocturne','.'], answer: 'Les etoiles brillent dans le ciel nocturne.' },
  { words: ['La','grand-mere','prepare','un','gateau','au','chocolat','.'], answer: 'La grand-mere prepare un gateau au chocolat.' },
  { words: ['Le','petit','lapin','mange','des','carottes','.'], answer: 'Le petit lapin mange des carottes.' },
  { words: ['Jade','dessine','un','beau','paysage','en','couleurs','.'], answer: 'Jade dessine un beau paysage en couleurs.' },
  { words: ['Les','papillons','volent','de','fleur','en','fleur','.'], answer: 'Les papillons volent de fleur en fleur.' },
  { words: ['Mon','institutrice','explique','la','lecon','avec','patience','.'], answer: 'Mon institutrice explique la lecon avec patience.' },
  { words: ['Le','chien','aboie','quand','quelqu\'un','sonne','a','la','porte','.'], answer: 'Le chien aboie quand quelqu\'un sonne a la porte.' },
  { words: ['Les','enfants','font','un','bonhomme','de','neige','.'], answer: 'Les enfants font un bonhomme de neige.' },
  { words: ['La','riviere','coule','doucement','vers','la','mer','.'], answer: 'La riviere coule doucement vers la mer.' },
  { words: ['Noah','apprend','a','lire','avec','sa','maman','.'], answer: 'Noah apprend a lire avec sa maman.' },

  // ── DIFFICILE : 10-14 mots + subordonnees ──
  { words: ['Quand','le','soleil','se','couche',',','le','ciel','devient','orange','et','rose','.'], answer: 'Quand le soleil se couche, le ciel devient orange et rose.', difficulty: 'difficile' },
  { words: ['L\'','astronaute','flottait','dans','l\'','espace','et','regardait','la','Terre','tourner','.'], answer: 'L\'astronaute flottait dans l\'espace et regardait la Terre tourner.', difficulty: 'difficile' },
  { words: ['Si','tu','travailles','bien',',','tu','pourras','regarder','la','television','ce','soir','.'], answer: 'Si tu travailles bien, tu pourras regarder la television ce soir.', difficulty: 'difficile' },
  { words: ['Les','fourmis','transportaient','des','miettes','de','pain','vers','leur','fourmiliere','.'], answer: 'Les fourmis transportaient des miettes de pain vers leur fourmiliere.', difficulty: 'difficile' },
  { words: ['La','petite','fille','aux','cheveux','roux','lisait','un','livre','sous','le','grand','chene','.'], answer: 'La petite fille aux cheveux roux lisait un livre sous le grand chene.', difficulty: 'difficile' },
  { words: ['Bien','que','le','temps','soit','nuageux',',','les','enfants','jouent','dehors','avec','entrain','.'], answer: 'Bien que le temps soit nuageux, les enfants jouent dehors avec entrain.', difficulty: 'difficile' },
  { words: ['Depuis','que','ma','soeur','a','commence','la','guitare',',','elle','s\'','entraine','chaque','soir','.'], answer: 'Depuis que ma soeur a commence la guitare, elle s\'entraine chaque soir.', difficulty: 'difficile' },
  { words: ['Le','vieux','fermier','rentrait','chez','lui','apres','une','longue','journee','de','travail','.'], answer: 'Le vieux fermier rentrait chez lui apres une longue journee de travail.', difficulty: 'difficile' },
  { words: ['Malgre','la','pluie',',','les','supporters','chantaient','pour','encourager','leur','equipe','favorite','.'], answer: 'Malgre la pluie, les supporters chantaient pour encourager leur equipe favorite.', difficulty: 'difficile' },
  { words: ['Le','scientifique','observait','les','etoiles','a','travers','son','puissant','telescope','chaque','nuit','.'], answer: 'Le scientifique observait les etoiles a travers son puissant telescope chaque nuit.', difficulty: 'difficile' },
];

// ── MEMOIRE VISUELLE (Univers 6) ────────────────────────────────────────
export const MEMOIRE_PHRASES = [
  // court (5-7 mots)
  { text: 'Le chat dort sur le tapis.', level: 'court' },
  { text: 'Lena mange une belle pomme.', level: 'court' },
  { text: 'Il fait beau ce matin.', level: 'court' },
  { text: 'Mon chien aime les carottes.', level: 'court' },
  { text: 'Les fleurs poussent au printemps.', level: 'court' },
  { text: 'Emma chante tres bien.', level: 'court' },
  { text: 'Le soleil brille ce matin.', level: 'court' },
  { text: 'Hugo lit un livre rouge.', level: 'court' },
  { text: 'La neige tombe en hiver.', level: 'court' },
  { text: 'Mon papa aime le cafe.', level: 'court' },
  // moyen (8-12 mots)
  { text: 'Les enfants jouent dans le grand jardin vert.', level: 'moyen' },
  { text: 'La petite fille chante une joyeuse chanson.', level: 'moyen' },
  { text: 'Mon frere mange une grande glace au chocolat.', level: 'moyen' },
  { text: 'Le vieux chat dort pres de la cheminee chaude.', level: 'moyen' },
  { text: 'Jade et Emma courent vite dans la cour de recreation.', level: 'moyen' },
  { text: 'Les oiseaux chantent dans les hauts arbres de la foret.', level: 'moyen' },
  { text: 'Mon institutrice explique la lecon avec beaucoup de patience.', level: 'moyen' },
  { text: 'La grand-mere prepare un delicieux gateau pour l\'anniversaire.', level: 'moyen' },
  { text: 'Le petit lapin gris mange des carottes dans le jardin.', level: 'moyen' },
  { text: 'Les papillons colorees volent de fleur en fleur au printemps.', level: 'moyen' },
  // long (13-18 mots)
  { text: 'Ce matin, les enfants joyeux courent dans la grande cour ensoleille de l\'ecole.', level: 'long' },
  { text: 'Le vieux renard ruse traverse la foret sombre pour trouver quelque chose a manger.', level: 'long' },
  { text: 'Ma grand-mere habite dans une belle maison rouge avec un grand jardin plein de fleurs.', level: 'long' },
  { text: 'L\'astronaute courageuse regarde la Terre depuis son vaisseau spatial en orbite autour de notre planete.', level: 'long' },
  { text: 'En automne, les feuilles des arbres changent de couleur et tombent doucement sur le sol du jardin.', level: 'long' },

  // ── TRES LONG : 18-28 mots ──
  { text: 'Le vieux savant aux lunettes rondes rangea soigneusement ses notes dans sa serviette de cuir avant de quitter le laboratoire.', level: 'tres_long' },
  { text: 'Chaque soir d\'ete, les villageois se reunissaient sur la place pour ecouter les musiciens et danser jusqu\'a la nuit tombee.', level: 'tres_long' },
  { text: 'La bibliothecaire aux cheveux blancs guidait les enfants entre les etageres, leur soufflant le nom des livres les plus merveilleux.', level: 'tres_long' },
  { text: 'Quand les premieres neiges de l\'annee tombent sur les toits de la ville, les enfants pressent leur nez contre les vitres froides.', level: 'tres_long' },
  { text: 'Le capitaine du voilier observait l\'horizon depuis le pont, cherchant le signe d\'une ile qui n\'apparaissait pas encore sur les cartes.', level: 'tres_long' },
];

// ── CLASSIFICATION GRAMMAR (Univers 7) ───────────────────────────────────
// type: 'adjectif' | 'verbe_infinitif' | 'verbe_conjugue'
export const CLASSIFICATION_ITEMS = [
  { word: 'jolie', type: 'adjectif' },
  { word: 'grande', type: 'adjectif' },
  { word: 'faire', type: 'verbe_infinitif' },
  { word: 'sortir', type: 'verbe_infinitif' },
  { word: 'elle porte', type: 'verbe_conjugue' },
  { word: 'il ouvre', type: 'verbe_conjugue' },
  { word: 'rouge', type: 'adjectif' },
  { word: 'courir', type: 'verbe_infinitif' },
  { word: 'nous chantons', type: 'verbe_conjugue' },
  { word: 'petit', type: 'adjectif' },
  { word: 'manger', type: 'verbe_infinitif' },
  { word: 'ils jouent', type: 'verbe_conjugue' },
  { word: 'intelligent', type: 'adjectif' },
  { word: 'dormir', type: 'verbe_infinitif' },
  { word: 'tu cours', type: 'verbe_conjugue' },
  { word: 'rapide', type: 'adjectif' },
  { word: 'lire', type: 'verbe_infinitif' },
  { word: 'je mange', type: 'verbe_conjugue' },
  { word: 'gentil', type: 'adjectif' },
  { word: 'ecrire', type: 'verbe_infinitif' },
  { word: 'vous lisez', type: 'verbe_conjugue' },
  { word: 'triste', type: 'adjectif' },
  { word: 'danser', type: 'verbe_infinitif' },
  { word: 'elle dort', type: 'verbe_conjugue' },
  { word: 'magnifique', type: 'adjectif' },
  { word: 'nager', type: 'verbe_infinitif' },
  { word: 'nous apprenons', type: 'verbe_conjugue' },
  { word: 'bleu', type: 'adjectif' },
  { word: 'prendre', type: 'verbe_infinitif' },
  { word: 'il construit', type: 'verbe_conjugue' },
  { word: 'fort', type: 'adjectif' },
  { word: 'chanter', type: 'verbe_infinitif' },
  { word: 'elles arrivent', type: 'verbe_conjugue' },
  { word: 'mignon', type: 'adjectif' },
  { word: 'voler', type: 'verbe_infinitif' },
  { word: 'tu ecris', type: 'verbe_conjugue' },
  { word: 'doux', type: 'adjectif' },
  { word: 'construire', type: 'verbe_infinitif' },
  { word: 'je chante', type: 'verbe_conjugue' },
  { word: 'courageux', type: 'adjectif' },
  { word: 'grandir', type: 'verbe_infinitif' },
  { word: 'nous partons', type: 'verbe_conjugue' },
  { word: 'sympa', type: 'adjectif' },
  { word: 'partir', type: 'verbe_infinitif' },
  { word: 'ils rient', type: 'verbe_conjugue' },
  { word: 'calme', type: 'adjectif' },
  { word: 'finir', type: 'verbe_infinitif' },
  { word: 'elle rit', type: 'verbe_conjugue' },
  { word: 'drole', type: 'adjectif' },
  { word: 'sauter', type: 'verbe_infinitif' },
  { word: 'tu joues', type: 'verbe_conjugue' },
  { word: 'bizarre', type: 'adjectif' },
  { word: 'venir', type: 'verbe_infinitif' },
  { word: 'il croit', type: 'verbe_conjugue' },
  { word: 'ancien', type: 'adjectif' },
  { word: 'voir', type: 'verbe_infinitif' },
  { word: 'nous voyons', type: 'verbe_conjugue' },
  { word: 'beau', type: 'adjectif' },
  { word: 'tenir', type: 'verbe_infinitif' },
  { word: 'je viens', type: 'verbe_conjugue' },
  { word: 'fatigue', type: 'adjectif' },

  // ── DIFFICILE : participes, -ant, homophones grammaticaux ──
  { word: 'charmant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'en chantant', type: 'verbe_infinitif', difficulty: 'difficile' },
  { word: 'obéissant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'elle avait mange', type: 'verbe_conjugue', difficulty: 'difficile' },
  { word: 'surprenant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'resoudre', type: 'verbe_infinitif', difficulty: 'difficile' },
  { word: 'ils auraient voulu', type: 'verbe_conjugue', difficulty: 'difficile' },
  { word: 'passionnant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'se souvenir', type: 'verbe_infinitif', difficulty: 'difficile' },
  { word: 'nous serions partis', type: 'verbe_conjugue', difficulty: 'difficile' },
  { word: 'touchant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'se plaindre', type: 'verbe_infinitif', difficulty: 'difficile' },
  { word: 'tu auras fini', type: 'verbe_conjugue', difficulty: 'difficile' },
  { word: 'etonnant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'prevenir', type: 'verbe_infinitif', difficulty: 'difficile' },
  { word: 'on aurait pu', type: 'verbe_conjugue', difficulty: 'difficile' },
  { word: 'vieillissant', type: 'adjectif', difficulty: 'difficile' },
  { word: 'se taire', type: 'verbe_infinitif', difficulty: 'difficile' },
  { word: 'vous etiez arrives', type: 'verbe_conjugue', difficulty: 'difficile' },
  { word: 'reconfortant', type: 'adjectif', difficulty: 'difficile' },
];

// ── SONS COMPLEXES (Univers 9) ─────────────────────────────────────────────
export const SONS_FAMILLES = [
  {
    family: 'eil / eille',
    description: 'Le son "eil" : au singulier on ecrit -eil (masculin) ou -eille (feminin)',
    words: [
      { word: 'reveil', blank: 'reve__', suffix: 'il', example: 'Le ___ sonne le matin.' },
      { word: 'soleil', blank: 'sole__', suffix: 'il', example: 'Le ___ brille en ete.' },
      { word: 'abeille', blank: 'abe__', suffix: 'ille', example: 'L\'___ fabrique du miel.' },
      { word: 'bouteille', blank: 'boute__', suffix: 'ille', example: 'La ___ est pleine d\'eau.' },
      { word: 'oreille', blank: 'ore__', suffix: 'ille', example: 'J\'entends avec mes ___.' },
      { word: 'merveille', blank: 'merve__', suffix: 'ille', example: 'C\'est une vraie ___.' },
    ],
    options: ['il', 'ille', 'eil', 'eille'],
  },
  {
    family: 'ail / aille',
    description: 'Le son "ail" : -ail (masculin) ou -aille (feminin)',
    words: [
      { word: 'travail', blank: 'trava__', suffix: 'il', example: 'Papa part au ___ le matin.' },
      { word: 'vitrail', blank: 'vitra__', suffix: 'il', example: 'Le ___ de l\'eglise est beau.' },
      { word: 'paille', blank: 'pa__', suffix: 'ille', example: 'Le fermier met de la ___ pour les vaches.' },
      { word: 'bataille', blank: 'bata__', suffix: 'ille', example: 'Les chevaliers se battent en ___.' },
      { word: 'medaille', blank: 'meda__', suffix: 'ille', example: 'Le champion porte une ___ d\'or.' },
    ],
    options: ['il', 'ille', 'ail', 'aille'],
  },
  {
    family: 'euil / euille',
    description: 'Le son "euil" : -euil (masculin) ou -euille (feminin)',
    words: [
      { word: 'ecureuil', blank: 'ecure__', suffix: 'il', example: 'L\'___ grimpe dans les arbres.' },
      { word: 'feuille', blank: 'fe__', suffix: 'ille', example: 'La ___ tombe en automne.' },
      { word: 'fauteuil', blank: 'faute__', suffix: 'il', example: 'Grand-pere s\'assoit dans son ___.' },
      { word: 'seuil', blank: 'se__', suffix: 'il', example: 'Il est debout sur le ___ de la porte.' },
      { word: 'portefeuille', blank: 'porte-fe__', suffix: 'ille', example: 'Papa range son argent dans son ___.' },
    ],
    options: ['il', 'ille', 'euil', 'euille'],
  },
  {
    family: 'ouil / ouille',
    description: 'Le son "ouil" : -ouille (feminin le plus souvent)',
    words: [
      { word: 'grenouille', blank: 'greno__', suffix: 'ille', example: 'La ___ coasse pres de la mare.' },
      { word: 'citrouille', blank: 'citro__', suffix: 'ille', example: 'La ___ est orange a Halloween.' },
      { word: 'rouille', blank: 'ro__', suffix: 'ille', example: 'La ___ attaque le metal.' },
      { word: 'fouille', blank: 'fo__', suffix: 'ille', example: 'L\'archeologue ___ le sol.' },
      { word: 'fenouil', blank: 'feno__', suffix: 'il', example: 'Le ___ est une plante aromatique.' },
    ],
    options: ['il', 'ille', 'uil', 'uille'],
  },
  {
    family: 'ill',
    description: 'Le son "ill" se prononce [j] dans les mots comme "fille", "bille", "famille"',
    words: [
      { word: 'famille', blank: 'fam__', suffix: 'ille', example: 'Ma ___ habite a Bruxelles.' },
      { word: 'bille', blank: 'b__', suffix: 'ille', example: 'Je joue aux ___ dans la cour.' },
      { word: 'village', blank: 'v__age', suffix: 'ill', example: 'Mon grand-pere habite dans un ___.' },
      { word: 'briller', blank: 'br__er', suffix: 'ill', example: 'Les etoiles ___ la nuit.' },
      { word: 'gorille', blank: 'gor__', suffix: 'ille', example: 'Le ___ est un grand singe.' },
      { word: 'vanille', blank: 'van__', suffix: 'ille', example: 'La creme a la ___ est delicieuse.' },
    ],
    options: ['ille', 'ile', 'ill', 'il'],
  },

  // ── DIFFICILE : nouvelles familles de sons ──
  {
    family: 'tion / sion',
    description: 'Le son "sion" s\'ecrit -tion (apres une consonne) ou -sion (apres une voyelle ou s)',
    words: [
      { word: 'nation', blank: 'na__', suffix: 'tion', example: 'La ___ belge a gagne la coupe.' },
      { word: 'passion', blank: 'pas__', suffix: 'sion', example: 'La musique est sa grande ___.' },
      { word: 'attention', blank: 'atten__', suffix: 'tion', example: '___ ! La voiture arrive.' },
      { word: 'mission', blank: 'mis__', suffix: 'sion', example: 'L\'astronaute a accompli sa ___.' },
      { word: 'solution', blank: 'solu__', suffix: 'tion', example: 'J\'ai trouve la ___ au probleme.' },
      { word: 'invasion', blank: 'inva__', suffix: 'sion', example: 'L\'___ des sauterelles a ravage les champs.' },
    ],
    options: ['tion', 'sion', 'cion', 'zion'],
    difficulty: 'difficile',
  },
  {
    family: 'ent / ant',
    description: 'La terminaison -ent est souvent muette au pluriel des verbes. -ant est le participe present.',
    words: [
      { word: 'patient', blank: 'pa__', suffix: 'tient', example: 'Le docteur est tres ___.' },
      { word: 'chantant', blank: 'chan__', suffix: 'tant', example: 'Elle rit en ___ une chanson.' },
      { word: 'evident', blank: 'evi__', suffix: 'dent', example: 'C\'est ___ comme reponse.' },
      { word: 'courant', blank: 'cou__', suffix: 'rant', example: 'Il est sorti en ___ de la maison.' },
      { word: 'prudent', blank: 'pru__', suffix: 'dent', example: 'Sois ___ en traversant la rue.' },
      { word: 'souriant', blank: 'sou__', suffix: 'riant', example: 'Il arrive toujours ___.' },
    ],
    options: ['tient', 'tant', 'dent', 'rant'],
    difficulty: 'difficile',
  },
  {
    family: 'eau / au / o',
    description: 'Le son [o] peut s\'ecrire "eau", "au" ou "o".',
    words: [
      { word: 'chapeau', blank: 'chap__', suffix: 'eau', example: 'Il porte un ___ sur la tete.' },
      { word: 'chauffeur', blank: 'ch__ffeur', suffix: 'au', example: 'Le ___ conduit la voiture.' },
      { word: 'peau', blank: 'p__', suffix: 'eau', example: 'La ___ de la peche est douce.' },
      { word: 'automne', blank: '__tomne', suffix: 'au', example: 'En ___, les feuilles tombent.' },
      { word: 'oiseau', blank: 'ois__', suffix: 'eau', example: 'L\'___ chante dans l\'arbre.' },
      { word: 'bureau', blank: 'bur__', suffix: 'eau', example: 'Papa travaille a son ___.' },
    ],
    options: ['eau', 'au', 'o', 'ot'],
    difficulty: 'difficile',
  },
];

// ── DETECTIVE DES ERREURS (Univers 10) ──────────────────────────────────
// error_type: 'accord'|'majuscule'|'ponctuation'|'orthographe'
export const DETECTIVE_ERREURS = [
  { wrong: 'les enfants jouent dans le jardin.', correct: 'Les enfants jouent dans le jardin.', error_type: 'majuscule', error_word: 'les', fix: 'Les' },
  { wrong: 'Le chat dorment sur le canape.', correct: 'Le chat dort sur le canape.', error_type: 'accord', error_word: 'dorment', fix: 'dort' },
  { wrong: 'Lena mange une pomme rouge', correct: 'Lena mange une pomme rouge.', error_type: 'ponctuation', error_word: 'rouge', fix: 'rouge.' },
  { wrong: 'Les fleur poussent au printemps.', correct: 'Les fleurs poussent au printemps.', error_type: 'accord', error_word: 'fleur', fix: 'fleurs' },
  { wrong: 'il fait beau aujourd\'hui.', correct: 'Il fait beau aujourd\'hui.', error_type: 'majuscule', error_word: 'il', fix: 'Il' },
  { wrong: 'Les chien courent dans le parc.', correct: 'Les chiens courent dans le parc.', error_type: 'accord', error_word: 'chien', fix: 'chiens' },
  { wrong: 'emma et hugo jouent ensemble.', correct: 'Emma et Hugo jouent ensemble.', error_type: 'majuscule', error_word: 'emma', fix: 'Emma' },
  { wrong: 'La voiture roule vite ?', correct: 'La voiture roule vite.', error_type: 'ponctuation', error_word: '?', fix: '.' },
  { wrong: 'Le petit fille chante une chanson.', correct: 'La petite fille chante une chanson.', error_type: 'accord', error_word: 'petit', fix: 'petite' },
  { wrong: 'je vais a l\'ecole a pied.', correct: 'Je vais a l\'ecole a pied.', error_type: 'majuscule', error_word: 'je', fix: 'Je' },
  { wrong: 'La mer est tres bleus aujourd\'hui.', correct: 'La mer est tres bleue aujourd\'hui.', error_type: 'accord', error_word: 'bleus', fix: 'bleue' },
  { wrong: 'Les oiseaux chante dans les arbres.', correct: 'Les oiseaux chantent dans les arbres.', error_type: 'accord', error_word: 'chante', fix: 'chantent' },
  { wrong: 'Mon institutrice est gentile.', correct: 'Mon institutrice est gentille.', error_type: 'orthographe', error_word: 'gentile', fix: 'gentille' },
  { wrong: 'paris est la capitale de la france.', correct: 'Paris est la capitale de la France.', error_type: 'majuscule', error_word: 'paris', fix: 'Paris' },
  { wrong: 'Les enfants ont manges leur gateau.', correct: 'Les enfants ont mange leur gateau.', error_type: 'orthographe', error_word: 'manges', fix: 'mange' },
  { wrong: 'Le soleil brillent dans le ciel.', correct: 'Le soleil brille dans le ciel.', error_type: 'accord', error_word: 'brillent', fix: 'brille' },
  { wrong: 'Ma soeur joue du piano', correct: 'Ma soeur joue du piano.', error_type: 'ponctuation', error_word: 'piano', fix: 'piano.' },
  { wrong: 'Les chevaux courents tres vite.', correct: 'Les chevaux courent tres vite.', error_type: 'orthographe', error_word: 'courents', fix: 'courent' },
  { wrong: 'il neige en hiver.', correct: 'Il neige en hiver.', error_type: 'majuscule', error_word: 'il', fix: 'Il' },
  { wrong: 'La petits enfants dorment.', correct: 'Les petits enfants dorment.', error_type: 'accord', error_word: 'La', fix: 'Les' },
  { wrong: 'Mon chien est trop mignon!', correct: 'Mon chien est trop mignon.', error_type: 'ponctuation', error_word: 'mignon!', fix: 'mignon.' },
  { wrong: 'Le lion est le rois des animaux.', correct: 'Le lion est le roi des animaux.', error_type: 'orthographe', error_word: 'rois', fix: 'roi' },
  { wrong: 'Les enfants joue dans la cour.', correct: 'Les enfants jouent dans la cour.', error_type: 'accord', error_word: 'joue', fix: 'jouent' },
  { wrong: 'la lune brille la nuit.', correct: 'La lune brille la nuit.', error_type: 'majuscule', error_word: 'la', fix: 'La' },
  { wrong: 'Mon chat mange des croquette.', correct: 'Mon chat mange des croquettes.', error_type: 'accord', error_word: 'croquette', fix: 'croquettes' },

  // ── DIFFICILE : homophones grammaticaux ──
  { wrong: 'Il a beaucoup neige hier.', correct: 'Il a beaucoup neige hier.', error_type: 'accord', error_word: 'neige', fix: 'neige', difficulty: 'difficile' },
  { wrong: 'Mon frere et moi on joues ensemble.', correct: 'Mon frere et moi on joue ensemble.', error_type: 'orthographe', error_word: 'joues', fix: 'joue', difficulty: 'difficile' },
  { wrong: 'Elle c\'est blessée en tombant.', correct: 'Elle s\'est blessee en tombant.', error_type: 'orthographe', error_word: 'c\'est', fix: 's\'est', difficulty: 'difficile' },
  { wrong: 'Les athletes on gagne la course.', correct: 'Les athletes ont gagne la course.', error_type: 'orthographe', error_word: 'on', fix: 'ont', difficulty: 'difficile' },
  { wrong: 'Ce matin, il fait beau mais je sais pas ou aller.', correct: 'Ce matin, il fait beau mais je ne sais pas ou aller.', error_type: 'orthographe', error_word: 'sais', fix: 'ne sais', difficulty: 'difficile' },
  { wrong: 'Mes parents sont rentres de voyages.', correct: 'Mes parents sont rentres de voyage.', error_type: 'accord', error_word: 'voyages', fix: 'voyage', difficulty: 'difficile' },
  { wrong: 'Tu peut venir chez moi ce soir ?', correct: 'Tu peux venir chez moi ce soir ?', error_type: 'orthographe', error_word: 'peut', fix: 'peux', difficulty: 'difficile' },
  { wrong: 'Le chien a mordu son os avec plaisirs.', correct: 'Le chien a mordu son os avec plaisir.', error_type: 'accord', error_word: 'plaisirs', fix: 'plaisir', difficulty: 'difficile' },
  { wrong: 'Nous avons des beaux souvenirs de vacances.', correct: 'Nous avons de beaux souvenirs de vacances.', error_type: 'orthographe', error_word: 'des', fix: 'de', difficulty: 'difficile' },
  { wrong: 'Son frere et elle sont partis a l\'ecoles.', correct: 'Son frere et elle sont partis a l\'ecole.', error_type: 'accord', error_word: 'ecoles', fix: 'ecole', difficulty: 'difficile' },
  { wrong: 'Il ce levait tot chaque matin.', correct: 'Il se levait tot chaque matin.', error_type: 'orthographe', error_word: 'ce', fix: 'se', difficulty: 'difficile' },
  { wrong: 'Vous etes tres courageuse.', correct: 'Vous etes tres courageux.', error_type: 'accord', error_word: 'courageuse', fix: 'courageux', difficulty: 'difficile' },
  { wrong: 'Les enfants leurs ont dit au revoir.', correct: 'Les enfants leur ont dit au revoir.', error_type: 'orthographe', error_word: 'leurs', fix: 'leur', difficulty: 'difficile' },
  { wrong: 'Cette nuit, j\'ai rever d\'une belle aventure.', correct: 'Cette nuit, j\'ai reve d\'une belle aventure.', error_type: 'orthographe', error_word: 'rever', fix: 'reve', difficulty: 'difficile' },
  { wrong: 'Ma tante a une belle mais-on.', correct: 'Ma tante a une belle maison.', error_type: 'orthographe', error_word: 'mais-on', fix: 'maison', difficulty: 'difficile' },
];

// Show the wrong sentence + 4 options (1 correct version + 3 similar wrong ones)
export function genDetectiveQuestion(item) {
  const errorLabels = { accord: 'Erreur d\'accord', majuscule: 'Majuscule oubliee', ponctuation: 'Ponctuation incorrecte', orthographe: 'Faute d\'orthographe' };
  const opts = [item.correct, item.wrong,
    item.wrong.replace(item.error_word, item.fix + 's'),
    item.wrong.replace(item.error_word, item.fix.toLowerCase()),
  ].filter((v, i, a) => a.indexOf(v) === i).slice(0, 4).sort(() => Math.random() - .5);
  return {
    wrong: item.wrong,
    correct: item.correct,
    errorType: errorLabels[item.error_type] || 'Erreur',
    options: opts,
  };
}

// ── LECTURE RAPIDE (Univers 11) ──────────────────────────────────────────
export const LECTURE_RAPIDE = [
  // mots simples
  { text: 'chat', type: 'mot', level: 1 },
  { text: 'arbre', type: 'mot', level: 1 },
  { text: 'maison', type: 'mot', level: 1 },
  { text: 'soleil', type: 'mot', level: 1 },
  { text: 'jardin', type: 'mot', level: 1 },
  { text: 'ecole', type: 'mot', level: 1 },
  { text: 'abeille', type: 'mot', level: 2 },
  { text: 'grenouille', type: 'mot', level: 2 },
  { text: 'astronaute', type: 'mot', level: 2 },
  { text: 'bibliotheque', type: 'mot', level: 2 },
  // groupes de mots
  { text: 'le petit chat', type: 'groupe', level: 2 },
  { text: 'une belle fleur', type: 'groupe', level: 2 },
  { text: 'mon grand frere', type: 'groupe', level: 2 },
  { text: 'les enfants joyeux', type: 'groupe', level: 2 },
  { text: 'une grosse citrouille', type: 'groupe', level: 2 },
  { text: 'le soleil brille', type: 'groupe', level: 2 },
  // phrases courtes
  { text: 'Le chat dort.', type: 'phrase', level: 3 },
  { text: 'Il fait beau.', type: 'phrase', level: 3 },
  { text: 'Lena court vite.', type: 'phrase', level: 3 },
  { text: 'Mon chien aboie.', type: 'phrase', level: 3 },
  { text: 'La neige tombe.', type: 'phrase', level: 3 },
  { text: 'Les fleurs poussent.', type: 'phrase', level: 3 },
  { text: 'Emma chante fort.', type: 'phrase', level: 3 },
  { text: 'Hugo lit un livre.', type: 'phrase', level: 3 },
  { text: 'Le vent souffle.', type: 'phrase', level: 3 },
  { text: 'La mer est belle.', type: 'phrase', level: 3 },
  // phrases moyennes
  { text: 'Le lapin mange des carottes.', type: 'phrase_m', level: 4 },
  { text: 'Les enfants jouent dans la cour.', type: 'phrase_m', level: 4 },
  { text: 'Mon institutrice est tres gentille.', type: 'phrase_m', level: 4 },
  { text: 'Les papillons volent de fleur en fleur.', type: 'phrase_m', level: 4 },

  // ── NIVEAU 5 : longues phrases complexes, flash 1 seconde ──
  { text: 'Le vieux chat tigre dormait paisiblement pres de la cheminee.', type: 'phrase_l', level: 5 },
  { text: 'Les astronautes flottaient dans leur capsule en regardant la Terre.', type: 'phrase_l', level: 5 },
  { text: 'Emma et Hugo cherchaient des champignons dans la foret en automne.', type: 'phrase_l', level: 5 },
  { text: 'Le boulanger se levait chaque matin avant l\'aube pour petrir la pate.', type: 'phrase_l', level: 5 },
  { text: 'La petite tortue avancait lentement mais surement vers la mer scintillante.', type: 'phrase_l', level: 5 },
  { text: 'Depuis la fenetre de sa chambre, Lena regardait les flocons tomber doucement.', type: 'phrase_l', level: 5 },
  { text: 'Les fourmis transportaient methodiquement leurs provisions vers le nid souterrain.', type: 'phrase_l', level: 5 },
  { text: 'Le capitaine ordonna a son equipage de rentrer au port avant la tempete.', type: 'phrase_l', level: 5 },
  { text: 'Malgre la pluie battante, les enfants jouaient joyeusement dans les flaques.', type: 'phrase_l', level: 5 },
  { text: 'La bibliothecaire rangea soigneusement les livres sur les etageres en bois sombre.', type: 'phrase_l', level: 5 },
];

// ── VOCABULARY THEMES (Univers 12) ────────────────────────────────────────
export const VOCAB_THEMES = {
  ferme: { label: 'La Ferme', emoji: '🐄', words: ['vache','cochon','mouton','poule','cheval','lapin','oie','coq','ane','canard','tracteur','grange','foin','paille','fermier','ecurie','prairie','cloture','silo','champ'] },
  ecole: { label: 'L\'Ecole', emoji: '🏫', words: ['cahier','crayon','stylo','gomme','regle','colle','cartable','tableau','bureau','institutrice','recreation','cantine','bibliotheque','calculette','compas','agenda','trousse','feuille','classeur','livre'] },
  animaux: { label: 'Les Animaux', emoji: '🦁', words: ['lion','tigre','elephant','girafe','zebre','hippopotame','rhinoceros','gorille','leopard','guepard','crocodile','flamant','perroquet','toucan','serpent','tortue','requin','baleine','dauphin','pieuvre'] },
  nature: { label: 'La Nature', emoji: '🌲', words: ['arbre','foret','montagne','riviere','lac','ocean','plage','ile','desert','prairie','colline','vallee','rocher','falaise','grotte','cascade','marais','dune','volcan','glacier'] },
  saisons: { label: 'Les Saisons', emoji: '🍂', words: ['printemps','ete','automne','hiver','soleil','pluie','neige','vent','orage','arc-en-ciel','nuage','brume','givre','grele','tonnerre','eclair','chaleur','fraicheur','froid','tiede'] },
  metiers: { label: 'Les Metiers', emoji: '👷', words: ['medecin','pompier','policier','boulanger','jardinier','professeur','infirmiere','pilote','charpentier','cuisinier','peintre','musicien','acteur','veterinaire','facteur','architecte','pharmacien','dentiste','astronaute','pompiste'] },
  transports: { label: 'Les Transports', emoji: '🚂', words: ['voiture','train','avion','bateau','velo','moto','bus','tramway','metro','helicoptere','fusee','camion','ambulance','taxi','canoe','sous-marin','montgolfiere','scooter','trottinette','kayak'] },
  maison: { label: 'La Maison', emoji: '🏠', words: ['cuisine','salon','chambre','salle-de-bain','jardin','garage','grenier','cave','couloir','escalier','fenetre','porte','mur','toit','cheminee','meuble','canape','lit','table','armoire'] },

  // ── THEMES DIFFICILES ──
  corps: { label: 'Le Corps Humain', emoji: '🫀', difficulty: 'difficile', words: ['cerveau','poumon','coeur','foie','rein','estomac','intestin','muscle','squelette','articulation','vaisseau','nerf','peau','os','tendon','colonne','cote','phalange','tempe','nuque'] },
  instruments: { label: 'Les Instruments', emoji: '🎸', difficulty: 'difficile', words: ['violon','alto','violoncelle','contrebasse','flute','hautbois','clarinette','basson','trompette','trombone','tuba','cor','guitare','harpe','piano','orgue','accordeon','xylophone','marimba','batterie'] },
  sports: { label: 'Les Sports', emoji: '🏊', difficulty: 'difficile', words: ['natation','athletisme','escrime','aviron','haltérophilie','luge','bobsleigh','skeleton','biathlon','pentathlon','trampoline','gymnastique','equitation','taekwondo','judo','karate','boxe','lutte','tir','cyclisme'] },
  pays: { label: 'Les Pays', emoji: '🌍', difficulty: 'difficile', words: ['Belgique','Allemagne','Autriche','Suisse','Luxembourg','Pays-Bas','Danemark','Norvege','Suede','Finlande','Islande','Pologne','Republique-tcheque','Hongrie','Roumanie','Bulgarie','Grece','Portugal','Irlande','Ecosse'] },
};

// Generate vocab quiz: show a word, ask which theme it belongs to
export function genVocabQuestion(targetTheme) {
  const words = VOCAB_THEMES[targetTheme].words;
  const word = words[Math.floor(Math.random() * words.length)];
  const otherThemes = Object.keys(VOCAB_THEMES).filter(t => t !== targetTheme);
  const distractors = otherThemes.sort(() => Math.random() - .5).slice(0, 3);
  const options = [targetTheme, ...distractors].sort(() => Math.random() - .5);
  return { word, correctTheme: targetTheme, options };
}

// Harder vocab: show the definition/context, not just the word
export const VOCAB_DEFINITIONS = [
  { word: 'abdomen', correct: 'corps', hint: 'Partie du corps entre la poitrine et les hanches.' },
  { word: 'xylophone', correct: 'instruments', hint: 'Instrument a percussion avec des lames en bois.' },
  { word: 'biathlon', correct: 'sports', hint: 'Combinaison du ski de fond et du tir.' },
  { word: 'Luxembourg', correct: 'pays', hint: 'Petit pays voisin de la Belgique.' },
  { word: 'trombone', correct: 'instruments', hint: 'Instrument a vent avec une coulisse.' },
  { word: 'fémur', correct: 'corps', hint: 'L\'os le plus long du corps humain dans la jambe.' },
  { word: 'escrime', correct: 'sports', hint: 'Sport de combat avec des epees.' },
  { word: 'Islande', correct: 'pays', hint: 'Ile nordique pres du cercle arctique.' },
  { word: 'diaphragme', correct: 'corps', hint: 'Muscle qui permet la respiration.' },
  { word: 'hautbois', correct: 'instruments', hint: 'Instrument a anche double de l\'orchestre.' },
  { word: 'luge', correct: 'sports', hint: 'Sport d\'hiver: glisse couche sur le dos.' },
  { word: 'Suisse', correct: 'pays', hint: 'Pays connu pour ses montres et son chocolat.' },
  { word: 'marimba', correct: 'instruments', hint: 'Grand xylophone africain avec des resonateurs.' },
  { word: 'pentathlon', correct: 'sports', hint: 'Competition combinant cinq epreuves differentes.' },
  { word: 'pancreas', correct: 'corps', hint: 'Organe qui produit l\'insuline.' },
];

export const LEXI_BADGES = [
  { id: 'lecteur-debutant', label: 'Lecteur Debutant',  emoji: '📖', threshold: 5   },
  { id: 'maitre-phrases',   label: 'Maitre des Phrases', emoji: '📝', threshold: 20  },
  { id: 'chasseur-mots',    label: 'Chasseur de Mots',   emoji: '🔤', threshold: 50  },
  { id: 'expert-dictee',    label: 'Expert en Dictee',   emoji: '🦉', threshold: 100 },
  { id: 'champion-lexi',    label: 'Champion LexiLena',  emoji: '🏆', threshold: 200 },
];

export const ENCOURAGEMENTS_LEXI = [
  'Bravo, tu progresses ! 📖',
  'Essaie encore, tu y es presque !',
  'Super effort ! Continue ! 🌟',
  'Regarde bien les lettres !',
  'Tu es un vrai chasseur de mots ! 🔍',
  'Presque parfait ! Recommence !',
];

export function pickRandom(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
