export const histoireSubject = {
  id: 'histoire',
  label: 'Histoire & Geographie',
  description: 'La Belgique, l\'Europe, les grandes civilisations et la geographie mondiale.',
  color: '#f59e0b',
  accent: '#fde68a',
  grades: ['P2', 'P3', 'P4', 'P5', 'P6'],
  roadmap: [
    'Ma ville, ma region, mon pays',
    'La Belgique et ses regions',
    'L\'Europe et ses voisins',
    'Les grandes civilisations',
    'Le monde contemporain',
  ],
};

export const histoireActivities = [
  // ── hist-belgium-p2 ────────────────────────────────────────────────────────
  {
    id: 'hist-belgium-p2',
    slug: 'belgique-p2',
    title: 'Ma Belgique P2',
    subject: 'histoire',
    subskill: 'belgium',
    gradeBand: ['P2'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Les symboles de la Belgique: drapeau, capitale, langues.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['La capitale de la Belgique est Bruxelles.'],
    tags: ['histoire', 'belgium'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'be2-1', prompt: 'Quelle est la capitale de la Belgique ?', choices: ['Paris', 'Bruxelles', 'Amsterdam', 'Luxembourg'], answer: 'Bruxelles' },
          { id: 'be2-2', prompt: 'De quelle couleur est le drapeau belge ?', choices: ['Bleu, blanc, rouge', 'Vert, jaune, rouge', 'Noir, jaune, rouge', 'Bleu, rouge, jaune'], answer: 'Noir, jaune, rouge' },
          { id: 'be2-3', prompt: 'Combien de langues officielles la Belgique a-t-elle ?', choices: ['1', '2', '3', '4'], answer: '3' },
          { id: 'be2-4', prompt: 'Quelle langue parle-t-on en Wallonie ?', choices: ['Le neerlandais', 'L\'allemand', 'Le francais', 'L\'anglais'], answer: 'Le francais' },
          { id: 'be2-5', prompt: 'Quelle langue parle-t-on principalement en Flandre ?', choices: ['Le francais', 'Le neerlandais', 'L\'allemand', 'L\'anglais'], answer: 'Le neerlandais' },
          { id: 'be2-6', prompt: 'Comment s\'appelle le roi de Belgique actuel ?', choices: ['Albert II', 'Baudouin', 'Philippe', 'Leopold'], answer: 'Philippe' },
          { id: 'be2-7', prompt: 'Quelle est la forme du gouvernement en Belgique ?', choices: ['Une republique', 'Une monarchie constitutionnelle', 'Une dictature', 'Un empire'], answer: 'Une monarchie constitutionnelle' },
          { id: 'be2-8', prompt: 'La Belgique se trouve en...', choices: ['Asie', 'Amerique', 'Europe', 'Afrique'], answer: 'Europe' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'be2-9', prompt: 'Comment s\'appelle la monnaie utilisee en Belgique ?', choices: ['Le franc belge', 'La livre', 'L\'euro', 'Le dollar'], answer: 'L\'euro' },
          { id: 'be2-10', prompt: 'Quel animal figure sur l\'embleme de la Belgique ?', choices: ['L\'aigle', 'Le lion', 'L\'ours', 'Le taureau'], answer: 'Le lion' },
          { id: 'be2-11', prompt: 'Quelle est la fete nationale belge ?', choices: ['Le 14 juillet', 'Le 21 juillet', 'Le 11 novembre', 'Le 1er mai'], answer: 'Le 21 juillet' },
          { id: 'be2-12', prompt: 'La Belgique est un pays...', choices: ['Tres grand', 'De taille moyenne', 'Petit et densement peuple', 'Desertique'], answer: 'Petit et densement peuple' },
        ],
      },
    ],
  },

  // ── hist-regions-p2 ────────────────────────────────────────────────────────
  {
    id: 'hist-regions-p2',
    slug: 'regions-p2',
    title: 'Regions de Belgique P2',
    subject: 'histoire',
    subskill: 'regions',
    gradeBand: ['P2'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Wallonie, Flandre et Bruxelles.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['3 regions en Belgique.'],
    tags: ['histoire', 'regions'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'rg2-1', prompt: 'Combien de regions compte la Belgique ?', choices: ['2', '3', '4', '5'], answer: '3' },
          { id: 'rg2-2', prompt: 'Quelle region se trouve au sud de la Belgique ?', choices: ['La Flandre', 'Bruxelles', 'La Wallonie', 'Le Limbourg'], answer: 'La Wallonie' },
          { id: 'rg2-3', prompt: 'Quelle region se trouve au nord de la Belgique ?', choices: ['La Wallonie', 'La Flandre', 'Bruxelles', 'Le Hainaut'], answer: 'La Flandre' },
          { id: 'rg2-4', prompt: 'Bruxelles est une region a part entiere. Elle est aussi...', choices: ['Une ville ordinaire', 'La capitale de la Belgique et de l\'UE', 'Une province wallonne', 'Une ville flamande'], answer: 'La capitale de la Belgique et de l\'UE' },
          { id: 'rg2-5', prompt: 'Quelle est la ville principale de la Wallonie ?', choices: ['Gand', 'Bruges', 'Liege', 'Anvers'], answer: 'Liege' },
          { id: 'rg2-6', prompt: 'Quelle est la plus grande ville de Flandre ?', choices: ['Bruxelles', 'Liege', 'Anvers', 'Namur'], answer: 'Anvers' },
          { id: 'rg2-7', prompt: 'Quelle est la capitale administrative de la Wallonie ?', choices: ['Liege', 'Mons', 'Namur', 'Charleroi'], answer: 'Namur' },
          { id: 'rg2-8', prompt: 'Dans quelle region se trouve la foret des Ardennes ?', choices: ['En Flandre', 'A Bruxelles', 'En Wallonie', 'Au Luxembourg'], answer: 'En Wallonie' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'rg2-9', prompt: 'Quelle mer borde la cote belge en Flandre ?', choices: ['La mer Mediterranee', 'La mer du Nord', 'L\'ocean Atlantique', 'La mer Baltique'], answer: 'La mer du Nord' },
          { id: 'rg2-10', prompt: 'Quel fleuve traverse Liege et la Wallonie ?', choices: ['La Meuse', 'Le Rhin', 'La Seine', 'L\'Escaut'], answer: 'La Meuse' },
          { id: 'rg2-11', prompt: 'Bruxelles est une enclave dans quelle region ?', choices: ['La Wallonie', 'La Flandre', 'Les deux', 'Aucune'], answer: 'La Flandre' },
          { id: 'rg2-12', prompt: 'Quelle ville belge est connue pour ses dentelles et ses canaux ?', choices: ['Liege', 'Anvers', 'Bruges', 'Charleroi'], answer: 'Bruges' },
        ],
      },
    ],
  },

  // ── hist-europe-p3 ────────────────────────────────────────────────────────
  {
    id: 'hist-europe-p3',
    slug: 'europe-p3',
    title: 'L\'Europe P3',
    subject: 'histoire',
    subskill: 'europe',
    gradeBand: ['P3'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Les pays voisins de la Belgique et leurs capitales.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['France, Allemagne, Pays-Bas, Luxembourg.'],
    tags: ['histoire', 'europe'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'eu3-1', prompt: 'Combien de pays voisins directs a la Belgique ?', choices: ['2', '3', '4', '5'], answer: '4' },
          { id: 'eu3-2', prompt: 'Quel pays se trouve au sud de la Belgique ?', choices: ['L\'Allemagne', 'Les Pays-Bas', 'La France', 'Le Luxembourg'], answer: 'La France' },
          { id: 'eu3-3', prompt: 'Quel pays se trouve au nord de la Belgique ?', choices: ['La France', 'L\'Allemagne', 'Les Pays-Bas', 'Le Luxembourg'], answer: 'Les Pays-Bas' },
          { id: 'eu3-4', prompt: 'Quelle est la capitale de la France ?', choices: ['Lyon', 'Paris', 'Marseille', 'Bordeaux'], answer: 'Paris' },
          { id: 'eu3-5', prompt: 'Quelle est la capitale de l\'Allemagne ?', choices: ['Munich', 'Hambourg', 'Berlin', 'Francfort'], answer: 'Berlin' },
          { id: 'eu3-6', prompt: 'Quelle est la capitale des Pays-Bas ?', choices: ['Rotterdam', 'Amsterdam', 'La Haye', 'Utrecht'], answer: 'Amsterdam' },
          { id: 'eu3-7', prompt: 'Quelle est la capitale du Luxembourg ?', choices: ['Luxembourg-Ville', 'Echternach', 'Esch-sur-Alzette', 'Diekirch'], answer: 'Luxembourg-Ville' },
          { id: 'eu3-8', prompt: 'Sur quel continent se trouve l\'Europe ?', choices: ['Asie', 'Amerique', 'Afrique', 'Europe'], answer: 'Europe' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'eu3-9', prompt: 'Combien de pays compte l\'Union europeenne environ ?', choices: ['10', '20', '27', '50'], answer: '27' },
          { id: 'eu3-10', prompt: 'Quelle ville est consideree comme la capitale de l\'Union europeenne ?', choices: ['Paris', 'Berlin', 'Bruxelles', 'Rome'], answer: 'Bruxelles' },
          { id: 'eu3-11', prompt: 'Quel pays est la plus grande ile d\'Europe ?', choices: ['La Corse', 'La Sardaigne', 'La Grande-Bretagne', 'L\'Islande'], answer: 'La Grande-Bretagne' },
          { id: 'eu3-12', prompt: 'Quelle mer separe l\'Europe du nord de l\'Afrique ?', choices: ['La mer du Nord', 'La mer Baltique', 'La mer Mediterranee', 'La mer Noire'], answer: 'La mer Mediterranee' },
        ],
      },
    ],
  },

  // ── hist-timeline-p3 ──────────────────────────────────────────────────────
  {
    id: 'hist-timeline-p3',
    slug: 'frise-chronologique-p3',
    title: 'Frise chronologique P3',
    subject: 'histoire',
    subskill: 'timeline',
    gradeBand: ['P3'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Lire et placer des evenements sur une frise.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Avant Jesus-Christ = av. J.-C., apres = apr. J.-C.'],
    tags: ['histoire', 'timeline'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'tl3-1', prompt: 'Comment appelle-t-on la ligne qui represente le temps en histoire ?', choices: ['Une carte', 'Une frise chronologique', 'Un tableau', 'Un calendrier'], answer: 'Une frise chronologique' },
          { id: 'tl3-2', prompt: 'Que signifie "av. J.-C." ?', choices: ['Apres Jesus-Christ', 'Avant Jesus-Christ', 'Aux alentours de Jesus-Christ', 'Autour de Jerusalem-Capitale'], answer: 'Avant Jesus-Christ' },
          { id: 'tl3-3', prompt: 'Un siecle correspond a combien d\'annees ?', choices: ['10 ans', '50 ans', '100 ans', '1000 ans'], answer: '100 ans' },
          { id: 'tl3-4', prompt: 'Un millenaire correspond a combien d\'annees ?', choices: ['100 ans', '500 ans', '1000 ans', '10 000 ans'], answer: '1000 ans', explanation: 'Mille = 1000.' },
          { id: 'tl3-5', prompt: 'Dans quel ordre ces evenements se produisent-ils sur une frise ?', choices: ['Du plus recent au plus ancien', 'Du plus ancien au plus recent', 'De facon aleatoire', 'Par importance'], answer: 'Du plus ancien au plus recent' },
          { id: 'tl3-6', prompt: 'L\'an 500 av. J.-C. est-il avant ou apres l\'an 200 av. J.-C. ?', choices: ['Apres', 'Avant', 'En meme temps', 'On ne peut pas comparer'], answer: 'Avant' },
          { id: 'tl3-7', prompt: 'Combien y a-t-il de siecles dans un millenaire ?', choices: ['5', '10', '100', '1000'], answer: '10' },
          { id: 'tl3-8', prompt: 'Nous sommes actuellement au... siecle.', choices: ['19eme siecle', '20eme siecle', '21eme siecle', '22eme siecle'], answer: '21eme siecle' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'tl3-9', prompt: 'Une decennie est une periode de...', choices: ['5 ans', '10 ans', '20 ans', '100 ans'], answer: '10 ans' },
          { id: 'tl3-10', prompt: 'L\'an 1492 correspond a quelle periode ?', choices: ['Prehistoire', 'Antiquite', 'Moyen Age tardif / debut des temps modernes', 'Epoque contemporaine'], answer: 'Moyen Age tardif / debut des temps modernes' },
          { id: 'tl3-11', prompt: 'La Prehistoire precede quelle periode ?', choices: ['Le Moyen Age', 'L\'Antiquite', 'Les Temps modernes', 'L\'Epoque contemporaine'], answer: 'L\'Antiquite' },
          { id: 'tl3-12', prompt: 'Qu\'est-ce qu\'une ere en histoire ?', choices: ['Une saison', 'Une tres longue periode historique', 'Un siecle precis', 'Une epoque recente'], answer: 'Une tres longue periode historique' },
        ],
      },
    ],
  },

  // ── hist-ancient-p4 ───────────────────────────────────────────────────────
  {
    id: 'hist-ancient-p4',
    slug: 'antiquite-p4',
    title: 'Antiquite P4',
    subject: 'histoire',
    subskill: 'ancient-history',
    gradeBand: ['P4'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Egypte ancienne, Grece et Rome antique.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Les pyramides = Egypte, le Colisee = Rome.'],
    tags: ['histoire', 'ancient-history'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'an4-1', prompt: 'Quelle civilisation a construit les grandes pyramides ?', choices: ['Les Romains', 'Les Grecs', 'Les Egyptiens', 'Les Mesopotamiens'], answer: 'Les Egyptiens' },
          { id: 'an4-2', prompt: 'Comment s\'appelait le chef supreme de l\'Egypte ancienne ?', choices: ['L\'Empereur', 'Le Pharaon', 'Le Sultan', 'Le Roi'], answer: 'Le Pharaon' },
          { id: 'an4-3', prompt: 'Comment les Egyptiens ecrivaient-ils ?', choices: ['Avec des lettres latines', 'Avec des hieroglyphes', 'Avec des runes', 'Avec des chiffres'], answer: 'Avec des hieroglyphes' },
          { id: 'an4-4', prompt: 'Quel celebre monument se trouve a Rome ?', choices: ['Le Parthenon', 'Le Colisee', 'Les Pyramides', 'Le Sphinx'], answer: 'Le Colisee' },
          { id: 'an4-5', prompt: 'Quelle ville etait la capitale de l\'Empire romain ?', choices: ['Athenes', 'Carthage', 'Rome', 'Constantinople'], answer: 'Rome' },
          { id: 'an4-6', prompt: 'Quel celebre temple grec se trouve sur l\'Acropole d\'Athenes ?', choices: ['Le Colisee', 'Le Parthenon', 'Le Pantheon', 'Les Pyramides'], answer: 'Le Parthenon' },
          { id: 'an4-7', prompt: 'Qui etait le dieu principal des Romains ?', choices: ['Zeus', 'Jupiter', 'Mars', 'Apollon'], answer: 'Jupiter' },
          { id: 'an4-8', prompt: 'Quelle langue parlaient les Romains ?', choices: ['Le grec', 'Le latin', 'L\'egyptien', 'L\'arameen'], answer: 'Le latin' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'an4-9', prompt: 'Ou se trouvait la Grece antique ?', choices: ['En Afrique du nord', 'En Asie', 'Dans le sud de l\'Europe, au bord de la Mediterranee', 'En Gaule'], answer: 'Dans le sud de l\'Europe, au bord de la Mediterranee' },
          { id: 'an4-10', prompt: 'Les Romains ont fonde quelle ville en Belgique actuelle ?', choices: ['Bruxelles', 'Liege', 'Tongres', 'Namur'], answer: 'Tongres' },
          { id: 'an4-11', prompt: 'Comment s\'appelaient les combattants dans les arenes romaines ?', choices: ['Les centurions', 'Les gladiateurs', 'Les legionnaires', 'Les pretoriens'], answer: 'Les gladiateurs' },
          { id: 'an4-12', prompt: 'L\'Antiquite se termine approximativement en...', choices: ['l\'an 0', 'l\'an 476 apr. J.-C.', 'l\'an 1000', 'l\'an 1492'], answer: 'l\'an 476 apr. J.-C.' },
        ],
      },
    ],
  },

  // ── hist-medieval-p4 ──────────────────────────────────────────────────────
  {
    id: 'hist-medieval-p4',
    slug: 'moyen-age-p4',
    title: 'Moyen Age P4',
    subject: 'histoire',
    subskill: 'medieval',
    gradeBand: ['P4'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Chateaux, chevaliers et vie medievale.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Le Moyen Age: de 476 a 1492.'],
    tags: ['histoire', 'medieval'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'ma4-1', prompt: 'Quand commence le Moyen Age ?', choices: ['En l\'an 0', 'En 476 apr. J.-C.', 'En 1000 apr. J.-C.', 'En 1492'], answer: 'En 476 apr. J.-C.' },
          { id: 'ma4-2', prompt: 'Quand se termine le Moyen Age ?', choices: ['En l\'an 1000', 'En 1348', 'En 1492', 'En 1600'], answer: 'En 1492' },
          { id: 'ma4-3', prompt: 'Comment s\'appelle la forteresse ou vivait le seigneur au Moyen Age ?', choices: ['Une cathedrale', 'Un chateau fort', 'Un palais', 'Une abbaye'], answer: 'Un chateau fort' },
          { id: 'ma4-4', prompt: 'Comment appelle-t-on un guerrier a cheval au Moyen Age ?', choices: ['Un soldat', 'Un pirate', 'Un chevalier', 'Un archer'], answer: 'Un chevalier' },
          { id: 'ma4-5', prompt: 'Comment appelle-t-on les paysans qui travaillaient les terres du seigneur ?', choices: ['Les bourgeois', 'Les serfs', 'Les marchands', 'Les moines'], answer: 'Les serfs' },
          { id: 'ma4-6', prompt: 'Quel evenement marque la fin du Moyen Age en 1492 ?', choices: ['La chute de Rome', 'La decouverte de l\'Amerique', 'La Revolution francaise', 'La naissance de Napoleon'], answer: 'La decouverte de l\'Amerique' },
          { id: 'ma4-7', prompt: 'Comment s\'appelait le systeme d\'organisation sociale au Moyen Age ?', choices: ['La democratie', 'La republique', 'La feodalite', 'L\'empire'], answer: 'La feodalite' },
          { id: 'ma4-8', prompt: 'Quelle institution religieuse avait beaucoup de pouvoir au Moyen Age en Europe ?', choices: ['L\'Islam', 'Le Bouddhisme', 'L\'Eglise catholique', 'Le Protestantisme'], answer: 'L\'Eglise catholique' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'ma4-9', prompt: 'Comment appelle-t-on les grandes expeditions militaires chretiennes pour conquerir Jerusalem ?', choices: ['Les invasions', 'Les croisades', 'Les conquetes', 'Les guerres de cent ans'], answer: 'Les croisades' },
          { id: 'ma4-10', prompt: 'La Guerre de Cent Ans opposait la France a quel pays ?', choices: ['L\'Espagne', 'Le Saint-Empire', 'L\'Angleterre', 'L\'Italie'], answer: 'L\'Angleterre' },
          { id: 'ma4-11', prompt: 'Quelle jeune fille a aide la France a gagner la Guerre de Cent Ans ?', choices: ['Marie de Medicis', 'Isabelle de Castille', 'Jeanne d\'Arc', 'Marguerite de Bourgogne'], answer: 'Jeanne d\'Arc' },
          { id: 'ma4-12', prompt: 'Comment s\'appelle le document signe en 1215 qui limitait le pouvoir du roi d\'Angleterre ?', choices: ['La Declaration des droits', 'La Magna Carta', 'Le traite de Westphalie', 'L\'Edit de Nantes'], answer: 'La Magna Carta' },
        ],
      },
    ],
  },

  // ── hist-world-geo-p5 ─────────────────────────────────────────────────────
  {
    id: 'hist-world-geo-p5',
    slug: 'geographie-mondiale-p5',
    title: 'Geographie mondiale P5',
    subject: 'histoire',
    subskill: 'world-geography',
    gradeBand: ['P5'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Les continents, oceans et grandes villes du monde.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['7 continents, 5 oceans.'],
    tags: ['histoire', 'world-geography'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'wg5-1', prompt: 'Combien de continents y a-t-il sur Terre ?', choices: ['5', '6', '7', '8'], answer: '7' },
          { id: 'wg5-2', prompt: 'Quel est le plus grand continent du monde ?', choices: ['L\'Amerique', 'L\'Afrique', 'L\'Asie', 'L\'Europe'], answer: 'L\'Asie' },
          { id: 'wg5-3', prompt: 'Sur quel continent se trouve le Bresil ?', choices: ['Afrique', 'Asie', 'Amerique du Sud', 'Oceanie'], answer: 'Amerique du Sud' },
          { id: 'wg5-4', prompt: 'Quel est le plus grand ocean du monde ?', choices: ['L\'ocean Atlantique', 'L\'ocean Indien', 'L\'ocean Arctique', 'L\'ocean Pacifique'], answer: 'L\'ocean Pacifique' },
          { id: 'wg5-5', prompt: 'Combien d\'oceans y a-t-il sur Terre ?', choices: ['3', '4', '5', '6'], answer: '5' },
          { id: 'wg5-6', prompt: 'Quel desert est le plus grand du monde ?', choices: ['Le Gobi', 'Le Kalahari', 'Le Sahara', 'L\'Atacama'], answer: 'Le Sahara' },
          { id: 'wg5-7', prompt: 'Sur quel continent se trouve l\'Egypte ?', choices: ['Asie', 'Europe', 'Afrique', 'Amerique'], answer: 'Afrique' },
          { id: 'wg5-8', prompt: 'Quelle ligne imaginaire partage la Terre en hemisphere nord et hemisphere sud ?', choices: ['Le meridien de Greenwich', 'Le tropique du Cancer', 'L\'equateur', 'Le cercle polaire'], answer: 'L\'equateur' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'wg5-9', prompt: 'Quel est le plus long fleuve du monde ?', choices: ['L\'Amazone', 'Le Nil', 'Le Yang-Tse', 'Le Mississippi'], answer: 'Le Nil' },
          { id: 'wg5-10', prompt: 'Quelle est la plus haute montagne du monde ?', choices: ['Le Mont Blanc', 'Le Kilimandjaro', 'L\'Everest', 'Le Mont McKinley'], answer: 'L\'Everest' },
          { id: 'wg5-11', prompt: 'Quel pays est le plus peuple du monde ?', choices: ['Les Etats-Unis', 'L\'Inde', 'La Chine', 'Le Bresil'], answer: 'L\'Inde' },
          { id: 'wg5-12', prompt: 'Quelle ville est la plus grande d\'Afrique ?', choices: ['Nairobi', 'Lagos', 'Le Caire', 'Kinshasa'], answer: 'Le Caire' },
        ],
      },
    ],
  },

  // ── hist-modern-p5 ────────────────────────────────────────────────────────
  {
    id: 'hist-modern-p5',
    slug: 'epoque-moderne-p5',
    title: 'Epoque moderne P5',
    subject: 'histoire',
    subskill: 'modern-history',
    gradeBand: ['P5'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Grandes decouvertes, Renaissance et Revolution.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Christophe Colomb en 1492.'],
    tags: ['histoire', 'modern-history'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'mo5-1', prompt: 'Qui a decouvert l\'Amerique en 1492 ?', choices: ['Vasco de Gama', 'Magellan', 'Christophe Colomb', 'Marco Polo'], answer: 'Christophe Colomb' },
          { id: 'mo5-2', prompt: 'Que signifie la Renaissance ?', choices: ['Une guerre europeenne', 'Un renouveau artistique et intellectuel en Europe', 'Une revolution politique', 'La reconquete de Jerusalem'], answer: 'Un renouveau artistique et intellectuel en Europe' },
          { id: 'mo5-3', prompt: 'Quel artiste de la Renaissance a peint La Joconde ?', choices: ['Michel-Ange', 'Leonard de Vinci', 'Raphael', 'Botticelli'], answer: 'Leonard de Vinci' },
          { id: 'mo5-4', prompt: 'Qui a realise le premier tour du monde en bateau ?', choices: ['Christophe Colomb', 'Vasco de Gama', 'Magellan et son equipage', 'Marco Polo'], answer: 'Magellan et son equipage' },
          { id: 'mo5-5', prompt: 'Quelle invention de Gutenberg a revolutionne la diffusion des idees ?', choices: ['La boussole', 'L\'imprimerie', 'La poudre a canon', 'La lunette astronomique'], answer: 'L\'imprimerie' },
          { id: 'mo5-6', prompt: 'La Revolution francaise a eu lieu en quelle annee ?', choices: ['1776', '1789', '1815', '1848'], answer: '1789' },
          { id: 'mo5-7', prompt: 'Quel scientifique a defendu l\'idee que la Terre tourne autour du Soleil ?', choices: ['Newton', 'Copernic', 'Galilee', 'Kepler'], answer: 'Copernic' },
          { id: 'mo5-8', prompt: 'Que representait la guillotine pendant la Revolution francaise ?', choices: ['Un instrument de musique', 'Un instrument d\'execution capitale', 'Une machine agricole', 'Un outil de construction'], answer: 'Un instrument d\'execution capitale' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'mo5-9', prompt: 'Quelle devise symbolise la Revolution francaise ?', choices: ['Travail, Famille, Patrie', 'Liberte, Egalite, Fraternite', 'Foi, Esperance, Charite', 'Honneur, Patrie, Valeur'], answer: 'Liberte, Egalite, Fraternite' },
          { id: 'mo5-10', prompt: 'Qui etait Napoleon Bonaparte ?', choices: ['Un roi de France', 'Un explorateur', 'Un general devenu empereur des Francais', 'Un peintre de la Renaissance'], answer: 'Un general devenu empereur des Francais' },
          { id: 'mo5-11', prompt: 'L\'Epoque moderne s\'etend approximativement de 1492 jusqu\'a...', choices: ['1600', '1789', '1815', '1900'], answer: '1789' },
          { id: 'mo5-12', prompt: 'Quel explorateur portugais a ouvert la route maritime vers l\'Inde ?', choices: ['Christophe Colomb', 'Amerigo Vespucci', 'Vasco de Gama', 'Bartolomeu Dias'], answer: 'Vasco de Gama' },
        ],
      },
    ],
  },

  // ── hist-contemporary-p6 ──────────────────────────────────────────────────
  {
    id: 'hist-contemporary-p6',
    slug: 'epoque-contemporaine-p6',
    title: 'Monde contemporain P6',
    subject: 'histoire',
    subskill: 'contemporary',
    gradeBand: ['P6'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'La Premiere et Deuxieme Guerre mondiale, la construction de l\'Europe.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['L\'UE a ete fondee en 1957.'],
    tags: ['histoire', 'contemporary'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'co6-1', prompt: 'En quelle annee a commence la Premiere Guerre mondiale ?', choices: ['1905', '1914', '1918', '1939'], answer: '1914' },
          { id: 'co6-2', prompt: 'En quelle annee s\'est terminee la Premiere Guerre mondiale ?', choices: ['1914', '1916', '1918', '1920'], answer: '1918' },
          { id: 'co6-3', prompt: 'En quelle annee a commence la Seconde Guerre mondiale ?', choices: ['1933', '1936', '1939', '1941'], answer: '1939' },
          { id: 'co6-4', prompt: 'Quel evenement a marque la fin de la Seconde Guerre mondiale en Europe ?', choices: ['La bataille de Verdun', 'Le debarquement en Normandie', 'La chute de Berlin en mai 1945', 'La bombe atomique'], answer: 'La chute de Berlin en mai 1945' },
          { id: 'co6-5', prompt: 'Qui etait Adolf Hitler ?', choices: ['Un general americain', 'Le chef du regime nazi en Allemagne', 'Le roi d\'Allemagne', 'Un homme politique francais'], answer: 'Le chef du regime nazi en Allemagne' },
          { id: 'co6-6', prompt: 'Comment s\'appelait l\'extermination systematique des Juifs par les nazis ?', choices: ['La deportation', 'La guerre totale', 'La Shoah ou Holocaust', 'Le grand nettoyage'], answer: 'La Shoah ou Holocaust' },
          { id: 'co6-7', prompt: 'En quelle annee a ete fondee la Communaute economique europeenne (ancetre de l\'UE) ?', choices: ['1945', '1950', '1957', '1975'], answer: '1957' },
          { id: 'co6-8', prompt: 'Quel mur symbole de la Guerre froide est tombe en 1989 ?', choices: ['Le mur d\'Hadrien', 'Le mur de Chine', 'Le mur de Berlin', 'Le mur de Varsovie'], answer: 'Le mur de Berlin' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'co6-9', prompt: 'Quelle organisation internationale a ete creee apres la Seconde Guerre mondiale pour maintenir la paix ?', choices: ['L\'OTAN', 'L\'ONU', 'L\'OSCE', 'L\'UNESCO'], answer: 'L\'ONU' },
          { id: 'co6-10', prompt: 'Quel etait le president americain lors du debarquement en Normandie en 1944 ?', choices: ['Woodrow Wilson', 'Herbert Hoover', 'Franklin Roosevelt', 'Harry Truman'], answer: 'Franklin Roosevelt' },
          { id: 'co6-11', prompt: 'La Belgique a ete independante depuis...', choices: ['1789', '1815', '1830', '1848'], answer: '1830' },
          { id: 'co6-12', prompt: 'Comment appelle-t-on la periode de tension entre les Etats-Unis et l\'URSS apres 1945 ?', choices: ['La Guerre chaude', 'La Guerre froide', 'La Detente', 'La coexistence'], answer: 'La Guerre froide' },
        ],
      },
    ],
  },

  // ── hist-citizenship-p6 ───────────────────────────────────────────────────
  {
    id: 'hist-citizenship-p6',
    slug: 'citoyennete-p6',
    title: 'Citoyennete P6',
    subject: 'histoire',
    subskill: 'citizenship',
    gradeBand: ['P6'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Democratie, droits de l\'enfant et institutions belges.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Les droits de l\'enfant: ONU 1989.'],
    tags: ['histoire', 'citizenship'],
    sections: [
      {
        id: 'practice',
        title: 'Exploration',
        kind: 'practice',
        lessons: [
          { id: 'ci6-1', prompt: 'En quelle annee la Convention des droits de l\'enfant a-t-elle ete adoptee par l\'ONU ?', choices: ['1945', '1959', '1989', '2000'], answer: '1989' },
          { id: 'ci6-2', prompt: 'Que signifie la democratie ?', choices: ['Le pouvoir d\'un seul homme', 'Le pouvoir du peuple', 'Le pouvoir de l\'eglise', 'Le pouvoir de l\'armee'], answer: 'Le pouvoir du peuple' },
          { id: 'ci6-3', prompt: 'Comment les citoyens participent-ils a la democratie ?', choices: ['En obeissant au roi', 'En votant et en participant a la vie publique', 'En payant des impots seulement', 'En ne faisant rien'], answer: 'En votant et en participant a la vie publique' },
          { id: 'ci6-4', prompt: 'Quel est le droit fondamental de tout enfant selon la Convention de l\'ONU ?', choices: ['Le droit de travailler', 'Le droit a l\'education, a la sante et a la protection', 'Le droit de voter', 'Le droit de quitter son pays'], answer: 'Le droit a l\'education, a la sante et a la protection' },
          { id: 'ci6-5', prompt: 'Comment s\'appelle le parlement federal de la Belgique ?', choices: ['L\'Assemblee nationale', 'La Chambre des representants', 'Le Senat uniquement', 'Le Conseil d\'Etat'], answer: 'La Chambre des representants' },
          { id: 'ci6-6', prompt: 'Combien de pouvoirs composent un Etat democratique ?', choices: ['1', '2', '3', '4'], answer: '3', explanation: 'Pouvoir legislatif, executif et judiciaire.' },
          { id: 'ci6-7', prompt: 'Quel pouvoir fait les lois en Belgique ?', choices: ['Le pouvoir executif', 'Le pouvoir judiciaire', 'Le pouvoir legislatif', 'Le pouvoir royal'], answer: 'Le pouvoir legislatif' },
          { id: 'ci6-8', prompt: 'Quel pouvoir applique les lois et gouverne en Belgique ?', choices: ['Le pouvoir legislatif', 'Le pouvoir executif', 'Le pouvoir judiciaire', 'Le pouvoir communal'], answer: 'Le pouvoir executif' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'ci6-9', prompt: 'Que signifie l\'egalite dans une democratie ?', choices: ['Tout le monde est identique', 'Tous les citoyens ont les memes droits devant la loi', 'Les riches ont plus de droits', 'Seuls les adultes ont des droits'], answer: 'Tous les citoyens ont les memes droits devant la loi' },
          { id: 'ci6-10', prompt: 'Qu\'est-ce qu\'une constitution ?', choices: ['Un impot obligatoire', 'La loi fondamentale qui organise l\'Etat', 'Un traite international', 'Un reglement scolaire'], answer: 'La loi fondamentale qui organise l\'Etat' },
          { id: 'ci6-11', prompt: 'A partir de quel age peut-on voter en Belgique ?', choices: ['16 ans', '18 ans', '21 ans', '25 ans'], answer: '18 ans' },
          { id: 'ci6-12', prompt: 'Qu\'est-ce que la liberte d\'expression ?', choices: ['Le droit de tout faire', 'Le droit d\'exprimer ses opinions dans le respect des autres', 'Le droit de mentir sans consequence', 'Le droit de refuser l\'ecole'], answer: 'Le droit d\'exprimer ses opinions dans le respect des autres' },
        ],
      },
    ],
  },
];
