// Spanish translations for all 19 fairy tales.
// Only content fields are translated — id, emoji, coverImage, palette,
// difficulty, ageMin, ageMax, rewardEmoji are intentionally omitted.

export const CONTES_ES = {
  'snow-white': {
    title: 'Blancanieves',
    summary: 'Una dulce princesa con la piel blanca como la nieve encuentra un hogar junto a siete pequenos amigos bondadosos y aprende que los verdaderos amigos siempre cuidan los unos de los otros.',
    theme: 'bondad y amistad',
    scenes: [
      { text: 'Hace mucho tiempo, nacio una pequena princesa con la piel blanca como la nieve. Todo el mundo la llamaba Blancanieves.' },
      { text: 'Una reina celosa tenia un espejo magico y le hacia la misma pregunta cada dia.', dialogue: { speaker: 'Reina', line: 'Espejito, espejito, quien es la mas bondadosa y hermosa de todas?' } },
      { text: 'Blancanieves camino hasta el corazon del bosque. Siete pequenos mineros bondadosos la acogieron en su acogedora cabana.', dialogue: { speaker: 'Un minero', line: 'Estas a salvo aqui, pequeña amiga. Ven a descansar.' } },
      { text: 'La reina la engano con una manzana brillante, y Blancanieves cayo en un sueno muy, muy profundo.' },
      { text: 'Una amiga carinosa la desperto con un gesto muy suave. Blancanieves sonrio, y todos celebraron a su valiente amiga.', dialogue: { speaker: 'Blancanieves', line: 'Nunca me abandonasteis. Gracias, mis amigos!' } },
    ],
    vocabulary: [
      { word: 'la mas bella', meaning: 'la persona mas bondadosa y mas bonita', emoji: '🌷' },
      { word: 'celosa', meaning: 'enfadada porque quiere lo que tiene otra persona', emoji: '😠' },
      { word: 'cabana', meaning: 'una casita pequena y acogedora', emoji: '🏡' },
      { word: 'acoger', meaning: 'hacer que alguien se sienta feliz de haber llegado', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos pequenos mineros bondadosos acogieron a Blancanieves?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'rodeada y protegida', prompt: 'Los amigos de Blancanieves velaban por ella. Quien vela por ti?' },
    rewardName: 'Espejo bondadoso',
  },

  'cinderella': {
    title: 'Cenicienta',
    summary: 'Una chica trabajadora con un gran corazon recibe un poco de ayuda de una amiga magica y descubre que ser amable es una magia en si misma.',
    theme: 'esperanza y bondad',
    scenes: [
      { text: 'Cenicienta hacia todas las tareas y nunca perdia su dulce sonrisa, aunque los demas fueran crueles.' },
      { text: 'Una noche, se anuncio un gran baile, pero Cenicienta no tenia nada que ponerse.', dialogue: { speaker: 'Cenicienta', line: 'Si al menos pudiera ir a bailar, solo una vez.' } },
      { text: 'Aparecio un hada bondadosa y, con un toque de su varita, convirtio una calabaza en una carroza.', dialogue: { speaker: 'Hada amiga', line: 'Vuelve antes de medianoche, querida — entonces la magia se acaba.' } },
      { text: 'En el baile, Cenicienta bailo y rio. Pero cuando el reloj empezo a sonar, tuvo que correr.' },
      { text: 'El zapatito le quedaba perfectamente. Su bondad siempre habia sido visible, y la alegria lleno sus dias.', dialogue: { speaker: 'Cenicienta', line: 'Ser amable no cuesta nada.' } },
    ],
    vocabulary: [
      { word: 'tareas', meaning: 'pequenos trabajos para ayudar en casa', emoji: '🧹' },
      { word: 'carroza', meaning: 'un coche tirado para transportar a personas', emoji: '🛞' },
      { word: 'medianoche', meaning: 'las doce de la noche', emoji: '🕛' },
      { word: 'dulce', meaning: 'tierno, tranquilo y amable', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'A que hora debe volver Cenicienta? Cuenta los golpes del reloj!', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'llena de esperanza', prompt: 'Incluso en los dias dificiles, Cenicienta seguia siendo amable. Que te ayuda a mantener la esperanza?' },
    rewardName: 'Zapatilla de cristal',
  },

  'little-red-riding-hood': {
    title: 'Caperucita Roja',
    summary: 'Una valiente nina con una caperuza roja va a casa de su abuela y aprende a escuchar sus sabios instintos durante el camino.',
    theme: 'escuchar y mantenerse a salvo',
    scenes: [
      { text: 'Una ninita llevaba una brillante caperuza roja a todas partes, asi que todo el mundo la llamaba Caperucita Roja.' },
      { text: 'Su mama le dio una cesta con pan para la abuela.', dialogue: { speaker: 'Mama', line: 'Quédate en el camino y todo ira bien.' } },
      { text: 'En el bosque, un lobo astuto hizo muchas preguntas. Caperucita sintio que algo era extrano y siguio caminando.', dialogue: { speaker: 'Caperucita', line: 'No tengo que responderte. Se lo dire a un adulto.' } },
      { text: 'Un amable lenador la escucho y camino con ella. Juntos llegaron a casa de la abuela.' },
      { text: 'La abuela estaba a salvo, y Caperucita tambien. Compartieron pan caliente y rieron toda la tarde.', dialogue: { speaker: 'Abuela', line: 'Escuchaste tus sabios instintos. Estoy muy orgullosa de ti.' } },
    ],
    vocabulary: [
      { word: 'camino', meaning: 'una senda que te muestra por donde ir a salvo', emoji: '🛤️' },
      { word: 'cesta', meaning: 'un portador con asa para llevar cosas', emoji: '🧺' },
      { word: 'astuto', meaning: 'alguien que usa trucos para enganarte', emoji: '🦊' },
      { word: 'lenador', meaning: 'una persona que trabaja entre los arboles', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'Un desconocido le pregunta a Caperucita adonde va. Cual es la eleccion segura?', options: ['Contarle todo', 'Seguir caminando y avisar a un adulto', 'Seguirle entre los arboles'], answerIndex: 1 },
    emotionalMoment: { feeling: 'a salvo', prompt: 'Caperucita escucho su extrana sensacion. Cuando te ha ayudado un instinto a mantenerte a salvo?' },
    rewardName: 'Caperuza roja',
  },

  'hansel-and-gretel': {
    title: 'Hansel y Gretel',
    summary: 'Un hermano y una hermana se pierden en el bosque y usan un plan astuto, y su trabajo en equipo, para llegar sanos y salvos a casa.',
    theme: 'astucia y permanecer juntos',
    scenes: [
      { text: 'Hansel y Gretel se adentraron en el gran bosque cogidos de la mano para no perderse.' },
      { text: 'El astuto Hansel fue dejando caer pequenas piedrecitas blancas y brillantes, una a una, para marcar el camino de vuelta.', dialogue: { speaker: 'Hansel', line: 'Estas piedrecitas brillaran y nos llevaran a casa.' } },
      { text: 'Encontraron una casita hecha de dulces, pero una vieja astuta vivia alli.' },
      { text: 'Los ninos eran demasiado listos para dejarse enganar. Se cogieron de la mano y salieron de puntillas.', dialogue: { speaker: 'Gretel', line: 'Rapido — juntos somos mas valientes que solos.' } },
      { text: 'Las brillantes piedrecitas destellaron a la luz de la luna y los llevaron directamente a casa, hacia un calido abrazo.' },
    ],
    vocabulary: [
      { word: 'piedrecitas', meaning: 'pequenas y lisas piedritas', emoji: '🪨' },
      { word: 'astuto', meaning: 'bueno para pensar ideas inteligentes', emoji: '💡' },
      { word: 'de puntillas', meaning: 'caminar muy despacio sobre los dedos de los pies', emoji: '🦶' },
      { word: 'juntos', meaning: 'el uno con el otro, codo con codo', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon el plan astuto de Hansel en el orden correcto!', steps: ['Dejar caer las piedrecitas brillantes', 'Seguir el rastro que centellea', 'Encontrar el camino a casa'] },
    emotionalMoment: { feeling: 'valientes juntos', prompt: 'Los ninos eran mas valientes en equipo. Quien te hace mas valiente?' },
    rewardName: 'Piedrecita brillante',
  },

  'rapunzel': {
    title: 'Rapunzel',
    summary: 'Una nina amable con un pelo muy largo vive en una alta torre y aprende que la paciencia y un corazon lleno de esperanza pueden abrir cualquier puerta.',
    theme: 'paciencia y esperanza',
    scenes: [
      { text: 'En lo alto de una gran torre vivia Rapunzel, una nina con la trenza dorada mas larga del mundo.' },
      { text: 'Cada dia, Rapunzel cantaba a los pajaros. Su dulce cancion flotaba por todo el bosque.', dialogue: { speaker: 'Rapunzel', line: 'Algun dia vere el mundo de ahi abajo, bajo los arboles.' } },
      { text: 'Un amable viajero escucho su cancion y le grito: "Tu musica hace sonreir a todo el bosque!"', dialogue: { speaker: 'Viajero', line: 'Tu musica hace sonreir a todo el bosque!' } },
      { text: 'Se hicieron amigos. Dia tras dia, con paciencia, pensaron en una forma inteligente de bajar.' },
      { text: 'Por fin, Rapunzel puso el pie en la hierba suave y giro bajo el sol, libre y feliz.', dialogue: { speaker: 'Rapunzel', line: 'Esperar fue dificil, pero la esperanza me mantuvo fuerte.' } },
    ],
    vocabulary: [
      { word: 'torre', meaning: 'un edificio muy alto y estrecho', emoji: '🗼' },
      { word: 'trenza', meaning: 'pelo entrelazado formando una larga cuerda', emoji: '💇' },
      { word: 'paciencia', meaning: 'esperar con calma sin rendirse', emoji: '⏳' },
      { word: 'prado', meaning: 'un campo de hierba lleno de flores', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Encuentra lo que uso Rapunzel para bajar a salvo.', target: 'la escalera de trenza dorada', decoys: ['una cometa de papel', 'una cuchara de madera', 'una tacita'] },
    emotionalMoment: { feeling: 'paciente', prompt: 'Rapunzel espero con esperanza. Que cosa bonita has esperado durante mucho tiempo?' },
    rewardName: 'Trenza dorada',
  },

  'the-ugly-duckling': {
    title: 'El Patito Feo',
    summary: 'Un pajarito que se siente diferente a los demas crece y descubre que siempre fue maravilloso exactamente como era.',
    theme: 'pertenecer y quererse a uno mismo',
    scenes: [
      { text: 'En un estanque soleado, un pajarito no se parecia a sus hermanos y hermanas.' },
      { text: 'Los otros pajaros se burlaban de el, y en el fondo se sentia solo y muy triste.', dialogue: { speaker: 'Pajarito', line: 'Ojala alguien me dejara jugar tambien.' } },
      { text: 'Una rana amable se acerco saltando y se sento a su lado. "Eres bienvenido conmigo", dijo.', dialogue: { speaker: 'Rana', line: 'Eres bienvenido conmigo, amigo mio.' } },
      { text: 'Pasaron las estaciones. Una manana luminosa, el pajarito vio su cara en el agua tranquila.' },
      { text: 'Se habia convertido en un hermoso cisne! Siempre habia sido especial: simplemente el mismo.', dialogue: { speaker: 'Cisne', line: 'No necesitaba cambiar. Solo necesitaba crecer.' } },
    ],
    vocabulary: [
      { word: 'estanque', meaning: 'una pequena extension de agua tranquila', emoji: '💧' },
      { word: 'solo', meaning: 'triste porque te sientes completamente solo', emoji: '🥺' },
      { word: 'reflejo', meaning: 'la imagen que ves en el agua tranquila', emoji: '🪞' },
      { word: 'cisne', meaning: 'un gran pajaro de agua blanco y elegante', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'Un nuevo amigo se siente excluido. Que cosa amable puedes decirle?', options: ['No perteneces aqui', 'Puedes jugar con nosotros!', 'Vete'], answerIndex: 1 },
    emotionalMoment: { feeling: 'pertenezco aqui', prompt: 'El pajarito era especial tal como era. Que te hace ser un maravilloso tu?' },
    rewardName: 'Cisne suave',
  },

  'the-little-mermaid': {
    title: 'La Sirenita',
    summary: 'Una joven sirena curiosa tiene el valor de explorar un mundo nuevo y aprende que un corazon bondadoso y generoso brilla mas que cualquier cosa.',
    theme: 'valentia y buen corazon',
    scenes: [
      { text: 'En el fondo de las olas vivia una joven sirena, la mas pequena de seis hermanas.' },
      { text: 'Le encantaba nadar hasta la superficie y contemplar el luminoso mundo sobre el agua.', dialogue: { speaker: 'Sirena', line: 'El mundo de ahi arriba esta lleno de cosas que quiero aprender!' } },
      { text: 'Una noche de tormenta, con valentia, ayudo a un marinero a llegar a la orilla a salvo.' },
      { text: 'No se quedo para ser agradecida. Ayudar a alguien llenaba su corazon de calor.', dialogue: { speaker: 'Sirena', line: 'Ayude por bondad, no para recibir las gracias.' } },
      { text: 'De vuelta en casa, conto su valiente historia, y su buen corazon hizo brillar todo el mar.' },
    ],
    vocabulary: [
      { word: 'sirena', meaning: 'una chica del mar imaginaria, con cola de pez', emoji: '🧜' },
      { word: 'olas', meaning: 'el agua que sube y baja en el mar', emoji: '🌊' },
      { word: 'valiente', meaning: 'hacer algo dificil aunque de miedo', emoji: '💪' },
      { word: 'generosa', meaning: 'feliz de dar y ayudar a los demas', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantas hermanas mayores tenia la Sirenita?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'de gran corazon', prompt: 'La sirena ayudo solo por bondad. Cuando has ayudado sin que nadie te lo pidiera?' },
    rewardName: 'Perla del mar',
  },

  'the-snow-queen': {
    title: 'La Reina de las Nieves',
    summary: 'Cuando el corazon de su mejor amigo se vuelve frio, una fiel nina llamada Gerda viaja lejos entre la nieve para calentarlo con amor.',
    theme: 'amistad fiel',
    scenes: [
      { text: 'Gerda y Kai eran los mejores amigos y cultivaban rosas juntos cerca de su ventana.' },
      { text: 'Un minusculo cristal de hielo toco el corazon de Kai, y el se volvio frio y distante.', dialogue: { speaker: 'Gerda', line: 'Espera... adonde vas, Kai?' } },
      { text: 'La valiente Gerda no se rindio. Partio a traves de la nieve a buscar a su amigo.', dialogue: { speaker: 'Gerda', line: 'Te encontrare, Kai. Los amigos no se rinden.' } },
      { text: 'Encontro a Kai en un palacio de hielo, sentado, inmovil y frio como una piedra.' },
      { text: 'Gerda lo abrazo y lagrimas calidas cayeron. El hielo se derrrtio, y Kai sonrio y lo recordo todo.', dialogue: { speaker: 'Kai', line: 'Has venido hasta aqui por mi. Gracias, Gerda.' } },
    ],
    vocabulary: [
      { word: 'escarcha', meaning: 'una fina capa de hielo que se forma cuando hace mucho frio', emoji: '🌨️' },
      { word: 'fiel', meaning: 'siempre estar ahi para tus amigos', emoji: '🤲' },
      { word: 'palacio', meaning: 'una casa muy grande y magnifica', emoji: '🏰' },
      { word: 'derretirse', meaning: 'pasar del hielo al agua con el calor', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'Como derrrtio Gerda el hielo en el corazon de Kai?', options: ['Con un gran fuego', 'Con lagrimas calidas y un abrazo', 'Con un martillo'], answerIndex: 1 },
    emotionalMoment: { feeling: 'fiel', prompt: 'Gerda nunca abandono a su amigo. Como le muestras a un amigo que te importa?' },
    rewardName: 'Rosa calida',
  },

  'puss-in-boots': {
    title: 'El Gato con Botas',
    summary: 'Un gato listo con unas botas preciosas usa su ingenio y su leal corazon para ayudar a su bondadoso amigo a encontrar la felicidad.',
    theme: 'astucia y lealtad',
    scenes: [
      { text: 'Un gato listo se puso unas botas preciosas y un sombrero con pluma, listo para la aventura.' },
      { text: 'Su amigo era pobre pero bondadoso, asi que el gato penso en un plan astuto para ayudarle.', dialogue: { speaker: 'El Gato', line: 'Confía en mi, amigo. Una idea lista esta en camino!' } },
      { text: 'El gato saludo al rey con cortesia y le ofrecio regalos, haciendo sonreir a todo el mundo.' },
      { text: 'Con ingenio en lugar de trucos, el gato ayudo a su amigo a ganar un gran castillo junto al rio.', dialogue: { speaker: 'El Gato', line: 'Las buenas ideas abren mas puertas que los grandes rugidos.' } },
      { text: 'Su amigo fue feliz por fin, y el gato se acurruco junto al fuego, el gato mas fiel de todos.' },
    ],
    vocabulary: [
      { word: 'listo', meaning: 'bueno para encontrar ideas ingeniosas', emoji: '🧠' },
      { word: 'botas', meaning: 'zapatos que suben alto por las piernas', emoji: '🥾' },
      { word: 'cortes', meaning: 'amable y gentil con sus palabras', emoji: '🙏' },
      { word: 'leal', meaning: 'siempre estar ahi para tus amigos', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon el plan astuto del Gato en el orden correcto!', steps: ['Ponerse las botas preciosas', 'Saludar al rey con cortesia', 'Ayudar a su amigo a ganar el dia'] },
    emotionalMoment: { feeling: 'servicial', prompt: 'El Gato uso ideas listas para ayudar a un amigo. De que forma astuta has ayudado tu a alguien?' },
    rewardName: 'Botas preciosas',
  },

  'pinocchio': {
    title: 'Pinocho',
    summary: 'Un muneco de madera que suena con ser un nino de verdad aprende que decir la verdad es lo que hace crecer un buen corazon.',
    theme: 'honestidad',
    scenes: [
      { text: 'Habia una vez un pequeno muneco de madera llamado Pinocho, que sonaba con convertirse en un nino de verdad.' },
      { text: 'Cada vez que Pinocho decia una mentira, su nariz crecía como una rama.', dialogue: { speaker: 'Pinocho', line: 'No fui yo! Te lo prometo!' } },
      { text: 'Su amigo el grillo intentaba ensenarle a decir siempre la verdad.', dialogue: { speaker: 'Grillo', line: 'Decir la verdad te hara sentir ligero como una pluma.' } },
      { text: 'Pinocho cometio un gran error y se perdio. Aprendio entonces que la honestidad era su unica guia.' },
      { text: 'Cuando Pinocho dijo por fin la verdad, su corazon crecio, y su mayor deseo se hizo realidad.', dialogue: { speaker: 'Pinocho', line: 'La verdad es la magia mas poderosa de todas.' } },
    ],
    vocabulary: [
      { word: 'muneco', meaning: 'una muneca que se hace mover', emoji: '🎭' },
      { word: 'verdad', meaning: 'decir exactamente lo que ha pasado', emoji: '✅' },
      { word: 'mentira', meaning: 'decir algo que no es cierto', emoji: '❌' },
      { word: 'honesto', meaning: 'alguien que siempre dice la verdad', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'Cuando se alarga la nariz de Pinocho?', options: ['Cuando dice la verdad', 'Cuando dice una mentira', 'Cuando canta una cancion'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honesto', prompt: 'Decir la verdad hizo sentir a Pinocho ligero. Como te sientes tu cuando dices la verdad?' },
    rewardName: 'Grillo de la verdad',
  },

  'peter-pan': {
    title: 'Peter Pan',
    summary: 'Un nino que nunca crece lleva a nuevos amigos a una aventura voladora donde los pensamientos felices y un poco de valentia te llevan a cualquier parte.',
    theme: 'imaginacion y valentia',
    scenes: [
      { text: 'En una habitacion llena de estrellas, un nino llamado Peter Pan enseno a los ninos a volar.' },
      { text: 'Peter le dijo a Wendy el secreto: habia que pensar en algo muy feliz.', dialogue: { speaker: 'Peter Pan', line: 'Piensa en tu cosa mas feliz — y hop, te elevas!' } },
      { text: 'Juntos volaron hacia el Pais de Nunca Jamas, una isla magica llena de aventuras.' },
      { text: 'Incluso frente al malvado capitan, Peter no tuvo miedo. Afronto el peligro con una gran sonrisa.', dialogue: { speaker: 'Peter Pan', line: 'Ser valiente es intentarlo de todas formas.' } },
      { text: 'Los ninos volvieron a casa con recuerdos en el corazon y un poco de magia para siempre.' },
    ],
    vocabulary: [
      { word: 'habitacion', meaning: 'la habitacion donde duermes y suenas', emoji: '🛏️' },
      { word: 'sombra', meaning: 'la forma oscura que hace tu cuerpo en el suelo', emoji: '👤' },
      { word: 'imaginar', meaning: 'crear cosas bonitas dentro de tu cabeza', emoji: '💭' },
      { word: 'valentia', meaning: 'intentarlo aunque tengas miedo', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Que ayudo a los ninos a volar?', options: ['Pensamientos felices y polvo de hada', 'Botas pesadas', 'Gritar muy fuerte'], answerIndex: 0 },
    emotionalMoment: { feeling: 'valiente', prompt: 'Peter dice que ser valiente es intentarlo de todas formas. Que cosa valiente te gustaria intentar?' },
    rewardName: 'Polvo de hada',
  },

  'alice-in-wonderland': {
    title: 'Alicia en el Pais de las Maravillas',
    summary: 'Una nina curiosa sigue a un conejo apresurado a un mundo al reves y aprende que hacer preguntas es una especie de magia.',
    theme: 'curiosidad',
    scenes: [
      { text: 'Alicia vio un conejo blanco apresurado que saltaba a una madriguera y, muy curiosa, lo siguio.' },
      { text: 'Cayo por un largo pasillo magico y encontro una pequenísima puerta que daba a un jardin.', dialogue: { speaker: 'Alicia', line: 'Que raro! Me pregunto que pasa aqui.' } },
      { text: 'Alicia bebio un pequeno frasco y se encogio, luego comio un pastel y crecio muy rapido.', dialogue: { speaker: 'Alicia', line: 'Las preguntas son la llave de todas las maravillas!' } },
      { text: 'Conocio a un gato sonriente, una reina enfadada y un sombrerero muy loco.' },
      { text: 'Alicia se desperto y sonrio. Hacer preguntas la habia llevado al mas bonito de los suenos.', dialogue: { speaker: 'Alicia', line: 'La curiosidad es la aventura mas grande.' } },
    ],
    vocabulary: [
      { word: 'curiosa', meaning: 'alguien que ama descubrir cosas nuevas', emoji: '🔍' },
      { word: 'madriguera', meaning: 'un tunel excavado en la tierra por un animal', emoji: '🕳️' },
      { word: 'encogerse', meaning: 'hacerse mas pequeno', emoji: '🔻' },
      { word: 'maravilla', meaning: 'algo increible y muy sorprendente', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon la aventura de Alicia en el orden correcto!', steps: ['Beber el frasco y encogerse', 'Comer el pastel y crecer', 'Encontrar la pequena puerta del jardin'] },
    emotionalMoment: { feeling: 'curiosa', prompt: 'A Alicia le encantaba hacer preguntas. De que tienes curiosidad hoy?' },
    rewardName: 'Reloj curioso',
  },

  'the-wizard-of-oz': {
    title: 'El Mago de Oz',
    summary: 'Una nina y tres nuevos amigos siguen un camino dorado y descubren que los dones que buscaban estaban dentro de ellos desde el principio.',
    theme: 'ya tienes lo que necesitas',
    scenes: [
      { text: 'Un gran torbellino llevo a Dorothy y a su pequeno perro Toto al magico pais de Oz.' },
      { text: 'En el camino dorado, Dorothy conocio a un espantapajaros, un hombre de hojalata y un leon.', dialogue: { speaker: 'Espantapajaros', line: 'Solo quiero un cerebro listo!' } },
      { text: 'Juntos caminaron hacia la Ciudad Esmeralda para encontrar al gran Mago.', dialogue: { speaker: 'Dorothy', line: 'Si estamos juntos, podemos hacer cualquier cosa.' } },
      { text: 'El Mago les revelo un gran secreto: ya tenian todo lo que deseaban.' },
      { text: 'Dorothy golpeo tres veces sus zapatillas y volvio a casa. Cada uno habia encontrado su don.', dialogue: { speaker: 'Dorothy', line: 'No hay ningun lugar como el hogar.' } },
    ],
    vocabulary: [
      { word: 'torbellino', meaning: 'un viento muy fuerte que gira en redondo', emoji: '🌪️' },
      { word: 'espantapajaros', meaning: 'un muneco grande de paja para espantar a los pajaros', emoji: '🌾' },
      { word: 'valentia', meaning: 'seguir adelante aunque tengas miedo', emoji: '💪' },
      { word: 'viaje', meaning: 'un largo camino o aventura hacia un lugar nuevo', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Cual de los amigos ya tenia valentia desde el principio?', options: ['El espantapajaros', 'El hombre de hojalata', 'El leon'], answerIndex: 2 },
    emotionalMoment: { feeling: 'capaz', prompt: 'Los amigos ya tenian sus dones dentro de ellos. Que don tienes ya en ti?' },
    rewardName: 'Zapatillas brillantes',
  },

  'robin-hood': {
    title: 'Robin Hood',
    summary: 'Un amable arquero del bosque verde comparte con quienes tienen muy poco y ensena a sus amigos que la justicia hace a todos mas felices.',
    theme: 'justicia y generosidad',
    scenes: [
      { text: 'En un gran bosque verde vivia Robin Hood, el mejor arquero del pais.' },
      { text: 'Vio que mucha gente era muy pobre mientras que otros lo tenian todo.', dialogue: { speaker: 'Robin', line: 'Compartir es el mejor de los regalos.' } },
      { text: 'Con sus alegres amigos, Robin diseno un plan para ayudar a quienes estaban en necesidad.', dialogue: { speaker: 'Pequeno Juan', line: 'Juntos somos la fuerza del bosque!' } },
      { text: 'Robin repartio lo que la gente necesitaba, y las sonrisas florecieron por todas partes.' },
      { text: 'El bosque vibro de felicidad. Robin habia aprendido que la generosidad es la verdadera victoria.', dialogue: { speaker: 'Robin', line: 'La generosidad hace a todos mas ricos.' } },
    ],
    vocabulary: [
      { word: 'arquero', meaning: 'alguien que dispara flechas con un arco', emoji: '🎯' },
      { word: 'bosque', meaning: 'un gran lugar lleno de arboles y animales', emoji: '🌳' },
      { word: 'justo', meaning: 'tratar a todo el mundo de la misma manera', emoji: '⚖️' },
      { word: 'generoso', meaning: 'que le gusta dar y compartir', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin Hood compartia con personas que estaban...', options: ['hambrientas y necesitadas', 'ya muy ricas', 'siendo crueles con otros'], answerIndex: 0 },
    emotionalMoment: { feeling: 'justo', prompt: 'A Robin le encantaba compartir. Que podrias compartir para hacer sonreir a un amigo?' },
    rewardName: 'Arco amistoso',
  },

  'goldilocks': {
    title: 'Ricitos de Oro',
    summary: 'Una nina curiosa entra en la acogedora cabana de los osos y aprende que es mejor pedir permiso primero y cuidar las cosas de los demas.',
    theme: 'respeto a los demas',
    scenes: [
      { text: 'Una ninita con rizos dorados paseaba por el bosque cuando encontro una bonita cabana.' },
      { text: 'Entro y probo tres cuencos de gachas. El del osito era perfecto.', dialogue: { speaker: 'Ricitos de Oro', line: 'Oh! Este cuenco es perfecto, ni demasiado caliente ni demasiado frio!' } },
      { text: 'Probo tres sillas y luego tres camas. Se quedo dormida en la mas acogedora.' },
      { text: 'Los tres osos volvieron y encontraron su casa desordenada.', dialogue: { speaker: 'Osito', line: 'Alguien ha comido de mi cuenco!' } },
      { text: 'Ricitos de Oro se desperto, pidio perdon y aprendio que pedir primero es la educacion mas dulce.', dialogue: { speaker: 'Ricitos de Oro', line: 'Perdon. Siempre pedire permiso antes de entrar.' } },
    ],
    vocabulary: [
      { word: 'gachas', meaning: 'una comida caliente y suave, como los cereales del desayuno', emoji: '🥣' },
      { word: 'cabana', meaning: 'una casita acogedora en el bosque', emoji: '🏡' },
      { word: 'respeto', meaning: 'cuidar las cosas y los sentimientos de los demas', emoji: '🙏' },
      { word: 'perdon', meaning: 'lo que dices cuando sientes haber hecho algo mal', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos osos vivian en la acogedora cabana?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respetuosa', prompt: 'Ricitos de Oro aprendio a pedir primero. Cuando es amable pedir permiso antes de coger algo prestado?' },
    rewardName: 'Cuenco perfecto',
  },

  'three-little-pigs': {
    title: 'Los Tres Cerditos',
    summary: 'Tres cerditos construyen tres casas diferentes y aprenden que un trabajo cuidadoso y aplicado mantiene a todos a salvo y calentitos.',
    theme: 'trabajo y organizacion',
    scenes: [
      { text: 'Tres cerditos se fueron al mundo a construir sus casas.' },
      { text: 'El primero construyo rapidamente una casa de paja. El segundo, una casa de madera.', dialogue: { speaker: 'Primer cerdito', line: 'Rapido y listo! Quiero ir a jugar!' } },
      { text: 'El tercer cerdito trabajo duro y construyo ladrillo a ladrillo una casa solida de ladrillos.', dialogue: { speaker: 'Tercer cerdito', line: 'Me tomo mi tiempo para que mi casa sea solida.' } },
      { text: 'El gran lobo malo soplo sobre las casas de paja y madera, y se derrumbaron.' },
      { text: 'Pero la casa de ladrillos siguio firme. Los tres cerditos estaban a salvo, y todos aprendieron que trabajar con cuidado protege.', dialogue: { speaker: 'Tercer cerdito', line: 'Un buen trabajo lleva tiempo, pero merece la pena!' } },
    ],
    vocabulary: [
      { word: 'paja', meaning: 'tallos secos de plantas, faciles de romper', emoji: '🌾' },
      { word: 'ladrillos', meaning: 'bloques de tierra cocida muy solidos', emoji: '🧱' },
      { word: 'resistente', meaning: 'muy solido, no facil de romper', emoji: '💪' },
      { word: 'planificar', meaning: 'pensar antes de empezar algo', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos cerditos construyeron casas?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'orgulloso de mi trabajo', prompt: 'El tercer cerdito trabajo duro y se mantuvo a salvo. En que has trabajado duro tu?' },
    rewardName: 'Ladrillo solido',
  },

  'aladdin': {
    title: 'Aladino',
    summary: 'Un nino ordinario pero bondadoso encuentra una lampara magica y aprende que lo que deseas importa menos que el bien que haces por los demas.',
    theme: 'honestidad y corazon humilde',
    scenes: [
      { text: 'En un animado mercado vivia Aladino, un nino pobre con un corazon de oro.' },
      { text: 'Encontro una vieja lampara y, al frotarla, aparecio un gran genio!', dialogue: { speaker: 'Genio', line: 'Te concedo tres deseos. Elige con cuidado!' } },
      { text: 'Aladino deseo primero ayudar a su familia, luego a la gente pobre de su barrio.', dialogue: { speaker: 'Aladino', line: 'Quiero que nadie en este mercado pase hambre.' } },
      { text: 'Su humildad y generosidad le ganaron amigos de verdad y mucha felicidad.' },
      { text: 'Aladino aprendio que los mejores deseos son los que uno pide para los demas.', dialogue: { speaker: 'Aladino', line: 'Un corazon generoso es el mas grande de los tesoros.' } },
    ],
    vocabulary: [
      { word: 'mercado', meaning: 'un lugar animado donde la gente vende y compra', emoji: '🏪' },
      { word: 'lampara', meaning: 'un objeto que da luz o guarda un genio', emoji: '🪔' },
      { word: 'humilde', meaning: 'alguien que no presume de si mismo', emoji: '🙏' },
      { word: 'deseo', meaning: 'algo que quieres muchísimo', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos deseos le dio el genio a Aladino?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'generoso', prompt: 'Aladino deseo ayudar a los demas. Si tuvieras un deseo bondadoso, cual seria?' },
    rewardName: 'Lampara de los deseos',
  },

  'ali-baba': {
    title: 'Ali Baba',
    summary: 'Un dulce lenador descubre una cueva secreta y aprende que ser honesto y prudente vale mucho mas que ser codicioso.',
    theme: 'la honestidad antes que la codicia',
    scenes: [
      { text: 'Ali Baba era un dulce lenador que vivia de manera sencilla y contenta.' },
      { text: 'Un dia en el bosque, oyo a unos ladrones decir las palabras magicas frente a una gran roca.', dialogue: { speaker: 'Ladrones', line: 'Abrete, Sesamo!' } },
      { text: 'Ali Baba entro en la cueva y vio tesoros deslumbrantes de todos los colores.', dialogue: { speaker: 'Ali Baba', line: 'Tomare solo lo que necesitamos, nada mas.' } },
      { text: 'Su codicioso hermano tomo demasiado y fue sorprendido por los ladrones. Ali Baba entendio la leccion.' },
      { text: 'Ali Baba compartio su buena fortuna con los demas y vivio de manera sencilla y feliz.', dialogue: { speaker: 'Ali Baba', line: 'Tener suficiente y ser honesto es la verdadera riqueza.' } },
    ],
    vocabulary: [
      { word: 'cueva', meaning: 'una gran cavidad natural en la roca', emoji: '🕳️' },
      { word: 'tesoro', meaning: 'una gran cantidad de oro y cosas valiosas', emoji: '💎' },
      { word: 'codicioso', meaning: 'alguien que siempre quiere mas de lo que necesita', emoji: '😤' },
      { word: 'suficiente', meaning: 'justo lo que uno necesita, ni mas ni menos', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Cuales son las palabras magicas que abren la cueva?', options: ['Abrete, Sesamo!', 'Cierra la puerta!', 'Buenos dias!'], answerIndex: 0 },
    emotionalMoment: { feeling: 'contento', prompt: 'Ali Baba solo tomo lo que necesitaba. Que cosa que ya tienes es justo suficiente para ti?' },
    rewardName: 'Cueva secreta',
  },

  'aesops-fables': {
    title: 'La Liebre y la Tortuga',
    summary: 'Una liebre rapida y una tortuga lenta hacen una carrera amistosa, y la tortuga le ensenaa todos que nunca rendirse gana el dia.',
    theme: 'perseverancia — despacio pero sin parar',
    scenes: [
      { text: 'En un prado soleado, una liebre rapida siempre presumia de su velocidad.' },
      { text: 'La tortuga lenta y tranquila le propuso un reto. La liebre acepto riendose.', dialogue: { speaker: 'Liebre', line: 'Una carrera contra ti? Facilísimo! Descansare por el camino.' } },
      { text: 'La tortuga avanzo paso a paso, de manera constante, sin detenerse nunca.', dialogue: { speaker: 'Tortuga', line: 'Despacio pero sin parar, seguire avanzando.' } },
      { text: 'La liebre se durmio bajo un arbol, segura de que la tortuga jamas podria alcanzarla.' },
      { text: 'Cuando la liebre se desperto, la tortuga ya habia cruzado la linea de meta. Perseverar siempre gana.', dialogue: { speaker: 'Tortuga', line: 'Paso a paso, se llega mas lejos de lo que uno cree.' } },
    ],
    vocabulary: [
      { word: 'liebre', meaning: 'un conejo salvaje grande que es muy rapido', emoji: '🐇' },
      { word: 'tortuga', meaning: 'un animal con caparazon que camina despacio pero sin parar', emoji: '🐢' },
      { word: 'constante', meaning: 'avanzar al mismo ritmo sin detenerse', emoji: '⏱️' },
      { word: 'perseverar', meaning: 'seguir intentandolo aunque sea dificil', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Quien gano la carrera sin rendirse nunca?', options: ['la liebre rapida', 'la tortuga lenta y constante', 'el zorro dormido'], answerIndex: 1 },
    emotionalMoment: { feeling: 'determinado', prompt: 'La tortuga siguio paso a paso. En que sigues tu intentandolo?' },
    rewardName: 'Tortuga perseverante',
  },
};
