// French fairy tale content for the Story Library feature.
// All French text is verbatim from NuboMagic — do not alter.

export const CONTES = [
  {
    id: 'snow-white',
    title: 'Blanche-Neige',
    summary: 'Une douce princesse a la peau blanche comme la neige trouve un foyer aupres de sept petits aides bienveillants et apprend que les vrais amis veillent les uns sur les autres.',
    theme: 'gentillesse et amitie',
    emoji: '🍎',
    palette: { primary: '#C0392B', accent: '#F8C8DC', background: '#FFF5F6' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Il y a longtemps, une petite princesse naquit avec la peau blanche comme la neige. Tout le monde l\'appelait Blanche-Neige.' },
      { text: 'Une reine jalouse possedait un miroir magique et lui posait la meme question chaque jour.', dialogue: { speaker: 'Reine', line: 'Miroir, miroir, qui est la plus gentille et la plus belle de toutes ?' } },
      { text: 'Blanche-Neige marcha au coeur de la foret. Sept petits mineurs bienveillants l\'accueillirent dans leur chaumiere douillette.', dialogue: { speaker: 'Un mineur', line: 'Tu es en securite ici, petite amie. Viens te reposer.' } },
      { text: 'La reine la trompa avec une pomme brillante, et Blanche-Neige tomba dans un sommeil tres, tres profond.' },
      { text: 'Une amie attentionnee la reveilla d\'un geste tout doux. Blanche-Neige sourit, et tous feterent leur courageuse amie.', dialogue: { speaker: 'Blanche-Neige', line: 'Vous ne m\'avez jamais quittee. Merci, mes amis !' } },
    ],
    vocabulary: [
      { word: 'la plus belle', meaning: 'la plus gentille et la plus jolie', emoji: '🌷' },
      { word: 'jalouse', meaning: 'fachee parce qu\'on veut ce qu\'un autre a', emoji: '😠' },
      { word: 'chaumiere', meaning: 'une petite maison toute douillette', emoji: '🏡' },
      { word: 'accueillir', meaning: 'rendre quelqu\'un heureux d\'etre arrive', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de gentils petits mineurs ont accueilli Blanche-Neige ?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'entoure et protege', prompt: 'Les amis de Blanche-Neige veillaient sur elle. Qui veille sur toi ?' },
    rewardEmoji: '🪞',
    rewardName: 'Miroir bienveillant',
  },
  {
    id: 'cinderella',
    title: 'Cendrillon',
    summary: 'Une fille travailleuse et au grand coeur recoit un peu d\'aide d\'une amie magique et decouvre qu\'etre gentille est une magie en soi.',
    theme: 'espoir et gentillesse',
    emoji: '👠',
    palette: { primary: '#6C5CE7', accent: '#A29BFE', background: '#F4F2FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Cendrillon faisait toutes les taches et ne perdait jamais son doux sourire, meme quand les autres etaient mechants.' },
      { text: 'Un soir, un grand bal fut annonce, mais Cendrillon n\'avait rien a se mettre.', dialogue: { speaker: 'Cendrillon', line: 'Si seulement je pouvais aller danser, juste une fois.' } },
      { text: 'Une gentille fee apparut et, d\'un coup de baguette, changea une citrouille en carrosse.', dialogue: { speaker: 'Fee amie', line: 'Rentre avant minuit, ma cherie — la magie s\'arrete alors.' } },
      { text: 'Au bal, Cendrillon dansa et rit. Mais quand l\'horloge se mit a sonner, elle dut courir.' },
      { text: 'La pantoufle lui allait parfaitement. Sa gentillesse s\'etait vue depuis toujours, et la joie remplit ses journees.', dialogue: { speaker: 'Cendrillon', line: 'Etre gentil ne coute rien.' } },
    ],
    vocabulary: [
      { word: 'taches', meaning: 'petits travaux pour aider a la maison', emoji: '🧹' },
      { word: 'carrosse', meaning: 'une voiture tiree pour transporter des gens', emoji: '🛞' },
      { word: 'minuit', meaning: 'douze heures de la nuit', emoji: '🕛' },
      { word: 'doux', meaning: 'tendre, calme et gentil', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'A quelle heure Cendrillon doit-elle rentrer ? Compte les coups de l\'horloge !', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'plein d\'espoir', prompt: 'Meme les jours difficiles, Cendrillon restait gentille. Qu\'est-ce qui t\'aide a garder espoir ?' },
    rewardEmoji: '👠',
    rewardName: 'Pantoufle de verre',
  },
  {
    id: 'little-red-riding-hood',
    title: 'Le Petit Chaperon rouge',
    summary: 'Une petite fille courageuse au chaperon rouge va chez sa grand-mere et apprend a ecouter ses sentiments sages en chemin.',
    theme: 'ecouter et rester en securite',
    emoji: '🧣',
    palette: { primary: '#E84855', accent: '#FFB3B3', background: '#FFF4F2' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Une petite fille portait partout un chaperon rouge vif ; alors tout le monde l\'appelait le Petit Chaperon rouge.' },
      { text: 'Sa maman lui donna un panier de pain pour mamie.', dialogue: { speaker: 'Maman', line: 'Reste sur le chemin et tout ira tres bien.' } },
      { text: 'Dans les bois, un loup ruse posa beaucoup de questions. Le Petit Chaperon sentit quelque chose de bizarre et continua a marcher.', dialogue: { speaker: 'Petit Chaperon', line: 'Je n\'ai pas a te repondre. Je le dirai a un adulte.' } },
      { text: 'Un gentil bucheron l\'entendit et marcha avec elle. Ensemble, ils arriverent chez mamie.' },
      { text: 'Mamie etait en securite, et le Petit Chaperon aussi. Ils partagerent du bon pain chaud et rirent tout l\'apres-midi.', dialogue: { speaker: 'Mamie', line: 'Tu as ecoute tes sentiments sages. Je suis fiere de toi.' } },
    ],
    vocabulary: [
      { word: 'chemin', meaning: 'une voie qui montre par ou aller en securite', emoji: '🛤️' },
      { word: 'panier', meaning: 'un porteur avec une anse pour transporter des choses', emoji: '🧺' },
      { word: 'ruse', meaning: 'qui fait des tours pour te tromper', emoji: '🦊' },
      { word: 'bucheron', meaning: 'une personne qui travaille parmi les arbres', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'Un inconnu demande au Petit Chaperon ou elle va. Quel est le choix sur ?', options: ['Tout lui raconter', 'Continuer a marcher et prevenir un adulte', 'Le suivre entre les arbres'], answerIndex: 1 },
    emotionalMoment: { feeling: 'en securite', prompt: 'Le Petit Chaperon a ecoute sa sensation bizarre. Quand un sentiment t\'a-t-il aide a rester en securite ?' },
    rewardEmoji: '🧣',
    rewardName: 'Chaperon rouge',
  },
  {
    id: 'hansel-and-gretel',
    title: 'Hansel et Gretel',
    summary: 'Un frere et une soeur se perdent dans les bois et utilisent un plan astucieux, et leur esprit d\'equipe, pour rentrer sains et saufs.',
    theme: 'astuce et rester ensemble',
    emoji: '✨',
    palette: { primary: '#B7791F', accent: '#FBD38D', background: '#FFFBF0' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Hansel et Gretel entrerent dans la grande foret, se tenant la main pour ne pas se perdre.' },
      { text: 'L\'astucieux Hansel laissa tomber de petits cailloux blancs et brillants, un a un, pour marquer le retour.', dialogue: { speaker: 'Hansel', line: 'Ces cailloux brilleront et nous rameneront a la maison.' } },
      { text: 'Ils trouverent une petite maison faite de friandises, mais une vieille femme rusee y habitait.' },
      { text: 'Les enfants etaient trop malins pour se laisser tromper. Ils se prirent la main et sortirent sur la pointe des pieds.', dialogue: { speaker: 'Gretel', line: 'Vite — ensemble, nous sommes plus courageux que seuls.' } },
      { text: 'Les cailloux brillants luisirent au clair de lune et les ramenerent droit a la maison, vers un calin tout chaud.' },
    ],
    vocabulary: [
      { word: 'cailloux', meaning: 'de petites pierres bien lisses', emoji: '🪨' },
      { word: 'astucieux', meaning: 'doue pour trouver des idees malines', emoji: '💡' },
      { word: 'sur la pointe des pieds', meaning: 'marcher tout doucement sur les orteils', emoji: '🦶' },
      { word: 'ensemble', meaning: 'l\'un avec l\'autre, cote a cote', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets le plan astucieux de Hansel dans l\'ordre !', steps: ['Laisser tomber les cailloux brillants', 'Suivre la piste qui scintille', 'Retrouver le chemin de la maison'] },
    emotionalMoment: { feeling: 'courageux ensemble', prompt: 'Les enfants etaient plus courageux en equipe. Qui te rend plus courageux ?' },
    rewardEmoji: '✨',
    rewardName: 'Caillou brillant',
  },
  {
    id: 'rapunzel',
    title: 'Raiponce',
    summary: 'Une gentille fille aux tres longs cheveux vit dans une haute tour et apprend que la patience et un coeur plein d\'espoir peuvent ouvrir n\'importe quelle porte.',
    theme: 'patience et espoir',
    emoji: '👑',
    palette: { primary: '#9B59B6', accent: '#D7BDE2', background: '#FAF4FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Tout en haut d\'une grande tour vivait Raiponce, une fille avec la plus longue tresse doree du monde.' },
      { text: 'Chaque jour, Raiponce chantait aux oiseaux. Sa douce chanson flottait sur toute la foret.', dialogue: { speaker: 'Raiponce', line: 'Un jour, je verrai le monde la-bas, sous les arbres.' } },
      { text: 'Un gentil voyageur entendit sa chanson et lui cria : "Ta musique fait sourire la foret !"', dialogue: { speaker: 'Voyageur', line: 'Ta musique fait sourire toute la foret !' } },
      { text: 'Ils devinrent amis. Jour apres jour, avec patience, ils imaginerent une maniere maline de descendre.' },
      { text: 'Enfin, Raiponce posa le pied sur l\'herbe douce et tournoya au soleil, libre et heureuse.', dialogue: { speaker: 'Raiponce', line: 'Attendre etait dur, mais l\'espoir m\'a gardee forte.' } },
    ],
    vocabulary: [
      { word: 'tour', meaning: 'un batiment tres haut et etroit', emoji: '🗼' },
      { word: 'tresse', meaning: 'des cheveux tisses en une longue corde', emoji: '💇' },
      { word: 'patience', meaning: 'attendre calmement sans abandonner', emoji: '⏳' },
      { word: 'prairie', meaning: 'un champ d\'herbe plein de fleurs', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Trouve ce que Raiponce a utilise pour descendre en securite.', target: 'l\'echelle en tresse doree', decoys: ['un cerf-volant en papier', 'une cuillere en bois', 'une petite tasse'] },
    emotionalMoment: { feeling: 'patient', prompt: 'Raiponce a attendu avec espoir. Quelle belle chose as-tu attendue longtemps ?' },
    rewardEmoji: '👑',
    rewardName: 'Tresse doree',
  },
  {
    id: 'the-ugly-duckling',
    title: 'Le Vilain Petit Canard',
    summary: 'Un petit oiseau qui se sent different des autres grandit et decouvre qu\'il etait merveilleux exactement comme il etait, depuis toujours.',
    theme: 'appartenir et s\'aimer',
    emoji: '🦢',
    palette: { primary: '#3498DB', accent: '#AED6F1', background: '#EBF5FB' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Dans une mare ensoleillee, un petit oiseau ne ressemblait pas a ses freres et soeurs.' },
      { text: 'Les autres oiseaux se moquaient de lui, et au fond il se sentait seul et tres triste.', dialogue: { speaker: 'Petit oiseau', line: 'J\'aimerais que quelqu\'un me laisse jouer aussi.' } },
      { text: 'Une gentille grenouille s\'approcha en sautant et s\'assit pres de lui. "Tu es le bienvenu avec moi", dit-elle.', dialogue: { speaker: 'Grenouille', line: 'Tu es le bienvenu avec moi, mon ami.' } },
      { text: 'Les saisons passerent. Un matin lumineux, le petit oiseau vit son visage dans l\'eau calme.' },
      { text: 'Il etait devenu un magnifique cygne ! Il avait toujours ete special : tout simplement lui-meme.', dialogue: { speaker: 'Cygne', line: 'Je n\'avais pas besoin de changer. J\'avais juste besoin de grandir.' } },
    ],
    vocabulary: [
      { word: 'mare', meaning: 'une petite etendue d\'eau calme', emoji: '💧' },
      { word: 'seul', meaning: 'triste parce qu\'on se sent tout seul', emoji: '🥺' },
      { word: 'reflet', meaning: 'l\'image que tu vois dans l\'eau calme', emoji: '🪞' },
      { word: 'cygne', meaning: 'un grand oiseau d\'eau blanc et gracieux', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'Un nouvel ami se sent mis a l\'ecart. Quelle chose gentille peux-tu dire ?', options: ['Tu n\'es pas a ta place ici', 'Tu peux jouer avec nous !', 'Va-t\'en'], answerIndex: 1 },
    emotionalMoment: { feeling: 'j\'ai ma place', prompt: 'Le petit oiseau etait special tel qu\'il etait. Qu\'est-ce qui fait de toi un merveilleux toi ?' },
    rewardEmoji: '🦢',
    rewardName: 'Cygne tout doux',
  },
  {
    id: 'the-little-mermaid',
    title: 'La Petite Sirene',
    summary: 'Une jeune sirene curieuse a le courage d\'explorer un monde nouveau, et apprend qu\'un coeur gentil et genereux brille plus que tout.',
    theme: 'courage et bon coeur',
    emoji: '🐚',
    palette: { primary: '#1ABC9C', accent: '#A9DFBF', background: '#F0FBF7' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Au fond des vagues vivait une jeune sirene, la plus petite de six soeurs.' },
      { text: 'Elle adorait monter a la surface et regarder le monde lumineux au-dessus de l\'eau.', dialogue: { speaker: 'Sirene', line: 'Le monde d\'en haut est plein de choses que je veux apprendre !' } },
      { text: 'Une nuit de tempete, avec courage, elle aida un marin a rejoindre le rivage sain et sauf.' },
      { text: 'Elle ne resta pas pour etre remerciee. Aider quelqu\'un remplissait son coeur de chaleur.', dialogue: { speaker: 'Sirene', line: 'J\'ai aide par gentillesse, pas pour un merci.' } },
      { text: 'De retour chez elle, elle raconta son histoire courageuse, et son bon coeur fit briller toute la mer.' },
    ],
    vocabulary: [
      { word: 'sirene', meaning: 'une fille de la mer imaginaire, avec une queue de poisson', emoji: '🧜' },
      { word: 'vagues', meaning: 'l\'eau qui monte et descend sur la mer', emoji: '🌊' },
      { word: 'courageux', meaning: 'faire une chose difficile meme si elle fait peur', emoji: '💪' },
      { word: 'genereux', meaning: 'heureux de donner et d\'aider les autres', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de grandes soeurs avait la Petite Sirene ?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'au grand coeur', prompt: 'La sirene a aide juste par gentillesse. Quand as-tu aide sans qu\'on te le demande ?' },
    rewardEmoji: '🐚',
    rewardName: 'Perle de la mer',
  },
  {
    id: 'the-snow-queen',
    title: 'La Reine des Neiges',
    summary: 'Quand le coeur de son meilleur ami devient froid, une fille fidele nommee Gerda voyage loin dans la neige pour le rechauffer avec amour.',
    theme: 'amitie fidele',
    emoji: '❄️',
    palette: { primary: '#5DADE2', accent: '#AED6F1', background: '#EBF5FB' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Gerda et Kai etaient les meilleurs amis et cultivaient des roses ensemble pres de leur fenetre.' },
      { text: 'Un tout petit eclat de givre toucha le coeur de Kai, et il devint froid et lointain.', dialogue: { speaker: 'Gerda', line: 'Attends... ou vas-tu, Kai ?' } },
      { text: 'La courageuse Gerda n\'abandonna pas. Elle partit a travers la neige chercher son ami.', dialogue: { speaker: 'Gerda', line: 'Je vais te retrouver, Kai. Les amis n\'abandonnent pas.' } },
      { text: 'Elle trouva Kai dans un palais de glace, assis, immobile et froid comme la pierre.' },
      { text: 'Gerda le serra dans ses bras et des larmes chaudes coulerent. Le givre fondit, et Kai sourit et se souvint.', dialogue: { speaker: 'Kai', line: 'Tu es venue jusqu\'ici pour moi. Merci, Gerda.' } },
    ],
    vocabulary: [
      { word: 'givre', meaning: 'une fine glace qui se forme quand il fait tres froid', emoji: '🌨️' },
      { word: 'fidele', meaning: 'toujours la pour ses amis', emoji: '🤲' },
      { word: 'palais', meaning: 'une maison tres grande et magnifique', emoji: '🏰' },
      { word: 'fondre', meaning: 'passer de la glace a l\'eau avec la chaleur', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'Comment Gerda a-t-elle fait fondre la glace dans le coeur de Kai ?', options: ['Avec un grand feu', 'Avec des larmes chaudes et un calin', 'Avec un marteau'], answerIndex: 1 },
    emotionalMoment: { feeling: 'fidele', prompt: 'Gerda n\'a jamais abandonne son ami. Comment montres-tu a un ami que tu tiens a lui ?' },
    rewardEmoji: '🌹',
    rewardName: 'Rose toute chaude',
  },
  {
    id: 'puss-in-boots',
    title: 'Le Chat botte',
    summary: 'Un chat malin aux belles bottes utilise sa vivacite d\'esprit, et son grand coeur fidele, pour aider son gentil ami a trouver le bonheur.',
    theme: 'astuce et loyaute',
    emoji: '🐱',
    palette: { primary: '#E67E22', accent: '#FAD7A0', background: '#FFFAF0' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Un chat malin enfila de belles bottes et un chapeau a plume, pret pour l\'aventure.' },
      { text: 'Son ami etait pauvre mais gentil, alors le chat imagina un plan malin pour l\'aider.', dialogue: { speaker: 'Le Chat', line: 'Fais-moi confiance, mon ami. Une idee maline arrive !' } },
      { text: 'Le chat salua le roi avec politesse et offrit des cadeaux, faisant sourire tout le monde.' },
      { text: 'Avec de l\'esprit plutot que des ruses, le chat aida son ami a gagner un grand chateau au bord de la riviere.', dialogue: { speaker: 'Le Chat', line: 'Les bonnes idees ouvrent plus de portes que les grands rugissements.' } },
      { text: 'Son ami fut enfin heureux, et le chat se pelotonna pres du feu, le chat le plus fidele de tous.' },
    ],
    vocabulary: [
      { word: 'malin', meaning: 'doue pour trouver des idees astucieuses', emoji: '🧠' },
      { word: 'bottes', meaning: 'des chaussures qui montent haut sur les jambes', emoji: '🥾' },
      { word: 'poli', meaning: 'gentil et doux avec ses mots', emoji: '🙏' },
      { word: 'fidele', meaning: 'toujours la pour ses amis', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets le plan malin du Chat dans l\'ordre !', steps: ['Enfiler les belles bottes', 'Saluer le roi avec politesse', 'Aider son ami a gagner la journee'] },
    emotionalMoment: { feeling: 'serviable', prompt: 'Le Chat a use d\'idees malines pour aider un ami. De quelle facon astucieuse as-tu deja aide quelqu\'un ?' },
    rewardEmoji: '🥾',
    rewardName: 'Belles bottes',
  },
  {
    id: 'pinocchio',
    title: 'Pinocchio',
    summary: 'Une marionnette de bois qui reve d\'etre un vrai garcon apprend que dire la verite, c\'est ce qui fait grandir un bon coeur.',
    theme: 'honnetete',
    emoji: '🪵',
    palette: { primary: '#27AE60', accent: '#A9DFBF', background: '#F0FBF5' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Il etait une fois une petite marionnette de bois nommee Pinocchio, qui revait de devenir un vrai garcon.' },
      { text: 'Chaque fois que Pinocchio disait un mensonge, son nez s\'allongeait comme une branche.', dialogue: { speaker: 'Pinocchio', line: 'Ce n\'est pas moi ! Je promets !' } },
      { text: 'Son ami grillon essayait de lui apprendre a toujours dire la verite.', dialogue: { speaker: 'Grillon', line: 'Dire la verite te rendra leger comme une plume.' } },
      { text: 'Pinocchio fit une grosse erreur et se retrouva perdu. Il apprit alors que l\'honnetete etait son seul guide.' },
      { text: 'Quand Pinocchio dit enfin la verite, son coeur grandit, et son voeu le plus cher se realisa.', dialogue: { speaker: 'Pinocchio', line: 'La verite, c\'est la magie la plus puissante de toutes.' } },
    ],
    vocabulary: [
      { word: 'marionnette', meaning: 'une poupee que l\'on fait bouger', emoji: '🎭' },
      { word: 'verite', meaning: 'dire exactement ce qui s\'est passe', emoji: '✅' },
      { word: 'mensonge', meaning: 'dire quelque chose qui n\'est pas vrai', emoji: '❌' },
      { word: 'honnete', meaning: 'quelqu\'un qui dit toujours la verite', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'Quand le nez de Pinocchio s\'allonge-t-il ?', options: ['Quand il dit la verite', 'Quand il dit un mensonge', 'Quand il chante une chanson'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honnete', prompt: 'Dire la verite a rendu Pinocchio leger. Que ressens-tu quand tu dis la verite ?' },
    rewardEmoji: '🦗',
    rewardName: 'Grillon de la verite',
  },
  {
    id: 'peter-pan',
    title: 'Peter Pan',
    summary: 'Un garcon qui ne grandit jamais emmene de nouveaux amis dans une aventure volante ou les pensees heureuses et un peu de courage menent partout.',
    theme: 'imagination et courage',
    emoji: '🧚',
    palette: { primary: '#16A085', accent: '#A2D9CE', background: '#F0F9F8' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Dans une chambre pleine d\'etoiles, un garcon nomme Peter Pan apprit aux enfants a voler.' },
      { text: 'Peter dit a Wendy le secret : il fallait penser a quelque chose de tres heureux.', dialogue: { speaker: 'Peter Pan', line: 'Pense a ta chose la plus heureuse — et hop, tu t\'envoles !' } },
      { text: 'Ensemble, ils s\'envolerent vers le Pays Imaginaire, une ile magique pleine d\'aventures.' },
      { text: 'Meme face au mechant capitaine, Peter n\'eut pas peur. Il affronta le danger avec un grand sourire.', dialogue: { speaker: 'Peter Pan', line: 'Etre courageux, c\'est essayer quand meme.' } },
      { text: 'Les enfants rentrerent chez eux avec des souvenirs plein le coeur et un zeste de magie pour toujours.' },
    ],
    vocabulary: [
      { word: 'chambre', meaning: 'la piece ou l\'on dort et ou l\'on reve', emoji: '🛏️' },
      { word: 'ombre', meaning: 'la forme sombre que ton corps fait sur le sol', emoji: '👤' },
      { word: 'imaginer', meaning: 'creer des choses belles dans sa tete', emoji: '💭' },
      { word: 'courage', meaning: 'essayer meme quand on a peur', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Qu\'est-ce qui a aide les enfants a voler ?', options: ['Des pensees heureuses et de la poudre de fee', 'Des bottes lourdes', 'Crier tres fort'], answerIndex: 0 },
    emotionalMoment: { feeling: 'courageux', prompt: 'Peter dit qu\'etre courageux, c\'est essayer quand meme. Quelle chose courageuse aimerais-tu essayer ?' },
    rewardEmoji: '✨',
    rewardName: 'Poudre de fee',
  },
  {
    id: 'alice-in-wonderland',
    title: 'Alice au pays des merveilles',
    summary: 'Une fille curieuse suit un lapin presse dans un monde sens dessus dessous et apprend que poser des questions, c\'est une sorte de magie.',
    theme: 'curiosite',
    emoji: '🐇',
    palette: { primary: '#8E44AD', accent: '#D2B4DE', background: '#F9F0FF' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Alice vit un lapin blanc presse sauter dans un terrier et, tres curieuse, elle le suivit.' },
      { text: 'Elle tomba dans un long couloir magique et trouva une toute petite porte dans un jardin.', dialogue: { speaker: 'Alice', line: 'Comme c\'est etrange ! Je me demande ce qui se passe ici.' } },
      { text: 'Alice but une petite bouteille et rapetissa, puis mangea un gateau et grandit tres vite.', dialogue: { speaker: 'Alice', line: 'Les questions sont la cle de toutes les merveilles !' } },
      { text: 'Elle rencontra un chat souriant, une reine colereuse et un grand chapelier fou.' },
      { text: 'Alice se reveilla et sourit. Poser des questions l\'avait menee dans le plus beau des reves.', dialogue: { speaker: 'Alice', line: 'La curiosite est la plus grande aventure.' } },
    ],
    vocabulary: [
      { word: 'curieuse', meaning: 'quelqu\'un qui aime decouvrir de nouvelles choses', emoji: '🔍' },
      { word: 'terrier', meaning: 'un tunnel creuse dans la terre par un animal', emoji: '🕳️' },
      { word: 'rapetisser', meaning: 'devenir plus petit', emoji: '🔻' },
      { word: 'merveille', meaning: 'quelque chose d\'incroyable et de tres surprenant', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets l\'aventure d\'Alice dans l\'ordre !', steps: ['Boire la bouteille et rapetisser', 'Manger le gateau et grandir', 'Trouver la petite porte du jardin'] },
    emotionalMoment: { feeling: 'curieux', prompt: 'Alice adorait poser des questions. Qu\'est-ce qui te rend curieux aujourd\'hui ?' },
    rewardEmoji: '⏰',
    rewardName: 'Horloge curieuse',
  },
  {
    id: 'the-wizard-of-oz',
    title: 'Le Magicien d\'Oz',
    summary: 'Une fille et trois nouveaux amis suivent une route doree et decouvrent que les cadeaux qu\'ils cherchaient etaient en eux depuis le debut.',
    theme: 'tu as deja ce qu\'il te faut',
    emoji: '🌈',
    palette: { primary: '#F39C12', accent: '#FAD7A0', background: '#FFFBF0' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Un grand tourbillon emporta Dorothee et son petit chien Toto dans le pays magique d\'Oz.' },
      { text: 'Sur la route doree, Dorothee rencontra un epouvantail, un homme de fer-blanc et un lion.', dialogue: { speaker: 'Epouvantail', line: 'Je veux juste un cerveau malin !' } },
      { text: 'Ensemble, ils marchererent vers la ville d\'Emeraude pour trouver le grand Magicien.', dialogue: { speaker: 'Dorothee', line: 'Si nous sommes ensemble, nous pouvons tout faire.' } },
      { text: 'Le Magicien leur revela un grand secret : ils possedaient deja tout ce qu\'ils desiraient.' },
      { text: 'Dorothee appuya trois fois ses souliers et retrouva sa maison. Chacun avait trouve son cadeau.', dialogue: { speaker: 'Dorothee', line: 'Il n\'y a nulle part de mieux que chez soi.' } },
    ],
    vocabulary: [
      { word: 'tourbillon', meaning: 'un vent tres fort qui tourne en rond', emoji: '🌪️' },
      { word: 'epouvantail', meaning: 'une grande poupee de paille pour effrayer les oiseaux', emoji: '🌾' },
      { word: 'courage', meaning: 'continuer meme quand on a peur', emoji: '💪' },
      { word: 'voyage', meaning: 'une longue marche ou aventure vers un endroit nouveau', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Quel ami avait deja du courage depuis le debut ?', options: ['L\'epouvantail', 'L\'homme de fer-blanc', 'Le lion'], answerIndex: 2 },
    emotionalMoment: { feeling: 'capable', prompt: 'Les amis avaient deja leurs cadeaux en eux. Quel cadeau as-tu deja en toi ?' },
    rewardEmoji: '👟',
    rewardName: 'Souliers scintillants',
  },
  {
    id: 'robin-hood',
    title: 'Robin des Bois',
    summary: 'Un gentil archer de la foret verte partage avec ceux qui ont tres peu et apprend a ses amis que la justice rend tout le monde plus heureux.',
    theme: 'justice et generosite',
    emoji: '🏹',
    palette: { primary: '#27AE60', accent: '#A9DFBF', background: '#F0FBF5' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Dans une grande foret verte vivait Robin des Bois, le meilleur archer du pays.' },
      { text: 'Il vit que beaucoup de gens etaient tres pauvres pendant que d\'autres avaient tout.', dialogue: { speaker: 'Robin', line: 'Partager, c\'est le plus beau des cadeaux.' } },
      { text: 'Avec ses amis joyeux, Robin devisa un plan pour aider ceux dans le besoin.', dialogue: { speaker: 'Petit Jean', line: 'Ensemble, nous sommes la force de la foret !' } },
      { text: 'Robin distribua ce dont les gens avaient besoin, et des sourires fleurirent partout.' },
      { text: 'La foret bourdonnait de bonheur. Robin avait appris que la generosite est la vraie victoire.', dialogue: { speaker: 'Robin', line: 'La generosite rend tout le monde plus riche.' } },
    ],
    vocabulary: [
      { word: 'archer', meaning: 'quelqu\'un qui tire des fleches avec un arc', emoji: '🎯' },
      { word: 'foret', meaning: 'un grand endroit plein d\'arbres et d\'animaux', emoji: '🌳' },
      { word: 'juste', meaning: 'traiter tout le monde de la meme facon', emoji: '⚖️' },
      { word: 'genereux', meaning: 'qui aime donner et partager', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin des Bois partageait avec des gens qui etaient...', options: ['affames et dans le besoin', 'deja tres riches', 'mechants avec les autres'], answerIndex: 0 },
    emotionalMoment: { feeling: 'juste', prompt: 'Robin adorait partager. Que pourrais-tu partager pour faire sourire un ami ?' },
    rewardEmoji: '🏹',
    rewardName: 'Arc amical',
  },
  {
    id: 'goldilocks',
    title: 'Boucle d\'or et les trois ours',
    summary: 'Une fille curieuse entre dans la chaumiere douillette des ours et apprend qu\'il vaut mieux demander d\'abord et prendre soin des affaires des autres.',
    theme: 'le respect des autres',
    emoji: '🐻',
    palette: { primary: '#D4A017', accent: '#FAD7A0', background: '#FFFBF0' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Une petite fille aux boucles dorees se promenait dans la foret quand elle trouva une jolie chaumiere.' },
      { text: 'Elle entra et gouta trois bols de bouillie. Celui du bebe ours etait parfait.', dialogue: { speaker: 'Boucle d\'or', line: 'Oh ! Ce bol est parfait, ni trop chaud ni trop froid !' } },
      { text: 'Elle essaya trois chaises, puis trois lits. Elle s\'endormit dans le plus douillet.' },
      { text: 'Les trois ours rentrerent et trouverent leur maison bousculee.', dialogue: { speaker: 'Bebe ours', line: 'Quelqu\'un a mange dans mon bol !' } },
      { text: 'Boucle d\'or se reveilla, s\'excusa et apprit que demander d\'abord est la politesse la plus douce.', dialogue: { speaker: 'Boucle d\'or', line: 'Pardon. Je demanderai toujours avant d\'entrer.' } },
    ],
    vocabulary: [
      { word: 'bouillie', meaning: 'une nourriture chaude et douce, comme la cereale du matin', emoji: '🥣' },
      { word: 'chaumiere', meaning: 'une petite maison douillette dans la foret', emoji: '🏡' },
      { word: 'respect', meaning: 'prendre soin des affaires et des sentiments des autres', emoji: '🙏' },
      { word: 'desole', meaning: 'ce qu\'on dit quand on regrette quelque chose', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'Combien d\'ours vivaient dans la chaumiere douillette ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respectueux', prompt: 'Boucle d\'or a appris a demander d\'abord. Quand est-ce gentil de demander avant d\'emprunter quelque chose ?' },
    rewardEmoji: '🥣',
    rewardName: 'Bol parfait',
  },
  {
    id: 'three-little-pigs',
    title: 'Les Trois Petits Cochons',
    summary: 'Trois petits cochons construisent trois maisons differentes et apprennent qu\'un travail soigneux et applique garde tout le monde en securite et au chaud.',
    theme: 'travail et organisation',
    emoji: '🐷',
    palette: { primary: '#E74C3C', accent: '#FADBD8', background: '#FFF5F4' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Trois petits cochons partirent dans le monde pour construire leur maison.' },
      { text: 'Le premier construisit vite une maison de paille. Le deuxieme, une maison de bois.', dialogue: { speaker: 'Premier cochon', line: 'Vite fait, bien fait ! Je veux aller jouer !' } },
      { text: 'Le troisieme cochon travailla dur et construisit une maison solide de briques, pierre par pierre.', dialogue: { speaker: 'Troisieme cochon', line: 'Je prends mon temps pour que ma maison soit solide.' } },
      { text: 'Le grand mechant loup souffla sur les maisons de paille et de bois, et elles s\'ecroulerent.' },
      { text: 'Mais la maison de briques resta solide. Les trois cochons etaient en securite, et tout le monde apprit que travailler avec soin protege.', dialogue: { speaker: 'Troisieme cochon', line: 'Un bon travail prend du temps, mais ca en vaut la peine !' } },
    ],
    vocabulary: [
      { word: 'paille', meaning: 'des tiges seches de plantes, faciles a casser', emoji: '🌾' },
      { word: 'briques', meaning: 'des blocs de terre cuite tres solides', emoji: '🧱' },
      { word: 'resistante', meaning: 'tres solide, pas facile a casser', emoji: '💪' },
      { word: 'planifier', meaning: 'reflechir avant de commencer quelque chose', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de petits cochons construisirent des maisons ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'fier de mon travail', prompt: 'Le troisieme cochon a travaille dur et est reste en securite. Sur quoi as-tu travaille dur, toi ?' },
    rewardEmoji: '🧱',
    rewardName: 'Brique solide',
  },
  {
    id: 'aladdin',
    title: 'Aladin et la lampe merveilleuse',
    summary: 'Un garcon ordinaire et gentil trouve une lampe magique et apprend que ce que tu souhaites compte moins que le bien que tu fais aux autres.',
    theme: 'honnetete et coeur humble',
    emoji: '🪔',
    palette: { primary: '#F39C12', accent: '#FAD7A0', background: '#FFFBF0' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Dans un marche anime vivait Aladin, un garcon pauvre mais au coeur d\'or.' },
      { text: 'Il trouva une vieille lampe et, en la frottant, un grand genie en sortit !', dialogue: { speaker: 'Genie', line: 'Je t\'accorde trois souhaits. Choisis avec soin !' } },
      { text: 'Aladin souhaiita d\'abord aider sa famille, puis les gens pauvres de son quartier.', dialogue: { speaker: 'Aladin', line: 'Je veux que personne dans ce marche ne soit affame.' } },
      { text: 'Son humilite et sa generosite lui gagnererent de vrais amis et beaucoup de bonheur.' },
      { text: 'Aladin apprit que les meilleurs souhaits sont ceux que l\'on fait pour les autres.', dialogue: { speaker: 'Aladin', line: 'Un coeur genereux est le plus grand des tresors.' } },
    ],
    vocabulary: [
      { word: 'marche', meaning: 'un endroit anime ou les gens vendent et achetent', emoji: '🏪' },
      { word: 'lampe', meaning: 'un objet qui donne de la lumiere ou garde un genie', emoji: '🪔' },
      { word: 'humble', meaning: 'quelqu\'un qui ne se vante pas de lui-meme', emoji: '🙏' },
      { word: 'souhait', meaning: 'quelque chose que tu desires tres fort', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de souhaits le genie a-t-il donnes a Aladin ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'genereux', prompt: 'Aladin a souhaite aider les autres. Si tu avais un souhait gentil, lequel serait-ce ?' },
    rewardEmoji: '🪔',
    rewardName: 'Lampe a souhaits',
  },
  {
    id: 'ali-baba',
    title: 'Ali Baba et les quarante voleurs',
    summary: 'Un doux bucheron decouvre une grotte secrete et apprend qu\'etre honnete et prudent vaut bien mieux qu\'etre avide.',
    theme: 'l\'honnetete plutot que l\'avidite',
    emoji: '💎',
    palette: { primary: '#8E44AD', accent: '#D2B4DE', background: '#F9F0FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Ali Baba etait un bucheron doux qui vivait simplement et contenment.' },
      { text: 'Un jour dans la foret, il entendit des voleurs dire les mots magiques devant un grand rocher.', dialogue: { speaker: 'Voleurs', line: 'Sesame, ouvre-toi !' } },
      { text: 'Ali Baba entra dans la grotte et vit des tresors etincelants de toutes les couleurs.', dialogue: { speaker: 'Ali Baba', line: 'Je prendrai juste ce qu\'il nous faut, pas plus.' } },
      { text: 'Son frere avide prit trop et fut surpris par les voleurs. Ali Baba comprit la lecon.' },
      { text: 'Ali Baba partagea sa bonne fortune avec les autres et vecut simplement et heureusement.', dialogue: { speaker: 'Ali Baba', line: 'Avoir assez et etre honnete, c\'est la vraie richesse.' } },
    ],
    vocabulary: [
      { word: 'grotte', meaning: 'une grande cavite naturelle dans la roche', emoji: '🕳️' },
      { word: 'tresor', meaning: 'une grande quantite d\'or et de choses precieuses', emoji: '💎' },
      { word: 'avide', meaning: 'quelqu\'un qui veut toujours plus que ce qu\'il lui faut', emoji: '😤' },
      { word: 'assez', meaning: 'juste ce dont on a besoin, ni plus ni moins', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Quels sont les mots magiques qui ouvrent la grotte ?', options: ['Sesame, ouvre-toi !', 'Ferme la porte !', 'Bonjour !'], answerIndex: 0 },
    emotionalMoment: { feeling: 'content', prompt: 'Ali Baba n\'a pris que ce qu\'il fallait. Quelle chose que tu as deja est juste suffisante pour toi ?' },
    rewardEmoji: '🗝️',
    rewardName: 'Grotte secrete',
  },
  {
    id: 'aesops-fables',
    title: 'Fables d\'Esope : Le Lievre et la Tortue',
    summary: 'Un lievre rapide et une tortue lente font une course amicale, et la tortue apprend a tous que ne jamais abandonner gagne la journee.',
    theme: 'perseverance — doucement mais surement',
    emoji: '🐢',
    palette: { primary: '#27AE60', accent: '#A9DFBF', background: '#F0FBF5' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Dans une prairie ensoleilee, un lievre rapide se vantait toujours de sa vitesse.' },
      { text: 'La tortue lente et calme proposa un defi. Le lievre accepta en riant.', dialogue: { speaker: 'Lievre', line: 'Une course contre toi ? Facile ! Je vais me reposer en chemin.' } },
      { text: 'La tortue avanca pas a pas, regulierement, sans jamais s\'arreter.', dialogue: { speaker: 'Tortue', line: 'Doucement mais surement, j\'avancerai.' } },
      { text: 'Le lievre s\'endormit sous un arbre, sur que la tortue ne pourrait jamais le rattraper.' },
      { text: 'Quand le lievre se reveilla, la tortue avait deja franchi la ligne d\'arrivee. Perseverer gagne toujours.', dialogue: { speaker: 'Tortue', line: 'Pas a pas, on arrive plus loin qu\'on ne croit.' } },
    ],
    vocabulary: [
      { word: 'lievre', meaning: 'un grand lapin sauvage tres rapide', emoji: '🐇' },
      { word: 'tortue', meaning: 'un animal a carapace qui marche lentement mais sans s\'arreter', emoji: '🐢' },
      { word: 'regulier', meaning: 'avancer au meme rythme, sans s\'arretere', emoji: '⏱️' },
      { word: 'perseverer', meaning: 'continuer a essayer meme quand c\'est difficile', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Qui a gagne la course en n\'abandonnant jamais ?', options: ['le lievre rapide', 'la tortue lente et reguliere', 'le renard endormi'], answerIndex: 1 },
    emotionalMoment: { feeling: 'determine', prompt: 'La tortue a continue pas apres pas. Sur quoi continues-tu d\'essayer, toi ?' },
    rewardEmoji: '🐢',
    rewardName: 'Tortue perseverante',
  },
];

export function getConteById(id) {
  return CONTES.find((c) => c.id === id) || null;
}
