// Dutch translations for all 19 fairy tales.
// Only content fields are translated — id, emoji, coverImage, palette,
// difficulty, ageMin, ageMax, rewardEmoji are intentionally omitted.

export const CONTES_NL = {
  'snow-white': {
    title: 'Sneeuwwitje',
    summary: 'Een lief prinsesje met een huid zo wit als sneeuw vindt een thuis bij zeven vriendelijke kleine helpers en leert dat echte vrienden voor elkaar zorgen.',
    theme: 'vriendelijkheid en vriendschap',
    scenes: [
      { text: 'Lang geleden werd er een prinsesje geboren met een huid zo wit als sneeuw. Iedereen noemde haar Sneeuwwitje.' },
      { text: 'Een jaloerse koningin bezat een magische spiegel en stelde hem elke dag dezelfde vraag.', dialogue: { speaker: 'Koningin', line: 'Spiegel, spiegel, wie is de liefste en de mooiste van allemaal?' } },
      { text: 'Sneeuwwitje liep diep het bos in. Zeven kleine, vriendelijke mijnwerkers verwelkomden haar in hun gezellige huisje.', dialogue: { speaker: 'Een mijnwerker', line: 'Je bent hier veilig, kleine vriendin. Kom uitrusten.' } },
      { text: 'De koningin bedroog haar met een glanzende appel, en Sneeuwwitje viel in een heel, heel diepe slaap.' },
      { text: 'Een zorgzame vriendin wekte haar heel zachtjes. Sneeuwwitje glimlachte, en iedereen vierde haar dappere vriendin.', dialogue: { speaker: 'Sneeuwwitje', line: 'Jullie hebben me nooit verlaten. Dank jullie wel, vrienden!' } },
    ],
    vocabulary: [
      { word: 'de mooiste', meaning: 'de liefste en de knapste persoon', emoji: '🌷' },
      { word: 'jaloers', meaning: 'boos omdat je wil wat een ander heeft', emoji: '😠' },
      { word: 'huisje', meaning: 'een klein, knus huisje', emoji: '🏡' },
      { word: 'verwelkomen', meaning: 'iemand blij maken dat hij er is', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel vriendelijke kleine mijnwerkers verwelkomden Sneeuwwitje?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'omringd en beschermd', prompt: 'De vrienden van Sneeuwwitje pasten op haar. Wie past er op jou?' },
    rewardName: 'Vriendelijke spiegel',
  },

  'cinderella': {
    title: 'Assepoester',
    summary: 'Een hardwerkend meisje met een groot hart krijgt wat hulp van een magische vriendin en ontdekt dat vriendelijk zijn zelf een soort magie is.',
    theme: 'hoop en vriendelijkheid',
    scenes: [
      { text: 'Assepoester deed alle klusjes en verloor nooit haar lieve glimlach, ook niet als anderen gemeen waren.' },
      { text: 'Op een avond werd er een groot bal aangekondigd, maar Assepoester had niets om aan te trekken.', dialogue: { speaker: 'Assepoester', line: 'Was ik maar een keertje mee kunnen dansen.' } },
      { text: 'Een vriendelijke fee verscheen en veranderde met een zwaai van haar toverstaf een pompoen in een koets.', dialogue: { speaker: 'Vriendin-fee', line: 'Wees terug voor middernacht, lieverd — dan stopt de magie.' } },
      { text: 'Op het bal danste en lachte Assepoester. Maar toen de klok begon te slaan, moest ze rennen.' },
      { text: 'Het muiltje paste haar precies. Haar vriendelijkheid was altijd zichtbaar geweest, en vreugde vulde haar dagen.', dialogue: { speaker: 'Assepoester', line: 'Vriendelijk zijn kost niets.' } },
    ],
    vocabulary: [
      { word: 'klusjes', meaning: 'kleine taakjes om thuis te helpen', emoji: '🧹' },
      { word: 'koets', meaning: 'een wagen die getrokken wordt om mensen te vervoeren', emoji: '🛞' },
      { word: 'middernacht', meaning: 'twaalf uur s nachts', emoji: '🕛' },
      { word: 'lief', meaning: 'teder, rustig en vriendelijk', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'Hoe laat moet Assepoester terug zijn? Tel de slagen van de klok!', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'vol hoop', prompt: 'Zelfs op moeilijke dagen bleef Assepoester vriendelijk. Wat helpt jou om hoopvol te blijven?' },
    rewardName: 'Glazen muiltje',
  },

  'little-red-riding-hood': {
    title: 'Roodkapje',
    summary: 'Een dapper meisje met een rood kapje gaat naar haar oma en leert onderweg naar haar wijze gevoel te luisteren.',
    theme: 'luisteren en veilig blijven',
    scenes: [
      { text: 'Een klein meisje droeg overal een felrood kapje; daarom noemde iedereen haar Roodkapje.' },
      { text: 'Haar mama gaf haar een mand met brood voor oma.', dialogue: { speaker: 'Mama', line: 'Blijf op het pad en alles komt goed.' } },
      { text: 'In het bos stelde een slimme wolf veel vragen. Roodkapje voelde dat er iets vreemds was en liep gewoon door.', dialogue: { speaker: 'Roodkapje', line: 'Ik hoef jou geen antwoord te geven. Ik zeg het aan een volwassene.' } },
      { text: 'Een vriendelijke houthakker hoorde haar en liep met haar mee. Samen kwamen ze bij oma aan.' },
      { text: 'Oma was veilig, en Roodkapje ook. Ze deelden lekker warm brood en lachten de hele middag.', dialogue: { speaker: 'Oma', line: 'Je hebt naar je verstandige gevoel geluisterd. Ik ben trots op jou.' } },
    ],
    vocabulary: [
      { word: 'pad', meaning: 'een weg die laat zien waar je veilig kunt lopen', emoji: '🛤️' },
      { word: 'mand', meaning: 'een drager met een hengsel om dingen in te vervoeren', emoji: '🧺' },
      { word: 'slim', meaning: 'iemand die trucjes gebruikt om je te bedriegen', emoji: '🦊' },
      { word: 'houthakker', meaning: 'iemand die tussen de bomen werkt', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'Een vreemde vraagt Roodkapje waar ze naartoe gaat. Wat is de veilige keuze?', options: ['Alles vertellen', 'Doorlopen en een volwassene waarschuwen', 'Hem volgen het bos in'], answerIndex: 1 },
    emotionalMoment: { feeling: 'veilig', prompt: 'Roodkapje luisterde naar haar rare gevoel. Wanneer hielp een gevoel jou veilig te blijven?' },
    rewardName: 'Rood kapje',
  },

  'hansel-and-gretel': {
    title: 'Hans en Grietje',
    summary: 'Een broer en zus raken verdwaald in het bos en gebruiken een slim plan en teamwork om veilig thuis te komen.',
    theme: 'slimheid en samen blijven',
    scenes: [
      { text: 'Hans en Grietje liepen het grote bos in, hand in hand om niet te verdwalen.' },
      { text: 'De slimme Hans liet kleine, glanzende witte steentjes vallen, een voor een, om de weg terug te markeren.', dialogue: { speaker: 'Hans', line: 'Deze steentjes zullen schitteren en ons naar huis brengen.' } },
      { text: 'Ze vonden een klein huisje van snoep, maar een slimme oude vrouw woonde er.' },
      { text: 'De kinderen waren te slim om zich te laten bedriegen. Ze pakten elkaars hand en sloopen naar buiten.', dialogue: { speaker: 'Grietje', line: 'Snel — samen zijn we moediger dan alleen.' } },
      { text: 'De glanzende steentjes glinsterden in het maanlicht en brachten hen recht naar huis, naar een warme knuffel.' },
    ],
    vocabulary: [
      { word: 'steentjes', meaning: 'kleine, gladde kiezels', emoji: '🪨' },
      { word: 'slim', meaning: 'goed in het bedenken van slimme ideeen', emoji: '💡' },
      { word: 'op je tenen', meaning: 'heel zachtjes lopen op je tenen', emoji: '🦶' },
      { word: 'samen', meaning: 'met elkaar, zij aan zij', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet het slimme plan van Hans in de goede volgorde!', steps: ['De glanzende steentjes laten vallen', 'Het schitterende spoor volgen', 'De weg naar huis terugvinden'] },
    emotionalMoment: { feeling: 'samen dapper', prompt: 'De kinderen waren moediger als team. Wie maakt jou moediger?' },
    rewardName: 'Glanzend steentje',
  },

  'rapunzel': {
    title: 'Rapunzel',
    summary: 'Een lief meisje met heel lang haar woont in een hoge toren en leert dat geduld en een hart vol hoop elke deur kunnen openen.',
    theme: 'geduld en hoop',
    scenes: [
      { text: 'Helemaal bovenin een hoge toren woonde Rapunzel, een meisje met de langste gouden vlecht ter wereld.' },
      { text: 'Elke dag zong Rapunzel voor de vogels. Haar zachte lied zweefde door het hele bos.', dialogue: { speaker: 'Rapunzel', line: 'Op een dag zal ik de wereld daarbineden zien, onder de bomen.' } },
      { text: 'Een vriendelijke reiziger hoorde haar lied en riep: "Jouw muziek laat het bos glimlachen!"', dialogue: { speaker: 'Reiziger', line: 'Jouw muziek laat het hele bos glimlachen!' } },
      { text: 'Ze werden vrienden. Dag na dag bedachten ze geduldig een slimme manier om naar beneden te komen.' },
      { text: 'Eindelijk zette Rapunzel haar voet op het zachte gras en draaide rond in de zon, vrij en blij.', dialogue: { speaker: 'Rapunzel', line: 'Wachten was moeilijk, maar hoop hield me sterk.' } },
    ],
    vocabulary: [
      { word: 'toren', meaning: 'een heel hoog en smal gebouw', emoji: '🗼' },
      { word: 'vlecht', meaning: 'haar dat gevlochten is tot een lange touwachtige streng', emoji: '💇' },
      { word: 'geduld', meaning: 'rustig wachten zonder op te geven', emoji: '⏳' },
      { word: 'weide', meaning: 'een veld met gras vol bloemen', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Zoek wat Rapunzel gebruikte om veilig naar beneden te komen.', target: 'de gouden gevlochten ladder', decoys: ['een papieren vlieger', 'een houten lepel', 'een klein kopje'] },
    emotionalMoment: { feeling: 'geduldig', prompt: 'Rapunzel wachtte met hoop. Op welk mooi ding heb jij lang gewacht?' },
    rewardName: 'Gouden vlecht',
  },

  'the-ugly-duckling': {
    title: 'Het Lelijke Eendje',
    summary: 'Een klein vogeltje dat zich anders voelt dan de anderen groeit op en ontdekt dat het al die tijd prachtig was, precies zoals het was.',
    theme: 'erbij horen en van jezelf houden',
    scenes: [
      { text: 'In een zonnige vijver leek een klein vogeltje niet op zijn broers en zussen.' },
      { text: 'De andere vogels lachten hem uit, en diep vanbinnen voelde hij zich eenzaam en heel verdrietig.', dialogue: { speaker: 'Klein vogeltje', line: 'Ik wou dat iemand mij ook liet meedoen.' } },
      { text: 'Een vriendelijke kikker sprong dichterbij en ging naast hem zitten. "Jij bent bij mij welkom", zei ze.', dialogue: { speaker: 'Kikker', line: 'Jij bent bij mij welkom, mijn vriend.' } },
      { text: 'De seizoenen gingen voorbij. Op een heldere ochtend zag het kleine vogeltje zijn gezicht in het stille water.' },
      { text: 'Het was een prachtige zwaan geworden! Het was altijd al bijzonder geweest: gewoon zichzelf.', dialogue: { speaker: 'Zwaan', line: 'Ik hoefde niet te veranderen. Ik moest alleen groeien.' } },
    ],
    vocabulary: [
      { word: 'vijver', meaning: 'een kleine plas rustig water', emoji: '💧' },
      { word: 'eenzaam', meaning: 'verdrietig omdat je je helemaal alleen voelt', emoji: '🥺' },
      { word: 'spiegeling', meaning: 'het beeld dat je ziet in stil water', emoji: '🪞' },
      { word: 'zwaan', meaning: 'een grote, witte, sierlijke watervogel', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'Een nieuwe vriend voelt zich buitengesloten. Wat is iets liefs om te zeggen?', options: ['Je hoort hier niet thuis', 'Je mag met ons meedoen!', 'Ga weg'], answerIndex: 1 },
    emotionalMoment: { feeling: 'ik hoor erbij', prompt: 'Het kleine vogeltje was bijzonder zoals het was. Wat maakt jou een geweldige jij?' },
    rewardName: 'Zacht zwaan',
  },

  'the-little-mermaid': {
    title: 'De Kleine Zeemeermin',
    summary: 'Een nieuwsgierige jonge zeemeermin heeft de moed om een nieuwe wereld te verkennen en leert dat een lief en grootmoedig hart meer straalt dan alles.',
    theme: 'moed en een goed hart',
    scenes: [
      { text: 'Diep onder de golven woonde een jonge zeemeermin, de kleinste van zes zusjes.' },
      { text: 'Ze hield ervan om naar de oppervlakte te zwemmen en de lichte wereld boven het water te bekijken.', dialogue: { speaker: 'Zeemeermin', line: 'De wereld daarboven zit vol dingen die ik wil leren!' } },
      { text: 'Op een stormachtige nacht hielp ze met moed een zeeman veilig naar de kust.' },
      { text: 'Ze bleef niet om bedankt te worden. Iemand helpen vulde haar hart met warmte.', dialogue: { speaker: 'Zeemeermin', line: 'Ik hielp uit vriendelijkheid, niet voor een bedankje.' } },
      { text: 'Thuis vertelde ze haar dappere verhaal, en haar goede hart liet de hele zee stralen.' },
    ],
    vocabulary: [
      { word: 'zeemeermin', meaning: 'een denkbeeldig meisje van de zee, met een vissenstaart', emoji: '🧜' },
      { word: 'golven', meaning: 'water dat op en neer beweegt op de zee', emoji: '🌊' },
      { word: 'moedig', meaning: 'iets moeilijks doen ook al ben je bang', emoji: '💪' },
      { word: 'grootmoedig', meaning: 'blij om te geven en anderen te helpen', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel grote zusjes had de Kleine Zeemeermin?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'een groot hart', prompt: 'De zeemeermin hielp puur uit vriendelijkheid. Wanneer hielp jij zonder dat iemand het vroeg?' },
    rewardName: 'Zeeparel',
  },

  'the-snow-queen': {
    title: 'De Sneeuwkoningin',
    summary: 'Als het hart van haar beste vriend koud wordt, reist een trouw meisje genaamd Gerda ver door de sneeuw om hem met liefde te verwarmen.',
    theme: 'trouwe vriendschap',
    scenes: [
      { text: 'Gerda en Kai waren de beste vrienden en verbouwden samen rozen bij hun raam.' },
      { text: 'Een heel klein ijssplintje raakte het hart van Kai, en hij werd koud en afstandelijk.', dialogue: { speaker: 'Gerda', line: 'Wacht... waar ga je naartoe, Kai?' } },
      { text: 'De dappere Gerda gaf niet op. Ze vertrok door de sneeuw om haar vriend te zoeken.', dialogue: { speaker: 'Gerda', line: 'Ik vind je terug, Kai. Vrienden geven niet op.' } },
      { text: 'Ze vond Kai in een ijspaleis, roerloos en koud als steen.' },
      { text: 'Gerda omhelsde hem en warme tranen stroomden. Het ijs smolt, en Kai glimlachte en herinnerde zich alles.', dialogue: { speaker: 'Kai', line: 'Je bent helemaal hierheen voor mij gekomen. Dank je, Gerda.' } },
    ],
    vocabulary: [
      { word: 'rijp', meaning: 'een dunne laag ijs die vormt als het heel erg koud is', emoji: '🌨️' },
      { word: 'trouw', meaning: 'er altijd zijn voor je vrienden', emoji: '🤲' },
      { word: 'paleis', meaning: 'een heel groot en prachtig huis', emoji: '🏰' },
      { word: 'smelten', meaning: 'van ijs naar water gaan door warmte', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'Hoe liet Gerda het ijs in Kais hart smelten?', options: ['Met een groot vuur', 'Met warme tranen en een knuffel', 'Met een hamer'], answerIndex: 1 },
    emotionalMoment: { feeling: 'trouw', prompt: 'Gerda gaf haar vriend nooit op. Hoe laat jij een vriend zien dat je om hem geeft?' },
    rewardName: 'Warme roos',
  },

  'puss-in-boots': {
    title: 'De Gelaarsde Kat',
    summary: 'Een slimme kat met mooie laarzen gebruikt zijn vindingrijkheid en trouwe hart om zijn vriendelijke vriend te helpen het geluk te vinden.',
    theme: 'slimheid en loyaliteit',
    scenes: [
      { text: 'Een slimme kat trok mooie laarzen aan en een hoed met een veer, klaar voor het avontuur.' },
      { text: 'Zijn vriend was arm maar lief, dus de kat bedacht een slim plan om hem te helpen.', dialogue: { speaker: 'De Kat', line: 'Vertrouw me, mijn vriend. Er komt een slim idee!' } },
      { text: 'De kat begroette de koning beleefd en bood cadeaus aan, waardoor iedereen glimlachte.' },
      { text: 'Met vindingrijkheid in plaats van trucjes hielp de kat zijn vriend een groot kasteel aan de rivier te winnen.', dialogue: { speaker: 'De Kat', line: 'Goede ideeen openen meer deuren dan hard gebrul.' } },
      { text: 'Zijn vriend was eindelijk gelukkig, en de kat kroelde op bij het vuur, de trouwste kat van allemaal.' },
    ],
    vocabulary: [
      { word: 'slim', meaning: 'goed in het bedenken van slimme ideeen', emoji: '🧠' },
      { word: 'laarzen', meaning: 'schoenen die hoog op de benen reiken', emoji: '🥾' },
      { word: 'beleefd', meaning: 'vriendelijk en zacht met je woorden', emoji: '🙏' },
      { word: 'trouw', meaning: 'er altijd zijn voor je vrienden', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet het slimme plan van de Kat in de goede volgorde!', steps: ['De mooie laarzen aantrekken', 'De koning beleefd begroeten', 'Zijn vriend helpen de dag te winnen'] },
    emotionalMoment: { feeling: 'behulpzaam', prompt: 'De Kat gebruikte slimme ideeen om een vriend te helpen. Op welke slimme manier heb jij al eens iemand geholpen?' },
    rewardName: 'Mooie laarzen',
  },

  'pinocchio': {
    title: 'Pinokkio',
    summary: 'Een houten poppetje dat droomt van een echt jongetje te zijn, leert dat de waarheid spreken is wat een goed hart doet groeien.',
    theme: 'eerlijkheid',
    scenes: [
      { text: 'Er was eens een klein houten poppetje dat Pinokkio heette en dat droomde van een echt jongetje te worden.' },
      { text: 'Elke keer als Pinokkio een leugen vertelde, groeide zijn neus uit als een tak.', dialogue: { speaker: 'Pinokkio', line: 'Dat was ik niet! Echt waar!' } },
      { text: 'Zijn vriend het krekel probeerde hem te leren altijd de waarheid te vertellen.', dialogue: { speaker: 'Krekel', line: 'De waarheid vertellen maakt je licht als een veertje.' } },
      { text: 'Pinokkio maakte een grote fout en raakte verdwaald. Toen leerde hij dat eerlijkheid zijn enige gids was.' },
      { text: 'Toen Pinokkio eindelijk de waarheid zei, groeide zijn hart, en zijn liefste wens ging in vervulling.', dialogue: { speaker: 'Pinokkio', line: 'De waarheid is de krachtigste magie van allemaal.' } },
    ],
    vocabulary: [
      { word: 'poppetje', meaning: 'een pop die beweegt', emoji: '🎭' },
      { word: 'waarheid', meaning: 'precies vertellen wat er is gebeurd', emoji: '✅' },
      { word: 'leugen', meaning: 'iets zeggen dat niet waar is', emoji: '❌' },
      { word: 'eerlijk', meaning: 'iemand die altijd de waarheid zegt', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'Wanneer wordt de neus van Pinokkio langer?', options: ['Als hij de waarheid zegt', 'Als hij een leugen vertelt', 'Als hij een liedje zingt'], answerIndex: 1 },
    emotionalMoment: { feeling: 'eerlijk', prompt: 'De waarheid zeggen maakte Pinokkio licht. Hoe voel jij je als je de waarheid vertelt?' },
    rewardName: 'Krekel van de waarheid',
  },

  'peter-pan': {
    title: 'Peter Pan',
    summary: 'Een jongen die nooit opgroeit neemt nieuwe vrienden mee op een vliegavontuur waarbij blije gedachten en een beetje moed je overal brengen.',
    theme: 'verbeelding en moed',
    scenes: [
      { text: 'In een kamer vol sterren leerde een jongen genaamd Peter Pan de kinderen vliegen.' },
      { text: 'Peter vertelde Wendy het geheim: je moest aan iets heel gelukkigs denken.', dialogue: { speaker: 'Peter Pan', line: 'Denk aan je gelukkigste ding — en hop, je vliegt!' } },
      { text: 'Samen vlogen ze naar Nooitgedachtland, een magisch eiland vol avonturen.' },
      { text: 'Zelfs tegenover de boze kapitein was Peter niet bang. Hij stond het gevaar met een grote glimlach te woord.', dialogue: { speaker: 'Peter Pan', line: 'Dapper zijn is toch proberen.' } },
      { text: 'De kinderen gingen naar huis met herinneringen in hun hart en een vleugje magie voor altijd.' },
    ],
    vocabulary: [
      { word: 'slaapkamer', meaning: 'de kamer waar je slaapt en droomt', emoji: '🛏️' },
      { word: 'schaduw', meaning: 'de donkere vorm die jouw lichaam op de grond maakt', emoji: '👤' },
      { word: 'verbeelden', meaning: 'mooie dingen bedenken in je hoofd', emoji: '💭' },
      { word: 'moed', meaning: 'toch proberen ook al ben je bang', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Wat hielp de kinderen vliegen?', options: ['Blije gedachten en feestenstuif', 'Zware laarzen', 'Heel hard schreeuwen'], answerIndex: 0 },
    emotionalMoment: { feeling: 'moedig', prompt: 'Peter zegt dat dapper zijn toch proberen is. Wat moedigs zou jij graag willen proberen?' },
    rewardName: 'Feenstof',
  },

  'alice-in-wonderland': {
    title: 'Alice in Wonderland',
    summary: 'Een nieuwsgierig meisje volgt een haastig konijn een ondersteboven wereld in en leert dat vragen stellen een soort magie is.',
    theme: 'nieuwsgierigheid',
    scenes: [
      { text: 'Alice zag een haastig wit konijn in een hol springen en volgde het uit pure nieuwsgierigheid.' },
      { text: 'Ze viel in een lange magische gang en vond een heel kleine deur naar een tuin.', dialogue: { speaker: 'Alice', line: 'Wat raar! Ik vraag me af wat hier aan de hand is.' } },
      { text: 'Alice dronk een klein flesje en werd kleiner, daarna at ze een koekje en werd heel snel groter.', dialogue: { speaker: 'Alice', line: 'Vragen zijn de sleutel tot alle wonderen!' } },
      { text: 'Ze ontmoette een glimlachende kat, een boze koningin en een gekke hoedenmaker.' },
      { text: 'Alice werd wakker en glimlachte. Vragen stellen had haar naar de mooiste droom geleid.', dialogue: { speaker: 'Alice', line: 'Nieuwsgierigheid is het grootste avontuur.' } },
    ],
    vocabulary: [
      { word: 'nieuwsgierig', meaning: 'iemand die graag nieuwe dingen ontdekt', emoji: '🔍' },
      { word: 'hol', meaning: 'een tunnel gegraven in de grond door een dier', emoji: '🕳️' },
      { word: 'krimpen', meaning: 'kleiner worden', emoji: '🔻' },
      { word: 'wonder', meaning: 'iets ongelooflijks en heel verrassends', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet het avontuur van Alice in de goede volgorde!', steps: ['Het flesje drinken en krimpen', 'Het koekje eten en groeien', 'De kleine tuindeur vinden'] },
    emotionalMoment: { feeling: 'nieuwsgierig', prompt: 'Alice hield van vragen stellen. Waar ben jij vandaag nieuwsgierig naar?' },
    rewardName: 'Nieuwsgierig klokje',
  },

  'the-wizard-of-oz': {
    title: 'De Tovenaar van Oz',
    summary: 'Een meisje en drie nieuwe vrienden volgen een gouden weg en ontdekken dat de gaven die ze zochten al die tijd al in henzelf zaten.',
    theme: 'je hebt al wat je nodig hebt',
    scenes: [
      { text: 'Een grote wervelwind nam Dorothee en haar kleine hond Toto mee naar het magische land Oz.' },
      { text: 'Op de gouden weg ontmoette Dorothee een vogelverschrikker, een man van blik en een leeuw.', dialogue: { speaker: 'Vogelverschrikker', line: 'Ik wil gewoon een slim brein!' } },
      { text: 'Samen liepen ze naar de Smaragdstad om de grote Tovenaar te vinden.', dialogue: { speaker: 'Dorothee', line: 'Als we samen zijn, kunnen we alles.' } },
      { text: 'De Tovenaar onthulde hun een groot geheim: ze hadden al die tijd al alles wat ze begeerden.' },
      { text: 'Dorothee tikte drie keer met haar schoentjes en was weer thuis. Iedereen had zijn gave gevonden.', dialogue: { speaker: 'Dorothee', line: 'Er is geen plek zoals thuis.' } },
    ],
    vocabulary: [
      { word: 'wervelwind', meaning: 'een heel sterke wind die in het rond draait', emoji: '🌪️' },
      { word: 'vogelverschrikker', meaning: 'een grote stropen pop om vogels te verjagen', emoji: '🌾' },
      { word: 'moed', meaning: 'doorgaan ook al ben je bang', emoji: '💪' },
      { word: 'reis', meaning: 'een lange wandeling of avontuur naar een nieuwe plek', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Welke vriend had van het begin af aan al moed?', options: ['De vogelverschrikker', 'De blikken man', 'De leeuw'], answerIndex: 2 },
    emotionalMoment: { feeling: 'bekwaam', prompt: 'De vrienden hadden hun gaven al in henzelf. Welke gave heb jij al in jezelf?' },
    rewardName: 'Schitterende schoentjes',
  },

  'robin-hood': {
    title: 'Robin Hood',
    summary: 'Een vriendelijke boogschutter uit het groene bos deelt met mensen die weinig hebben en leert zijn vrienden dat rechtvaardigheid iedereen gelukkiger maakt.',
    theme: 'rechtvaardigheid en vrijgevigheid',
    scenes: [
      { text: 'In een groot groen bos woonde Robin Hood, de beste boogschutter van het land.' },
      { text: 'Hij zag dat veel mensen erg arm waren terwijl anderen alles hadden.', dialogue: { speaker: 'Robin', line: 'Delen is het mooiste cadeau.' } },
      { text: 'Samen met zijn vrolijke vrienden bedacht Robin een plan om mensen in nood te helpen.', dialogue: { speaker: 'Kleine Jan', line: 'Samen zijn we de kracht van het bos!' } },
      { text: 'Robin deelde wat mensen nodig hadden, en overal verschenen glimlachen.' },
      { text: 'Het bos gonste van geluk. Robin had geleerd dat vrijgevigheid de echte overwinning is.', dialogue: { speaker: 'Robin', line: 'Vrijgevigheid maakt iedereen rijker.' } },
    ],
    vocabulary: [
      { word: 'boogschutter', meaning: 'iemand die pijlen schiet met een boog', emoji: '🎯' },
      { word: 'bos', meaning: 'een grote plek vol bomen en dieren', emoji: '🌳' },
      { word: 'rechtvaardig', meaning: 'iedereen op dezelfde manier behandelen', emoji: '⚖️' },
      { word: 'vrijgevig', meaning: 'graag geven en delen', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin Hood deelde met mensen die...', options: ['honger hadden en in nood waren', 'al heel rijk waren', 'gemeen waren voor anderen'], answerIndex: 0 },
    emotionalMoment: { feeling: 'rechtvaardig', prompt: 'Robin hield van delen. Wat zou jij kunnen delen om een vriend te laten glimlachen?' },
    rewardName: 'Vriendschapsboog',
  },

  'goldilocks': {
    title: 'Goudlokje',
    summary: 'Een nieuwsgierig meisje gaat het gezellige berenhuisje binnen en leert dat het beter is eerst te vragen en goed te zorgen voor andermans spullen.',
    theme: 'respect voor anderen',
    scenes: [
      { text: 'Een meisje met gouden krullen wandelde door het bos en vond een lief huisje.' },
      { text: 'Ze ging naar binnen en proefde drie kommetjes pap. Die van het kleine beertje was precies goed.', dialogue: { speaker: 'Goudlokje', line: 'Oh! Dit kommetje is perfect, niet te warm en niet te koud!' } },
      { text: 'Ze probeerde drie stoelen, daarna drie bedden. Ze viel in slaap in het zachtste.' },
      { text: 'De drie beren kwamen terug en vonden hun huis overhoop.', dialogue: { speaker: 'Klein beertje', line: 'Iemand heeft uit mijn kommetje gegeten!' } },
      { text: 'Goudlokje werd wakker, zei sorry en leerde dat eerst vragen de liefste beleefdheidsvorm is.', dialogue: { speaker: 'Goudlokje', line: 'Sorry. Ik zal altijd eerst vragen voor ik binnenkom.' } },
    ],
    vocabulary: [
      { word: 'pap', meaning: 'warm en zacht eten, zoals ontbijtgranen', emoji: '🥣' },
      { word: 'huisje', meaning: 'een klein, gezellig huisje in het bos', emoji: '🏡' },
      { word: 'respect', meaning: 'goed zorgen voor andermans spullen en gevoelens', emoji: '🙏' },
      { word: 'sorry', meaning: 'wat je zegt als je ergens spijt van hebt', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel beren woonden er in het gezellige huisje?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respectvol', prompt: 'Goudlokje leerde eerst te vragen. Wanneer is het vriendelijk om toestemming te vragen voor je iets leent?' },
    rewardName: 'Perfect kommetje',
  },

  'three-little-pigs': {
    title: 'De Drie Biggetjes',
    summary: 'Drie kleine biggetjes bouwen drie verschillende huizen en leren dat zorgvuldig en ijverig werk iedereen veilig en warm houdt.',
    theme: 'werk en organisatie',
    scenes: [
      { text: 'Drie kleine biggetjes trokken de wereld in om hun huis te bouwen.' },
      { text: 'Het eerste biggetje bouwde snel een huis van stro. Het tweede een huis van hout.', dialogue: { speaker: 'Eerste biggetje', line: 'Snel klaar, goed gedaan! Ik wil gaan spelen!' } },
      { text: 'Het derde biggetje werkte hard en bouwde steen voor steen een stevig huis van bakstenen.', dialogue: { speaker: 'Derde biggetje', line: 'Ik neem de tijd zodat mijn huis stevig is.' } },
      { text: 'De grote boze wolf blies op de huizen van stro en hout, en ze stortten in.' },
      { text: 'Maar het bakstenen huis bleef stevig staan. De drie biggetjes waren veilig, en iedereen leerde dat zorgvuldig werken beschermt.', dialogue: { speaker: 'Derde biggetje', line: 'Goed werk kost tijd, maar het is de moeite waard!' } },
    ],
    vocabulary: [
      { word: 'stro', meaning: 'droge plantenstengels die makkelijk breken', emoji: '🌾' },
      { word: 'bakstenen', meaning: 'heel stevige gebakken aardblokken', emoji: '🧱' },
      { word: 'stevig', meaning: 'heel sterk, niet makkelijk te breken', emoji: '💪' },
      { word: 'plannen', meaning: 'nadenken voor je ergens mee begint', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel kleine biggetjes bouwden een huis?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'trots op mijn werk', prompt: 'Het derde biggetje werkte hard en bleef veilig. Waar heb jij hard aan gewerkt?' },
    rewardName: 'Stevige baksteen',
  },

  'aladdin': {
    title: 'Aladdin',
    summary: 'Een gewoon maar lief jongetje vindt een magische lamp en leert dat wat je wenst minder telt dan het goede dat je voor anderen doet.',
    theme: 'eerlijkheid en bescheidenheid',
    scenes: [
      { text: 'Op een levendige markt woonde Aladdin, een arme jongen met een hart van goud.' },
      { text: 'Hij vond een oude lamp en toen hij eraan wreef, verscheen er een grote geest!', dialogue: { speaker: 'Geest', line: 'Ik geef je drie wensen. Kies zorgvuldig!' } },
      { text: 'Aladdin wenste eerst zijn familie te helpen, dan de arme mensen in zijn wijk.', dialogue: { speaker: 'Aladdin', line: 'Ik wil dat niemand op deze markt honger heeft.' } },
      { text: 'Zijn bescheidenheid en vrijgevigheid bezorgden hem echte vrienden en veel geluk.' },
      { text: 'Aladdin leerde dat de beste wensen die zijn die je voor anderen doet.', dialogue: { speaker: 'Aladdin', line: 'Een vrijgevig hart is de grootste schat.' } },
    ],
    vocabulary: [
      { word: 'markt', meaning: 'een drukke plek waar mensen kopen en verkopen', emoji: '🏪' },
      { word: 'lamp', meaning: 'een voorwerp dat licht geeft of een geest bewaart', emoji: '🪔' },
      { word: 'bescheiden', meaning: 'iemand die niet opschept over zichzelf', emoji: '🙏' },
      { word: 'wens', meaning: 'iets waar je heel erg naar verlangt', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel wensen gaf de geest aan Aladdin?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'vrijgevig', prompt: 'Aladdin wenste om anderen te helpen. Als jij een lieve wens mocht doen, welke zou dat zijn?' },
    rewardName: 'Wensenlamp',
  },

  'ali-baba': {
    title: 'Ali Baba',
    summary: 'Een vriendelijke houthakker ontdekt een geheime grot en leert dat eerlijk en voorzichtig zijn veel beter is dan hebzuchtig zijn.',
    theme: 'eerlijkheid boven hebzucht',
    scenes: [
      { text: 'Ali Baba was een vriendelijke houthakker die eenvoudig en tevreden leefde.' },
      { text: 'Op een dag in het bos hoorde hij rovers de magische woorden zeggen bij een grote rots.', dialogue: { speaker: 'Rovers', line: 'Sesam, open u!' } },
      { text: 'Ali Baba liep de grot in en zag schitterende schatten in alle kleuren.', dialogue: { speaker: 'Ali Baba', line: 'Ik neem alleen wat we nodig hebben, niet meer.' } },
      { text: 'Zijn hebzuchtige broer nam te veel en werd verrast door de rovers. Ali Baba begreep de les.' },
      { text: 'Ali Baba deelde zijn goede fortuin met anderen en leefde eenvoudig en gelukkig.', dialogue: { speaker: 'Ali Baba', line: 'Genoeg hebben en eerlijk zijn, dat is de echte rijkdom.' } },
    ],
    vocabulary: [
      { word: 'grot', meaning: 'een grote, natuurlijke holte in de rots', emoji: '🕳️' },
      { word: 'schat', meaning: 'een grote hoeveelheid goud en kostbare dingen', emoji: '💎' },
      { word: 'hebzuchtig', meaning: 'iemand die altijd meer wil dan hij nodig heeft', emoji: '😤' },
      { word: 'genoeg', meaning: 'precies wat je nodig hebt, niet meer en niet minder', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Welke magische woorden openen de grot?', options: ['Sesam, open u!', 'Doe de deur dicht!', 'Goedemorgen!'], answerIndex: 0 },
    emotionalMoment: { feeling: 'tevreden', prompt: 'Ali Baba nam alleen wat nodig was. Welk ding dat je al hebt, is precies genoeg voor jou?' },
    rewardName: 'Geheime grot',
  },

  'aesops-fables': {
    title: 'De Haas en de Schildpad',
    summary: 'Een snelle haas en een langzame schildpad houden een vriendschappelijke race, en de schildpad laat iedereen zien dat nooit opgeven de dag wint.',
    theme: 'doorzettingsvermogen — langzaam maar zeker',
    scenes: [
      { text: 'In een zonnige weide schepte een snelle haas altijd op over zijn snelheid.' },
      { text: 'De langzame, rustige schildpad daagde hem uit. De haas accepteerde lachend.', dialogue: { speaker: 'Haas', line: 'Een race tegen jou? Makkelijk! Ik ga onderweg even rusten.' } },
      { text: 'De schildpad liep stap voor stap, gestaag, zonder ooit te stoppen.', dialogue: { speaker: 'Schildpad', line: 'Langzaam maar zeker kom ik vooruit.' } },
      { text: 'De haas viel in slaap onder een boom, zeker dat de schildpad hem nooit zou inhalen.' },
      { text: 'Toen de haas wakker werd, had de schildpad de finish al gehaald. Doorzetten wint altijd.', dialogue: { speaker: 'Schildpad', line: 'Stap voor stap kom je verder dan je denkt.' } },
    ],
    vocabulary: [
      { word: 'haas', meaning: 'een groot, wild konijn dat heel snel is', emoji: '🐇' },
      { word: 'schildpad', meaning: 'een dier met een schild dat langzaam maar zonder stoppen loopt', emoji: '🐢' },
      { word: 'gestaag', meaning: 'in hetzelfde tempo vooruitgaan zonder te stoppen', emoji: '⏱️' },
      { word: 'doorzetten', meaning: 'blijven proberen ook als het moeilijk is', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Wie won de race door nooit op te geven?', options: ['de snelle haas', 'de langzame, gestadige schildpad', 'de slapende vos'], answerIndex: 1 },
    emotionalMoment: { feeling: 'vastberaden', prompt: 'De schildpad ging stap voor stap door. Waar blijf jij zelf mee doorgaan?' },
    rewardName: 'Doorzettingsschildpad',
  },
};
