// Spanish translations for all 19 fairy tales.
// Only content fields are translated — id, emoji, coverImage, palette,
// difficulty, ageMin, ageMax, rewardEmoji are intentionally omitted.

export const CONTES_ES = {
  'snow-white': {
    title: 'Blancanieves',
    summary: 'Una dulce princesa con la piel blanca como la nieve encuentra un hogar junto a siete pequenos amigos bondadosos y aprende que los verdaderos amigos siempre cuidan los unos de los otros.',
    theme: 'bondad y amistad',
    scenes: [
      { text: 'Hace mucho tiempo, nacio una pequena princesa con la piel blanca como la nieve. Todo el mundo la llamaba Blancanieves.' },
      { text: 'Una reina celosa tenia un espejo magico y le hacia la misma pregunta cada dia.', dialogue: { speaker: 'Reina', line: 'Espejito, espejito, quien es la mas bondadosa y hermosa de todas?' } },
      { text: 'Blancanieves camino hasta el corazon del bosque. Siete pequenos mineros bondadosos la acogieron en su acogedora cabana.', dialogue: { speaker: 'Un minero', line: 'Estas a salvo aqui, pequeña amiga. Ven a descansar.' } },
      { text: 'La reina la engano con una manzana brillante, y Blancanieves cayo en un sueno muy, muy profundo.' },
      { text: 'Una amiga carinosa la desperto con un gesto muy suave. Blancanieves sonrio, y todos celebraron a su valiente amiga.', dialogue: { speaker: 'Blancanieves', line: 'Nunca me abandonasteis. Gracias, mis amigos!' } },
    ],
    vocabulary: [
      { word: 'la mas bella', meaning: 'la persona mas bondadosa y mas bonita', emoji: '🌷' },
      { word: 'celosa', meaning: 'enfadada porque quiere lo que tiene otra persona', emoji: '😠' },
      { word: 'cabana', meaning: 'una casita pequena y acogedora', emoji: '🏡' },
      { word: 'acoger', meaning: 'hacer que alguien se sienta feliz de haber llegado', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos pequenos mineros bondadosos acogieron a Blancanieves?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'rodeada y protegida', prompt: 'Los amigos de Blancanieves velaban por ella. Quien vela por ti?' },
    rewardName: 'Espejo bondadoso',
  },

  'cinderella': {
    title: 'Cenicienta',
    summary: 'Una chica trabajadora con un gran corazon recibe un poco de ayuda de una amiga magica y descubre que ser amable es una magia en si misma.',
    theme: 'esperanza y bondad',
    scenes: [
      { text: 'Cenicienta hacia todas las tareas y nunca perdia su dulce sonrisa, aunque los demas fueran crueles.' },
      { text: 'Una noche, se anuncio un gran baile, pero Cenicienta no tenia nada que ponerse.', dialogue: { speaker: 'Cenicienta', line: 'Si al menos pudiera ir a bailar, solo una vez.' } },
      { text: 'Aparecio un hada bondadosa y, con un toque de su varita, convirtio una calabaza en una carroza.', dialogue: { speaker: 'Hada amiga', line: 'Vuelve antes de medianoche, querida — entonces la magia se acaba.' } },
      { text: 'En el baile, Cenicienta bailo y rio. Pero cuando el reloj empezo a sonar, tuvo que correr.' },
      { text: 'El zapatito le quedaba perfectamente. Su bondad siempre habia sido visible, y la alegria lleno sus dias.', dialogue: { speaker: 'Cenicienta', line: 'Ser amable no cuesta nada.' } },
    ],
    vocabulary: [
      { word: 'tareas', meaning: 'pequenos trabajos para ayudar en casa', emoji: '🧹' },
      { word: 'carroza', meaning: 'un coche tirado para transportar a personas', emoji: '🛞' },
      { word: 'medianoche', meaning: 'las doce de la noche', emoji: '🕛' },
      { word: 'dulce', meaning: 'tierno, tranquilo y amable', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'A que hora debe volver Cenicienta? Cuenta los golpes del reloj!', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'llena de esperanza', prompt: 'Incluso en los dias dificiles, Cenicienta seguia siendo amable. Que te ayuda a mantener la esperanza?' },
    rewardName: 'Zapatilla de cristal',
  },

  'little-red-riding-hood': {
    title: 'Caperucita Roja',
    summary: 'Una valiente nina con una caperuza roja va a casa de su abuela y aprende a escuchar sus sabios instintos durante el camino.',
    theme: 'escuchar y mantenerse a salvo',
    scenes: [
      { text: 'Una ninita llevaba una brillante caperuza roja a todas partes, asi que todo el mundo la llamaba Caperucita Roja.' },
      { text: 'Su mama le dio una cesta con pan para la abuela.', dialogue: { speaker: 'Mama', line: 'Quédate en el camino y todo ira bien.' } },
      { text: 'En el bosque, un lobo astuto hizo muchas preguntas. Caperucita sintio que algo era extrano y siguio caminando.', dialogue: { speaker: 'Caperucita', line: 'No tengo que responderte. Se lo dire a un adulto.' } },
      { text: 'Un amable lenador la escucho y camino con ella. Juntos llegaron a casa de la abuela.' },
      { text: 'La abuela estaba a salvo, y Caperucita tambien. Compartieron pan caliente y rieron toda la tarde.', dialogue: { speaker: 'Abuela', line: 'Escuchaste tus sabios instintos. Estoy muy orgullosa de ti.' } },
    ],
    vocabulary: [
      { word: 'camino', meaning: 'una senda que te muestra por donde ir a salvo', emoji: '🛤️' },
      { word: 'cesta', meaning: 'un portador con asa para llevar cosas', emoji: '🧺' },
      { word: 'astuto', meaning: 'alguien que usa trucos para enganarte', emoji: '🦊' },
      { word: 'lenador', meaning: 'una persona que trabaja entre los arboles', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'Un desconocido le pregunta a Caperucita adonde va. Cual es la eleccion segura?', options: ['Contarle todo', 'Seguir caminando y avisar a un adulto', 'Seguirle entre los arboles'], answerIndex: 1 },
    emotionalMoment: { feeling: 'a salvo', prompt: 'Caperucita escucho su extrana sensacion. Cuando te ha ayudado un instinto a mantenerte a salvo?' },
    rewardName: 'Caperuza roja',
  },

  'hansel-and-gretel': {
    title: 'Hansel y Gretel',
    summary: 'Un hermano y una hermana se pierden en el bosque y usan un plan astuto, y su trabajo en equipo, para llegar sanos y salvos a casa.',
    theme: 'astucia y permanecer juntos',
    scenes: [
      { text: 'Hansel y Gretel se adentraron en el gran bosque cogidos de la mano para no perderse.' },
      { text: 'El astuto Hansel fue dejando caer pequenas piedrecitas blancas y brillantes, una a una, para marcar el camino de vuelta.', dialogue: { speaker: 'Hansel', line: 'Estas piedrecitas brillaran y nos llevaran a casa.' } },
      { text: 'Encontraron una casita hecha de dulces, pero una vieja astuta vivia alli.' },
      { text: 'Los ninos eran demasiado listos para dejarse enganar. Se cogieron de la mano y salieron de puntillas.', dialogue: { speaker: 'Gretel', line: 'Rapido — juntos somos mas valientes que solos.' } },
      { text: 'Las brillantes piedrecitas destellaron a la luz de la luna y los llevaron directamente a casa, hacia un calido abrazo.' },
    ],
    vocabulary: [
      { word: 'piedrecitas', meaning: 'pequenas y lisas piedritas', emoji: '🪨' },
      { word: 'astuto', meaning: 'bueno para pensar ideas inteligentes', emoji: '💡' },
      { word: 'de puntillas', meaning: 'caminar muy despacio sobre los dedos de los pies', emoji: '🦶' },
      { word: 'juntos', meaning: 'el uno con el otro, codo con codo', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon el plan astuto de Hansel en el orden correcto!', steps: ['Dejar caer las piedrecitas brillantes', 'Seguir el rastro que centellea', 'Encontrar el camino a casa'] },
    emotionalMoment: { feeling: 'valientes juntos', prompt: 'Los ninos eran mas valientes en equipo. Quien te hace mas valiente?' },
    rewardName: 'Piedrecita brillante',
  },

  'rapunzel': {
    title: 'Rapunzel',
    summary: 'Una nina amable con un pelo muy largo vive en una alta torre y aprende que la paciencia y un corazon lleno de esperanza pueden abrir cualquier puerta.',
    theme: 'paciencia y esperanza',
    scenes: [
      { text: 'En lo alto de una gran torre vivia Rapunzel, una nina con la trenza dorada mas larga del mundo.' },
      { text: 'Cada dia, Rapunzel cantaba a los pajaros. Su dulce cancion flotaba por todo el bosque.', dialogue: { speaker: 'Rapunzel', line: 'Algun dia vere el mundo de ahi abajo, bajo los arboles.' } },
      { text: 'Un amable viajero escucho su cancion y le grito: "Tu musica hace sonreir a todo el bosque!"', dialogue: { speaker: 'Viajero', line: 'Tu musica hace sonreir a todo el bosque!' } },
      { text: 'Se hicieron amigos. Dia tras dia, con paciencia, pensaron en una forma inteligente de bajar.' },
      { text: 'Por fin, Rapunzel puso el pie en la hierba suave y giro bajo el sol, libre y feliz.', dialogue: { speaker: 'Rapunzel', line: 'Esperar fue dificil, pero la esperanza me mantuvo fuerte.' } },
    ],
    vocabulary: [
      { word: 'torre', meaning: 'un edificio muy alto y estrecho', emoji: '🗼' },
      { word: 'trenza', meaning: 'pelo entrelazado formando una larga cuerda', emoji: '💇' },
      { word: 'paciencia', meaning: 'esperar con calma sin rendirse', emoji: '⏳' },
      { word: 'prado', meaning: 'un campo de hierba lleno de flores', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Encuentra lo que uso Rapunzel para bajar a salvo.', target: 'la escalera de trenza dorada', decoys: ['una cometa de papel', 'una cuchara de madera', 'una tacita'] },
    emotionalMoment: { feeling: 'paciente', prompt: 'Rapunzel espero con esperanza. Que cosa bonita has esperado durante mucho tiempo?' },
    rewardName: 'Trenza dorada',
  },

  'the-ugly-duckling': {
    title: 'El Patito Feo',
    summary: 'Un pajarito que se siente diferente a los demas crece y descubre que siempre fue maravilloso exactamente como era.',
    theme: 'pertenecer y quererse a uno mismo',
    scenes: [
      { text: 'En un estanque soleado, un pajarito no se parecia a sus hermanos y hermanas.' },
      { text: 'Los otros pajaros se burlaban de el, y en el fondo se sentia solo y muy triste.', dialogue: { speaker: 'Pajarito', line: 'Ojala alguien me dejara jugar tambien.' } },
      { text: 'Una rana amable se acerco saltando y se sento a su lado. "Eres bienvenido conmigo", dijo.', dialogue: { speaker: 'Rana', line: 'Eres bienvenido conmigo, amigo mio.' } },
      { text: 'Pasaron las estaciones. Una manana luminosa, el pajarito vio su cara en el agua tranquila.' },
      { text: 'Se habia convertido en un hermoso cisne! Siempre habia sido especial: simplemente el mismo.', dialogue: { speaker: 'Cisne', line: 'No necesitaba cambiar. Solo necesitaba crecer.' } },
    ],
    vocabulary: [
      { word: 'estanque', meaning: 'una pequena extension de agua tranquila', emoji: '💧' },
      { word: 'solo', meaning: 'triste porque te sientes completamente solo', emoji: '🥺' },
      { word: 'reflejo', meaning: 'la imagen que ves en el agua tranquila', emoji: '🪞' },
      { word: 'cisne', meaning: 'un gran pajaro de agua blanco y elegante', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'Un nuevo amigo se siente excluido. Que cosa amable puedes decirle?', options: ['No perteneces aqui', 'Puedes jugar con nosotros!', 'Vete'], answerIndex: 1 },
    emotionalMoment: { feeling: 'pertenezco aqui', prompt: 'El pajarito era especial tal como era. Que te hace ser un maravilloso tu?' },
    rewardName: 'Cisne suave',
  },

  'the-little-mermaid': {
    title: 'La Sirenita',
    summary: 'Una joven sirena curiosa tiene el valor de explorar un mundo nuevo y aprende que un corazon bondadoso y generoso brilla mas que cualquier cosa.',
    theme: 'valentia y buen corazon',
    scenes: [
      { text: 'En el fondo de las olas vivia una joven sirena, la mas pequena de seis hermanas.' },
      { text: 'Le encantaba nadar hasta la superficie y contemplar el luminoso mundo sobre el agua.', dialogue: { speaker: 'Sirena', line: 'El mundo de ahi arriba esta lleno de cosas que quiero aprender!' } },
      { text: 'Una noche de tormenta, con valentia, ayudo a un marinero a llegar a la orilla a salvo.' },
      { text: 'No se quedo para ser agradecida. Ayudar a alguien llenaba su corazon de calor.', dialogue: { speaker: 'Sirena', line: 'Ayude por bondad, no para recibir las gracias.' } },
      { text: 'De vuelta en casa, conto su valiente historia, y su buen corazon hizo brillar todo el mar.' },
    ],
    vocabulary: [
      { word: 'sirena', meaning: 'una chica del mar imaginaria, con cola de pez', emoji: '🧜' },
      { word: 'olas', meaning: 'el agua que sube y baja en el mar', emoji: '🌊' },
      { word: 'valiente', meaning: 'hacer algo dificil aunque de miedo', emoji: '💪' },
      { word: 'generosa', meaning: 'feliz de dar y ayudar a los demas', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantas hermanas mayores tenia la Sirenita?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'de gran corazon', prompt: 'La sirena ayudo solo por bondad. Cuando has ayudado sin que nadie te lo pidiera?' },
    rewardName: 'Perla del mar',
  },

  'the-snow-queen': {
    title: 'La Reina de las Nieves',
    summary: 'Cuando el corazon de su mejor amigo se vuelve frio, una fiel nina llamada Gerda viaja lejos entre la nieve para calentarlo con amor.',
    theme: 'amistad fiel',
    scenes: [
      { text: 'Gerda y Kai eran los mejores amigos y cultivaban rosas juntos cerca de su ventana.' },
      { text: 'Un minusculo cristal de hielo toco el corazon de Kai, y el se volvio frio y distante.', dialogue: { speaker: 'Gerda', line: 'Espera... adonde vas, Kai?' } },
      { text: 'La valiente Gerda no se rindio. Partio a traves de la nieve a buscar a su amigo.', dialogue: { speaker: 'Gerda', line: 'Te encontrare, Kai. Los amigos no se rinden.' } },
      { text: 'Encontro a Kai en un palacio de hielo, sentado, inmovil y frio como una piedra.' },
      { text: 'Gerda lo abrazo y lagrimas calidas cayeron. El hielo se derrrtio, y Kai sonrio y lo recordo todo.', dialogue: { speaker: 'Kai', line: 'Has venido hasta aqui por mi. Gracias, Gerda.' } },
    ],
    vocabulary: [
      { word: 'escarcha', meaning: 'una fina capa de hielo que se forma cuando hace mucho frio', emoji: '🌨️' },
      { word: 'fiel', meaning: 'siempre estar ahi para tus amigos', emoji: '🤲' },
      { word: 'palacio', meaning: 'una casa muy grande y magnifica', emoji: '🏰' },
      { word: 'derretirse', meaning: 'pasar del hielo al agua con el calor', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'Como derrrtio Gerda el hielo en el corazon de Kai?', options: ['Con un gran fuego', 'Con lagrimas calidas y un abrazo', 'Con un martillo'], answerIndex: 1 },
    emotionalMoment: { feeling: 'fiel', prompt: 'Gerda nunca abandono a su amigo. Como le muestras a un amigo que te importa?' },
    rewardName: 'Rosa calida',
  },

  'puss-in-boots': {
    title: 'El Gato con Botas',
    summary: 'Un gato listo con unas botas preciosas usa su ingenio y su leal corazon para ayudar a su bondadoso amigo a encontrar la felicidad.',
    theme: 'astucia y lealtad',
    scenes: [
      { text: 'Un gato listo se puso unas botas preciosas y un sombrero con pluma, listo para la aventura.' },
      { text: 'Su amigo era pobre pero bondadoso, asi que el gato penso en un plan astuto para ayudarle.', dialogue: { speaker: 'El Gato', line: 'Confía en mi, amigo. Una idea lista esta en camino!' } },
      { text: 'El gato saludo al rey con cortesia y le ofrecio regalos, haciendo sonreir a todo el mundo.' },
      { text: 'Con ingenio en lugar de trucos, el gato ayudo a su amigo a ganar un gran castillo junto al rio.', dialogue: { speaker: 'El Gato', line: 'Las buenas ideas abren mas puertas que los grandes rugidos.' } },
      { text: 'Su amigo fue feliz por fin, y el gato se acurruco junto al fuego, el gato mas fiel de todos.' },
    ],
    vocabulary: [
      { word: 'listo', meaning: 'bueno para encontrar ideas ingeniosas', emoji: '🧠' },
      { word: 'botas', meaning: 'zapatos que suben alto por las piernas', emoji: '🥾' },
      { word: 'cortes', meaning: 'amable y gentil con sus palabras', emoji: '🙏' },
      { word: 'leal', meaning: 'siempre estar ahi para tus amigos', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon el plan astuto del Gato en el orden correcto!', steps: ['Ponerse las botas preciosas', 'Saludar al rey con cortesia', 'Ayudar a su amigo a ganar el dia'] },
    emotionalMoment: { feeling: 'servicial', prompt: 'El Gato uso ideas listas para ayudar a un amigo. De que forma astuta has ayudado tu a alguien?' },
    rewardName: 'Botas preciosas',
  },

  'pinocchio': {
    title: 'Pinocho',
    summary: 'Un muneco de madera que suena con ser un nino de verdad aprende que decir la verdad es lo que hace crecer un buen corazon.',
    theme: 'honestidad',
    scenes: [
      { text: 'Habia una vez un pequeno muneco de madera llamado Pinocho, que sonaba con convertirse en un nino de verdad.' },
      { text: 'Cada vez que Pinocho decia una mentira, su nariz crecía como una rama.', dialogue: { speaker: 'Pinocho', line: 'No fui yo! Te lo prometo!' } },
      { text: 'Su amigo el grillo intentaba ensenarle a decir siempre la verdad.', dialogue: { speaker: 'Grillo', line: 'Decir la verdad te hara sentir ligero como una pluma.' } },
      { text: 'Pinocho cometio un gran error y se perdio. Aprendio entonces que la honestidad era su unica guia.' },
      { text: 'Cuando Pinocho dijo por fin la verdad, su corazon crecio, y su mayor deseo se hizo realidad.', dialogue: { speaker: 'Pinocho', line: 'La verdad es la magia mas poderosa de todas.' } },
    ],
    vocabulary: [
      { word: 'muneco', meaning: 'una muneca que se hace mover', emoji: '🎭' },
      { word: 'verdad', meaning: 'decir exactamente lo que ha pasado', emoji: '✅' },
      { word: 'mentira', meaning: 'decir algo que no es cierto', emoji: '❌' },
      { word: 'honesto', meaning: 'alguien que siempre dice la verdad', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'Cuando se alarga la nariz de Pinocho?', options: ['Cuando dice la verdad', 'Cuando dice una mentira', 'Cuando canta una cancion'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honesto', prompt: 'Decir la verdad hizo sentir a Pinocho ligero. Como te sientes tu cuando dices la verdad?' },
    rewardName: 'Grillo de la verdad',
  },

  'peter-pan': {
    title: 'Peter Pan',
    summary: 'Un nino que nunca crece lleva a nuevos amigos a una aventura voladora donde los pensamientos felices y un poco de valentia te llevan a cualquier parte.',
    theme: 'imaginacion y valentia',
    scenes: [
      { text: 'En una habitacion llena de estrellas, un nino llamado Peter Pan enseno a los ninos a volar.' },
      { text: 'Peter le dijo a Wendy el secreto: habia que pensar en algo muy feliz.', dialogue: { speaker: 'Peter Pan', line: 'Piensa en tu cosa mas feliz — y hop, te elevas!' } },
      { text: 'Juntos volaron hacia el Pais de Nunca Jamas, una isla magica llena de aventuras.' },
      { text: 'Incluso frente al malvado capitan, Peter no tuvo miedo. Afronto el peligro con una gran sonrisa.', dialogue: { speaker: 'Peter Pan', line: 'Ser valiente es intentarlo de todas formas.' } },
      { text: 'Los ninos volvieron a casa con recuerdos en el corazon y un poco de magia para siempre.' },
    ],
    vocabulary: [
      { word: 'habitacion', meaning: 'la habitacion donde duermes y suenas', emoji: '🛏️' },
      { word: 'sombra', meaning: 'la forma oscura que hace tu cuerpo en el suelo', emoji: '👤' },
      { word: 'imaginar', meaning: 'crear cosas bonitas dentro de tu cabeza', emoji: '💭' },
      { word: 'valentia', meaning: 'intentarlo aunque tengas miedo', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Que ayudo a los ninos a volar?', options: ['Pensamientos felices y polvo de hada', 'Botas pesadas', 'Gritar muy fuerte'], answerIndex: 0 },
    emotionalMoment: { feeling: 'valiente', prompt: 'Peter dice que ser valiente es intentarlo de todas formas. Que cosa valiente te gustaria intentar?' },
    rewardName: 'Polvo de hada',
  },

  'alice-in-wonderland': {
    title: 'Alicia en el Pais de las Maravillas',
    summary: 'Una nina curiosa sigue a un conejo apresurado a un mundo al reves y aprende que hacer preguntas es una especie de magia.',
    theme: 'curiosidad',
    scenes: [
      { text: 'Alicia vio un conejo blanco apresurado que saltaba a una madriguera y, muy curiosa, lo siguio.' },
      { text: 'Cayo por un largo pasillo magico y encontro una pequenísima puerta que daba a un jardin.', dialogue: { speaker: 'Alicia', line: 'Que raro! Me pregunto que pasa aqui.' } },
      { text: 'Alicia bebio un pequeno frasco y se encogio, luego comio un pastel y crecio muy rapido.', dialogue: { speaker: 'Alicia', line: 'Las preguntas son la llave de todas las maravillas!' } },
      { text: 'Conocio a un gato sonriente, una reina enfadada y un sombrerero muy loco.' },
      { text: 'Alicia se desperto y sonrio. Hacer preguntas la habia llevado al mas bonito de los suenos.', dialogue: { speaker: 'Alicia', line: 'La curiosidad es la aventura mas grande.' } },
    ],
    vocabulary: [
      { word: 'curiosa', meaning: 'alguien que ama descubrir cosas nuevas', emoji: '🔍' },
      { word: 'madriguera', meaning: 'un tunel excavado en la tierra por un animal', emoji: '🕳️' },
      { word: 'encogerse', meaning: 'hacerse mas pequeno', emoji: '🔻' },
      { word: 'maravilla', meaning: 'algo increible y muy sorprendente', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon la aventura de Alicia en el orden correcto!', steps: ['Beber el frasco y encogerse', 'Comer el pastel y crecer', 'Encontrar la pequena puerta del jardin'] },
    emotionalMoment: { feeling: 'curiosa', prompt: 'A Alicia le encantaba hacer preguntas. De que tienes curiosidad hoy?' },
    rewardName: 'Reloj curioso',
  },

  'the-wizard-of-oz': {
    title: 'El Mago de Oz',
    summary: 'Una nina y tres nuevos amigos siguen un camino dorado y descubren que los dones que buscaban estaban dentro de ellos desde el principio.',
    theme: 'ya tienes lo que necesitas',
    scenes: [
      { text: 'Un gran torbellino llevo a Dorothy y a su pequeno perro Toto al magico pais de Oz.' },
      { text: 'En el camino dorado, Dorothy conocio a un espantapajaros, un hombre de hojalata y un leon.', dialogue: { speaker: 'Espantapajaros', line: 'Solo quiero un cerebro listo!' } },
      { text: 'Juntos caminaron hacia la Ciudad Esmeralda para encontrar al gran Mago.', dialogue: { speaker: 'Dorothy', line: 'Si estamos juntos, podemos hacer cualquier cosa.' } },
      { text: 'El Mago les revelo un gran secreto: ya tenian todo lo que deseaban.' },
      { text: 'Dorothy golpeo tres veces sus zapatillas y volvio a casa. Cada uno habia encontrado su don.', dialogue: { speaker: 'Dorothy', line: 'No hay ningun lugar como el hogar.' } },
    ],
    vocabulary: [
      { word: 'torbellino', meaning: 'un viento muy fuerte que gira en redondo', emoji: '🌪️' },
      { word: 'espantapajaros', meaning: 'un muneco grande de paja para espantar a los pajaros', emoji: '🌾' },
      { word: 'valentia', meaning: 'seguir adelante aunque tengas miedo', emoji: '💪' },
      { word: 'viaje', meaning: 'un largo camino o aventura hacia un lugar nuevo', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Cual de los amigos ya tenia valentia desde el principio?', options: ['El espantapajaros', 'El hombre de hojalata', 'El leon'], answerIndex: 2 },
    emotionalMoment: { feeling: 'capaz', prompt: 'Los amigos ya tenian sus dones dentro de ellos. Que don tienes ya en ti?' },
    rewardName: 'Zapatillas brillantes',
  },

  'robin-hood': {
    title: 'Robin Hood',
    summary: 'Un amable arquero del bosque verde comparte con quienes tienen muy poco y ensena a sus amigos que la justicia hace a todos mas felices.',
    theme: 'justicia y generosidad',
    scenes: [
      { text: 'En un gran bosque verde vivia Robin Hood, el mejor arquero del pais.' },
      { text: 'Vio que mucha gente era muy pobre mientras que otros lo tenian todo.', dialogue: { speaker: 'Robin', line: 'Compartir es el mejor de los regalos.' } },
      { text: 'Con sus alegres amigos, Robin diseno un plan para ayudar a quienes estaban en necesidad.', dialogue: { speaker: 'Pequeno Juan', line: 'Juntos somos la fuerza del bosque!' } },
      { text: 'Robin repartio lo que la gente necesitaba, y las sonrisas florecieron por todas partes.' },
      { text: 'El bosque vibro de felicidad. Robin habia aprendido que la generosidad es la verdadera victoria.', dialogue: { speaker: 'Robin', line: 'La generosidad hace a todos mas ricos.' } },
    ],
    vocabulary: [
      { word: 'arquero', meaning: 'alguien que dispara flechas con un arco', emoji: '🎯' },
      { word: 'bosque', meaning: 'un gran lugar lleno de arboles y animales', emoji: '🌳' },
      { word: 'justo', meaning: 'tratar a todo el mundo de la misma manera', emoji: '⚖️' },
      { word: 'generoso', meaning: 'que le gusta dar y compartir', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin Hood compartia con personas que estaban...', options: ['hambrientas y necesitadas', 'ya muy ricas', 'siendo crueles con otros'], answerIndex: 0 },
    emotionalMoment: { feeling: 'justo', prompt: 'A Robin le encantaba compartir. Que podrias compartir para hacer sonreir a un amigo?' },
    rewardName: 'Arco amistoso',
  },

  'goldilocks': {
    title: 'Ricitos de Oro',
    summary: 'Una nina curiosa entra en la acogedora cabana de los osos y aprende que es mejor pedir permiso primero y cuidar las cosas de los demas.',
    theme: 'respeto a los demas',
    scenes: [
      { text: 'Una ninita con rizos dorados paseaba por el bosque cuando encontro una bonita cabana.' },
      { text: 'Entro y probo tres cuencos de gachas. El del osito era perfecto.', dialogue: { speaker: 'Ricitos de Oro', line: 'Oh! Este cuenco es perfecto, ni demasiado caliente ni demasiado frio!' } },
      { text: 'Probo tres sillas y luego tres camas. Se quedo dormida en la mas acogedora.' },
      { text: 'Los tres osos volvieron y encontraron su casa desordenada.', dialogue: { speaker: 'Osito', line: 'Alguien ha comido de mi cuenco!' } },
      { text: 'Ricitos de Oro se desperto, pidio perdon y aprendio que pedir primero es la educacion mas dulce.', dialogue: { speaker: 'Ricitos de Oro', line: 'Perdon. Siempre pedire permiso antes de entrar.' } },
    ],
    vocabulary: [
      { word: 'gachas', meaning: 'una comida caliente y suave, como los cereales del desayuno', emoji: '🥣' },
      { word: 'cabana', meaning: 'una casita acogedora en el bosque', emoji: '🏡' },
      { word: 'respeto', meaning: 'cuidar las cosas y los sentimientos de los demas', emoji: '🙏' },
      { word: 'perdon', meaning: 'lo que dices cuando sientes haber hecho algo mal', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos osos vivian en la acogedora cabana?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respetuosa', prompt: 'Ricitos de Oro aprendio a pedir primero. Cuando es amable pedir permiso antes de coger algo prestado?' },
    rewardName: 'Cuenco perfecto',
  },

  'three-little-pigs': {
    title: 'Los Tres Cerditos',
    summary: 'Tres cerditos construyen tres casas diferentes y aprenden que un trabajo cuidadoso y aplicado mantiene a todos a salvo y calentitos.',
    theme: 'trabajo y organizacion',
    scenes: [
      { text: 'Tres cerditos se fueron al mundo a construir sus casas.' },
      { text: 'El primero construyo rapidamente una casa de paja. El segundo, una casa de madera.', dialogue: { speaker: 'Primer cerdito', line: 'Rapido y listo! Quiero ir a jugar!' } },
      { text: 'El tercer cerdito trabajo duro y construyo ladrillo a ladrillo una casa solida de ladrillos.', dialogue: { speaker: 'Tercer cerdito', line: 'Me tomo mi tiempo para que mi casa sea solida.' } },
      { text: 'El gran lobo malo soplo sobre las casas de paja y madera, y se derrumbaron.' },
      { text: 'Pero la casa de ladrillos siguio firme. Los tres cerditos estaban a salvo, y todos aprendieron que trabajar con cuidado protege.', dialogue: { speaker: 'Tercer cerdito', line: 'Un buen trabajo lleva tiempo, pero merece la pena!' } },
    ],
    vocabulary: [
      { word: 'paja', meaning: 'tallos secos de plantas, faciles de romper', emoji: '🌾' },
      { word: 'ladrillos', meaning: 'bloques de tierra cocida muy solidos', emoji: '🧱' },
      { word: 'resistente', meaning: 'muy solido, no facil de romper', emoji: '💪' },
      { word: 'planificar', meaning: 'pensar antes de empezar algo', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos cerditos construyeron casas?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'orgulloso de mi trabajo', prompt: 'El tercer cerdito trabajo duro y se mantuvo a salvo. En que has trabajado duro tu?' },
    rewardName: 'Ladrillo solido',
  },

  'aladdin': {
    title: 'Aladino',
    summary: 'Un nino ordinario pero bondadoso encuentra una lampara magica y aprende que lo que deseas importa menos que el bien que haces por los demas.',
    theme: 'honestidad y corazon humilde',
    scenes: [
      { text: 'En un animado mercado vivia Aladino, un nino pobre con un corazon de oro.' },
      { text: 'Encontro una vieja lampara y, al frotarla, aparecio un gran genio!', dialogue: { speaker: 'Genio', line: 'Te concedo tres deseos. Elige con cuidado!' } },
      { text: 'Aladino deseo primero ayudar a su familia, luego a la gente pobre de su barrio.', dialogue: { speaker: 'Aladino', line: 'Quiero que nadie en este mercado pase hambre.' } },
      { text: 'Su humildad y generosidad le ganaron amigos de verdad y mucha felicidad.' },
      { text: 'Aladino aprendio que los mejores deseos son los que uno pide para los demas.', dialogue: { speaker: 'Aladino', line: 'Un corazon generoso es el mas grande de los tesoros.' } },
    ],
    vocabulary: [
      { word: 'mercado', meaning: 'un lugar animado donde la gente vende y compra', emoji: '🏪' },
      { word: 'lampara', meaning: 'un objeto que da luz o guarda un genio', emoji: '🪔' },
      { word: 'humilde', meaning: 'alguien que no presume de si mismo', emoji: '🙏' },
      { word: 'deseo', meaning: 'algo que quieres muchísimo', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'Cuantos deseos le dio el genio a Aladino?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'generoso', prompt: 'Aladino deseo ayudar a los demas. Si tuvieras un deseo bondadoso, cual seria?' },
    rewardName: 'Lampara de los deseos',
  },

  'ali-baba': {
    title: 'Ali Baba',
    summary: 'Un dulce lenador descubre una cueva secreta y aprende que ser honesto y prudente vale mucho mas que ser codicioso.',
    theme: 'la honestidad antes que la codicia',
    scenes: [
      { text: 'Ali Baba era un dulce lenador que vivia de manera sencilla y contenta.' },
      { text: 'Un dia en el bosque, oyo a unos ladrones decir las palabras magicas frente a una gran roca.', dialogue: { speaker: 'Ladrones', line: 'Abrete, Sesamo!' } },
      { text: 'Ali Baba entro en la cueva y vio tesoros deslumbrantes de todos los colores.', dialogue: { speaker: 'Ali Baba', line: 'Tomare solo lo que necesitamos, nada mas.' } },
      { text: 'Su codicioso hermano tomo demasiado y fue sorprendido por los ladrones. Ali Baba entendio la leccion.' },
      { text: 'Ali Baba compartio su buena fortuna con los demas y vivio de manera sencilla y feliz.', dialogue: { speaker: 'Ali Baba', line: 'Tener suficiente y ser honesto es la verdadera riqueza.' } },
    ],
    vocabulary: [
      { word: 'cueva', meaning: 'una gran cavidad natural en la roca', emoji: '🕳️' },
      { word: 'tesoro', meaning: 'una gran cantidad de oro y cosas valiosas', emoji: '💎' },
      { word: 'codicioso', meaning: 'alguien que siempre quiere mas de lo que necesita', emoji: '😤' },
      { word: 'suficiente', meaning: 'justo lo que uno necesita, ni mas ni menos', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Cuales son las palabras magicas que abren la cueva?', options: ['Abrete, Sesamo!', 'Cierra la puerta!', 'Buenos dias!'], answerIndex: 0 },
    emotionalMoment: { feeling: 'contento', prompt: 'Ali Baba solo tomo lo que necesitaba. Que cosa que ya tienes es justo suficiente para ti?' },
    rewardName: 'Cueva secreta',
  },

  'aesops-fables': {
    title: 'La Liebre y la Tortuga',
    summary: 'Una liebre rapida y una tortuga lenta hacen una carrera amistosa, y la tortuga le ensenaa todos que nunca rendirse gana el dia.',
    theme: 'perseverancia — despacio pero sin parar',
    scenes: [
      { text: 'En un prado soleado, una liebre rapida siempre presumia de su velocidad.' },
      { text: 'La tortuga lenta y tranquila le propuso un reto. La liebre acepto riendose.', dialogue: { speaker: 'Liebre', line: 'Una carrera contra ti? Facilísimo! Descansare por el camino.' } },
      { text: 'La tortuga avanzo paso a paso, de manera constante, sin detenerse nunca.', dialogue: { speaker: 'Tortuga', line: 'Despacio pero sin parar, seguire avanzando.' } },
      { text: 'La liebre se durmio bajo un arbol, segura de que la tortuga jamas podria alcanzarla.' },
      { text: 'Cuando la liebre se desperto, la tortuga ya habia cruzado la linea de meta. Perseverar siempre gana.', dialogue: { speaker: 'Tortuga', line: 'Paso a paso, se llega mas lejos de lo que uno cree.' } },
    ],
    vocabulary: [
      { word: 'liebre', meaning: 'un conejo salvaje grande que es muy rapido', emoji: '🐇' },
      { word: 'tortuga', meaning: 'un animal con caparazon que camina despacio pero sin parar', emoji: '🐢' },
      { word: 'constante', meaning: 'avanzar al mismo ritmo sin detenerse', emoji: '⏱️' },
      { word: 'perseverar', meaning: 'seguir intentandolo aunque sea dificil', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Quien gano la carrera sin rendirse nunca?', options: ['la liebre rapida', 'la tortuga lenta y constante', 'el zorro dormido'], answerIndex: 1 },
    emotionalMoment: { feeling: 'determinado', prompt: 'La tortuga siguio paso a paso. En que sigues tu intentandolo?' },
    rewardName: 'Tortuga perseverante',
  },

  'sleeping-beauty': {
    title: 'La Bella Durmiente',
    summary: 'Una bella princesa cae en un sueno magico y espera el amor verdadero.',
    theme: 'paciencia y esperanza',
    scenes: [
      { text: 'Un rey y una reina felices tuvieron por fin una hijita. Invitaron a todas las hadas del reino a su bautizo.' },
      { text: 'Las buenas hadas ofrecieron sus dones a la princesa: belleza, gracia y dulzura. Pero un hada malvada llego furiosa sin haber sido invitada.', dialogue: { speaker: 'Hada malvada', line: 'Cuando cumpla dieciseis anos, se pinchara el dedo con un huso y caera muerta!' } },
      { text: 'El ultimo hada buena aun no habia hablado. Suavizo el hechizo: la princesa no moriria, sino que dormira cien anos.', dialogue: { speaker: 'Hada buena', line: 'Dormira, pero el amor la despertara.' } },
      { text: 'A los dieciseis anos, la princesa encontro a una anciana que hilaba. Toco el huso y cayo en un profundo sueno. Todo el castillo se durmio con ella.' },
      { text: 'Un principe oyo hablar del castillo dormido escondido tras un bosque de rosas. Corto las zarzas y entro en el silencioso castillo.', dialogue: { speaker: 'Principe', line: 'Que bella es! La voy a despertar.' } },
      { text: 'El principe se acerco a la bella princesa y le dio un suave beso. Ella abrio los ojos y sonrio. Todo el castillo desperto al mismo tiempo y vivieron felices para siempre.', dialogue: { speaker: 'Princesa', line: 'He esperado tanto tiempo. Por fin has llegado!' } },
    ],
    vocabulary: [
      { word: 'huso', meaning: 'una herramienta para hilar lana, con una punta afilada', emoji: '🧵' },
      { word: 'maleficio', meaning: 'alguien que usa magia mala para hacer dano', emoji: '🧙' },
      { word: 'encantado', meaning: 'transformado por un hechizo especial', emoji: '✨' },
      { word: 'rosal', meaning: 'un arbusto espinoso que hace crecer bonitas rosas', emoji: '🌹' },
    ],
    miniGame: { type: 'choice', prompt: 'Que hada malvada lanza el hechizo sobre la princesa?', options: ['Un hada que no fue invitada', 'El hada del palacio', 'El hada del bosque'], answerIndex: 0 },
    emotionalMoment: { feeling: 'esperanza', prompt: 'Has esperado alguna vez algo con impaciencia? Como te sentiste?' },
    rewardName: 'Rosa Encantada',
  },

  'beauty-and-the-beast': {
    title: 'La Bella y la Bestia',
    summary: 'Bella aprende que la verdadera belleza esta en el corazon, no en el aspecto.',
    theme: 'bondad y amor verdadero',
    scenes: [
      { text: 'Un mercader se perdio en el bosque durante una tormenta. Encontro un gran castillo misterioso y se refugio alli para pasar la noche.' },
      { text: 'Al marcharse, corto una rosa para su hija Bella. Una terrible Bestia aparecio de repente.', dialogue: { speaker: 'Bestia', line: 'Has robado mi rosa! Eres mi prisionero!' } },
      { text: 'El mercader suplico a la Bestia que le dejara despedirse de sus hijos. La Bestia acepto, con la condicion de que una de sus hijas volviera en su lugar.', dialogue: { speaker: 'Bella', line: 'Papa, yo ire. No tengo miedo.' } },
      { text: 'Bella vivio en el castillo. La Bestia era fea pero dulce y bondadosa. Cada noche hablaban y reian juntos.' },
      { text: 'Bella pidio volver a casa para ver a su padre enfermo. La Bestia acepto tristemente.', dialogue: { speaker: 'Bestia', line: 'Te echare de menos, Bella. Pero tu felicidad esta antes que la mia.' } },
      { text: 'Lejos del castillo, Bella se dio cuenta de que amaba a la Bestia. Corrio a reunirse con ella. Al confesar su amor, la Bestia se transformo en un apuesto principe.', dialogue: { speaker: 'Bella', line: 'Te quiero, no por tu cara, sino por tu corazon.' } },
      { text: 'El principe explico que una bruja lo habia hechizado. Solo el amor sincero podia liberarlo. Bella y el principe vivieron felices para siempre.' },
    ],
    vocabulary: [
      { word: 'bestia', meaning: 'un gran animal aterrador, aqui un monstruo hechizado', emoji: '🐾' },
      { word: 'prisionero', meaning: 'alguien que no puede marcharse libremente', emoji: '🔒' },
      { word: 'apariencia', meaning: 'lo que ves de alguien por fuera', emoji: '👁️' },
      { word: 'transformacion', meaning: 'cambiar completamente de forma o aspecto', emoji: '✨' },
    ],
    miniGame: { type: 'choice', prompt: 'Por que va el padre de Bella al castillo?', options: ['Busca un tesoro', 'Se refugia de la tormenta y corta una rosa', 'Visita a la Bestia'], answerIndex: 1 },
    emotionalMoment: { feeling: 'bondad', prompt: 'Has juzgado alguna vez a alguien por su apariencia antes de conocerlo?' },
    rewardName: 'Rosa Magica',
  },

  'little-thumb': {
    title: 'Pulgarcito',
    summary: 'El mas pequeno de siete hermanos usa su inteligencia para salvar a toda su familia.',
    theme: 'valor e inteligencia',
    scenes: [
      { text: 'Un pobre lenador y su mujer tenian siete hijos. El mas pequeno se llamaba Pulgarcito. Era minusculo pero muy inteligente.' },
      { text: 'Una tarde los padres, demasiado pobres para alimentar a los ninos, los abandonaron en el bosque.', dialogue: { speaker: 'Pulgarcito', line: 'Sabia que iban a hacer esto. Estoy preparado.' } },
      { text: 'Pulgarcito se habia preparado: habia llenado sus bolsillos de pequenas piedrecitas blancas. Las fue sembrando a lo largo del camino, y los ninos encontraron el camino a casa siguiendolas.' },
      { text: 'La segunda vez que los abandonaron, Pulgarcito solo tenia pan para sembrar migas. Los pajaros se las comieron y los hermanos se perdieron de verdad.' },
      { text: 'Perdidos, llegaron a la casa de un ogro. La mujer del ogro los escondio, pero el ogro los encontro.', dialogue: { speaker: 'Ogro', line: 'Huelo carne fresca! Donde estan escondidos?' } },
      { text: 'Pulgarcito tuvo una idea brillante: intercambio los gorros de sus hermanos con las coronas de las hijas del ogro. El ogro se equivoco en la oscuridad.' },
      { text: 'Pulgarcito robo las botas de siete leguas del ogro dormido. En unos pocos pasos trajo oro y salvo a toda su familia.', dialogue: { speaker: 'Pulgarcito', line: 'La inteligencia vale mas que la fuerza!' } },
    ],
    vocabulary: [
      { word: 'piedrecitas', meaning: 'pequenas piedras lisas que puedes sembrar a lo largo de un camino', emoji: '🪨' },
      { word: 'ogro', meaning: 'un monstruo gigante en los cuentos que come ninos', emoji: '👹' },
      { word: 'legua', meaning: 'una gran distancia, como varios kilometros', emoji: '🗺️' },
      { word: 'astucia', meaning: 'una idea lista para enganar a alguien', emoji: '💡' },
    ],
    miniGame: { type: 'sequence', prompt: 'Pon los pasos en el orden correcto!', steps: ['Sembrar piedrecitas blancas para encontrar el camino', 'Llegar a la casa del ogro en el bosque', 'Robar las botas de siete leguas'] },
    emotionalMoment: { feeling: 'valor', prompt: 'Has tenido miedo alguna vez pero seguiste adelante de todas formas? Que te ayudo?' },
    rewardName: 'Botas de Siete Leguas',
  },

  'jack-beanstalk': {
    title: 'Juan y las Habichuelas Magicas',
    summary: 'Juan cambia su vaca por habichuelas magicas y descubre un castillo entre las nubes.',
    theme: 'aventura y curiosidad',
    scenes: [
      { text: 'Juan y su madre eran muy pobres. Un dia su madre envio a Juan a vender su vieja vaca al mercado.' },
      { text: 'Por el camino, un viejo le ofrecio a Juan habichuelas magicas a cambio de la vaca. Juan acepto.', dialogue: { speaker: 'Juan', line: 'Habichuelas magicas! Es un buen trato!' } },
      { text: 'La madre de Juan se enfado mucho y tiro las habichuelas por la ventana. Pero durante la noche crecio un enorme tallo de habichuela hasta las nubes.' },
      { text: 'Juan trepo por el tallo y descubrio un inmenso castillo entre las nubes. Alli vivia un terrible gigante.', dialogue: { speaker: 'Gigante', line: 'Fe, fi, fo, fum! Huelo sangre de cristiano!' } },
      { text: 'La mujer del gigante ayudo a Juan a esconderse. Mientras el gigante dormia, Juan robo la gallina de los huevos de oro y el arpa encantada.' },
      { text: 'Juan bajo por el tallo corriendo. El gigante lo persiguio. Juan agarro su hacha y corto el tallo. El gigante cayo muy, muy lejos.', dialogue: { speaker: 'Juan', line: 'Mama! Seremos ricos! Nunca mas pasaremos hambre!' } },
    ],
    vocabulary: [
      { word: 'habichuela', meaning: 'una pequena semilla que puede crecer muy alta', emoji: '🫘' },
      { word: 'gigante', meaning: 'un ser imaginario de tamano enorme y muy fuerte', emoji: '🦣' },
      { word: 'nubes', meaning: 'las grandes formas blancas o grises en el cielo', emoji: '☁️' },
      { word: 'tesoro', meaning: 'objetos preciosos como el oro o las joyas', emoji: '🪙' },
    ],
    miniGame: { type: 'choice', prompt: 'Por que cambia Juan su vaca?', options: ['Monedas de oro', 'Habichuelas magicas', 'Un arpa'], answerIndex: 1 },
    emotionalMoment: { feeling: 'curiosidad', prompt: 'Has descubierto alguna vez algo sorprendente? Como te sentiste?' },
    rewardName: 'Tesoro del Gigante',
  },

  'thumbelina': {
    title: 'Pulgarcita',
    summary: 'Pulgarcita, una nina muy pequena, busca su lugar en un mundo demasiado grande para ella.',
    theme: 'identidad y pertenencia',
    scenes: [
      { text: 'Una mujer que deseaba tener un hijo planto una semilla magica. Crecio una flor y dentro de ella dormia una nina muy pequena. Se llamaba Pulgarcita.' },
      { text: 'Una noche, un sapo horrible rapto a Pulgarcita para casarla con su hijo. Pulgarcita lloraba sobre su nenufar.', dialogue: { speaker: 'Pulgarcita', line: 'No quiero quedarme aqui. Quiero encontrar mi verdadero hogar.' } },
      { text: 'Unos peces amables royeron el tallo del nenufar y Pulgarcita escapo. Viajo por prados y bosques, siempre demasiado pequena para los demas.' },
      { text: 'En invierno, Pulgarcita encontro refugio en casa de un raton campesino. Pero el raton queria casarla con un viejo topo ciego.' },
      { text: 'Pulgarcita encontro una golondrina herida y la cuido con ternura durante todo el invierno.', dialogue: { speaker: 'Golondrina', line: 'Me has salvado. Cuando llegue la primavera, te llevare lejos de aqui.' } },
      { text: 'En primavera, la golondrina llevo a Pulgarcita a una tierra calida y florida. Alli conocio a un pequeno principe de las flores. Por fin habia encontrado su lugar.', dialogue: { speaker: 'Principe de las flores', line: 'Eres bienvenida aqui. Quieres ser nuestra reina?' } },
    ],
    vocabulary: [
      { word: 'minuscula', meaning: 'extremadamente pequena, mucho mas pequena que todos los demas', emoji: '🔬' },
      { word: 'raptar', meaning: 'llevarse a alguien a la fuerza sin su permiso', emoji: '😨' },
      { word: 'golondrina', meaning: 'un pajaro pequeno y rapido que viaja a paises calidos', emoji: '🐦' },
      { word: 'hada', meaning: 'un ser magico con alas que ayuda a los demas', emoji: '🧚' },
    ],
    miniGame: { type: 'find', prompt: 'Encuentra la flor donde duerme Pulgarcita!', target: 'la gran flor rosa', decoys: ['un nenufar verde', 'una hoja seca', 'una seta'] },
    emotionalMoment: { feeling: 'pertenencia', prompt: 'Has tenido alguna vez la sensacion de no estar en tu lugar? Como encontraste tu lugar?' },
    rewardName: 'Alas de Hada',
  },

  'twelve-dancing-princesses': {
    title: 'Las Doce Princesas Bailarinas',
    summary: 'Cada noche doce princesas desgastan en secreto sus zapatos bailando. Un soldado descubre su misterio.',
    theme: 'misterio y perseverancia',
    scenes: [
      { text: 'Un rey tenia doce hijas. Cada manana sus zapatos aparecian desgastados como si hubieran bailado toda la noche. Pero nadie sabia por que.' },
      { text: 'El rey anuncio que quien descubriera el secreto podria casarse con una de sus hijas. Varios principes lo intentaron, pero todos se quedaban dormidos misteriosamente.', dialogue: { speaker: 'Rey', line: 'Quien resolvera este misterio? Sus zapatos estan desgastados otra vez!' } },
      { text: 'Un viejo soldado que volvia de la guerra encontro a una anciana sabia que le dio una capa invisible.', dialogue: { speaker: 'Anciana', line: 'No bebas la bebida que te ofrezcan. Y ten cuidado!' } },
      { text: 'El soldado fingio dormir. A medianoche las princesas se levantaron. El las siguio invisible por un pasadizo secreto bajo tierra.' },
      { text: 'Bajo tierra descubrio un lago con barcas, un bosque de arboles de plata y oro, y un castillo iluminado donde doce principes esperaban a las princesas para bailar.' },
      { text: 'El soldado corto en secreto una rama de plata para probar su descubrimiento. La princesa mayor oyo un ruido.', dialogue: { speaker: 'Princesa mayor', line: 'Esta noche algo no va bien. Tengo miedo.' } },
      { text: 'A la manana siguiente, el soldado presento la rama al rey y le conto todo. El rey reconocio la verdad. El soldado eligio casarse con la princesa mayor y el secreto quedo revelado para siempre.', dialogue: { speaker: 'Soldado', line: 'La verdad vale mas que todos los secretos.' } },
    ],
    vocabulary: [
      { word: 'misterio', meaning: 'algo oculto que todavia no comprendes', emoji: '🔍' },
      { word: 'invisible', meaning: 'que no se puede ver aunque este alli', emoji: '👻' },
      { word: 'zapato', meaning: 'un zapato elegante, a menudo para bailar', emoji: '👠' },
      { word: 'subterraneo', meaning: 'lo que se encuentra bajo tierra, escondido debajo', emoji: '🕳️' },
    ],
    miniGame: { type: 'match', prompt: 'Empareja a cada princesa con su principe bailarin!', pairs: [{ left: 'Princesa Rosa', right: 'Principe Dorian' }, { left: 'Princesa Luna', right: 'Principe Silvain' }, { left: 'Princesa Estrella', right: 'Principe Aurele' }, { left: 'Princesa Violeta', right: 'Principe Florian' }] },
    emotionalMoment: { feeling: 'misterio', prompt: 'Tienes algun secreto? Como se siente guardar un secreto?' },
    rewardName: 'Corona del Misterio',
  },

  'rumpelstiltskin': {
    title: 'Rumpelstiltskin',
    summary: 'Un misterioso hombrecillo ayuda a una chica a hilar paja en oro — pero a que precio?',
    theme: 'promesas y honestidad',
    scenes: [
      { text: 'Un molinero quiso impresionar al rey y dijo una gran mentira: "Mi hija puede hilar paja en oro!" El rey encerro a la chica en una torre llena de paja.' },
      { text: 'La chica lloraba cuando aparecio un extrano hombrecillo.', dialogue: { speaker: 'Rumpelstiltskin', line: 'Que me daras si hilo toda esta paja en oro por ti?' } },
      { text: 'Ella le dio su collar. El hombrecillo hilo toda la paja en oro. El rey, maravillado, la metio en una sala aun mas grande.' },
      { text: 'La tercera noche la chica no tenia nada mas que dar. Prometio a su primer hijo. El rey se caso con ella y se convirtio en reina.' },
      { text: 'Un ano despues el hombrecillo volvio a reclamar al nino. La reina le suplico. El le dio tres dias para adivinar su nombre.', dialogue: { speaker: 'Rumpelstiltskin', line: 'Si adivinas mi nombre, podras quedarte con el nino!' } },
      { text: 'Un mensajero oyo al hombrecillo bailando y cantando su nombre en el bosque. Corrio de vuelta a decirlo a la reina.', dialogue: { speaker: 'Mensajero', line: 'Se llama Rumpelstiltskin! Lo oí cantarlo!' } },
    ],
    vocabulary: [
      { word: 'paja', meaning: 'tallos secos de cereales, amarillos y ligeros', emoji: '🌾' },
      { word: 'hilar', meaning: 'convertir fibras en hilo con una rueca', emoji: '🧶' },
      { word: 'promesa', meaning: 'lo que dices que vas a hacer y debes cumplir', emoji: '🤝' },
      { word: 'adivinanza', meaning: 'una pregunta con una respuesta oculta que hay que encontrar', emoji: '❓' },
    ],
    miniGame: { type: 'choice', prompt: 'Como adivina la reina el nombre del duende?', options: ['Un mensajero lo oyo cantar en el bosque', 'Lo leyo en un libro', 'El duende se lo dijo el mismo'], answerIndex: 0 },
    emotionalMoment: { feeling: 'honestidad', prompt: 'Es importante cumplir las promesas? Por que?' },
    rewardName: 'Hilo de Oro',
  },

  'emperor-new-clothes': {
    title: 'El Traje Nuevo del Emperador',
    summary: 'Dos estafadores convencen a un emperador vanidoso de que le estan tejiendo un traje invisible para los tontos.',
    theme: 'honestidad y valentia',
    scenes: [
      { text: 'Habia una vez un emperador que amaba la ropa fina por encima de todo. Se cambiaba de traje varias veces al dia.' },
      { text: 'Dos estafadores se presentaron como los mejores tejedores del mundo. Dijeron que tejian una tela magica: invisible para los tontos e incompetentes.', dialogue: { speaker: 'Estafador', line: 'Solo las personas verdaderamente inteligentes pueden ver esta ropa!' } },
      { text: 'Los ministros fueron enviados a ver los avances. No veian nada, pero no se atrevieron a decirlo por miedo a parecer tontos.', dialogue: { speaker: 'Ministro', line: 'Es magnifico... absolutamente magnifico.' } },
      { text: 'Los estafadores entregaron al emperador su ropa nueva imaginaria. El emperador tampoco veia nada, pero fingio.' },
      { text: 'El emperador desfilo por las calles. Todo el mundo aplaudio, temeroso de parecer tonto.' },
      { text: 'De repente, un nino pequeno grito la verdad.', dialogue: { speaker: 'Nino', line: 'Pero si no lleva nada puesto! El emperador esta completamente desnudo!' } },
    ],
    vocabulary: [
      { word: 'vanidoso', meaning: 'alguien que piensa demasiado en su aspecto y se cree guapo', emoji: '🪞' },
      { word: 'estafador', meaning: 'alguien que miente para robar o enganar a otros', emoji: '🎭' },
      { word: 'invisible', meaning: 'imposible de ver con los ojos', emoji: '👻' },
      { word: 'verdad', meaning: 'lo que es realmente cierto, aunque incomode', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Quien dice la verdad primero?', options: ['Un nino pequeno', 'Un ministro', 'El propio emperador'], answerIndex: 0 },
    emotionalMoment: { feeling: 'valentia', prompt: 'Has tenido alguna vez el valor de decir una verdad dificil?' },
    rewardName: 'Valor de la Verdad',
  },

  'steadfast-tin-soldier': {
    title: 'El Soldadito de Plomo',
    summary: 'Un valiente soldadito de plomo vive una gran aventura y demuestra que el valor viene del corazon.',
    theme: 'valor y fidelidad',
    scenes: [
      { text: 'Entre una caja de soldaditos de plomo, uno tenia una sola pierna. Pero se mantenia erguido y orgulloso como los demas.' },
      { text: 'En un estante enfrente, una pequena bailarina de papel levantaba una pierna. El soldado penso que era como el, y se enamoro de ella.', dialogue: { speaker: 'Soldado', line: 'Es tan bonita. Quisiera quedarme cerca de ella para siempre.' } },
      { text: 'Un duende celoso dentro de una caja grito que el soldado no debia mirar a la bailarina. Al dia siguiente el soldado cayo por una ventana.' },
      { text: 'En la calle, unos ninos lo encontraron y lo pusieron en un barco de papel. Navego por el arroyo bajo la lluvia, y despues fue tragado por un gran pez.' },
      { text: 'El pez fue pescado y llego a la cocina. La cocinera lo abrio y encontro al soldadito ileso, todavia erguido.', dialogue: { speaker: 'Cocinera', line: 'Como pudiste sobrevivir a todo eso!' } },
      { text: 'El soldado fue devuelto al nino. Pero el duende celoso arrojo al soldado al fuego. La pequena bailarina tambien cayo por el viento. Del soldado solo quedo un pequeno corazon de metal, simbolo de su fidelidad eterna.', dialogue: { speaker: 'Soldado', line: 'Me mantuve firme hasta el final.' } },
    ],
    vocabulary: [
      { word: 'plomo', meaning: 'un metal gris muy pesado, antes usado para hacer juguetes', emoji: '⚙️' },
      { word: 'valiente', meaning: 'con coraje y firmeza ante el peligro', emoji: '🛡️' },
      { word: 'torrente', meaning: 'una corriente de agua fuerte y rapida', emoji: '🌊' },
      { word: 'fidelidad', meaning: 'permanecer leal a alguien que amas pase lo que pase', emoji: '💙' },
    ],
    miniGame: { type: 'choice', prompt: 'De quien se enamora el soldadito de plomo?', options: ['De una pequena bailarina de papel', 'De una princesa en el castillo', 'De un hada magica'], answerIndex: 0 },
    emotionalMoment: { feeling: 'fidelidad', prompt: 'Hay alguien o algo a quien seas muy fiel? Que significa eso para ti?' },
    rewardName: 'Medalla de Valor',
  },

  'la-fontaine-crow-fox': {
    title: 'El Cuervo y el Zorro',
    summary: 'Un zorro muy astuto halaga a un cuervo para robarle su queso. Una fabula sobre la vanidad.',
    theme: 'astucia y humildad',
    scenes: [
      { text: 'Un cuervo estaba posado en una rama, sosteniendo en su pico un buen trozo de queso muy perfumado.' },
      { text: 'Un zorro muy astuto paso por alli y olio el queso. Decidio robarselo usando halagos.', dialogue: { speaker: 'Zorro', line: 'Oh senor Cuervo, que hermoso es usted! Que magnifico plumaje tiene!' } },
      { text: 'El cuervo, muy orgulloso de los cumplidos, esponjaba sus plumas de placer. El zorro continuo.', dialogue: { speaker: 'Zorro', line: 'Si su voz es tan bella como sus plumas, usted es el rey de las aves!' } },
      { text: 'El cuervo, demasiado halagado, abrio el pico de par en par para cantar. El queso cayo.' },
      { text: 'El zorro atrapo el queso riendose y dijo la moraleja de la fabula.', dialogue: { speaker: 'Zorro', line: 'Todo adulador vive a expensas de quien lo escucha. Esta leccion bien vale un queso!' } },
    ],
    vocabulary: [
      { word: 'cuervo', meaning: 'un gran pajaro negro con un pico fuerte y curvo', emoji: '🐦‍⬛' },
      { word: 'adulador', meaning: 'alguien que da demasiados cumplidos para conseguir algo', emoji: '😏' },
      { word: 'queso', meaning: 'un alimento hecho con leche, a menudo amarillo o blanco', emoji: '🧀' },
      { word: 'moraleja', meaning: 'la leccion que aprendes al final de una fabula', emoji: '📜' },
    ],
    miniGame: { type: 'choice', prompt: 'Como consigue el zorro el queso?', options: ['Halagando al cuervo para que abra el pico', 'Subiendo al arbol', 'Pidiendolo amablemente'], answerIndex: 0 },
    emotionalMoment: { feeling: 'humildad', prompt: 'Te han halagado alguna vez y has hecho algo tonto? Que aprendiste?' },
    rewardName: 'Sabiduria de la Fabula',
  },
};
