// English translations for all 19 fairy tales.
// Only content fields are translated — id, emoji, coverImage, palette,
// difficulty, ageMin, ageMax, rewardEmoji are intentionally omitted.

export const CONTES_EN = {
  'snow-white': {
    title: 'Snow White',
    summary: 'A gentle princess with skin as white as snow finds a home with seven kind little helpers and learns that true friends always look after each other.',
    theme: 'kindness and friendship',
    scenes: [
      { text: 'Long ago, a little princess was born with skin as white as snow. Everyone called her Snow White.' },
      { text: 'A jealous queen owned a magic mirror and asked it the same question every day.', dialogue: { speaker: 'Queen', line: 'Mirror, mirror, who is the kindest and most beautiful of all?' } },
      { text: 'Snow White walked into the heart of the forest. Seven kind little miners welcomed her into their cosy cottage.', dialogue: { speaker: 'A miner', line: 'You are safe here, little friend. Come and rest.' } },
      { text: 'The queen tricked her with a shiny apple, and Snow White fell into a very, very deep sleep.' },
      { text: 'A caring friend woke her with a gentle touch. Snow White smiled, and everyone celebrated their brave friend.', dialogue: { speaker: 'Snow White', line: 'You never left me. Thank you, my friends!' } },
    ],
    vocabulary: [
      { word: 'fairest', meaning: 'the kindest and most beautiful person', emoji: '🌷' },
      { word: 'jealous', meaning: 'upset because you want what someone else has', emoji: '😠' },
      { word: 'cottage', meaning: 'a small, cosy house', emoji: '🏡' },
      { word: 'welcome', meaning: 'to make someone glad they have arrived', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'How many kind little miners welcomed Snow White?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'surrounded and safe', prompt: 'Snow White\'s friends looked after her. Who looks after you?' },
    rewardName: 'Kind Mirror',
  },

  'cinderella': {
    title: 'Cinderella',
    summary: 'A hard-working girl with a big heart gets a little help from a magical friend and discovers that being kind is a magic all of its own.',
    theme: 'hope and kindness',
    scenes: [
      { text: 'Cinderella did all the chores and never lost her sweet smile, even when others were unkind.' },
      { text: 'One evening, a grand ball was announced, but Cinderella had nothing to wear.', dialogue: { speaker: 'Cinderella', line: 'If only I could go dancing, just once.' } },
      { text: 'A kind fairy appeared and, with a wave of her wand, turned a pumpkin into a carriage.', dialogue: { speaker: 'Fairy friend', line: 'Be back before midnight, my dear — the magic stops then.' } },
      { text: 'At the ball, Cinderella danced and laughed. But when the clock began to strike, she had to run.' },
      { text: 'The slipper fitted her perfectly. Her kindness had always been seen, and joy filled her days.', dialogue: { speaker: 'Cinderella', line: 'Being kind costs nothing.' } },
    ],
    vocabulary: [
      { word: 'chores', meaning: 'small jobs that help around the home', emoji: '🧹' },
      { word: 'carriage', meaning: 'a coach pulled along to carry people', emoji: '🛞' },
      { word: 'midnight', meaning: 'twelve o\'clock at night', emoji: '🕛' },
      { word: 'gentle', meaning: 'tender, calm, and kind', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'What time must Cinderella be back? Count the chimes of the clock!', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'full of hope', prompt: 'Even on hard days, Cinderella stayed kind. What helps you keep hoping?' },
    rewardName: 'Glass Slipper',
  },

  'little-red-riding-hood': {
    title: 'Little Red Riding Hood',
    summary: 'A brave little girl in a red hood visits her grandmother and learns to listen to her wise feelings along the way.',
    theme: 'listening and staying safe',
    scenes: [
      { text: 'A little girl wore a bright red hood everywhere she went, so everyone called her Little Red Riding Hood.' },
      { text: 'Her mum gave her a basket of bread for Grandma.', dialogue: { speaker: 'Mum', line: 'Stay on the path and everything will be fine.' } },
      { text: 'In the woods, a crafty wolf asked lots of questions. Little Red felt something strange and kept on walking.', dialogue: { speaker: 'Little Red', line: 'I don\'t have to answer you. I will tell a grown-up.' } },
      { text: 'A kind woodcutter heard her and walked with her. Together, they arrived at Grandma\'s house.' },
      { text: 'Grandma was safe, and so was Little Red. They shared warm bread and laughed all afternoon.', dialogue: { speaker: 'Grandma', line: 'You listened to your wise feelings. I am so proud of you.' } },
    ],
    vocabulary: [
      { word: 'path', meaning: 'a track that shows you where to walk safely', emoji: '🛤️' },
      { word: 'basket', meaning: 'a carrier with a handle for taking things along', emoji: '🧺' },
      { word: 'crafty', meaning: 'someone who plays tricks to fool you', emoji: '🦊' },
      { word: 'woodcutter', meaning: 'a person who works among the trees', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'A stranger asks Little Red where she is going. What is the safe choice?', options: ['Tell him everything', 'Keep walking and warn a grown-up', 'Follow him into the trees'], answerIndex: 1 },
    emotionalMoment: { feeling: 'safe', prompt: 'Little Red listened to her strange feeling. When has a feeling helped you stay safe?' },
    rewardName: 'Red Hood',
  },

  'hansel-and-gretel': {
    title: 'Hansel and Gretel',
    summary: 'A brother and sister get lost in the woods and use a clever plan, and great teamwork, to find their way safely home.',
    theme: 'cleverness and sticking together',
    scenes: [
      { text: 'Hansel and Gretel walked into the great forest, holding hands so they would not get lost.' },
      { text: 'Clever Hansel dropped small, shiny white pebbles one by one to mark the way back.', dialogue: { speaker: 'Hansel', line: 'These pebbles will shine and lead us home.' } },
      { text: 'They found a little house made of sweets, but a crafty old woman lived there.' },
      { text: 'The children were too clever to be tricked. They held hands and crept quietly outside.', dialogue: { speaker: 'Gretel', line: 'Quickly — together we are braver than alone.' } },
      { text: 'The shiny pebbles glittered in the moonlight and led them straight home to a warm hug.' },
    ],
    vocabulary: [
      { word: 'pebbles', meaning: 'small, smooth little stones', emoji: '🪨' },
      { word: 'clever', meaning: 'good at thinking of smart ideas', emoji: '💡' },
      { word: 'on tiptoe', meaning: 'walking very quietly on your toes', emoji: '🦶' },
      { word: 'together', meaning: 'with each other, side by side', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put Hansel\'s clever plan in the right order!', steps: ['Drop the shiny pebbles', 'Follow the glittering trail', 'Find the way back home'] },
    emotionalMoment: { feeling: 'brave together', prompt: 'The children were braver as a team. Who makes you feel braver?' },
    rewardName: 'Shiny Pebble',
  },

  'rapunzel': {
    title: 'Rapunzel',
    summary: 'A kind girl with very long hair lives in a tall tower and learns that patience and a heart full of hope can open any door.',
    theme: 'patience and hope',
    scenes: [
      { text: 'Right at the top of a tall tower lived Rapunzel, a girl with the longest golden plait in the world.' },
      { text: 'Every day, Rapunzel sang to the birds. Her sweet song floated all through the forest.', dialogue: { speaker: 'Rapunzel', line: 'One day I will see the world down there, beneath the trees.' } },
      { text: 'A kind traveller heard her song and called up: "Your music makes the whole forest smile!"', dialogue: { speaker: 'Traveller', line: 'Your music makes the whole forest smile!' } },
      { text: 'They became friends. Day after day, patiently, they thought of a clever way to climb down.' },
      { text: 'At last, Rapunzel set her foot on the soft grass and twirled in the sunshine, free and happy.', dialogue: { speaker: 'Rapunzel', line: 'Waiting was hard, but hope kept me strong.' } },
    ],
    vocabulary: [
      { word: 'tower', meaning: 'a very tall and narrow building', emoji: '🗼' },
      { word: 'plait', meaning: 'hair woven into a long rope-like braid', emoji: '💇' },
      { word: 'patience', meaning: 'waiting calmly without giving up', emoji: '⏳' },
      { word: 'meadow', meaning: 'a field of grass filled with flowers', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Find what Rapunzel used to climb down safely.', target: 'the golden plaited ladder', decoys: ['a paper kite', 'a wooden spoon', 'a little cup'] },
    emotionalMoment: { feeling: 'patient', prompt: 'Rapunzel waited with hope. What lovely thing have you waited a long time for?' },
    rewardName: 'Golden Plait',
  },

  'the-ugly-duckling': {
    title: 'The Ugly Duckling',
    summary: 'A little bird who feels different from the others grows up and discovers it was wonderful exactly as it was, all along.',
    theme: 'belonging and self-love',
    scenes: [
      { text: 'In a sunny pond, a little bird did not look like its brothers and sisters.' },
      { text: 'The other birds laughed at it, and deep inside it felt lonely and very sad.', dialogue: { speaker: 'Little bird', line: 'I wish someone would let me join in too.' } },
      { text: 'A kind frog hopped over and sat beside it. "You are welcome with me," it said.', dialogue: { speaker: 'Frog', line: 'You are welcome with me, my friend.' } },
      { text: 'The seasons passed. On a bright morning, the little bird saw its face in the still water.' },
      { text: 'It had become a beautiful swan! It had always been special — simply itself.', dialogue: { speaker: 'Swan', line: 'I did not need to change. I just needed to grow.' } },
    ],
    vocabulary: [
      { word: 'pond', meaning: 'a small stretch of calm water', emoji: '💧' },
      { word: 'lonely', meaning: 'sad because you feel all alone', emoji: '🥺' },
      { word: 'reflection', meaning: 'the image you see in still water', emoji: '🪞' },
      { word: 'swan', meaning: 'a large, graceful white water bird', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'A new friend feels left out. What kind thing could you say?', options: ['You don\'t belong here', 'You can play with us!', 'Go away'], answerIndex: 1 },
    emotionalMoment: { feeling: 'I belong', prompt: 'The little bird was special just as it was. What makes you a wonderful you?' },
    rewardName: 'Gentle Swan',
  },

  'the-little-mermaid': {
    title: 'The Little Mermaid',
    summary: 'A curious young mermaid bravely explores a new world and learns that a kind and generous heart shines brighter than anything.',
    theme: 'courage and a good heart',
    scenes: [
      { text: 'Deep beneath the waves lived a young mermaid, the smallest of six sisters.' },
      { text: 'She loved to swim to the surface and gaze at the bright world above the water.', dialogue: { speaker: 'Mermaid', line: 'The world up there is full of things I want to learn!' } },
      { text: 'On a stormy night, she bravely helped a sailor reach the shore safely.' },
      { text: 'She did not stay to be thanked. Helping someone filled her heart with warmth.', dialogue: { speaker: 'Mermaid', line: 'I helped out of kindness, not for a thank-you.' } },
      { text: 'Back home, she told her brave story, and her good heart made the whole sea shine.' },
    ],
    vocabulary: [
      { word: 'mermaid', meaning: 'an imaginary sea girl with a fish\'s tail', emoji: '🧜' },
      { word: 'waves', meaning: 'water that rises and falls on the sea', emoji: '🌊' },
      { word: 'brave', meaning: 'doing a hard thing even when it is scary', emoji: '💪' },
      { word: 'generous', meaning: 'happy to give and help others', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'How many older sisters did the Little Mermaid have?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'big-hearted', prompt: 'The mermaid helped purely out of kindness. When have you helped without being asked?' },
    rewardName: 'Sea Pearl',
  },

  'the-snow-queen': {
    title: 'The Snow Queen',
    summary: 'When her best friend\'s heart turns cold, a faithful girl called Gerda travels far through the snow to warm him with love.',
    theme: 'faithful friendship',
    scenes: [
      { text: 'Gerda and Kai were best friends and grew roses together by their window.' },
      { text: 'A tiny sliver of frost touched Kai\'s heart, and he became cold and distant.', dialogue: { speaker: 'Gerda', line: 'Wait... where are you going, Kai?' } },
      { text: 'Brave Gerda did not give up. She set off through the snow to find her friend.', dialogue: { speaker: 'Gerda', line: 'I will find you, Kai. Friends don\'t give up.' } },
      { text: 'She found Kai in an ice palace, sitting still and cold as stone.' },
      { text: 'Gerda hugged him and warm tears fell. The frost melted, and Kai smiled and remembered.', dialogue: { speaker: 'Kai', line: 'You came all this way for me. Thank you, Gerda.' } },
    ],
    vocabulary: [
      { word: 'frost', meaning: 'a thin layer of ice that forms when it is very cold', emoji: '🌨️' },
      { word: 'faithful', meaning: 'always there for your friends', emoji: '🤲' },
      { word: 'palace', meaning: 'a very large and beautiful house', emoji: '🏰' },
      { word: 'melt', meaning: 'to go from ice to water with warmth', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'How did Gerda melt the ice in Kai\'s heart?', options: ['With a big fire', 'With warm tears and a hug', 'With a hammer'], answerIndex: 1 },
    emotionalMoment: { feeling: 'faithful', prompt: 'Gerda never gave up on her friend. How do you show a friend you care about them?' },
    rewardName: 'Warm Rose',
  },

  'puss-in-boots': {
    title: 'Puss in Boots',
    summary: 'A clever cat in fine boots uses his quick wits and loyal heart to help his kind friend find happiness.',
    theme: 'cleverness and loyalty',
    scenes: [
      { text: 'A clever cat pulled on fine boots and a feathered hat, ready for adventure.' },
      { text: 'His friend was poor but kind, so the cat thought of a clever plan to help him.', dialogue: { speaker: 'The Cat', line: 'Trust me, my friend. A clever idea is on its way!' } },
      { text: 'The cat greeted the king politely and offered gifts, making everyone smile.' },
      { text: 'With wit rather than tricks, the cat helped his friend win a grand castle by the river.', dialogue: { speaker: 'The Cat', line: 'Good ideas open more doors than loud roars.' } },
      { text: 'His friend was happy at last, and the cat curled up by the fire, the most faithful cat of all.' },
    ],
    vocabulary: [
      { word: 'clever', meaning: 'good at thinking of smart ideas', emoji: '🧠' },
      { word: 'boots', meaning: 'shoes that go up high on your legs', emoji: '🥾' },
      { word: 'polite', meaning: 'kind and gentle with your words', emoji: '🙏' },
      { word: 'loyal', meaning: 'always there for your friends', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put the Cat\'s clever plan in the right order!', steps: ['Put on the fine boots', 'Greet the king politely', 'Help his friend win the day'] },
    emotionalMoment: { feeling: 'helpful', prompt: 'The Cat used clever ideas to help a friend. In what clever way have you helped someone?' },
    rewardName: 'Fine Boots',
  },

  'pinocchio': {
    title: 'Pinocchio',
    summary: 'A wooden puppet who dreams of being a real boy learns that telling the truth is what makes a good heart grow.',
    theme: 'honesty',
    scenes: [
      { text: 'Once upon a time there was a little wooden puppet called Pinocchio, who dreamed of becoming a real boy.' },
      { text: 'Every time Pinocchio told a lie, his nose grew longer like a branch.', dialogue: { speaker: 'Pinocchio', line: 'It wasn\'t me! I promise!' } },
      { text: 'His friend the cricket tried to teach him always to tell the truth.', dialogue: { speaker: 'Cricket', line: 'Telling the truth will make you feel light as a feather.' } },
      { text: 'Pinocchio made a big mistake and got lost. He learned then that honesty was his only guide.' },
      { text: 'When Pinocchio finally told the truth, his heart grew, and his dearest wish came true.', dialogue: { speaker: 'Pinocchio', line: 'The truth is the most powerful magic of all.' } },
    ],
    vocabulary: [
      { word: 'puppet', meaning: 'a doll that is made to move', emoji: '🎭' },
      { word: 'truth', meaning: 'saying exactly what happened', emoji: '✅' },
      { word: 'lie', meaning: 'saying something that is not true', emoji: '❌' },
      { word: 'honest', meaning: 'someone who always tells the truth', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'When does Pinocchio\'s nose grow longer?', options: ['When he tells the truth', 'When he tells a lie', 'When he sings a song'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honest', prompt: 'Telling the truth made Pinocchio feel light. How do you feel when you tell the truth?' },
    rewardName: 'Cricket of Truth',
  },

  'peter-pan': {
    title: 'Peter Pan',
    summary: 'A boy who never grows up takes new friends on a flying adventure where happy thoughts and a little courage take you anywhere.',
    theme: 'imagination and courage',
    scenes: [
      { text: 'In a bedroom full of stars, a boy called Peter Pan taught the children to fly.' },
      { text: 'Peter told Wendy the secret: you had to think of something very happy.', dialogue: { speaker: 'Peter Pan', line: 'Think of your happiest thing — and off you go!' } },
      { text: 'Together they flew to Neverland, a magical island full of adventures.' },
      { text: 'Even facing the wicked captain, Peter was not afraid. He met danger with a big smile.', dialogue: { speaker: 'Peter Pan', line: 'Being brave means trying anyway.' } },
      { text: 'The children went home with hearts full of memories and a little magic for ever.' },
    ],
    vocabulary: [
      { word: 'bedroom', meaning: 'the room where you sleep and dream', emoji: '🛏️' },
      { word: 'shadow', meaning: 'the dark shape your body makes on the ground', emoji: '👤' },
      { word: 'imagine', meaning: 'to create beautiful things inside your head', emoji: '💭' },
      { word: 'courage', meaning: 'trying even when you are scared', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'What helped the children fly?', options: ['Happy thoughts and fairy dust', 'Heavy boots', 'Shouting very loudly'], answerIndex: 0 },
    emotionalMoment: { feeling: 'brave', prompt: 'Peter says being brave means trying anyway. What brave thing would you like to try?' },
    rewardName: 'Fairy Dust',
  },

  'alice-in-wonderland': {
    title: 'Alice in Wonderland',
    summary: 'A curious girl follows a hurrying rabbit into a topsy-turvy world and learns that asking questions is a kind of magic.',
    theme: 'curiosity',
    scenes: [
      { text: 'Alice saw a hurrying white rabbit jump into a hole and, feeling very curious, she followed it.' },
      { text: 'She fell down a long magical tunnel and found a tiny door into a garden.', dialogue: { speaker: 'Alice', line: 'How very strange! I wonder what is going on here.' } },
      { text: 'Alice drank a little bottle and shrank, then ate a cake and grew very quickly.', dialogue: { speaker: 'Alice', line: 'Questions are the key to all the wonders!' } },
      { text: 'She met a grinning cat, an angry queen, and a very mad hatter.' },
      { text: 'Alice woke up and smiled. Asking questions had led her to the most beautiful of dreams.', dialogue: { speaker: 'Alice', line: 'Curiosity is the greatest adventure.' } },
    ],
    vocabulary: [
      { word: 'curious', meaning: 'someone who loves discovering new things', emoji: '🔍' },
      { word: 'burrow', meaning: 'a tunnel dug in the earth by an animal', emoji: '🕳️' },
      { word: 'shrink', meaning: 'to become smaller', emoji: '🔻' },
      { word: 'wonder', meaning: 'something incredible and very surprising', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put Alice\'s adventure in the right order!', steps: ['Drink the bottle and shrink', 'Eat the cake and grow', 'Find the tiny garden door'] },
    emotionalMoment: { feeling: 'curious', prompt: 'Alice loved asking questions. What makes you curious today?' },
    rewardName: 'Curious Clock',
  },

  'the-wizard-of-oz': {
    title: 'The Wizard of Oz',
    summary: 'A girl and three new friends follow a golden road and discover that the gifts they were searching for were inside them all along.',
    theme: 'you already have what you need',
    scenes: [
      { text: 'A great whirlwind carried Dorothy and her little dog Toto away to the magical land of Oz.' },
      { text: 'On the golden road, Dorothy met a scarecrow, a tin man, and a lion.', dialogue: { speaker: 'Scarecrow', line: 'I just want a clever brain!' } },
      { text: 'Together they walked towards the Emerald City to find the great Wizard.', dialogue: { speaker: 'Dorothy', line: 'If we are together, we can do anything.' } },
      { text: 'The Wizard revealed a great secret: they already had everything they desired.' },
      { text: 'Dorothy tapped her shoes three times and was back home. Everyone had found their gift.', dialogue: { speaker: 'Dorothy', line: 'There is no place like home.' } },
    ],
    vocabulary: [
      { word: 'whirlwind', meaning: 'a very strong wind that spins round and round', emoji: '🌪️' },
      { word: 'scarecrow', meaning: 'a large straw figure put out to frighten birds', emoji: '🌾' },
      { word: 'courage', meaning: 'to keep going even when you are afraid', emoji: '💪' },
      { word: 'journey', meaning: 'a long walk or adventure to a new place', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Which friend already had courage from the very beginning?', options: ['The scarecrow', 'The tin man', 'The lion'], answerIndex: 2 },
    emotionalMoment: { feeling: 'capable', prompt: 'The friends already had their gifts inside them. What gift do you already have inside you?' },
    rewardName: 'Sparkling Shoes',
  },

  'robin-hood': {
    title: 'Robin Hood',
    summary: 'A kind archer from the green forest shares with those who have very little and teaches his friends that fairness makes everyone happier.',
    theme: 'fairness and generosity',
    scenes: [
      { text: 'In a great green forest lived Robin Hood, the finest archer in the land.' },
      { text: 'He saw that many people were very poor while others had everything.', dialogue: { speaker: 'Robin', line: 'Sharing is the finest gift of all.' } },
      { text: 'With his merry friends, Robin made a plan to help those in need.', dialogue: { speaker: 'Little John', line: 'Together we are the strength of the forest!' } },
      { text: 'Robin gave people what they needed, and smiles appeared everywhere.' },
      { text: 'The forest hummed with happiness. Robin had learned that generosity is the true victory.', dialogue: { speaker: 'Robin', line: 'Generosity makes everyone richer.' } },
    ],
    vocabulary: [
      { word: 'archer', meaning: 'someone who shoots arrows with a bow', emoji: '🎯' },
      { word: 'forest', meaning: 'a large place full of trees and animals', emoji: '🌳' },
      { word: 'fair', meaning: 'treating everyone in the same way', emoji: '⚖️' },
      { word: 'generous', meaning: 'happy to give and share', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin Hood shared with people who were...', options: ['hungry and in need', 'already very rich', 'unkind to others'], answerIndex: 0 },
    emotionalMoment: { feeling: 'fair', prompt: 'Robin loved to share. What could you share to make a friend smile?' },
    rewardName: 'Friendly Bow',
  },

  'goldilocks': {
    title: 'Goldilocks',
    summary: 'A curious girl steps into the bears\' cosy cottage and learns that it is best to ask first and take care of other people\'s things.',
    theme: 'respect for others',
    scenes: [
      { text: 'A little girl with golden curls was walking through the forest when she found a pretty cottage.' },
      { text: 'She went inside and tasted three bowls of porridge. The baby bear\'s was just right.', dialogue: { speaker: 'Goldilocks', line: 'Oh! This bowl is perfect — not too hot and not too cold!' } },
      { text: 'She tried three chairs, then three beds. She fell asleep in the cosiest one.' },
      { text: 'The three bears came home and found their house all mixed up.', dialogue: { speaker: 'Baby Bear', line: 'Someone has been eating my porridge!' } },
      { text: 'Goldilocks woke up, said sorry, and learned that asking first is the kindest manners.', dialogue: { speaker: 'Goldilocks', line: 'Sorry. I will always ask before I come in.' } },
    ],
    vocabulary: [
      { word: 'porridge', meaning: 'warm, soft food, like breakfast cereal', emoji: '🥣' },
      { word: 'cottage', meaning: 'a small, cosy house in the forest', emoji: '🏡' },
      { word: 'respect', meaning: 'taking care of other people\'s things and feelings', emoji: '🙏' },
      { word: 'sorry', meaning: 'what you say when you regret something', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'How many bears lived in the cosy cottage?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respectful', prompt: 'Goldilocks learned to ask first. When is it kind to ask permission before borrowing something?' },
    rewardName: 'Perfect Bowl',
  },

  'three-little-pigs': {
    title: 'The Three Little Pigs',
    summary: 'Three little pigs build three different houses and learn that careful, hard work keeps everyone safe and warm.',
    theme: 'hard work and planning',
    scenes: [
      { text: 'Three little pigs set off into the world to build their houses.' },
      { text: 'The first pig quickly built a house of straw. The second built a house of wood.', dialogue: { speaker: 'First pig', line: 'Quick and done! I want to go and play!' } },
      { text: 'The third pig worked hard and built a solid house of bricks, one by one.', dialogue: { speaker: 'Third pig', line: 'I am taking my time so my house will be strong.' } },
      { text: 'The big bad wolf blew down the houses of straw and wood, and they collapsed.' },
      { text: 'But the brick house stayed firm. The three pigs were safe, and everyone learned that careful work protects.', dialogue: { speaker: 'Third pig', line: 'Good work takes time, but it is worth it!' } },
    ],
    vocabulary: [
      { word: 'straw', meaning: 'dry plant stems that are easy to break', emoji: '🌾' },
      { word: 'bricks', meaning: 'very strong baked earth blocks', emoji: '🧱' },
      { word: 'strong', meaning: 'very solid and not easy to break', emoji: '💪' },
      { word: 'plan', meaning: 'to think carefully before you start something', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'How many little pigs built houses?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'proud of my work', prompt: 'The third pig worked hard and stayed safe. What have you worked hard on?' },
    rewardName: 'Solid Brick',
  },

  'aladdin': {
    title: 'Aladdin',
    summary: 'An ordinary but kind boy finds a magic lamp and learns that what you wish for matters far less than the good you do for others.',
    theme: 'honesty and humility',
    scenes: [
      { text: 'In a busy market lived Aladdin, a poor boy with a heart of gold.' },
      { text: 'He found an old lamp and, when he rubbed it, a great genie appeared!', dialogue: { speaker: 'Genie', line: 'I grant you three wishes. Choose carefully!' } },
      { text: 'Aladdin first wished to help his family, then the poor people of his neighbourhood.', dialogue: { speaker: 'Aladdin', line: 'I want no one in this market to go hungry.' } },
      { text: 'His humility and generosity earned him true friends and a great deal of happiness.' },
      { text: 'Aladdin learned that the best wishes are the ones you make for others.', dialogue: { speaker: 'Aladdin', line: 'A generous heart is the greatest treasure.' } },
    ],
    vocabulary: [
      { word: 'market', meaning: 'a busy place where people sell and buy things', emoji: '🏪' },
      { word: 'lamp', meaning: 'an object that gives light or holds a genie', emoji: '🪔' },
      { word: 'humble', meaning: 'someone who does not boast about themselves', emoji: '🙏' },
      { word: 'wish', meaning: 'something you want very, very much', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'How many wishes did the genie give Aladdin?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'generous', prompt: 'Aladdin wished to help others. If you had one kind wish, what would it be?' },
    rewardName: 'Wishing Lamp',
  },

  'ali-baba': {
    title: 'Ali Baba',
    summary: 'A gentle woodcutter discovers a secret cave and learns that being honest and careful is worth far more than being greedy.',
    theme: 'honesty over greed',
    scenes: [
      { text: 'Ali Baba was a gentle woodcutter who lived simply and happily.' },
      { text: 'One day in the forest, he heard thieves say the magic words in front of a great rock.', dialogue: { speaker: 'Thieves', line: 'Open Sesame!' } },
      { text: 'Ali Baba entered the cave and saw dazzling treasures of every colour.', dialogue: { speaker: 'Ali Baba', line: 'I will take only what we need — no more.' } },
      { text: 'His greedy brother took too much and was caught by the thieves. Ali Baba understood the lesson.' },
      { text: 'Ali Baba shared his good fortune with others and lived simply and happily.', dialogue: { speaker: 'Ali Baba', line: 'Having enough and being honest — that is true wealth.' } },
    ],
    vocabulary: [
      { word: 'cave', meaning: 'a large, natural hollow in the rock', emoji: '🕳️' },
      { word: 'treasure', meaning: 'a large amount of gold and precious things', emoji: '💎' },
      { word: 'greedy', meaning: 'someone who always wants more than they need', emoji: '😤' },
      { word: 'enough', meaning: 'just what you need — no more and no less', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'What magic words open the cave?', options: ['Open Sesame!', 'Shut the door!', 'Good morning!'], answerIndex: 0 },
    emotionalMoment: { feeling: 'content', prompt: 'Ali Baba only took what was needed. What thing you already have is just enough for you?' },
    rewardName: 'Secret Cave',
  },

  'aesops-fables': {
    title: 'The Hare and the Tortoise',
    summary: 'A speedy hare and a slow tortoise have a friendly race, and the tortoise shows everyone that never giving up wins the day.',
    theme: 'perseverance — slow and steady',
    scenes: [
      { text: 'In a sunny meadow, a speedy hare was always boasting about how fast he was.' },
      { text: 'The slow, calm tortoise suggested a race. The hare accepted with a laugh.', dialogue: { speaker: 'Hare', line: 'A race against you? Easy! I\'ll have a rest on the way.' } },
      { text: 'The tortoise moved step by step, steadily, never stopping.', dialogue: { speaker: 'Tortoise', line: 'Slow and steady, I will keep moving forward.' } },
      { text: 'The hare fell asleep under a tree, sure that the tortoise could never catch up.' },
      { text: 'When the hare woke up, the tortoise had already crossed the finish line. Perseverance always wins.', dialogue: { speaker: 'Tortoise', line: 'Step by step, you get further than you think.' } },
    ],
    vocabulary: [
      { word: 'hare', meaning: 'a large, wild rabbit that is very fast', emoji: '🐇' },
      { word: 'tortoise', meaning: 'a shelled animal that walks slowly but never stops', emoji: '🐢' },
      { word: 'steady', meaning: 'moving at the same pace without stopping', emoji: '⏱️' },
      { word: 'persevere', meaning: 'to keep trying even when it is hard', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Who won the race by never giving up?', options: ['the speedy hare', 'the slow, steady tortoise', 'the sleeping fox'], answerIndex: 1 },
    emotionalMoment: { feeling: 'determined', prompt: 'The tortoise kept going step by step. What do you keep trying at?' },
    rewardName: 'Persevering Tortoise',
  },

  'sleeping-beauty': {
    title: 'Sleeping Beauty',
    summary: 'A beautiful princess falls into a magical sleep and awaits true love.',
    theme: 'patience and hope',
    scenes: [
      { text: 'A happy king and queen finally had a little daughter. They invited all the fairies of the kingdom to her christening.' },
      { text: 'The good fairies gave the princess their gifts: beauty, grace, and gentleness. But an angry bad fairy arrived uninvited.', dialogue: { speaker: 'Bad fairy', line: 'When she turns sixteen, she shall prick her finger on a spindle and fall down dead!' } },
      { text: 'The last good fairy had not yet spoken. She softened the curse: the princess would not die, but sleep for a hundred years.', dialogue: { speaker: 'Good fairy', line: 'She will sleep, but love shall wake her.' } },
      { text: 'At sixteen, the princess found an old woman spinning. She touched the spindle and fell into a deep sleep. The whole castle fell asleep with her.' },
      { text: 'A prince heard of the sleeping castle hidden behind a forest of roses. He cut through the thorns and entered the silent castle.', dialogue: { speaker: 'Prince', line: 'How beautiful she is! I shall wake her.' } },
      { text: 'The prince leaned over the beautiful princess and gave her a gentle kiss. She opened her eyes and smiled. The whole castle woke at the same moment, and they lived happily ever after.', dialogue: { speaker: 'Princess', line: 'I have waited so long. At last you have come!' } },
    ],
    vocabulary: [
      { word: 'spindle', meaning: 'a tool for spinning wool, with a sharp point', emoji: '🧵' },
      { word: 'malevolent', meaning: 'someone who uses wicked magic to cause harm', emoji: '🧙' },
      { word: 'enchanted', meaning: 'changed by a special spell or magic', emoji: '✨' },
      { word: 'rose bush', meaning: 'a thorny bush that grows beautiful roses', emoji: '🌹' },
    ],
    miniGame: { type: 'choice', prompt: 'Which bad fairy casts the spell on the princess?', options: ['A fairy who was not invited', 'The palace fairy', 'The forest fairy'], answerIndex: 0 },
    emotionalMoment: { feeling: 'hope', prompt: 'Have you ever waited impatiently for something? How did it feel?' },
    rewardName: 'Enchanted Rose',
  },

  'beauty-and-the-beast': {
    title: 'Beauty and the Beast',
    summary: 'Beauty learns that true beauty lies in the heart, not in appearance.',
    theme: 'kindness and true love',
    scenes: [
      { text: 'A merchant got lost in the forest during a storm. He found a great mysterious castle and sheltered there for the night.' },
      { text: 'As he was leaving, he picked a rose for his daughter Beauty. A terrifying Beast suddenly appeared.', dialogue: { speaker: 'Beast', line: 'You have stolen my rose! You are my prisoner!' } },
      { text: 'The merchant begged the Beast to let him say goodbye to his children. The Beast agreed, on the condition that one of his daughters return in his place.', dialogue: { speaker: 'Beauty', line: 'Father, I will go. I am not afraid.' } },
      { text: 'Beauty lived in the castle. The Beast was ugly but gentle and kind. Each evening they talked and laughed together.' },
      { text: 'Beauty asked to go home to see her sick father. The Beast agreed, sadly.', dialogue: { speaker: 'Beast', line: 'I will miss you, Beauty. But your happiness comes before my own.' } },
      { text: 'Far from the castle, Beauty realised she loved the Beast. She ran back to him. When she confessed her love, the Beast was transformed into a handsome prince.', dialogue: { speaker: 'Beauty', line: 'I love you, not for your face, but for your heart.' } },
      { text: 'The prince explained that a sorceress had enchanted him. Only sincere love could set him free. Beauty and the prince lived happily ever after.' },
    ],
    vocabulary: [
      { word: 'beast', meaning: 'a large frightening animal, here an enchanted monster', emoji: '🐾' },
      { word: 'prisoner', meaning: 'someone who is not free to leave', emoji: '🔒' },
      { word: 'appearance', meaning: 'what you see of someone from the outside', emoji: '👁️' },
      { word: 'transformation', meaning: 'to change completely in shape or appearance', emoji: '✨' },
    ],
    miniGame: { type: 'choice', prompt: 'Why does Beauty\'s father go to the castle?', options: ['He is looking for treasure', 'He shelters from the storm and picks a rose', 'He visits the Beast'], answerIndex: 1 },
    emotionalMoment: { feeling: 'kindness', prompt: 'Have you ever judged someone by their appearance before getting to know them?' },
    rewardName: 'Magic Rose',
  },

  'little-thumb': {
    title: 'Hop o\' My Thumb',
    summary: 'The smallest of seven brothers uses his wits to save his whole family.',
    theme: 'courage and intelligence',
    scenes: [
      { text: 'A poor woodcutter and his wife had seven sons. The smallest was called Hop o\' My Thumb. He was tiny but very clever.' },
      { text: 'One evening the parents, too poor to feed their children, abandoned them in the forest.', dialogue: { speaker: 'Hop o\' My Thumb', line: 'I knew they would do this. I am ready.' } },
      { text: 'Hop o\' My Thumb had prepared: he had filled his pockets with small white pebbles. He scattered them all along the path, and the children found their way home by following them.' },
      { text: 'The second time they were abandoned, he had only bread to scatter crumbs. The birds ate them and the brothers were truly lost.' },
      { text: 'Lost, they arrived at an ogre\'s house. The ogre\'s wife hid them, but the ogre found them.', dialogue: { speaker: 'Ogre', line: 'I smell fresh flesh! Where are they hidden?' } },
      { text: 'Hop o\' My Thumb had a brilliant idea: he swapped his brothers\' caps with the crowns of the ogre\'s daughters. The ogre made the wrong choice in the dark.' },
      { text: 'Hop o\' My Thumb stole the ogre\'s seven-league boots while he slept. In a few strides he fetched gold and saved his whole family.', dialogue: { speaker: 'Hop o\' My Thumb', line: 'Cleverness is worth more than strength!' } },
    ],
    vocabulary: [
      { word: 'pebbles', meaning: 'small smooth stones you can scatter along a path', emoji: '🪨' },
      { word: 'ogre', meaning: 'a giant monster in fairy tales that eats children', emoji: '👹' },
      { word: 'league', meaning: 'a great distance, like several kilometres', emoji: '🗺️' },
      { word: 'ruse', meaning: 'a clever idea used to trick someone', emoji: '💡' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put the steps in the right order!', steps: ['Scatter white pebbles to find the way home', 'Arrive at the ogre\'s house in the forest', 'Steal the seven-league boots'] },
    emotionalMoment: { feeling: 'courage', prompt: 'Have you ever been frightened but carried on anyway? What helped you?' },
    rewardName: 'Seven-League Boots',
  },

  'jack-beanstalk': {
    title: 'Jack and the Beanstalk',
    summary: 'Jack swaps his cow for magic beans and discovers a castle in the clouds.',
    theme: 'adventure and curiosity',
    scenes: [
      { text: 'Jack and his mother were very poor. One day his mother sent Jack to sell their old cow at the market.' },
      { text: 'On the road, an old man offered Jack magic beans in exchange for the cow. Jack accepted.', dialogue: { speaker: 'Jack', line: 'Magic beans! That\'s a fine bargain!' } },
      { text: 'Jack\'s mother was very angry and threw the beans out of the window. But overnight an enormous beanstalk grew all the way up to the clouds.' },
      { text: 'Jack climbed the beanstalk and discovered a huge castle in the clouds. A terrible giant lived there.', dialogue: { speaker: 'Giant', line: 'Fee-fi-fo-fum! I smell the blood of an Englishman!' } },
      { text: 'The giant\'s wife helped Jack hide. While the giant slept, Jack seized the golden hen and the enchanted harp.' },
      { text: 'Jack slid down the beanstalk as fast as he could. The giant gave chase. Jack grabbed his axe and chopped the stalk down. The giant fell far, far away.', dialogue: { speaker: 'Jack', line: 'Mother! We will be rich! Never hungry again!' } },
    ],
    vocabulary: [
      { word: 'beanstalk', meaning: 'a very tall bean plant that grows up to the sky', emoji: '🫘' },
      { word: 'giant', meaning: 'an imaginary creature of enormous size and strength', emoji: '🦣' },
      { word: 'clouds', meaning: 'the large white or grey shapes floating in the sky', emoji: '☁️' },
      { word: 'treasure', meaning: 'precious objects such as gold or jewels', emoji: '🪙' },
    ],
    miniGame: { type: 'choice', prompt: 'What does Jack swap his cow for?', options: ['Gold coins', 'Magic beans', 'A harp'], answerIndex: 1 },
    emotionalMoment: { feeling: 'curiosity', prompt: 'Have you ever discovered something surprising? How did you feel?' },
    rewardName: 'Giant\'s Treasure',
  },

  'thumbelina': {
    title: 'Thumbelina',
    summary: 'Thumbelina, a tiny little girl, searches for her place in a world that is far too big for her.',
    theme: 'identity and belonging',
    scenes: [
      { text: 'A woman who longed for a child planted a magic seed. A flower grew, and inside it slept a very tiny girl. Her name was Thumbelina.' },
      { text: 'One evening a horrible toad kidnapped Thumbelina to marry his son. Thumbelina wept on her lily pad.', dialogue: { speaker: 'Thumbelina', line: 'I don\'t want to stay here. I want to find my true home.' } },
      { text: 'Friendly fish nibbled through the lily-pad stalk and Thumbelina escaped. She travelled through fields and forests, always too small for everyone around her.' },
      { text: 'In winter, Thumbelina found shelter with a field mouse. But the mouse wanted her to marry an old blind mole.' },
      { text: 'Thumbelina found an injured swallow and nursed it tenderly through the whole winter.', dialogue: { speaker: 'Swallow', line: 'You have saved me. When spring comes I will carry you far from here.' } },
      { text: 'In spring, the swallow carried Thumbelina to a warm and flowery land. There she met a tiny flower prince. At last she had found her place.', dialogue: { speaker: 'Flower prince', line: 'You are welcome here. Will you be our queen?' } },
    ],
    vocabulary: [
      { word: 'tiny', meaning: 'extremely small, much smaller than everyone else', emoji: '🔬' },
      { word: 'kidnap', meaning: 'to take someone away by force without their permission', emoji: '😨' },
      { word: 'swallow', meaning: 'a small, swift bird that travels to warm countries', emoji: '🐦' },
      { word: 'fairy', meaning: 'a magical winged creature that helps others', emoji: '🧚' },
    ],
    miniGame: { type: 'find', prompt: 'Find the flower where Thumbelina sleeps!', target: 'the big pink flower', decoys: ['a green lily pad', 'a dry leaf', 'a mushroom'] },
    emotionalMoment: { feeling: 'belonging', prompt: 'Have you ever felt you did not quite fit in? How did you find your place?' },
    rewardName: 'Fairy Wings',
  },

  'twelve-dancing-princesses': {
    title: 'The Twelve Dancing Princesses',
    summary: 'Every night twelve princesses secretly wear out their shoes dancing. A soldier uncovers their mystery.',
    theme: 'mystery and perseverance',
    scenes: [
      { text: 'A king had twelve daughters. Every morning their shoes were worn through as if they had danced all night. But nobody knew why.' },
      { text: 'The king announced that whoever discovered the secret could marry one of his daughters. Princes tried, but all fell mysteriously asleep.', dialogue: { speaker: 'King', line: 'Who will solve this mystery? Their shoes are worn out again!' } },
      { text: 'An old soldier returning from the wars met a wise old woman who gave him an invisible cloak.', dialogue: { speaker: 'Old woman', line: 'Do not drink the drink they offer you. And take care!' } },
      { text: 'The soldier pretended to sleep. At midnight the princesses rose. He followed them invisibly through a secret passage underground.' },
      { text: 'Underground he discovered a lake with boats, a forest of silver and golden trees, and a lit castle where twelve princes waited to dance with the princesses.' },
      { text: 'The soldier secretly broke off a silver branch to prove his discovery. The eldest princess heard a sound.', dialogue: { speaker: 'Eldest princess', line: 'Something is not right tonight. I am afraid.' } },
      { text: 'Next morning the soldier showed the king the branch and told him everything. The king accepted the truth. The soldier chose to marry the eldest princess, and the secret was revealed for ever.', dialogue: { speaker: 'Soldier', line: 'The truth is worth more than any secret.' } },
    ],
    vocabulary: [
      { word: 'mystery', meaning: 'something hidden that you do not yet understand', emoji: '🔍' },
      { word: 'invisible', meaning: 'cannot be seen even though it is there', emoji: '👻' },
      { word: 'slipper', meaning: 'an elegant shoe, often used for dancing', emoji: '👠' },
      { word: 'underground', meaning: 'beneath the ground, hidden below', emoji: '🕳️' },
    ],
    miniGame: { type: 'match', prompt: 'Match each princess to her dancing prince!', pairs: [{ left: 'Princess Rose', right: 'Prince Dorian' }, { left: 'Princess Moon', right: 'Prince Silvain' }, { left: 'Princess Star', right: 'Prince Aurele' }, { left: 'Princess Violet', right: 'Prince Florian' }] },
    emotionalMoment: { feeling: 'mystery', prompt: 'Do you have a secret? How does it feel to keep one?' },
    rewardName: 'Crown of Mystery',
  },

  'rumpelstiltskin': {
    title: 'Rumpelstiltskin',
    summary: 'A mysterious little man helps a girl spin straw into gold — but at what price?',
    theme: 'promises and honesty',
    scenes: [
      { text: 'A miller wanted to impress the king and told a great lie: "My daughter can spin straw into gold!" The king locked the girl in a tower full of straw.' },
      { text: 'The girl was weeping when a strange little man appeared.', dialogue: { speaker: 'Rumpelstiltskin', line: 'What will you give me if I spin all this straw into gold for you?' } },
      { text: 'She gave him her necklace. The little man spun all the straw into gold. The king, astonished, put her in an even larger room.' },
      { text: 'On the third night the girl had nothing left to give. She promised her first child. The king married her and she became queen.' },
      { text: 'A year later the little man returned to claim the child. The queen pleaded with him. He gave her three days to guess his name.', dialogue: { speaker: 'Rumpelstiltskin', line: 'If you guess my name, you may keep the child!' } },
      { text: 'A messenger overheard the little man dancing and singing his name in the forest. He ran back to tell the queen.', dialogue: { speaker: 'Messenger', line: 'His name is Rumpelstiltskin! I heard him singing it!' } },
    ],
    vocabulary: [
      { word: 'straw', meaning: 'dry cereal stalks, yellow and light', emoji: '🌾' },
      { word: 'spin', meaning: 'to turn fibres into thread using a spinning wheel', emoji: '🧶' },
      { word: 'promise', meaning: 'what you say you will do and must keep', emoji: '🤝' },
      { word: 'riddle', meaning: 'a puzzle question with a hidden answer to find', emoji: '❓' },
    ],
    miniGame: { type: 'choice', prompt: 'How does the queen guess the imp\'s name?', options: ['A messenger heard him singing in the forest', 'She read it in a book', 'The imp told her himself'], answerIndex: 0 },
    emotionalMoment: { feeling: 'honesty', prompt: 'Is it important to keep your promises? Why?' },
    rewardName: 'Golden Thread',
  },

  'emperor-new-clothes': {
    title: 'The Emperor\'s New Clothes',
    summary: 'Two swindlers convince a vain emperor they are weaving him invisible clothes that only clever people can see.',
    theme: 'honesty and courage',
    scenes: [
      { text: 'Once upon a time there was an emperor who loved fine clothes above all else. He changed his outfit several times a day.' },
      { text: 'Two swindlers presented themselves as the finest weavers in the world. They claimed to weave a magical cloth: invisible to fools and incompetents.', dialogue: { speaker: 'Swindler', line: 'Only truly intelligent people can see these clothes!' } },
      { text: 'Ministers were sent to check on the work. They saw nothing at all, but dared not say so for fear of looking foolish.', dialogue: { speaker: 'Minister', line: 'It is magnificent... absolutely magnificent.' } },
      { text: 'The swindlers handed the emperor his imaginary new clothes. The emperor saw nothing either, but he pretended.' },
      { text: 'The emperor processed through the streets. Everyone cheered, afraid to seem foolish.' },
      { text: 'Suddenly a small child cried out the truth.', dialogue: { speaker: 'Child', line: 'But he has nothing on! The emperor is completely naked!' } },
    ],
    vocabulary: [
      { word: 'vain', meaning: 'someone who thinks too much about their looks and believes themselves beautiful', emoji: '🪞' },
      { word: 'swindler', meaning: 'someone who lies to steal from or deceive others', emoji: '🎭' },
      { word: 'invisible', meaning: 'impossible to see with your eyes', emoji: '👻' },
      { word: 'truth', meaning: 'what is really true, even if it is uncomfortable', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Who tells the truth first?', options: ['A small child', 'A minister', 'The emperor himself'], answerIndex: 0 },
    emotionalMoment: { feeling: 'courage', prompt: 'Have you ever had the courage to tell a difficult truth?' },
    rewardName: 'Courage of Truth',
  },

  'steadfast-tin-soldier': {
    title: 'The Steadfast Tin Soldier',
    summary: 'A brave little tin soldier lives a great adventure and proves that courage comes from the heart.',
    theme: 'courage and faithfulness',
    scenes: [
      { text: 'Among a box of tin soldiers, one had only a single leg. Yet he stood straight and proud like all the others.' },
      { text: 'On a shelf opposite, a little paper dancer held up one leg. The soldier thought she was like him, and he fell in love with her.', dialogue: { speaker: 'Soldier', line: 'She is so beautiful. I wish I could stay close to her for ever.' } },
      { text: 'A jealous goblin inside a box shouted that the soldier must not look at the dancer. The next day the soldier fell from a window.' },
      { text: 'In the street, children found him and put him in a paper boat. He sailed down the gutter in the rain, and was later swallowed by a large fish.' },
      { text: 'The fish was caught and brought to the kitchen. The cook cut it open and found the tin soldier unharmed, still standing straight.', dialogue: { speaker: 'Cook', line: 'How on earth did you survive all of that!' } },
      { text: 'The soldier was returned to the child. But the jealous goblin threw the soldier into the fire. The little dancer also fell in on a gust of wind. All that remained of the soldier was a tiny heart of metal, a symbol of his undying faithfulness.', dialogue: { speaker: 'Soldier', line: 'I stayed steadfast to the very end.' } },
    ],
    vocabulary: [
      { word: 'tin', meaning: 'a grey heavy metal once used for making toys', emoji: '⚙️' },
      { word: 'steadfast', meaning: 'brave and firm in the face of danger', emoji: '🛡️' },
      { word: 'torrent', meaning: 'a powerful, rushing stream of water', emoji: '🌊' },
      { word: 'faithfulness', meaning: 'staying loyal to someone you love, whatever happens', emoji: '💙' },
    ],
    miniGame: { type: 'choice', prompt: 'Who does the tin soldier fall in love with?', options: ['A little paper dancer', 'A princess in the castle', 'A magic fairy'], answerIndex: 0 },
    emotionalMoment: { feeling: 'faithfulness', prompt: 'Is there someone or something you are very faithful to? What does that mean to you?' },
    rewardName: 'Medal of Courage',
  },

  'la-fontaine-crow-fox': {
    title: 'The Crow and the Fox',
    summary: 'A very cunning fox flatters a crow to steal his cheese. A fable about vanity.',
    theme: 'cunning and humility',
    scenes: [
      { text: 'A crow was perched on a branch, holding a fine piece of fragrant cheese in his beak.' },
      { text: 'A very crafty fox came by and smelled the cheese. He decided to steal it through flattery.', dialogue: { speaker: 'Fox', line: 'O Master Crow, how handsome you are! What magnificent feathers you have!' } },
      { text: 'The crow, puffed up with pleasure at the compliments, ruffled his feathers proudly. The fox went on.', dialogue: { speaker: 'Fox', line: 'If your voice is as beautiful as your feathers, you are the king of birds!' } },
      { text: 'The crow, far too flattered, opened his beak wide to sing. The cheese fell.' },
      { text: 'The fox snatched the cheese up laughing and spoke the moral of the fable.', dialogue: { speaker: 'Fox', line: 'Every flatterer lives at the expense of those who listen to him. That lesson is well worth a cheese!' } },
    ],
    vocabulary: [
      { word: 'crow', meaning: 'a large black bird with a strong curved beak', emoji: '🐦‍⬛' },
      { word: 'flatterer', meaning: 'someone who pays too many compliments to get something', emoji: '😏' },
      { word: 'cheese', meaning: 'a food made from milk, often yellow or white', emoji: '🧀' },
      { word: 'moral', meaning: 'the lesson you learn at the end of a fable', emoji: '📜' },
    ],
    miniGame: { type: 'choice', prompt: 'How does the fox get the cheese?', options: ['By flattering the crow into opening his beak', 'By climbing the tree', 'By asking politely'], answerIndex: 0 },
    emotionalMoment: { feeling: 'humility', prompt: 'Have you ever been flattered into doing something silly? What did you learn?' },
    rewardName: 'Wisdom of the Fable',
  },
  'musicians-of-bremen': {
    title: 'The Bremen Town Musicians',
    summary: 'A donkey, dog, cat and rooster — too old for their masters — head to Bremen and discover that friendship is stronger than force.',
    theme: 'friendship and courage',
    scenes: [
      { text: 'An old donkey decided to head to Bremen to become a musician.' },
      { text: 'Along the way he met a dog, cat and rooster. Together they walked on.', dialogue: { speaker: 'Donkey', line: 'Come with me! In Bremen we will make music together!' } },
      { text: 'That night they found a house with robbers inside and climbed on each other outside the window.' },
      { text: 'They all sang at once. The terrified robbers fled into the forest.', dialogue: { speaker: 'Rooster', line: 'Our music chases the bad guys away!' } },
      { text: 'The four friends settled into the house, so happy together they never needed to go to Bremen.' },
    ],
    vocabulary: [
      { word: 'musician', meaning: 'someone who plays music', emoji: '🎵' },
      { word: 'robber', meaning: 'a thief who scares people', emoji: '😈' },
      { word: 'together', meaning: 'all with each other', emoji: '🤝' },
      { word: 'terrified', meaning: 'very, very frightened', emoji: '😱' },
    ],
    miniGame: { type: 'count', prompt: 'How many animals go to Bremen?', answer: 4, options: [3, 4, 5] },
    emotionalMoment: { feeling: 'friendship', prompt: 'When did friends help you be brave?' },
    rewardName: 'Bremen Trumpet',
  },
  'pied-piper': {
    title: 'The Pied Piper of Hamelin',
    summary: 'A magical piper promises to solve a rat problem and teaches everyone that promises must always be kept.',
    theme: 'honesty and promises',
    scenes: [
      { text: 'The town of Hamelin was overrun with rats.' },
      { text: 'A colourful piper promised to chase all the rats away for a reward.', dialogue: { speaker: 'Piper', line: 'I can chase your rats. But you must keep your promise to pay.' } },
      { text: 'He played a magic melody. All the rats followed him to the river and disappeared.' },
      { text: 'The townspeople refused to pay.', dialogue: { speaker: 'Mayor', line: 'We will not pay you. Go away!' } },
      { text: 'The children followed the music. That day the whole town learned that promises must be kept.' },
    ],
    vocabulary: [
      { word: 'flute', meaning: 'a wind instrument you blow', emoji: '🎵' },
      { word: 'promise', meaning: 'saying you will do something and really doing it', emoji: '🤝' },
      { word: 'melody', meaning: 'a sequence of notes that make music', emoji: '🎼' },
      { word: 'reward', meaning: 'something given in exchange for a service', emoji: '🏆' },
    ],
    miniGame: { type: 'choice', prompt: 'What happens when you break a promise?', options: ['Nothing', 'You lose the trust of others', 'Others are happy'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honest', prompt: 'Have you ever kept a hard promise? How did it feel?' },
    rewardName: 'Magic flute',
  },
  'little-match-girl': {
    title: 'The Little Match Girl',
    summary: 'On a cold night, a poor little girl lights matches that show her beautiful dreams of warmth and love.',
    theme: 'hope and kindness',
    scenes: [
      { text: 'On New Year\'s Eve in terrible cold, a little girl walked barefoot in the snow selling matches.' },
      { text: 'No one bought any. She huddled in a corner and lit a match to warm her fingers.', dialogue: { speaker: 'Little girl', line: 'Just one match for a little warmth...' } },
      { text: 'In the flame she saw a big warm stove, then a table full of food.' },
      { text: 'She lit another match and saw her kind grandmother smiling at her.', dialogue: { speaker: 'Grandmother', line: 'I am here, dear. Come with me to a warm place.' } },
      { text: 'The next morning passers-by found the little girl asleep with a peaceful smile on her face.' },
    ],
    vocabulary: [
      { word: 'match', meaning: 'a small stick that makes fire when struck', emoji: '🔥' },
      { word: 'peaceful', meaning: 'calm and serene, without fear', emoji: '😌' },
      { word: 'hope', meaning: 'believing something good can happen', emoji: '🌟' },
      { word: 'huddle', meaning: 'curl up tightly to keep warm', emoji: '🤗' },
    ],
    miniGame: { type: 'choice', prompt: 'What does the girl see in her first match flame?', options: ['A big warm stove', 'Her grandmother', 'A Christmas tree'], answerIndex: 0 },
    emotionalMoment: { feeling: 'hope', prompt: 'What gives you hope when things are hard?' },
    rewardName: 'Light of Hope',
  },
  'princess-pea': {
    title: 'The Princess and the Pea',
    summary: 'A real princess is recognised by her great sensitivity — a fun fable about being yourself.',
    theme: 'being yourself',
    scenes: [
      { text: 'A prince was looking for a real princess to marry. But how do you know if she is real?' },
      { text: 'On a stormy night a soaking wet girl knocked and said she was a princess.', dialogue: { speaker: 'Girl', line: 'I am a real princess, I assure you!' } },
      { text: 'The queen had a clever idea. She placed a tiny pea under twenty mattresses.' },
      { text: 'The next morning they asked the girl how she had slept.', dialogue: { speaker: 'Girl', line: 'Terribly! I felt something hard all night. I am covered in bruises!' } },
      { text: 'Only a real princess could feel a pea through so many mattresses. The prince married her and they were very happy.' },
    ],
    vocabulary: [
      { word: 'princess', meaning: 'the daughter of a king or queen', emoji: '👸' },
      { word: 'mattress', meaning: 'the soft part of a bed you sleep on', emoji: '🛏️' },
      { word: 'sensitive', meaning: 'who feels things very strongly', emoji: '💝' },
      { word: 'storm', meaning: 'very bad weather with wind and rain', emoji: '⛈️' },
    ],
    miniGame: { type: 'count', prompt: 'How many mattresses did the queen stack?', answer: 20, options: [10, 15, 20] },
    emotionalMoment: { feeling: 'being yourself', prompt: 'What makes you unique?' },
    rewardName: 'Crown of Sensitivity',
  },
  'wild-swans': {
    title: 'The Wild Swans',
    summary: 'A brave princess works in silence for years to break the spell that turned her eleven brothers into swans.',
    theme: 'quiet courage and love',
    scenes: [
      { text: 'Elise had eleven brothers turned into wild swans by a wicked stepmother\'s spell.' },
      { text: 'A fairy told her the secret: she had to knit eleven nettle coats without speaking a single word.', dialogue: { speaker: 'Fairy', line: 'One single word and your brothers stay swans forever.' } },
      { text: 'Elise knitted without stopping, even when her hands bled.' },
      { text: 'Years passed. Finally, she threw the coats over the swans.', dialogue: { speaker: 'Elise', line: 'My brothers! I waited so long for you!' } },
      { text: 'The swans became her brothers again. Elise could at last speak and tell them all her love.' },
    ],
    vocabulary: [
      { word: 'spell', meaning: 'a magic that transforms someone', emoji: '✨' },
      { word: 'nettle', meaning: 'a plant with stinging leaves', emoji: '🌿' },
      { word: 'knit', meaning: 'to make clothes with yarn and needles', emoji: '🧶' },
      { word: 'silence', meaning: 'not saying a single word', emoji: '🤫' },
    ],
    miniGame: { type: 'count', prompt: 'How many brothers does Elise need to save?', answer: 11, options: [7, 9, 11] },
    emotionalMoment: { feeling: 'determination', prompt: 'What would you do for someone you love?' },
    rewardName: 'Swan Feather',
  },
  'chevre-monsieur-seguin': {
    title: 'The Goat of Monsieur Seguin',
    summary: 'The little goat Blanquette wants freedom but discovers that true freedom comes with responsibility.',
    theme: 'freedom and caution',
    scenes: [
      { text: 'Monsieur Seguin had a beautiful white goat called Blanquette. But Blanquette wanted the freedom of the mountains.' },
      { text: 'Monsieur Seguin begged her to stay.', dialogue: { speaker: 'M. Seguin', line: 'Blanquette, stay! There is a big wolf in the mountains!' } },
      { text: 'Blanquette did not listen. She leapt over the fence and ran happily to the mountain meadows.' },
      { text: 'All day she frolicked, ate fine grass and breathed fresh air. But in the evening, the big wolf arrived.', dialogue: { speaker: 'Blanquette', line: 'I will fight until dawn! I will not give up!' } },
      { text: 'Blanquette fought bravely all night and learned that freedom also asks for caution.' },
    ],
    vocabulary: [
      { word: 'goat', meaning: 'a farm animal with horns that gives milk', emoji: '🐐' },
      { word: 'frolic', meaning: 'to jump and run freely in play', emoji: '🦘' },
      { word: 'dawn', meaning: 'the first moment of morning when the sun rises', emoji: '🌅' },
      { word: 'freedom', meaning: 'being able to do what you want', emoji: '🕊️' },
    ],
    miniGame: { type: 'choice', prompt: 'Why does Monsieur Seguin want to keep Blanquette?', options: ['For her milk', 'To protect her from the wolf', 'So he is not lonely'], answerIndex: 1 },
    emotionalMoment: { feeling: 'freedom and caution', prompt: 'How can you be free and safe at the same time?' },
    rewardName: 'Mountain Bell',
  },
  'sinbad': {
    title: 'Sinbad the Sailor',
    summary: 'The brave sailor Sinbad travels the seas of the world and always returns wiser than he left.',
    theme: 'courage and wisdom',
    scenes: [
      { text: 'Sinbad was a rich merchant from Baghdad who loved adventures. He made seven great voyages.' },
      { text: 'On his first voyage his ship ran aground on what seemed like an island — but it was a sleeping giant fish!', dialogue: { speaker: 'Sinbad', line: 'This is no island... it is a living creature! Flee!' } },
      { text: 'On every voyage Sinbad faced new dangers. He overcame them all with his wits.' },
      { text: 'He always brought back treasures, but above all stories and wisdom.', dialogue: { speaker: 'Sinbad', line: 'True riches are not jewels but what you learn on the journey.' } },
      { text: 'Every voyage taught him something new about the world and about himself.' },
    ],
    vocabulary: [
      { word: 'sailor', meaning: 'someone who travels and works on the sea', emoji: '⚓' },
      { word: 'run aground', meaning: 'when a ship stops on the seabed or a beach', emoji: '🏖️' },
      { word: 'danger', meaning: 'a great threat', emoji: '⚠️' },
      { word: 'wisdom', meaning: 'knowledge gained through experience', emoji: '🦉' },
    ],
    miniGame: { type: 'count', prompt: 'How many great voyages did Sinbad make?', answer: 7, options: [5, 7, 9] },
    emotionalMoment: { feeling: 'adventure and wisdom', prompt: 'What did you learn during a trip or new experience?' },
    rewardName: 'Voyager\'s Compass',
  },
  'tinder-box': {
    title: 'The Tinderbox',
    summary: 'A soldier finds a magic tinderbox and learns that a generous heart is the real magic.',
    theme: 'generosity and friendship',
    scenes: [
      { text: 'A soldier returning from war met an old witch who offered him a deal: fetch a tinderbox from a hollow tree.' },
      { text: 'Inside the tree he found three enormous dogs guarding chests full of gold coins.', dialogue: { speaker: 'Soldier', line: 'They obey me as long as I have the tinderbox!' } },
      { text: 'He became rich and generous — he gave food to everyone in need.' },
      { text: 'With the tinderbox the dogs appeared and granted his wishes, but he always asked for kind things.', dialogue: { speaker: 'Soldier', line: 'Bring food for the whole village!' } },
      { text: 'Through his kindness the soldier won the love of everyone. The real magic was a generous heart.' },
    ],
    vocabulary: [
      { word: 'tinderbox', meaning: 'a small object that makes fire', emoji: '🔥' },
      { word: 'generous', meaning: 'happy to give and share with others', emoji: '🎁' },
      { word: 'witch', meaning: 'a person who does magic', emoji: '🧙' },
      { word: 'chest', meaning: 'a large strong box for treasure', emoji: '📦' },
    ],
    miniGame: { type: 'count', prompt: 'How many magic dogs guard the treasures?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'generosity', prompt: 'Have you ever shared something you loved? How did it feel?' },
    rewardName: 'Tinderbox of Kindness',
  },
  'blue-bird': {
    title: 'The Blue Bird',
    summary: 'Two children search the world for the Blue Bird of Happiness and discover that happiness is often close to home.',
    theme: 'happiness and gratitude',
    scenes: [
      { text: 'Tyltyl and Mytyl, two poor but cheerful children, lived with their parents in a small house at the edge of the forest.' },
      { text: 'The fairy Berylune appeared and asked them to find the Blue Bird of Happiness for her sick granddaughter.', dialogue: { speaker: 'Fairy Berylune', line: 'Go and find the Blue Bird! It is somewhere in the world.' } },
      { text: 'The children travelled far and wide. Everywhere the blue birds they found died or changed colour.' },
      { text: 'Disappointed, they returned home.', dialogue: { speaker: 'Tyltyl', line: 'We searched everywhere... does the Blue Bird even exist?' } },
      { text: 'Back home, Tyltyl noticed that his dove — which he had always had — had beautiful blue feathers. Happiness was there all along.' },
    ],
    vocabulary: [
      { word: 'happiness', meaning: 'a feeling of deep joy and satisfaction', emoji: '😊' },
      { word: 'gratitude', meaning: 'being thankful and content for what you have', emoji: '🙏' },
      { word: 'memory', meaning: 'an image or feeling kept in your mind', emoji: '💭' },
      { word: 'disappointed', meaning: 'sad because something did not work out', emoji: '😔' },
    ],
    miniGame: { type: 'choice', prompt: 'Where does Tyltyl finally find the Blue Bird?', options: ['In a distant castle', 'In his own home', 'At the bottom of the sea'], answerIndex: 1 },
    emotionalMoment: { feeling: 'gratitude', prompt: 'What beautiful things do you already have that make you happy?' },
    rewardName: 'Feather of Happiness',
  },
  'renart-goupil': {
    title: 'Reynard the Fox',
    summary: 'The cunning fox Reynard uses his intelligence in every situation — and learns that even the cleverest can be outsmarted.',
    theme: 'intelligence and humility',
    scenes: [
      { text: 'In the great forest of the Middle Ages lived Reynard the Fox, the cleverest of all animals.' },
      { text: 'One day Reynard stole a chicken from Chanticleer the rooster. But Chanticleer had a plan.', dialogue: { speaker: 'Chanticleer', line: 'Reynard, you are so handsome! Show me how you sing when you are proud!' } },
      { text: 'Reynard, flattered, opened his mouth to sing — and the chicken escaped!' },
      { text: 'He tried to steal the cheese from Isengrim the wolf. This time the wolf was one step ahead.', dialogue: { speaker: 'Isengrim', line: 'You are not the only one who can be clever, Reynard!' } },
      { text: 'Reynard learned that even the cleverest fox can be caught. Honesty is sometimes better than trickery.' },
    ],
    vocabulary: [
      { word: 'cunning', meaning: 'very good at tricking others', emoji: '🦊' },
      { word: 'flattered', meaning: 'pleased by too many compliments', emoji: '😏' },
      { word: 'honest', meaning: 'who tells the truth and does not cheat', emoji: '✅' },
      { word: 'outsmart', meaning: 'to be cleverer than someone else', emoji: '🎭' },
    ],
    miniGame: { type: 'choice', prompt: 'How does Chanticleer get his chicken back?', options: ['By running faster', 'By flattering Reynard into opening his mouth', 'By calling other animals'], answerIndex: 1 },
    emotionalMoment: { feeling: 'humility', prompt: 'Have you ever learned something important from making a mistake?' },
    rewardName: 'Fox\'s Tail',
  },
};
