// Dutch translations for all 19 fairy tales.
// Only content fields are translated — id, emoji, coverImage, palette,
// difficulty, ageMin, ageMax, rewardEmoji are intentionally omitted.

export const CONTES_NL = {
  'snow-white': {
    title: 'Sneeuwwitje',
    summary: 'Een lief prinsesje met een huid zo wit als sneeuw vindt een thuis bij zeven vriendelijke kleine helpers en leert dat echte vrienden voor elkaar zorgen.',
    theme: 'vriendelijkheid en vriendschap',
    scenes: [
      { text: 'Lang geleden werd er een prinsesje geboren met een huid zo wit als sneeuw. Iedereen noemde haar Sneeuwwitje.' },
      { text: 'Een jaloerse koningin bezat een magische spiegel en stelde hem elke dag dezelfde vraag.', dialogue: { speaker: 'Koningin', line: 'Spiegel, spiegel, wie is de liefste en de mooiste van allemaal?' } },
      { text: 'Sneeuwwitje liep diep het bos in. Zeven kleine, vriendelijke mijnwerkers verwelkomden haar in hun gezellige huisje.', dialogue: { speaker: 'Een mijnwerker', line: 'Je bent hier veilig, kleine vriendin. Kom uitrusten.' } },
      { text: 'De koningin bedroog haar met een glanzende appel, en Sneeuwwitje viel in een heel, heel diepe slaap.' },
      { text: 'Een zorgzame vriendin wekte haar heel zachtjes. Sneeuwwitje glimlachte, en iedereen vierde haar dappere vriendin.', dialogue: { speaker: 'Sneeuwwitje', line: 'Jullie hebben me nooit verlaten. Dank jullie wel, vrienden!' } },
    ],
    vocabulary: [
      { word: 'de mooiste', meaning: 'de liefste en de knapste persoon', emoji: '🌷' },
      { word: 'jaloers', meaning: 'boos omdat je wil wat een ander heeft', emoji: '😠' },
      { word: 'huisje', meaning: 'een klein, knus huisje', emoji: '🏡' },
      { word: 'verwelkomen', meaning: 'iemand blij maken dat hij er is', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel vriendelijke kleine mijnwerkers verwelkomden Sneeuwwitje?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'omringd en beschermd', prompt: 'De vrienden van Sneeuwwitje pasten op haar. Wie past er op jou?' },
    rewardName: 'Vriendelijke spiegel',
  },

  'cinderella': {
    title: 'Assepoester',
    summary: 'Een hardwerkend meisje met een groot hart krijgt wat hulp van een magische vriendin en ontdekt dat vriendelijk zijn zelf een soort magie is.',
    theme: 'hoop en vriendelijkheid',
    scenes: [
      { text: 'Assepoester deed alle klusjes en verloor nooit haar lieve glimlach, ook niet als anderen gemeen waren.' },
      { text: 'Op een avond werd er een groot bal aangekondigd, maar Assepoester had niets om aan te trekken.', dialogue: { speaker: 'Assepoester', line: 'Was ik maar een keertje mee kunnen dansen.' } },
      { text: 'Een vriendelijke fee verscheen en veranderde met een zwaai van haar toverstaf een pompoen in een koets.', dialogue: { speaker: 'Vriendin-fee', line: 'Wees terug voor middernacht, lieverd — dan stopt de magie.' } },
      { text: 'Op het bal danste en lachte Assepoester. Maar toen de klok begon te slaan, moest ze rennen.' },
      { text: 'Het muiltje paste haar precies. Haar vriendelijkheid was altijd zichtbaar geweest, en vreugde vulde haar dagen.', dialogue: { speaker: 'Assepoester', line: 'Vriendelijk zijn kost niets.' } },
    ],
    vocabulary: [
      { word: 'klusjes', meaning: 'kleine taakjes om thuis te helpen', emoji: '🧹' },
      { word: 'koets', meaning: 'een wagen die getrokken wordt om mensen te vervoeren', emoji: '🛞' },
      { word: 'middernacht', meaning: 'twaalf uur s nachts', emoji: '🕛' },
      { word: 'lief', meaning: 'teder, rustig en vriendelijk', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'Hoe laat moet Assepoester terug zijn? Tel de slagen van de klok!', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'vol hoop', prompt: 'Zelfs op moeilijke dagen bleef Assepoester vriendelijk. Wat helpt jou om hoopvol te blijven?' },
    rewardName: 'Glazen muiltje',
  },

  'little-red-riding-hood': {
    title: 'Roodkapje',
    summary: 'Een dapper meisje met een rood kapje gaat naar haar oma en leert onderweg naar haar wijze gevoel te luisteren.',
    theme: 'luisteren en veilig blijven',
    scenes: [
      { text: 'Een klein meisje droeg overal een felrood kapje; daarom noemde iedereen haar Roodkapje.' },
      { text: 'Haar mama gaf haar een mand met brood voor oma.', dialogue: { speaker: 'Mama', line: 'Blijf op het pad en alles komt goed.' } },
      { text: 'In het bos stelde een slimme wolf veel vragen. Roodkapje voelde dat er iets vreemds was en liep gewoon door.', dialogue: { speaker: 'Roodkapje', line: 'Ik hoef jou geen antwoord te geven. Ik zeg het aan een volwassene.' } },
      { text: 'Een vriendelijke houthakker hoorde haar en liep met haar mee. Samen kwamen ze bij oma aan.' },
      { text: 'Oma was veilig, en Roodkapje ook. Ze deelden lekker warm brood en lachten de hele middag.', dialogue: { speaker: 'Oma', line: 'Je hebt naar je verstandige gevoel geluisterd. Ik ben trots op jou.' } },
    ],
    vocabulary: [
      { word: 'pad', meaning: 'een weg die laat zien waar je veilig kunt lopen', emoji: '🛤️' },
      { word: 'mand', meaning: 'een drager met een hengsel om dingen in te vervoeren', emoji: '🧺' },
      { word: 'slim', meaning: 'iemand die trucjes gebruikt om je te bedriegen', emoji: '🦊' },
      { word: 'houthakker', meaning: 'iemand die tussen de bomen werkt', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'Een vreemde vraagt Roodkapje waar ze naartoe gaat. Wat is de veilige keuze?', options: ['Alles vertellen', 'Doorlopen en een volwassene waarschuwen', 'Hem volgen het bos in'], answerIndex: 1 },
    emotionalMoment: { feeling: 'veilig', prompt: 'Roodkapje luisterde naar haar rare gevoel. Wanneer hielp een gevoel jou veilig te blijven?' },
    rewardName: 'Rood kapje',
  },

  'hansel-and-gretel': {
    title: 'Hans en Grietje',
    summary: 'Een broer en zus raken verdwaald in het bos en gebruiken een slim plan en teamwork om veilig thuis te komen.',
    theme: 'slimheid en samen blijven',
    scenes: [
      { text: 'Hans en Grietje liepen het grote bos in, hand in hand om niet te verdwalen.' },
      { text: 'De slimme Hans liet kleine, glanzende witte steentjes vallen, een voor een, om de weg terug te markeren.', dialogue: { speaker: 'Hans', line: 'Deze steentjes zullen schitteren en ons naar huis brengen.' } },
      { text: 'Ze vonden een klein huisje van snoep, maar een slimme oude vrouw woonde er.' },
      { text: 'De kinderen waren te slim om zich te laten bedriegen. Ze pakten elkaars hand en sloopen naar buiten.', dialogue: { speaker: 'Grietje', line: 'Snel — samen zijn we moediger dan alleen.' } },
      { text: 'De glanzende steentjes glinsterden in het maanlicht en brachten hen recht naar huis, naar een warme knuffel.' },
    ],
    vocabulary: [
      { word: 'steentjes', meaning: 'kleine, gladde kiezels', emoji: '🪨' },
      { word: 'slim', meaning: 'goed in het bedenken van slimme ideeen', emoji: '💡' },
      { word: 'op je tenen', meaning: 'heel zachtjes lopen op je tenen', emoji: '🦶' },
      { word: 'samen', meaning: 'met elkaar, zij aan zij', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet het slimme plan van Hans in de goede volgorde!', steps: ['De glanzende steentjes laten vallen', 'Het schitterende spoor volgen', 'De weg naar huis terugvinden'] },
    emotionalMoment: { feeling: 'samen dapper', prompt: 'De kinderen waren moediger als team. Wie maakt jou moediger?' },
    rewardName: 'Glanzend steentje',
  },

  'rapunzel': {
    title: 'Rapunzel',
    summary: 'Een lief meisje met heel lang haar woont in een hoge toren en leert dat geduld en een hart vol hoop elke deur kunnen openen.',
    theme: 'geduld en hoop',
    scenes: [
      { text: 'Helemaal bovenin een hoge toren woonde Rapunzel, een meisje met de langste gouden vlecht ter wereld.' },
      { text: 'Elke dag zong Rapunzel voor de vogels. Haar zachte lied zweefde door het hele bos.', dialogue: { speaker: 'Rapunzel', line: 'Op een dag zal ik de wereld daarbineden zien, onder de bomen.' } },
      { text: 'Een vriendelijke reiziger hoorde haar lied en riep: "Jouw muziek laat het bos glimlachen!"', dialogue: { speaker: 'Reiziger', line: 'Jouw muziek laat het hele bos glimlachen!' } },
      { text: 'Ze werden vrienden. Dag na dag bedachten ze geduldig een slimme manier om naar beneden te komen.' },
      { text: 'Eindelijk zette Rapunzel haar voet op het zachte gras en draaide rond in de zon, vrij en blij.', dialogue: { speaker: 'Rapunzel', line: 'Wachten was moeilijk, maar hoop hield me sterk.' } },
    ],
    vocabulary: [
      { word: 'toren', meaning: 'een heel hoog en smal gebouw', emoji: '🗼' },
      { word: 'vlecht', meaning: 'haar dat gevlochten is tot een lange touwachtige streng', emoji: '💇' },
      { word: 'geduld', meaning: 'rustig wachten zonder op te geven', emoji: '⏳' },
      { word: 'weide', meaning: 'een veld met gras vol bloemen', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Zoek wat Rapunzel gebruikte om veilig naar beneden te komen.', target: 'de gouden gevlochten ladder', decoys: ['een papieren vlieger', 'een houten lepel', 'een klein kopje'] },
    emotionalMoment: { feeling: 'geduldig', prompt: 'Rapunzel wachtte met hoop. Op welk mooi ding heb jij lang gewacht?' },
    rewardName: 'Gouden vlecht',
  },

  'the-ugly-duckling': {
    title: 'Het Lelijke Eendje',
    summary: 'Een klein vogeltje dat zich anders voelt dan de anderen groeit op en ontdekt dat het al die tijd prachtig was, precies zoals het was.',
    theme: 'erbij horen en van jezelf houden',
    scenes: [
      { text: 'In een zonnige vijver leek een klein vogeltje niet op zijn broers en zussen.' },
      { text: 'De andere vogels lachten hem uit, en diep vanbinnen voelde hij zich eenzaam en heel verdrietig.', dialogue: { speaker: 'Klein vogeltje', line: 'Ik wou dat iemand mij ook liet meedoen.' } },
      { text: 'Een vriendelijke kikker sprong dichterbij en ging naast hem zitten. "Jij bent bij mij welkom", zei ze.', dialogue: { speaker: 'Kikker', line: 'Jij bent bij mij welkom, mijn vriend.' } },
      { text: 'De seizoenen gingen voorbij. Op een heldere ochtend zag het kleine vogeltje zijn gezicht in het stille water.' },
      { text: 'Het was een prachtige zwaan geworden! Het was altijd al bijzonder geweest: gewoon zichzelf.', dialogue: { speaker: 'Zwaan', line: 'Ik hoefde niet te veranderen. Ik moest alleen groeien.' } },
    ],
    vocabulary: [
      { word: 'vijver', meaning: 'een kleine plas rustig water', emoji: '💧' },
      { word: 'eenzaam', meaning: 'verdrietig omdat je je helemaal alleen voelt', emoji: '🥺' },
      { word: 'spiegeling', meaning: 'het beeld dat je ziet in stil water', emoji: '🪞' },
      { word: 'zwaan', meaning: 'een grote, witte, sierlijke watervogel', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'Een nieuwe vriend voelt zich buitengesloten. Wat is iets liefs om te zeggen?', options: ['Je hoort hier niet thuis', 'Je mag met ons meedoen!', 'Ga weg'], answerIndex: 1 },
    emotionalMoment: { feeling: 'ik hoor erbij', prompt: 'Het kleine vogeltje was bijzonder zoals het was. Wat maakt jou een geweldige jij?' },
    rewardName: 'Zacht zwaan',
  },

  'the-little-mermaid': {
    title: 'De Kleine Zeemeermin',
    summary: 'Een nieuwsgierige jonge zeemeermin heeft de moed om een nieuwe wereld te verkennen en leert dat een lief en grootmoedig hart meer straalt dan alles.',
    theme: 'moed en een goed hart',
    scenes: [
      { text: 'Diep onder de golven woonde een jonge zeemeermin, de kleinste van zes zusjes.' },
      { text: 'Ze hield ervan om naar de oppervlakte te zwemmen en de lichte wereld boven het water te bekijken.', dialogue: { speaker: 'Zeemeermin', line: 'De wereld daarboven zit vol dingen die ik wil leren!' } },
      { text: 'Op een stormachtige nacht hielp ze met moed een zeeman veilig naar de kust.' },
      { text: 'Ze bleef niet om bedankt te worden. Iemand helpen vulde haar hart met warmte.', dialogue: { speaker: 'Zeemeermin', line: 'Ik hielp uit vriendelijkheid, niet voor een bedankje.' } },
      { text: 'Thuis vertelde ze haar dappere verhaal, en haar goede hart liet de hele zee stralen.' },
    ],
    vocabulary: [
      { word: 'zeemeermin', meaning: 'een denkbeeldig meisje van de zee, met een vissenstaart', emoji: '🧜' },
      { word: 'golven', meaning: 'water dat op en neer beweegt op de zee', emoji: '🌊' },
      { word: 'moedig', meaning: 'iets moeilijks doen ook al ben je bang', emoji: '💪' },
      { word: 'grootmoedig', meaning: 'blij om te geven en anderen te helpen', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel grote zusjes had de Kleine Zeemeermin?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'een groot hart', prompt: 'De zeemeermin hielp puur uit vriendelijkheid. Wanneer hielp jij zonder dat iemand het vroeg?' },
    rewardName: 'Zeeparel',
  },

  'the-snow-queen': {
    title: 'De Sneeuwkoningin',
    summary: 'Als het hart van haar beste vriend koud wordt, reist een trouw meisje genaamd Gerda ver door de sneeuw om hem met liefde te verwarmen.',
    theme: 'trouwe vriendschap',
    scenes: [
      { text: 'Gerda en Kai waren de beste vrienden en verbouwden samen rozen bij hun raam.' },
      { text: 'Een heel klein ijssplintje raakte het hart van Kai, en hij werd koud en afstandelijk.', dialogue: { speaker: 'Gerda', line: 'Wacht... waar ga je naartoe, Kai?' } },
      { text: 'De dappere Gerda gaf niet op. Ze vertrok door de sneeuw om haar vriend te zoeken.', dialogue: { speaker: 'Gerda', line: 'Ik vind je terug, Kai. Vrienden geven niet op.' } },
      { text: 'Ze vond Kai in een ijspaleis, roerloos en koud als steen.' },
      { text: 'Gerda omhelsde hem en warme tranen stroomden. Het ijs smolt, en Kai glimlachte en herinnerde zich alles.', dialogue: { speaker: 'Kai', line: 'Je bent helemaal hierheen voor mij gekomen. Dank je, Gerda.' } },
    ],
    vocabulary: [
      { word: 'rijp', meaning: 'een dunne laag ijs die vormt als het heel erg koud is', emoji: '🌨️' },
      { word: 'trouw', meaning: 'er altijd zijn voor je vrienden', emoji: '🤲' },
      { word: 'paleis', meaning: 'een heel groot en prachtig huis', emoji: '🏰' },
      { word: 'smelten', meaning: 'van ijs naar water gaan door warmte', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'Hoe liet Gerda het ijs in Kais hart smelten?', options: ['Met een groot vuur', 'Met warme tranen en een knuffel', 'Met een hamer'], answerIndex: 1 },
    emotionalMoment: { feeling: 'trouw', prompt: 'Gerda gaf haar vriend nooit op. Hoe laat jij een vriend zien dat je om hem geeft?' },
    rewardName: 'Warme roos',
  },

  'puss-in-boots': {
    title: 'De Gelaarsde Kat',
    summary: 'Een slimme kat met mooie laarzen gebruikt zijn vindingrijkheid en trouwe hart om zijn vriendelijke vriend te helpen het geluk te vinden.',
    theme: 'slimheid en loyaliteit',
    scenes: [
      { text: 'Een slimme kat trok mooie laarzen aan en een hoed met een veer, klaar voor het avontuur.' },
      { text: 'Zijn vriend was arm maar lief, dus de kat bedacht een slim plan om hem te helpen.', dialogue: { speaker: 'De Kat', line: 'Vertrouw me, mijn vriend. Er komt een slim idee!' } },
      { text: 'De kat begroette de koning beleefd en bood cadeaus aan, waardoor iedereen glimlachte.' },
      { text: 'Met vindingrijkheid in plaats van trucjes hielp de kat zijn vriend een groot kasteel aan de rivier te winnen.', dialogue: { speaker: 'De Kat', line: 'Goede ideeen openen meer deuren dan hard gebrul.' } },
      { text: 'Zijn vriend was eindelijk gelukkig, en de kat kroelde op bij het vuur, de trouwste kat van allemaal.' },
    ],
    vocabulary: [
      { word: 'slim', meaning: 'goed in het bedenken van slimme ideeen', emoji: '🧠' },
      { word: 'laarzen', meaning: 'schoenen die hoog op de benen reiken', emoji: '🥾' },
      { word: 'beleefd', meaning: 'vriendelijk en zacht met je woorden', emoji: '🙏' },
      { word: 'trouw', meaning: 'er altijd zijn voor je vrienden', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet het slimme plan van de Kat in de goede volgorde!', steps: ['De mooie laarzen aantrekken', 'De koning beleefd begroeten', 'Zijn vriend helpen de dag te winnen'] },
    emotionalMoment: { feeling: 'behulpzaam', prompt: 'De Kat gebruikte slimme ideeen om een vriend te helpen. Op welke slimme manier heb jij al eens iemand geholpen?' },
    rewardName: 'Mooie laarzen',
  },

  'pinocchio': {
    title: 'Pinokkio',
    summary: 'Een houten poppetje dat droomt van een echt jongetje te zijn, leert dat de waarheid spreken is wat een goed hart doet groeien.',
    theme: 'eerlijkheid',
    scenes: [
      { text: 'Er was eens een klein houten poppetje dat Pinokkio heette en dat droomde van een echt jongetje te worden.' },
      { text: 'Elke keer als Pinokkio een leugen vertelde, groeide zijn neus uit als een tak.', dialogue: { speaker: 'Pinokkio', line: 'Dat was ik niet! Echt waar!' } },
      { text: 'Zijn vriend het krekel probeerde hem te leren altijd de waarheid te vertellen.', dialogue: { speaker: 'Krekel', line: 'De waarheid vertellen maakt je licht als een veertje.' } },
      { text: 'Pinokkio maakte een grote fout en raakte verdwaald. Toen leerde hij dat eerlijkheid zijn enige gids was.' },
      { text: 'Toen Pinokkio eindelijk de waarheid zei, groeide zijn hart, en zijn liefste wens ging in vervulling.', dialogue: { speaker: 'Pinokkio', line: 'De waarheid is de krachtigste magie van allemaal.' } },
    ],
    vocabulary: [
      { word: 'poppetje', meaning: 'een pop die beweegt', emoji: '🎭' },
      { word: 'waarheid', meaning: 'precies vertellen wat er is gebeurd', emoji: '✅' },
      { word: 'leugen', meaning: 'iets zeggen dat niet waar is', emoji: '❌' },
      { word: 'eerlijk', meaning: 'iemand die altijd de waarheid zegt', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'Wanneer wordt de neus van Pinokkio langer?', options: ['Als hij de waarheid zegt', 'Als hij een leugen vertelt', 'Als hij een liedje zingt'], answerIndex: 1 },
    emotionalMoment: { feeling: 'eerlijk', prompt: 'De waarheid zeggen maakte Pinokkio licht. Hoe voel jij je als je de waarheid vertelt?' },
    rewardName: 'Krekel van de waarheid',
  },

  'peter-pan': {
    title: 'Peter Pan',
    summary: 'Een jongen die nooit opgroeit neemt nieuwe vrienden mee op een vliegavontuur waarbij blije gedachten en een beetje moed je overal brengen.',
    theme: 'verbeelding en moed',
    scenes: [
      { text: 'In een kamer vol sterren leerde een jongen genaamd Peter Pan de kinderen vliegen.' },
      { text: 'Peter vertelde Wendy het geheim: je moest aan iets heel gelukkigs denken.', dialogue: { speaker: 'Peter Pan', line: 'Denk aan je gelukkigste ding — en hop, je vliegt!' } },
      { text: 'Samen vlogen ze naar Nooitgedachtland, een magisch eiland vol avonturen.' },
      { text: 'Zelfs tegenover de boze kapitein was Peter niet bang. Hij stond het gevaar met een grote glimlach te woord.', dialogue: { speaker: 'Peter Pan', line: 'Dapper zijn is toch proberen.' } },
      { text: 'De kinderen gingen naar huis met herinneringen in hun hart en een vleugje magie voor altijd.' },
    ],
    vocabulary: [
      { word: 'slaapkamer', meaning: 'de kamer waar je slaapt en droomt', emoji: '🛏️' },
      { word: 'schaduw', meaning: 'de donkere vorm die jouw lichaam op de grond maakt', emoji: '👤' },
      { word: 'verbeelden', meaning: 'mooie dingen bedenken in je hoofd', emoji: '💭' },
      { word: 'moed', meaning: 'toch proberen ook al ben je bang', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Wat hielp de kinderen vliegen?', options: ['Blije gedachten en feestenstuif', 'Zware laarzen', 'Heel hard schreeuwen'], answerIndex: 0 },
    emotionalMoment: { feeling: 'moedig', prompt: 'Peter zegt dat dapper zijn toch proberen is. Wat moedigs zou jij graag willen proberen?' },
    rewardName: 'Feenstof',
  },

  'alice-in-wonderland': {
    title: 'Alice in Wonderland',
    summary: 'Een nieuwsgierig meisje volgt een haastig konijn een ondersteboven wereld in en leert dat vragen stellen een soort magie is.',
    theme: 'nieuwsgierigheid',
    scenes: [
      { text: 'Alice zag een haastig wit konijn in een hol springen en volgde het uit pure nieuwsgierigheid.' },
      { text: 'Ze viel in een lange magische gang en vond een heel kleine deur naar een tuin.', dialogue: { speaker: 'Alice', line: 'Wat raar! Ik vraag me af wat hier aan de hand is.' } },
      { text: 'Alice dronk een klein flesje en werd kleiner, daarna at ze een koekje en werd heel snel groter.', dialogue: { speaker: 'Alice', line: 'Vragen zijn de sleutel tot alle wonderen!' } },
      { text: 'Ze ontmoette een glimlachende kat, een boze koningin en een gekke hoedenmaker.' },
      { text: 'Alice werd wakker en glimlachte. Vragen stellen had haar naar de mooiste droom geleid.', dialogue: { speaker: 'Alice', line: 'Nieuwsgierigheid is het grootste avontuur.' } },
    ],
    vocabulary: [
      { word: 'nieuwsgierig', meaning: 'iemand die graag nieuwe dingen ontdekt', emoji: '🔍' },
      { word: 'hol', meaning: 'een tunnel gegraven in de grond door een dier', emoji: '🕳️' },
      { word: 'krimpen', meaning: 'kleiner worden', emoji: '🔻' },
      { word: 'wonder', meaning: 'iets ongelooflijks en heel verrassends', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet het avontuur van Alice in de goede volgorde!', steps: ['Het flesje drinken en krimpen', 'Het koekje eten en groeien', 'De kleine tuindeur vinden'] },
    emotionalMoment: { feeling: 'nieuwsgierig', prompt: 'Alice hield van vragen stellen. Waar ben jij vandaag nieuwsgierig naar?' },
    rewardName: 'Nieuwsgierig klokje',
  },

  'the-wizard-of-oz': {
    title: 'De Tovenaar van Oz',
    summary: 'Een meisje en drie nieuwe vrienden volgen een gouden weg en ontdekken dat de gaven die ze zochten al die tijd al in henzelf zaten.',
    theme: 'je hebt al wat je nodig hebt',
    scenes: [
      { text: 'Een grote wervelwind nam Dorothee en haar kleine hond Toto mee naar het magische land Oz.' },
      { text: 'Op de gouden weg ontmoette Dorothee een vogelverschrikker, een man van blik en een leeuw.', dialogue: { speaker: 'Vogelverschrikker', line: 'Ik wil gewoon een slim brein!' } },
      { text: 'Samen liepen ze naar de Smaragdstad om de grote Tovenaar te vinden.', dialogue: { speaker: 'Dorothee', line: 'Als we samen zijn, kunnen we alles.' } },
      { text: 'De Tovenaar onthulde hun een groot geheim: ze hadden al die tijd al alles wat ze begeerden.' },
      { text: 'Dorothee tikte drie keer met haar schoentjes en was weer thuis. Iedereen had zijn gave gevonden.', dialogue: { speaker: 'Dorothee', line: 'Er is geen plek zoals thuis.' } },
    ],
    vocabulary: [
      { word: 'wervelwind', meaning: 'een heel sterke wind die in het rond draait', emoji: '🌪️' },
      { word: 'vogelverschrikker', meaning: 'een grote stropen pop om vogels te verjagen', emoji: '🌾' },
      { word: 'moed', meaning: 'doorgaan ook al ben je bang', emoji: '💪' },
      { word: 'reis', meaning: 'een lange wandeling of avontuur naar een nieuwe plek', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Welke vriend had van het begin af aan al moed?', options: ['De vogelverschrikker', 'De blikken man', 'De leeuw'], answerIndex: 2 },
    emotionalMoment: { feeling: 'bekwaam', prompt: 'De vrienden hadden hun gaven al in henzelf. Welke gave heb jij al in jezelf?' },
    rewardName: 'Schitterende schoentjes',
  },

  'robin-hood': {
    title: 'Robin Hood',
    summary: 'Een vriendelijke boogschutter uit het groene bos deelt met mensen die weinig hebben en leert zijn vrienden dat rechtvaardigheid iedereen gelukkiger maakt.',
    theme: 'rechtvaardigheid en vrijgevigheid',
    scenes: [
      { text: 'In een groot groen bos woonde Robin Hood, de beste boogschutter van het land.' },
      { text: 'Hij zag dat veel mensen erg arm waren terwijl anderen alles hadden.', dialogue: { speaker: 'Robin', line: 'Delen is het mooiste cadeau.' } },
      { text: 'Samen met zijn vrolijke vrienden bedacht Robin een plan om mensen in nood te helpen.', dialogue: { speaker: 'Kleine Jan', line: 'Samen zijn we de kracht van het bos!' } },
      { text: 'Robin deelde wat mensen nodig hadden, en overal verschenen glimlachen.' },
      { text: 'Het bos gonste van geluk. Robin had geleerd dat vrijgevigheid de echte overwinning is.', dialogue: { speaker: 'Robin', line: 'Vrijgevigheid maakt iedereen rijker.' } },
    ],
    vocabulary: [
      { word: 'boogschutter', meaning: 'iemand die pijlen schiet met een boog', emoji: '🎯' },
      { word: 'bos', meaning: 'een grote plek vol bomen en dieren', emoji: '🌳' },
      { word: 'rechtvaardig', meaning: 'iedereen op dezelfde manier behandelen', emoji: '⚖️' },
      { word: 'vrijgevig', meaning: 'graag geven en delen', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin Hood deelde met mensen die...', options: ['honger hadden en in nood waren', 'al heel rijk waren', 'gemeen waren voor anderen'], answerIndex: 0 },
    emotionalMoment: { feeling: 'rechtvaardig', prompt: 'Robin hield van delen. Wat zou jij kunnen delen om een vriend te laten glimlachen?' },
    rewardName: 'Vriendschapsboog',
  },

  'goldilocks': {
    title: 'Goudlokje',
    summary: 'Een nieuwsgierig meisje gaat het gezellige berenhuisje binnen en leert dat het beter is eerst te vragen en goed te zorgen voor andermans spullen.',
    theme: 'respect voor anderen',
    scenes: [
      { text: 'Een meisje met gouden krullen wandelde door het bos en vond een lief huisje.' },
      { text: 'Ze ging naar binnen en proefde drie kommetjes pap. Die van het kleine beertje was precies goed.', dialogue: { speaker: 'Goudlokje', line: 'Oh! Dit kommetje is perfect, niet te warm en niet te koud!' } },
      { text: 'Ze probeerde drie stoelen, daarna drie bedden. Ze viel in slaap in het zachtste.' },
      { text: 'De drie beren kwamen terug en vonden hun huis overhoop.', dialogue: { speaker: 'Klein beertje', line: 'Iemand heeft uit mijn kommetje gegeten!' } },
      { text: 'Goudlokje werd wakker, zei sorry en leerde dat eerst vragen de liefste beleefdheidsvorm is.', dialogue: { speaker: 'Goudlokje', line: 'Sorry. Ik zal altijd eerst vragen voor ik binnenkom.' } },
    ],
    vocabulary: [
      { word: 'pap', meaning: 'warm en zacht eten, zoals ontbijtgranen', emoji: '🥣' },
      { word: 'huisje', meaning: 'een klein, gezellig huisje in het bos', emoji: '🏡' },
      { word: 'respect', meaning: 'goed zorgen voor andermans spullen en gevoelens', emoji: '🙏' },
      { word: 'sorry', meaning: 'wat je zegt als je ergens spijt van hebt', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel beren woonden er in het gezellige huisje?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respectvol', prompt: 'Goudlokje leerde eerst te vragen. Wanneer is het vriendelijk om toestemming te vragen voor je iets leent?' },
    rewardName: 'Perfect kommetje',
  },

  'three-little-pigs': {
    title: 'De Drie Biggetjes',
    summary: 'Drie kleine biggetjes bouwen drie verschillende huizen en leren dat zorgvuldig en ijverig werk iedereen veilig en warm houdt.',
    theme: 'werk en organisatie',
    scenes: [
      { text: 'Drie kleine biggetjes trokken de wereld in om hun huis te bouwen.' },
      { text: 'Het eerste biggetje bouwde snel een huis van stro. Het tweede een huis van hout.', dialogue: { speaker: 'Eerste biggetje', line: 'Snel klaar, goed gedaan! Ik wil gaan spelen!' } },
      { text: 'Het derde biggetje werkte hard en bouwde steen voor steen een stevig huis van bakstenen.', dialogue: { speaker: 'Derde biggetje', line: 'Ik neem de tijd zodat mijn huis stevig is.' } },
      { text: 'De grote boze wolf blies op de huizen van stro en hout, en ze stortten in.' },
      { text: 'Maar het bakstenen huis bleef stevig staan. De drie biggetjes waren veilig, en iedereen leerde dat zorgvuldig werken beschermt.', dialogue: { speaker: 'Derde biggetje', line: 'Goed werk kost tijd, maar het is de moeite waard!' } },
    ],
    vocabulary: [
      { word: 'stro', meaning: 'droge plantenstengels die makkelijk breken', emoji: '🌾' },
      { word: 'bakstenen', meaning: 'heel stevige gebakken aardblokken', emoji: '🧱' },
      { word: 'stevig', meaning: 'heel sterk, niet makkelijk te breken', emoji: '💪' },
      { word: 'plannen', meaning: 'nadenken voor je ergens mee begint', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel kleine biggetjes bouwden een huis?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'trots op mijn werk', prompt: 'Het derde biggetje werkte hard en bleef veilig. Waar heb jij hard aan gewerkt?' },
    rewardName: 'Stevige baksteen',
  },

  'aladdin': {
    title: 'Aladdin',
    summary: 'Een gewoon maar lief jongetje vindt een magische lamp en leert dat wat je wenst minder telt dan het goede dat je voor anderen doet.',
    theme: 'eerlijkheid en bescheidenheid',
    scenes: [
      { text: 'Op een levendige markt woonde Aladdin, een arme jongen met een hart van goud.' },
      { text: 'Hij vond een oude lamp en toen hij eraan wreef, verscheen er een grote geest!', dialogue: { speaker: 'Geest', line: 'Ik geef je drie wensen. Kies zorgvuldig!' } },
      { text: 'Aladdin wenste eerst zijn familie te helpen, dan de arme mensen in zijn wijk.', dialogue: { speaker: 'Aladdin', line: 'Ik wil dat niemand op deze markt honger heeft.' } },
      { text: 'Zijn bescheidenheid en vrijgevigheid bezorgden hem echte vrienden en veel geluk.' },
      { text: 'Aladdin leerde dat de beste wensen die zijn die je voor anderen doet.', dialogue: { speaker: 'Aladdin', line: 'Een vrijgevig hart is de grootste schat.' } },
    ],
    vocabulary: [
      { word: 'markt', meaning: 'een drukke plek waar mensen kopen en verkopen', emoji: '🏪' },
      { word: 'lamp', meaning: 'een voorwerp dat licht geeft of een geest bewaart', emoji: '🪔' },
      { word: 'bescheiden', meaning: 'iemand die niet opschept over zichzelf', emoji: '🙏' },
      { word: 'wens', meaning: 'iets waar je heel erg naar verlangt', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'Hoeveel wensen gaf de geest aan Aladdin?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'vrijgevig', prompt: 'Aladdin wenste om anderen te helpen. Als jij een lieve wens mocht doen, welke zou dat zijn?' },
    rewardName: 'Wensenlamp',
  },

  'ali-baba': {
    title: 'Ali Baba',
    summary: 'Een vriendelijke houthakker ontdekt een geheime grot en leert dat eerlijk en voorzichtig zijn veel beter is dan hebzuchtig zijn.',
    theme: 'eerlijkheid boven hebzucht',
    scenes: [
      { text: 'Ali Baba was een vriendelijke houthakker die eenvoudig en tevreden leefde.' },
      { text: 'Op een dag in het bos hoorde hij rovers de magische woorden zeggen bij een grote rots.', dialogue: { speaker: 'Rovers', line: 'Sesam, open u!' } },
      { text: 'Ali Baba liep de grot in en zag schitterende schatten in alle kleuren.', dialogue: { speaker: 'Ali Baba', line: 'Ik neem alleen wat we nodig hebben, niet meer.' } },
      { text: 'Zijn hebzuchtige broer nam te veel en werd verrast door de rovers. Ali Baba begreep de les.' },
      { text: 'Ali Baba deelde zijn goede fortuin met anderen en leefde eenvoudig en gelukkig.', dialogue: { speaker: 'Ali Baba', line: 'Genoeg hebben en eerlijk zijn, dat is de echte rijkdom.' } },
    ],
    vocabulary: [
      { word: 'grot', meaning: 'een grote, natuurlijke holte in de rots', emoji: '🕳️' },
      { word: 'schat', meaning: 'een grote hoeveelheid goud en kostbare dingen', emoji: '💎' },
      { word: 'hebzuchtig', meaning: 'iemand die altijd meer wil dan hij nodig heeft', emoji: '😤' },
      { word: 'genoeg', meaning: 'precies wat je nodig hebt, niet meer en niet minder', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Welke magische woorden openen de grot?', options: ['Sesam, open u!', 'Doe de deur dicht!', 'Goedemorgen!'], answerIndex: 0 },
    emotionalMoment: { feeling: 'tevreden', prompt: 'Ali Baba nam alleen wat nodig was. Welk ding dat je al hebt, is precies genoeg voor jou?' },
    rewardName: 'Geheime grot',
  },

  'aesops-fables': {
    title: 'De Haas en de Schildpad',
    summary: 'Een snelle haas en een langzame schildpad houden een vriendschappelijke race, en de schildpad laat iedereen zien dat nooit opgeven de dag wint.',
    theme: 'doorzettingsvermogen — langzaam maar zeker',
    scenes: [
      { text: 'In een zonnige weide schepte een snelle haas altijd op over zijn snelheid.' },
      { text: 'De langzame, rustige schildpad daagde hem uit. De haas accepteerde lachend.', dialogue: { speaker: 'Haas', line: 'Een race tegen jou? Makkelijk! Ik ga onderweg even rusten.' } },
      { text: 'De schildpad liep stap voor stap, gestaag, zonder ooit te stoppen.', dialogue: { speaker: 'Schildpad', line: 'Langzaam maar zeker kom ik vooruit.' } },
      { text: 'De haas viel in slaap onder een boom, zeker dat de schildpad hem nooit zou inhalen.' },
      { text: 'Toen de haas wakker werd, had de schildpad de finish al gehaald. Doorzetten wint altijd.', dialogue: { speaker: 'Schildpad', line: 'Stap voor stap kom je verder dan je denkt.' } },
    ],
    vocabulary: [
      { word: 'haas', meaning: 'een groot, wild konijn dat heel snel is', emoji: '🐇' },
      { word: 'schildpad', meaning: 'een dier met een schild dat langzaam maar zonder stoppen loopt', emoji: '🐢' },
      { word: 'gestaag', meaning: 'in hetzelfde tempo vooruitgaan zonder te stoppen', emoji: '⏱️' },
      { word: 'doorzetten', meaning: 'blijven proberen ook als het moeilijk is', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Wie won de race door nooit op te geven?', options: ['de snelle haas', 'de langzame, gestadige schildpad', 'de slapende vos'], answerIndex: 1 },
    emotionalMoment: { feeling: 'vastberaden', prompt: 'De schildpad ging stap voor stap door. Waar blijf jij zelf mee doorgaan?' },
    rewardName: 'Doorzettingsschildpad',
  },

  'sleeping-beauty': {
    title: 'Doornroosje',
    summary: 'Een mooie prinses valt in een magische slaap en wacht op de ware liefde.',
    theme: 'geduld en hoop',
    scenes: [
      { text: 'Een blije koning en koningin kregen eindelijk een dochtertje. Ze nodigden alle feeeen van het koninkrijk uit voor de doop.' },
      { text: 'De goede feeeen schonken de prinses gaven: schoonheid, gratie en zachtheid. Maar een boze fee arriveerde woedend.', dialogue: { speaker: 'Boze fee', line: 'Wanneer ze zestien wordt, prikt ze haar vinger aan een spoel en valt ze dood neer!' } },
      { text: 'De laatste goede fee had nog niet gesproken. Ze verzachtte de vloek: de prinses zou niet sterven, maar honderd jaar slapen.', dialogue: { speaker: 'Goede fee', line: 'Ze slaapt, maar de liefde zal haar wakker maken.' } },
      { text: 'Op haar zestiende vond de prinses een oude vrouw die spon. Ze raakte de spoel aan en viel in een diepe slaap. Het hele kasteel sliep met haar mee.' },
      { text: 'Een prins hoorde over het slapende kasteel verborgen achter een rozenbos. Hij hakte door de dorens en betrad het stille kasteel.', dialogue: { speaker: 'Prins', line: 'Wat is ze mooi! Ik zal haar wakker kussen.' } },
      { text: 'De prins boog zich over de mooie prinses en gaf haar een zachte kus. Ze deed haar ogen open en glimlachte. Het hele kasteel ontwaakte, en ze leefden gelukkig.', dialogue: { speaker: 'Prinses', line: 'Ik heb zo lang gewacht. Eindelijk ben je er!' } },
    ],
    vocabulary: [
      { word: 'spoel', meaning: 'een gereedschap om wol mee te spinnen, met een punt', emoji: '🧵' },
      { word: 'kwaadaardig', meaning: 'iemand die met slechte magie schade doet', emoji: '🧙' },
      { word: 'betoverd', meaning: 'veranderd door bijzondere magie', emoji: '✨' },
      { word: 'rozenstruik', meaning: 'een struik die mooie rozen laat groeien', emoji: '🌹' },
    ],
    miniGame: { type: 'choice', prompt: 'Welke boze fee spreekt de vloek uit over de prinses?', options: ['Een fee die niet was uitgenodigd', 'De kasteelfee', 'De bosfee'], answerIndex: 0 },
    emotionalMoment: { feeling: 'hoop', prompt: 'Heb je wel eens ongeduldig op iets gewacht? Hoe voelde dat?' },
    rewardName: 'Betoverde Roos',
  },

  'beauty-and-the-beast': {
    title: 'Belle en het Beest',
    summary: 'Belle leert dat echte schoonheid in het hart zit, niet in het uiterlijk.',
    theme: 'vriendelijkheid en echte liefde',
    scenes: [
      { text: 'Een koopman verdwaalde in het bos tijdens een storm. Hij vond een groot mysterieus kasteel en schuilde er voor de nacht.' },
      { text: 'Bij het vertrek plukte hij een roos voor zijn dochter Belle. Een verschrikkelijk Beest dook plotseling op.', dialogue: { speaker: 'Beest', line: 'Je hebt mijn roos gestolen! Je bent mijn gevangene!' } },
      { text: 'De koopman smeekte het Beest hem gedag te laten zeggen. Het Beest stemde in, op voorwaarde dat een van zijn dochters zijn plaats innam.', dialogue: { speaker: 'Belle', line: 'Papa, ik ga. Ik ben niet bang.' } },
      { text: 'Belle woonde in het kasteel. Het Beest was lelijk maar zacht en vriendelijk. Elke avond praatten en lachten ze samen.' },
      { text: 'Belle vroeg naar huis te mogen om haar zieke vader te bezoeken. Het Beest stemde verdrietig in.', dialogue: { speaker: 'Beest', line: 'Ik zal je missen, Belle. Maar jouw geluk gaat voor het mijne.' } },
      { text: 'Belle besefte ver van het kasteel dat ze van het Beest hield. Ze rende terug. Toen ze haar liefde bekende, veranderde het Beest in een knappe prins.', dialogue: { speaker: 'Belle', line: 'Ik hou van jou, niet om je gezicht, maar om je hart.' } },
      { text: 'De prins vertelde dat een heks hem had betoverd. Alleen oprechte liefde kon hem bevrijden. Belle en de prins leefden voor altijd gelukkig.' },
    ],
    vocabulary: [
      { word: 'beest', meaning: 'een groot eng dier, hier een betoverd monster', emoji: '🐾' },
      { word: 'gevangene', meaning: 'iemand die niet vrij kan vertrekken', emoji: '🔒' },
      { word: 'uiterlijk', meaning: 'wat je van buiten van iemand ziet', emoji: '👁️' },
      { word: 'transformatie', meaning: 'volledig van vorm of aanzien veranderen', emoji: '✨' },
    ],
    miniGame: { type: 'choice', prompt: 'Waarom gaat Belles vader naar het kasteel?', options: ['Hij zoekt een schat', 'Hij schuilt voor de storm en plukt een roos', 'Hij bezoekt het Beest'], answerIndex: 1 },
    emotionalMoment: { feeling: 'vriendelijkheid', prompt: 'Heb je wel eens iemand beoordeeld op zijn uiterlijk voor je hem kende?' },
    rewardName: 'Magische Roos',
  },

  'little-thumb': {
    title: 'Klein Duimpje',
    summary: 'De kleinste van zeven broers gebruikt zijn slimheid om zijn familie te redden.',
    theme: 'moed en intelligentie',
    scenes: [
      { text: 'Een arme houtshakker en zijn vrouw hadden zeven zoons. De kleinste heette Klein Duimpje. Hij was minuscuul maar heel slim.' },
      { text: 'Op een avond lieten de ouders, te arm om de kinderen te voeden, hen achter in het bos.', dialogue: { speaker: 'Klein Duimpje', line: 'Ik wist dat ze dit zouden doen. Ik ben er klaar voor.' } },
      { text: 'Klein Duimpje had zich voorbereid: hij had zijn zakken gevuld met kleine witte kiezelstenen. Hij strooide ze langs het pad, en de kinderen vonden zo de weg naar huis terug.' },
      { text: 'De tweede keer verlaten had Klein Duimpje alleen brood om kruimels te strooien. De vogels aten ze op en de broers raakten voorgoed verdwaald.' },
      { text: 'Verdwaald kwamen ze aan bij het huis van een rees. De vrouw van de reus verstopte hen, maar de reus vond hen.', dialogue: { speaker: 'Reus', line: 'Ik ruik vers vlees! Waar zitten ze verstopt?' } },
      { text: 'Klein Duimpje had een briljant idee: hij wisselde de mutsen van zijn broers met de kroontjes van de dochters van de reus. De reus vergiste zich in het donker.' },
      { text: 'Klein Duimpje stal de zevenmijlslaarzen van de slapende reus. In enkele stappen haalde hij goud op en redde zijn hele familie.', dialogue: { speaker: 'Klein Duimpje', line: 'Slimheid is beter dan kracht!' } },
    ],
    vocabulary: [
      { word: 'kiezelstenen', meaning: 'kleine gladde steentjes die je langs een pad kunt strooien', emoji: '🪨' },
      { word: 'reus', meaning: 'een groot monster dat kinderen eet in sprookjes', emoji: '👹' },
      { word: 'mijl', meaning: 'een grote afstand, zoals meerdere kilometers', emoji: '🗺️' },
      { word: 'list', meaning: 'een slim idee om iemand te misleiden', emoji: '💡' },
    ],
    miniGame: { type: 'sequence', prompt: 'Zet de stappen in de goede volgorde!', steps: ['Witte kiezelstenen strooien om de weg terug te vinden', 'Aankomen bij het huis van de reus in het bos', 'De zevenmijlslaarzen stelen'] },
    emotionalMoment: { feeling: 'moed', prompt: 'Heb je wel eens bang geweest maar toch doorgegaan? Wat hielp je?' },
    rewardName: 'Zevenmijlslaarzen',
  },

  'jack-beanstalk': {
    title: 'Jaap en de Bonenstaak',
    summary: 'Jaap ruilt zijn koe voor magische bonen en ontdekt een kasteel in de wolken.',
    theme: 'avontuur en nieuwsgierigheid',
    scenes: [
      { text: 'Jaap en zijn moeder waren erg arm. Op een dag stuurde zijn moeder Jaap om hun oude koe te verkopen op de markt.' },
      { text: 'Onderweg bood een oude man Jaap magische bonen aan in ruil voor de koe. Jaap accepteerde.', dialogue: { speaker: 'Jaap', line: 'Magische bonen! Dat is een goede ruil!' } },
      { text: 'Jaaps moeder was erg boos en gooide de bonen uit het raam. Maar in de nacht groeide er een enorme bonenstaak tot aan de wolken.' },
      { text: 'Jaap klom langs de staak omhoog en ontdekte een reusachtig kasteel in de wolken. Een verschrikkelijke reus woonde er.', dialogue: { speaker: 'Reus', line: 'Fe, fi, fo, fum! Ik ruik het bloed van een mens!' } },
      { text: 'De vrouw van de reus hielp Jaap zich te verstoppen. Jaap profiteerde ervan dat de reus sliep om de gouden hen en de betoverde harp te stelen.' },
      { text: 'Jaap gleed snel langs de staak naar beneden. De reus achtervolgde hem. Jaap greep zijn bijl en hakte de staak om. De reus viel ver, ver weg.', dialogue: { speaker: 'Jaap', line: 'Mama! We worden rijk! Nooit meer honger!' } },
    ],
    vocabulary: [
      { word: 'boon', meaning: 'een klein zaadje dat heel hoog kan groeien', emoji: '🫘' },
      { word: 'reus', meaning: 'een denkbeeldig wezen dat enorm groot en sterk is', emoji: '🦣' },
      { word: 'wolken', meaning: 'de grote witte of grijze vormen in de lucht', emoji: '☁️' },
      { word: 'schat', meaning: 'waardevolle voorwerpen zoals goud of juwelen', emoji: '🪙' },
    ],
    miniGame: { type: 'choice', prompt: 'Waartegen ruilt Jaap zijn koe?', options: ['Gouden munten', 'Magische bonen', 'Een harp'], answerIndex: 1 },
    emotionalMoment: { feeling: 'nieuwsgierigheid', prompt: 'Heb je wel eens iets verrassends ontdekt? Hoe voelde dat?' },
    rewardName: 'Schat van de Reus',
  },

  'thumbelina': {
    title: 'Duimelijntje',
    summary: 'Duimelijntje, een heel klein meisje, zoekt haar plek in een wereld die te groot voor haar is.',
    theme: 'identiteit en erbij horen',
    scenes: [
      { text: 'Een vrouw die zo graag een kind wilde plantte een magisch zaad. Er groeide een bloem, en binnenin sliep een heel klein meisje. Ze heette Duimelijntje.' },
      { text: 'Op een avond ontvoerde een lelijke kikker Duimelijntje om haar met zijn zoon te laten trouwen. Duimelijntje huilde op haar waterlelie.', dialogue: { speaker: 'Duimelijntje', line: 'Ik wil hier niet blijven. Ik wil mijn echte thuis vinden.' } },
      { text: 'Vriendelijke vissen knabbelden de stengel van de waterlelie door en Duimelijntje ontsnapte. Ze reisde door velden en bossen, altijd te klein voor de anderen.' },
      { text: 'In de winter vond Duimelijntje onderdak bij een veldmuis. Maar de muis wilde haar laten trouwen met een oude blinde mol.' },
      { text: 'Duimelijntje vond een gewonde zwaluw en verzorgde haar de hele winter met tederheid.', dialogue: { speaker: 'Zwaluw', line: 'Je hebt me gered. Als de lente komt, breng ik je ver hiervandaan.' } },
      { text: 'In de lente droeg de zwaluw Duimelijntje naar een warm, bloeiend land. Daar ontmoette ze een heel kleine bloemenprinsen. Ze had eindelijk haar plek gevonden.', dialogue: { speaker: 'Bloemenprins', line: 'Je bent welkom hier. Wil jij onze koningin zijn?' } },
    ],
    vocabulary: [
      { word: 'minuscuul', meaning: 'extreem klein, veel kleiner dan iedereen', emoji: '🔬' },
      { word: 'ontvoeren', meaning: 'iemand met geweld meenemen zonder toestemming', emoji: '😨' },
      { word: 'zwaluw', meaning: 'een kleine snelle vogel die naar warme landen trekt', emoji: '🐦' },
      { word: 'fee', meaning: 'een magisch wezen met vleugels dat anderen helpt', emoji: '🧚' },
    ],
    miniGame: { type: 'find', prompt: 'Zoek de bloem waar Duimelijntje in slaapt!', target: 'de grote roze bloem', decoys: ['een groene waterlelie', 'een droog blad', 'een paddenstoel'] },
    emotionalMoment: { feeling: 'erbij horen', prompt: 'Heb je wel eens het gevoel gehad dat je niet op je plek was? Hoe heb je je plek gevonden?' },
    rewardName: 'Feevleugels',
  },

  'twelve-dancing-princesses': {
    title: 'De Twaalf Dansende Prinsessen',
    summary: 'Elke nacht verslijten twaalf prinsessen stiekem hun schoenen op de dansvloer. Een soldaat ontdekt hun geheim.',
    theme: 'mysterie en doorzettingsvermogen',
    scenes: [
      { text: 'Een koning had twaalf dochters. Elke ochtend waren hun schoenen versleten alsof ze de hele nacht hadden gedanst. Maar niemand wist waarom.' },
      { text: 'De koning kondigde aan dat degene die het geheim ontdekte een van zijn dochters mocht huwen. Prinsen probeerden het, maar vielen allemaal op mysterieuze wijze in slaap.', dialogue: { speaker: 'Koning', line: 'Wie lost dit mysterie op? Hun schoenen zijn alweer versleten!' } },
      { text: 'Een oude soldaat die terugkeerde van de oorlog ontmoette een wijze oude vrouw die hem een onzichtbare mantel gaf.', dialogue: { speaker: 'Oude vrouw', line: 'Drink niet van het drankje dat men je aanbiedt. En wees voorzichtig!' } },
      { text: 'De soldaat deed alsof hij sliep. Om middernacht stonden de prinsessen op. Hij volgde hen onzichtbaar door een geheime doorgang onder de grond.' },
      { text: 'Onder de grond ontdekte hij een meer met boten, een bos met zilveren en gouden bomen, en een verlicht kasteel waar twaalf prinsen de prinsessen opwachtten om te dansen.' },
      { text: 'De soldaat plukte stiekem een zilveren tak als bewijs. De oudste prinses hoorde een geluid.', dialogue: { speaker: 'Oudste prinses', line: 'Er klopt vanavond iets niet. Ik ben bang.' } },
      { text: 'De volgende dag presenteerde de soldaat de tak aan de koning en vertelde alles. De koning erkende de waarheid. De soldaat koos om met de oudste prinses te trouwen en het geheim was voor altijd onthuld.', dialogue: { speaker: 'Soldaat', line: 'De waarheid is meer waard dan alle geheimen.' } },
    ],
    vocabulary: [
      { word: 'mysterie', meaning: 'iets verborgens dat je nog niet begrijpt', emoji: '🔍' },
      { word: 'onzichtbaar', meaning: 'wat je niet kunt zien, ook al is het er', emoji: '👻' },
      { word: 'schoen', meaning: 'een elegante schoen, vaak voor het dansen', emoji: '👠' },
      { word: 'ondergronds', meaning: 'wat zich onder de grond bevindt, verborgen eronder', emoji: '🕳️' },
    ],
    miniGame: { type: 'match', prompt: 'Koppel elke prinses aan haar dansprins!', pairs: [{ left: 'Prinses Roos', right: 'Prins Dorian' }, { left: 'Prinses Maan', right: 'Prins Silvain' }, { left: 'Prinses Ster', right: 'Prins Aurele' }, { left: 'Prinses Violet', right: 'Prins Florian' }] },
    emotionalMoment: { feeling: 'mysterie', prompt: 'Heb jij een geheim? Hoe voelt het om een geheim te bewaren?' },
    rewardName: 'Kroon van het Mysterie',
  },

  'rumpelstiltskin': {
    title: 'Repelsteeltje',
    summary: 'Een mysterieus mannetje helpt een meisje stro in goud te spinnen — maar voor welke prijs?',
    theme: 'beloften en eerlijkheid',
    scenes: [
      { text: 'Een molenaar wilde de koning imponeren en vertelde een grote leugen: "Mijn dochter kan stro in goud spinnen!" De koning sloot het meisje op in een toren vol stro.' },
      { text: 'Het meisje huilde toen een vreemd klein mannetje verscheen.', dialogue: { speaker: 'Repelsteeltje', line: 'Wat geef je me als ik al dit stro in goud spin voor jou?' } },
      { text: 'Ze gaf hem haar ketting. Het kleine mannetje spon al het stro in goud. De koning, vol bewondering, bracht haar naar een nog grotere kamer.' },
      { text: 'De derde nacht had het meisje niets meer te geven. Ze beloofde haar eerste kind. De koning trouwde met haar en ze werd koningin.' },
      { text: 'Een jaar later kwam het kleine mannetje terug om het kind op te eisen. De koningin smeekte. Hij gaf haar drie dagen om zijn naam te raden.', dialogue: { speaker: 'Repelsteeltje', line: 'Als je mijn naam raadt, mag je het kind houden!' } },
      { text: 'Een boodschapper hoorde het kleine mannetje dansen en zijn naam zingen in het bos. Hij rende terug om het de koningin te vertellen.', dialogue: { speaker: 'Boodschapper', line: 'Hij heet Repelsteeltje! Ik heb hem horen zingen!' } },
    ],
    vocabulary: [
      { word: 'stro', meaning: 'droge grasstengels, geel en licht', emoji: '🌾' },
      { word: 'spinnen', meaning: 'vezels omzetten tot draad met een spinnenwiel', emoji: '🧶' },
      { word: 'belofte', meaning: 'wat je zegt dat je zult doen en moet nakomen', emoji: '🤝' },
      { word: 'raadsel', meaning: 'een vraag met een verborgen antwoord om te vinden', emoji: '❓' },
    ],
    miniGame: { type: 'choice', prompt: 'Hoe raadt de koningin de naam van het kabouter?', options: ['Een boodschapper hoorde hem zingen in het bos', 'Ze las het in een boek', 'De kabouter vertelde het haar zelf'], answerIndex: 0 },
    emotionalMoment: { feeling: 'eerlijkheid', prompt: 'Is het belangrijk om je beloften na te komen? Waarom?' },
    rewardName: 'Gouden Draad',
  },

  'emperor-new-clothes': {
    title: 'De Nieuwe Kleren van de Keizer',
    summary: 'Twee oplichters overtuigen een ijdele keizer dat ze hem onzichtbare kleren maken voor dwazen.',
    theme: 'eerlijkheid en moed',
    scenes: [
      { text: 'Er was eens een keizer die meer van mooie kleren hield dan van wat ook. Hij wisselde meerdere keren per dag van kleding.' },
      { text: 'Twee oplichters presenteerden zich als de beste wevers ter wereld. Ze beweerden een magische stof te weven: onzichtbaar voor dwazen en onbekwamen.', dialogue: { speaker: 'Oplichter', line: 'Alleen echt intelligente mensen kunnen deze kleren zien!' } },
      { text: 'De ministers werden gestuurd om de voortgang te bekijken. Ze zagen niets, maar durfden het niet te zeggen uit angst dom te lijken.', dialogue: { speaker: 'Minister', line: 'Het is prachtig... absoluut prachtig.' } },
      { text: 'De oplichters overhandigden de keizer zijn denkbeeldige nieuwe kleren. De keizer zag ook niets, maar deed alsof.' },
      { text: 'De keizer liep in optocht door de straten. Iedereen klapte, bang om dom te lijken.' },
      { text: 'Plotseling riep een klein kind de waarheid.', dialogue: { speaker: 'Kind', line: 'Maar hij heeft niets aan! De keizer is helemaal naakt!' } },
    ],
    vocabulary: [
      { word: 'ijdel', meaning: 'iemand die te veel aan zijn uiterlijk denkt en zichzelf mooi vindt', emoji: '🪞' },
      { word: 'oplichter', meaning: 'iemand die liegt om te stelen of anderen te bedriegen', emoji: '🎭' },
      { word: 'onzichtbaar', meaning: 'wat je met je ogen niet kunt zien', emoji: '👻' },
      { word: 'waarheid', meaning: 'wat echt waar is, ook al is het lastig', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Wie zegt als eerste de waarheid?', options: ['Een klein kind', 'Een minister', 'De keizer zelf'], answerIndex: 0 },
    emotionalMoment: { feeling: 'moed', prompt: 'Heb je wel eens de moed gehad om een moeilijke waarheid te zeggen?' },
    rewardName: 'Moed van de Waarheid',
  },

  'steadfast-tin-soldier': {
    title: 'De Standvastige Tinnen Soldaat',
    summary: 'Een dappere kleine tinnen soldaat beleeft een groot avontuur en bewijst dat moed uit het hart komt.',
    theme: 'moed en trouw',
    scenes: [
      { text: 'Tussen een doos tinnen soldaten had er een maar een been. Maar hij stond recht en trots zoals de anderen.' },
      { text: 'Op een plank tegenover hem stond een klein papieren danseres die een been ophief. De soldaat dacht dat ze net als hij was, en werd verliefd op haar.', dialogue: { speaker: 'Soldaat', line: 'Ze is zo mooi. Ik wil altijd dicht bij haar blijven.' } },
      { text: 'Een jaloerse duiveltje in een doos riep dat de soldaat niet naar de danseres mocht kijken. De volgende dag viel de soldaat uit een raam.' },
      { text: 'Op straat vonden kinderen hem en stopten hem in een papieren bootje. Hij voer door de goot in de regen, en werd daarna door een grote vis ingeslikt.' },
      { text: 'De vis werd gevangen en belandde in de keuken. De kok sneed hem open en vond de tinnen soldaat ongedeerd, nog steeds rechtop.', dialogue: { speaker: 'Kok', line: 'Maar hoe heb je dit allemaal overleefd!' } },
      { text: 'De soldaat werd teruggegeven aan het kind. Maar het jaloerse duiveltje gooide de soldaat in het vuur. De kleine danseres viel ook door de wind mee. Van de soldaat bleef alleen een klein metalen hartje over, symbool van zijn eeuwige trouw.', dialogue: { speaker: 'Soldaat', line: 'Ik bleef dapper tot het einde.' } },
    ],
    vocabulary: [
      { word: 'tin', meaning: 'een grijs zwaar metaal, vroeger gebruikt voor speelgoed', emoji: '⚙️' },
      { word: 'dapper', meaning: 'moedig en sterk tegenover gevaar', emoji: '🛡️' },
      { word: 'stroom', meaning: 'een krachtige, snelle waterstroom', emoji: '🌊' },
      { word: 'trouw', meaning: 'loyaal blijven aan iemand van wie je houdt, wat er ook gebeurt', emoji: '💙' },
    ],
    miniGame: { type: 'choice', prompt: 'Op wie wordt de tinnen soldaat verliefd?', options: ['Een klein papieren danseres', 'Een prinses in het kasteel', 'Een magische fee'], answerIndex: 0 },
    emotionalMoment: { feeling: 'trouw', prompt: 'Is er iemand of iets waaraan jij heel erg trouw bent? Wat betekent dat voor jou?' },
    rewardName: 'Moed Medaille',
  },

  'la-fontaine-crow-fox': {
    title: 'De Kraai en de Vos',
    summary: 'Een heel slimme vos vleit een kraai om zijn kaas te stelen. Een fabel over ijdelheid.',
    theme: 'slimheid en bescheidenheid',
    scenes: [
      { text: 'Een kraai zat op een tak met een lekker stuk kaas in zijn bek.' },
      { text: 'Een heel slimme vos liep voorbij en rook de kaas. Hij besloot hem te stelen door te vleien.', dialogue: { speaker: 'Vos', line: 'O Mijnheer de Kraai, wat bent u mooi! Wat zijn uw veren prachtig!' } },
      { text: 'De kraai, trots op de complimenten, blies zijn veren op van genoegen. De vos ging verder.', dialogue: { speaker: 'Vos', line: 'Als uw stem net zo mooi is als uw veren, bent u de koning der vogels!' } },
      { text: 'De kraai, te gevleid, opende zijn bek wijd om te zingen. De kaas viel naar beneden.' },
      { text: 'De vos greep de kaas lachend en sprak de moraal van de fabel.', dialogue: { speaker: 'Vos', line: 'Elke vleier leeft ten koste van degene die naar hem luistert. Die les is een kaas waard!' } },
    ],
    vocabulary: [
      { word: 'kraai', meaning: 'een grote zwarte vogel met een stevige gebogen snavel', emoji: '🐦‍⬛' },
      { word: 'vleier', meaning: 'iemand die te veel complimenten maakt om iets te krijgen', emoji: '😏' },
      { word: 'kaas', meaning: 'een gerecht gemaakt van melk, vaak geel of wit', emoji: '🧀' },
      { word: 'moraal', meaning: 'de les die je leert aan het einde van een fabel', emoji: '📜' },
    ],
    miniGame: { type: 'choice', prompt: 'Hoe krijgt de vos de kaas?', options: ['Door de kraai te vleien zodat hij zijn bek opent', 'Door in de boom te klimmen', 'Door vriendelijk te vragen'], answerIndex: 0 },
    emotionalMoment: { feeling: 'bescheidenheid', prompt: 'Ben je wel eens gevleid en iets doms gedaan? Wat heb je geleerd?' },
    rewardName: 'Wijsheid van de Fabel',
  },
};
