// English translations for all 19 fairy tales.
// Only content fields are translated — id, emoji, coverImage, palette,
// difficulty, ageMin, ageMax, rewardEmoji are intentionally omitted.

export const CONTES_EN = {
  'snow-white': {
    title: 'Snow White',
    summary: 'A gentle princess with skin as white as snow finds a home with seven kind little helpers and learns that true friends always look after each other.',
    theme: 'kindness and friendship',
    scenes: [
      { text: 'Long ago, a little princess was born with skin as white as snow. Everyone called her Snow White.' },
      { text: 'A jealous queen owned a magic mirror and asked it the same question every day.', dialogue: { speaker: 'Queen', line: 'Mirror, mirror, who is the kindest and most beautiful of all?' } },
      { text: 'Snow White walked into the heart of the forest. Seven kind little miners welcomed her into their cosy cottage.', dialogue: { speaker: 'A miner', line: 'You are safe here, little friend. Come and rest.' } },
      { text: 'The queen tricked her with a shiny apple, and Snow White fell into a very, very deep sleep.' },
      { text: 'A caring friend woke her with a gentle touch. Snow White smiled, and everyone celebrated their brave friend.', dialogue: { speaker: 'Snow White', line: 'You never left me. Thank you, my friends!' } },
    ],
    vocabulary: [
      { word: 'fairest', meaning: 'the kindest and most beautiful person', emoji: '🌷' },
      { word: 'jealous', meaning: 'upset because you want what someone else has', emoji: '😠' },
      { word: 'cottage', meaning: 'a small, cosy house', emoji: '🏡' },
      { word: 'welcome', meaning: 'to make someone glad they have arrived', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'How many kind little miners welcomed Snow White?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'surrounded and safe', prompt: 'Snow White\'s friends looked after her. Who looks after you?' },
    rewardName: 'Kind Mirror',
  },

  'cinderella': {
    title: 'Cinderella',
    summary: 'A hard-working girl with a big heart gets a little help from a magical friend and discovers that being kind is a magic all of its own.',
    theme: 'hope and kindness',
    scenes: [
      { text: 'Cinderella did all the chores and never lost her sweet smile, even when others were unkind.' },
      { text: 'One evening, a grand ball was announced, but Cinderella had nothing to wear.', dialogue: { speaker: 'Cinderella', line: 'If only I could go dancing, just once.' } },
      { text: 'A kind fairy appeared and, with a wave of her wand, turned a pumpkin into a carriage.', dialogue: { speaker: 'Fairy friend', line: 'Be back before midnight, my dear — the magic stops then.' } },
      { text: 'At the ball, Cinderella danced and laughed. But when the clock began to strike, she had to run.' },
      { text: 'The slipper fitted her perfectly. Her kindness had always been seen, and joy filled her days.', dialogue: { speaker: 'Cinderella', line: 'Being kind costs nothing.' } },
    ],
    vocabulary: [
      { word: 'chores', meaning: 'small jobs that help around the home', emoji: '🧹' },
      { word: 'carriage', meaning: 'a coach pulled along to carry people', emoji: '🛞' },
      { word: 'midnight', meaning: 'twelve o\'clock at night', emoji: '🕛' },
      { word: 'gentle', meaning: 'tender, calm, and kind', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'What time must Cinderella be back? Count the chimes of the clock!', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'full of hope', prompt: 'Even on hard days, Cinderella stayed kind. What helps you keep hoping?' },
    rewardName: 'Glass Slipper',
  },

  'little-red-riding-hood': {
    title: 'Little Red Riding Hood',
    summary: 'A brave little girl in a red hood visits her grandmother and learns to listen to her wise feelings along the way.',
    theme: 'listening and staying safe',
    scenes: [
      { text: 'A little girl wore a bright red hood everywhere she went, so everyone called her Little Red Riding Hood.' },
      { text: 'Her mum gave her a basket of bread for Grandma.', dialogue: { speaker: 'Mum', line: 'Stay on the path and everything will be fine.' } },
      { text: 'In the woods, a crafty wolf asked lots of questions. Little Red felt something strange and kept on walking.', dialogue: { speaker: 'Little Red', line: 'I don\'t have to answer you. I will tell a grown-up.' } },
      { text: 'A kind woodcutter heard her and walked with her. Together, they arrived at Grandma\'s house.' },
      { text: 'Grandma was safe, and so was Little Red. They shared warm bread and laughed all afternoon.', dialogue: { speaker: 'Grandma', line: 'You listened to your wise feelings. I am so proud of you.' } },
    ],
    vocabulary: [
      { word: 'path', meaning: 'a track that shows you where to walk safely', emoji: '🛤️' },
      { word: 'basket', meaning: 'a carrier with a handle for taking things along', emoji: '🧺' },
      { word: 'crafty', meaning: 'someone who plays tricks to fool you', emoji: '🦊' },
      { word: 'woodcutter', meaning: 'a person who works among the trees', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'A stranger asks Little Red where she is going. What is the safe choice?', options: ['Tell him everything', 'Keep walking and warn a grown-up', 'Follow him into the trees'], answerIndex: 1 },
    emotionalMoment: { feeling: 'safe', prompt: 'Little Red listened to her strange feeling. When has a feeling helped you stay safe?' },
    rewardName: 'Red Hood',
  },

  'hansel-and-gretel': {
    title: 'Hansel and Gretel',
    summary: 'A brother and sister get lost in the woods and use a clever plan, and great teamwork, to find their way safely home.',
    theme: 'cleverness and sticking together',
    scenes: [
      { text: 'Hansel and Gretel walked into the great forest, holding hands so they would not get lost.' },
      { text: 'Clever Hansel dropped small, shiny white pebbles one by one to mark the way back.', dialogue: { speaker: 'Hansel', line: 'These pebbles will shine and lead us home.' } },
      { text: 'They found a little house made of sweets, but a crafty old woman lived there.' },
      { text: 'The children were too clever to be tricked. They held hands and crept quietly outside.', dialogue: { speaker: 'Gretel', line: 'Quickly — together we are braver than alone.' } },
      { text: 'The shiny pebbles glittered in the moonlight and led them straight home to a warm hug.' },
    ],
    vocabulary: [
      { word: 'pebbles', meaning: 'small, smooth little stones', emoji: '🪨' },
      { word: 'clever', meaning: 'good at thinking of smart ideas', emoji: '💡' },
      { word: 'on tiptoe', meaning: 'walking very quietly on your toes', emoji: '🦶' },
      { word: 'together', meaning: 'with each other, side by side', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put Hansel\'s clever plan in the right order!', steps: ['Drop the shiny pebbles', 'Follow the glittering trail', 'Find the way back home'] },
    emotionalMoment: { feeling: 'brave together', prompt: 'The children were braver as a team. Who makes you feel braver?' },
    rewardName: 'Shiny Pebble',
  },

  'rapunzel': {
    title: 'Rapunzel',
    summary: 'A kind girl with very long hair lives in a tall tower and learns that patience and a heart full of hope can open any door.',
    theme: 'patience and hope',
    scenes: [
      { text: 'Right at the top of a tall tower lived Rapunzel, a girl with the longest golden plait in the world.' },
      { text: 'Every day, Rapunzel sang to the birds. Her sweet song floated all through the forest.', dialogue: { speaker: 'Rapunzel', line: 'One day I will see the world down there, beneath the trees.' } },
      { text: 'A kind traveller heard her song and called up: "Your music makes the whole forest smile!"', dialogue: { speaker: 'Traveller', line: 'Your music makes the whole forest smile!' } },
      { text: 'They became friends. Day after day, patiently, they thought of a clever way to climb down.' },
      { text: 'At last, Rapunzel set her foot on the soft grass and twirled in the sunshine, free and happy.', dialogue: { speaker: 'Rapunzel', line: 'Waiting was hard, but hope kept me strong.' } },
    ],
    vocabulary: [
      { word: 'tower', meaning: 'a very tall and narrow building', emoji: '🗼' },
      { word: 'plait', meaning: 'hair woven into a long rope-like braid', emoji: '💇' },
      { word: 'patience', meaning: 'waiting calmly without giving up', emoji: '⏳' },
      { word: 'meadow', meaning: 'a field of grass filled with flowers', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Find what Rapunzel used to climb down safely.', target: 'the golden plaited ladder', decoys: ['a paper kite', 'a wooden spoon', 'a little cup'] },
    emotionalMoment: { feeling: 'patient', prompt: 'Rapunzel waited with hope. What lovely thing have you waited a long time for?' },
    rewardName: 'Golden Plait',
  },

  'the-ugly-duckling': {
    title: 'The Ugly Duckling',
    summary: 'A little bird who feels different from the others grows up and discovers it was wonderful exactly as it was, all along.',
    theme: 'belonging and self-love',
    scenes: [
      { text: 'In a sunny pond, a little bird did not look like its brothers and sisters.' },
      { text: 'The other birds laughed at it, and deep inside it felt lonely and very sad.', dialogue: { speaker: 'Little bird', line: 'I wish someone would let me join in too.' } },
      { text: 'A kind frog hopped over and sat beside it. "You are welcome with me," it said.', dialogue: { speaker: 'Frog', line: 'You are welcome with me, my friend.' } },
      { text: 'The seasons passed. On a bright morning, the little bird saw its face in the still water.' },
      { text: 'It had become a beautiful swan! It had always been special — simply itself.', dialogue: { speaker: 'Swan', line: 'I did not need to change. I just needed to grow.' } },
    ],
    vocabulary: [
      { word: 'pond', meaning: 'a small stretch of calm water', emoji: '💧' },
      { word: 'lonely', meaning: 'sad because you feel all alone', emoji: '🥺' },
      { word: 'reflection', meaning: 'the image you see in still water', emoji: '🪞' },
      { word: 'swan', meaning: 'a large, graceful white water bird', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'A new friend feels left out. What kind thing could you say?', options: ['You don\'t belong here', 'You can play with us!', 'Go away'], answerIndex: 1 },
    emotionalMoment: { feeling: 'I belong', prompt: 'The little bird was special just as it was. What makes you a wonderful you?' },
    rewardName: 'Gentle Swan',
  },

  'the-little-mermaid': {
    title: 'The Little Mermaid',
    summary: 'A curious young mermaid bravely explores a new world and learns that a kind and generous heart shines brighter than anything.',
    theme: 'courage and a good heart',
    scenes: [
      { text: 'Deep beneath the waves lived a young mermaid, the smallest of six sisters.' },
      { text: 'She loved to swim to the surface and gaze at the bright world above the water.', dialogue: { speaker: 'Mermaid', line: 'The world up there is full of things I want to learn!' } },
      { text: 'On a stormy night, she bravely helped a sailor reach the shore safely.' },
      { text: 'She did not stay to be thanked. Helping someone filled her heart with warmth.', dialogue: { speaker: 'Mermaid', line: 'I helped out of kindness, not for a thank-you.' } },
      { text: 'Back home, she told her brave story, and her good heart made the whole sea shine.' },
    ],
    vocabulary: [
      { word: 'mermaid', meaning: 'an imaginary sea girl with a fish\'s tail', emoji: '🧜' },
      { word: 'waves', meaning: 'water that rises and falls on the sea', emoji: '🌊' },
      { word: 'brave', meaning: 'doing a hard thing even when it is scary', emoji: '💪' },
      { word: 'generous', meaning: 'happy to give and help others', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'How many older sisters did the Little Mermaid have?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'big-hearted', prompt: 'The mermaid helped purely out of kindness. When have you helped without being asked?' },
    rewardName: 'Sea Pearl',
  },

  'the-snow-queen': {
    title: 'The Snow Queen',
    summary: 'When her best friend\'s heart turns cold, a faithful girl called Gerda travels far through the snow to warm him with love.',
    theme: 'faithful friendship',
    scenes: [
      { text: 'Gerda and Kai were best friends and grew roses together by their window.' },
      { text: 'A tiny sliver of frost touched Kai\'s heart, and he became cold and distant.', dialogue: { speaker: 'Gerda', line: 'Wait... where are you going, Kai?' } },
      { text: 'Brave Gerda did not give up. She set off through the snow to find her friend.', dialogue: { speaker: 'Gerda', line: 'I will find you, Kai. Friends don\'t give up.' } },
      { text: 'She found Kai in an ice palace, sitting still and cold as stone.' },
      { text: 'Gerda hugged him and warm tears fell. The frost melted, and Kai smiled and remembered.', dialogue: { speaker: 'Kai', line: 'You came all this way for me. Thank you, Gerda.' } },
    ],
    vocabulary: [
      { word: 'frost', meaning: 'a thin layer of ice that forms when it is very cold', emoji: '🌨️' },
      { word: 'faithful', meaning: 'always there for your friends', emoji: '🤲' },
      { word: 'palace', meaning: 'a very large and beautiful house', emoji: '🏰' },
      { word: 'melt', meaning: 'to go from ice to water with warmth', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'How did Gerda melt the ice in Kai\'s heart?', options: ['With a big fire', 'With warm tears and a hug', 'With a hammer'], answerIndex: 1 },
    emotionalMoment: { feeling: 'faithful', prompt: 'Gerda never gave up on her friend. How do you show a friend you care about them?' },
    rewardName: 'Warm Rose',
  },

  'puss-in-boots': {
    title: 'Puss in Boots',
    summary: 'A clever cat in fine boots uses his quick wits and loyal heart to help his kind friend find happiness.',
    theme: 'cleverness and loyalty',
    scenes: [
      { text: 'A clever cat pulled on fine boots and a feathered hat, ready for adventure.' },
      { text: 'His friend was poor but kind, so the cat thought of a clever plan to help him.', dialogue: { speaker: 'The Cat', line: 'Trust me, my friend. A clever idea is on its way!' } },
      { text: 'The cat greeted the king politely and offered gifts, making everyone smile.' },
      { text: 'With wit rather than tricks, the cat helped his friend win a grand castle by the river.', dialogue: { speaker: 'The Cat', line: 'Good ideas open more doors than loud roars.' } },
      { text: 'His friend was happy at last, and the cat curled up by the fire, the most faithful cat of all.' },
    ],
    vocabulary: [
      { word: 'clever', meaning: 'good at thinking of smart ideas', emoji: '🧠' },
      { word: 'boots', meaning: 'shoes that go up high on your legs', emoji: '🥾' },
      { word: 'polite', meaning: 'kind and gentle with your words', emoji: '🙏' },
      { word: 'loyal', meaning: 'always there for your friends', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put the Cat\'s clever plan in the right order!', steps: ['Put on the fine boots', 'Greet the king politely', 'Help his friend win the day'] },
    emotionalMoment: { feeling: 'helpful', prompt: 'The Cat used clever ideas to help a friend. In what clever way have you helped someone?' },
    rewardName: 'Fine Boots',
  },

  'pinocchio': {
    title: 'Pinocchio',
    summary: 'A wooden puppet who dreams of being a real boy learns that telling the truth is what makes a good heart grow.',
    theme: 'honesty',
    scenes: [
      { text: 'Once upon a time there was a little wooden puppet called Pinocchio, who dreamed of becoming a real boy.' },
      { text: 'Every time Pinocchio told a lie, his nose grew longer like a branch.', dialogue: { speaker: 'Pinocchio', line: 'It wasn\'t me! I promise!' } },
      { text: 'His friend the cricket tried to teach him always to tell the truth.', dialogue: { speaker: 'Cricket', line: 'Telling the truth will make you feel light as a feather.' } },
      { text: 'Pinocchio made a big mistake and got lost. He learned then that honesty was his only guide.' },
      { text: 'When Pinocchio finally told the truth, his heart grew, and his dearest wish came true.', dialogue: { speaker: 'Pinocchio', line: 'The truth is the most powerful magic of all.' } },
    ],
    vocabulary: [
      { word: 'puppet', meaning: 'a doll that is made to move', emoji: '🎭' },
      { word: 'truth', meaning: 'saying exactly what happened', emoji: '✅' },
      { word: 'lie', meaning: 'saying something that is not true', emoji: '❌' },
      { word: 'honest', meaning: 'someone who always tells the truth', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'When does Pinocchio\'s nose grow longer?', options: ['When he tells the truth', 'When he tells a lie', 'When he sings a song'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honest', prompt: 'Telling the truth made Pinocchio feel light. How do you feel when you tell the truth?' },
    rewardName: 'Cricket of Truth',
  },

  'peter-pan': {
    title: 'Peter Pan',
    summary: 'A boy who never grows up takes new friends on a flying adventure where happy thoughts and a little courage take you anywhere.',
    theme: 'imagination and courage',
    scenes: [
      { text: 'In a bedroom full of stars, a boy called Peter Pan taught the children to fly.' },
      { text: 'Peter told Wendy the secret: you had to think of something very happy.', dialogue: { speaker: 'Peter Pan', line: 'Think of your happiest thing — and off you go!' } },
      { text: 'Together they flew to Neverland, a magical island full of adventures.' },
      { text: 'Even facing the wicked captain, Peter was not afraid. He met danger with a big smile.', dialogue: { speaker: 'Peter Pan', line: 'Being brave means trying anyway.' } },
      { text: 'The children went home with hearts full of memories and a little magic for ever.' },
    ],
    vocabulary: [
      { word: 'bedroom', meaning: 'the room where you sleep and dream', emoji: '🛏️' },
      { word: 'shadow', meaning: 'the dark shape your body makes on the ground', emoji: '👤' },
      { word: 'imagine', meaning: 'to create beautiful things inside your head', emoji: '💭' },
      { word: 'courage', meaning: 'trying even when you are scared', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'What helped the children fly?', options: ['Happy thoughts and fairy dust', 'Heavy boots', 'Shouting very loudly'], answerIndex: 0 },
    emotionalMoment: { feeling: 'brave', prompt: 'Peter says being brave means trying anyway. What brave thing would you like to try?' },
    rewardName: 'Fairy Dust',
  },

  'alice-in-wonderland': {
    title: 'Alice in Wonderland',
    summary: 'A curious girl follows a hurrying rabbit into a topsy-turvy world and learns that asking questions is a kind of magic.',
    theme: 'curiosity',
    scenes: [
      { text: 'Alice saw a hurrying white rabbit jump into a hole and, feeling very curious, she followed it.' },
      { text: 'She fell down a long magical tunnel and found a tiny door into a garden.', dialogue: { speaker: 'Alice', line: 'How very strange! I wonder what is going on here.' } },
      { text: 'Alice drank a little bottle and shrank, then ate a cake and grew very quickly.', dialogue: { speaker: 'Alice', line: 'Questions are the key to all the wonders!' } },
      { text: 'She met a grinning cat, an angry queen, and a very mad hatter.' },
      { text: 'Alice woke up and smiled. Asking questions had led her to the most beautiful of dreams.', dialogue: { speaker: 'Alice', line: 'Curiosity is the greatest adventure.' } },
    ],
    vocabulary: [
      { word: 'curious', meaning: 'someone who loves discovering new things', emoji: '🔍' },
      { word: 'burrow', meaning: 'a tunnel dug in the earth by an animal', emoji: '🕳️' },
      { word: 'shrink', meaning: 'to become smaller', emoji: '🔻' },
      { word: 'wonder', meaning: 'something incredible and very surprising', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Put Alice\'s adventure in the right order!', steps: ['Drink the bottle and shrink', 'Eat the cake and grow', 'Find the tiny garden door'] },
    emotionalMoment: { feeling: 'curious', prompt: 'Alice loved asking questions. What makes you curious today?' },
    rewardName: 'Curious Clock',
  },

  'the-wizard-of-oz': {
    title: 'The Wizard of Oz',
    summary: 'A girl and three new friends follow a golden road and discover that the gifts they were searching for were inside them all along.',
    theme: 'you already have what you need',
    scenes: [
      { text: 'A great whirlwind carried Dorothy and her little dog Toto away to the magical land of Oz.' },
      { text: 'On the golden road, Dorothy met a scarecrow, a tin man, and a lion.', dialogue: { speaker: 'Scarecrow', line: 'I just want a clever brain!' } },
      { text: 'Together they walked towards the Emerald City to find the great Wizard.', dialogue: { speaker: 'Dorothy', line: 'If we are together, we can do anything.' } },
      { text: 'The Wizard revealed a great secret: they already had everything they desired.' },
      { text: 'Dorothy tapped her shoes three times and was back home. Everyone had found their gift.', dialogue: { speaker: 'Dorothy', line: 'There is no place like home.' } },
    ],
    vocabulary: [
      { word: 'whirlwind', meaning: 'a very strong wind that spins round and round', emoji: '🌪️' },
      { word: 'scarecrow', meaning: 'a large straw figure put out to frighten birds', emoji: '🌾' },
      { word: 'courage', meaning: 'to keep going even when you are afraid', emoji: '💪' },
      { word: 'journey', meaning: 'a long walk or adventure to a new place', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Which friend already had courage from the very beginning?', options: ['The scarecrow', 'The tin man', 'The lion'], answerIndex: 2 },
    emotionalMoment: { feeling: 'capable', prompt: 'The friends already had their gifts inside them. What gift do you already have inside you?' },
    rewardName: 'Sparkling Shoes',
  },

  'robin-hood': {
    title: 'Robin Hood',
    summary: 'A kind archer from the green forest shares with those who have very little and teaches his friends that fairness makes everyone happier.',
    theme: 'fairness and generosity',
    scenes: [
      { text: 'In a great green forest lived Robin Hood, the finest archer in the land.' },
      { text: 'He saw that many people were very poor while others had everything.', dialogue: { speaker: 'Robin', line: 'Sharing is the finest gift of all.' } },
      { text: 'With his merry friends, Robin made a plan to help those in need.', dialogue: { speaker: 'Little John', line: 'Together we are the strength of the forest!' } },
      { text: 'Robin gave people what they needed, and smiles appeared everywhere.' },
      { text: 'The forest hummed with happiness. Robin had learned that generosity is the true victory.', dialogue: { speaker: 'Robin', line: 'Generosity makes everyone richer.' } },
    ],
    vocabulary: [
      { word: 'archer', meaning: 'someone who shoots arrows with a bow', emoji: '🎯' },
      { word: 'forest', meaning: 'a large place full of trees and animals', emoji: '🌳' },
      { word: 'fair', meaning: 'treating everyone in the same way', emoji: '⚖️' },
      { word: 'generous', meaning: 'happy to give and share', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin Hood shared with people who were...', options: ['hungry and in need', 'already very rich', 'unkind to others'], answerIndex: 0 },
    emotionalMoment: { feeling: 'fair', prompt: 'Robin loved to share. What could you share to make a friend smile?' },
    rewardName: 'Friendly Bow',
  },

  'goldilocks': {
    title: 'Goldilocks',
    summary: 'A curious girl steps into the bears\' cosy cottage and learns that it is best to ask first and take care of other people\'s things.',
    theme: 'respect for others',
    scenes: [
      { text: 'A little girl with golden curls was walking through the forest when she found a pretty cottage.' },
      { text: 'She went inside and tasted three bowls of porridge. The baby bear\'s was just right.', dialogue: { speaker: 'Goldilocks', line: 'Oh! This bowl is perfect — not too hot and not too cold!' } },
      { text: 'She tried three chairs, then three beds. She fell asleep in the cosiest one.' },
      { text: 'The three bears came home and found their house all mixed up.', dialogue: { speaker: 'Baby Bear', line: 'Someone has been eating my porridge!' } },
      { text: 'Goldilocks woke up, said sorry, and learned that asking first is the kindest manners.', dialogue: { speaker: 'Goldilocks', line: 'Sorry. I will always ask before I come in.' } },
    ],
    vocabulary: [
      { word: 'porridge', meaning: 'warm, soft food, like breakfast cereal', emoji: '🥣' },
      { word: 'cottage', meaning: 'a small, cosy house in the forest', emoji: '🏡' },
      { word: 'respect', meaning: 'taking care of other people\'s things and feelings', emoji: '🙏' },
      { word: 'sorry', meaning: 'what you say when you regret something', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'How many bears lived in the cosy cottage?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respectful', prompt: 'Goldilocks learned to ask first. When is it kind to ask permission before borrowing something?' },
    rewardName: 'Perfect Bowl',
  },

  'three-little-pigs': {
    title: 'The Three Little Pigs',
    summary: 'Three little pigs build three different houses and learn that careful, hard work keeps everyone safe and warm.',
    theme: 'hard work and planning',
    scenes: [
      { text: 'Three little pigs set off into the world to build their houses.' },
      { text: 'The first pig quickly built a house of straw. The second built a house of wood.', dialogue: { speaker: 'First pig', line: 'Quick and done! I want to go and play!' } },
      { text: 'The third pig worked hard and built a solid house of bricks, one by one.', dialogue: { speaker: 'Third pig', line: 'I am taking my time so my house will be strong.' } },
      { text: 'The big bad wolf blew down the houses of straw and wood, and they collapsed.' },
      { text: 'But the brick house stayed firm. The three pigs were safe, and everyone learned that careful work protects.', dialogue: { speaker: 'Third pig', line: 'Good work takes time, but it is worth it!' } },
    ],
    vocabulary: [
      { word: 'straw', meaning: 'dry plant stems that are easy to break', emoji: '🌾' },
      { word: 'bricks', meaning: 'very strong baked earth blocks', emoji: '🧱' },
      { word: 'strong', meaning: 'very solid and not easy to break', emoji: '💪' },
      { word: 'plan', meaning: 'to think carefully before you start something', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'How many little pigs built houses?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'proud of my work', prompt: 'The third pig worked hard and stayed safe. What have you worked hard on?' },
    rewardName: 'Solid Brick',
  },

  'aladdin': {
    title: 'Aladdin',
    summary: 'An ordinary but kind boy finds a magic lamp and learns that what you wish for matters far less than the good you do for others.',
    theme: 'honesty and humility',
    scenes: [
      { text: 'In a busy market lived Aladdin, a poor boy with a heart of gold.' },
      { text: 'He found an old lamp and, when he rubbed it, a great genie appeared!', dialogue: { speaker: 'Genie', line: 'I grant you three wishes. Choose carefully!' } },
      { text: 'Aladdin first wished to help his family, then the poor people of his neighbourhood.', dialogue: { speaker: 'Aladdin', line: 'I want no one in this market to go hungry.' } },
      { text: 'His humility and generosity earned him true friends and a great deal of happiness.' },
      { text: 'Aladdin learned that the best wishes are the ones you make for others.', dialogue: { speaker: 'Aladdin', line: 'A generous heart is the greatest treasure.' } },
    ],
    vocabulary: [
      { word: 'market', meaning: 'a busy place where people sell and buy things', emoji: '🏪' },
      { word: 'lamp', meaning: 'an object that gives light or holds a genie', emoji: '🪔' },
      { word: 'humble', meaning: 'someone who does not boast about themselves', emoji: '🙏' },
      { word: 'wish', meaning: 'something you want very, very much', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'How many wishes did the genie give Aladdin?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'generous', prompt: 'Aladdin wished to help others. If you had one kind wish, what would it be?' },
    rewardName: 'Wishing Lamp',
  },

  'ali-baba': {
    title: 'Ali Baba',
    summary: 'A gentle woodcutter discovers a secret cave and learns that being honest and careful is worth far more than being greedy.',
    theme: 'honesty over greed',
    scenes: [
      { text: 'Ali Baba was a gentle woodcutter who lived simply and happily.' },
      { text: 'One day in the forest, he heard thieves say the magic words in front of a great rock.', dialogue: { speaker: 'Thieves', line: 'Open Sesame!' } },
      { text: 'Ali Baba entered the cave and saw dazzling treasures of every colour.', dialogue: { speaker: 'Ali Baba', line: 'I will take only what we need — no more.' } },
      { text: 'His greedy brother took too much and was caught by the thieves. Ali Baba understood the lesson.' },
      { text: 'Ali Baba shared his good fortune with others and lived simply and happily.', dialogue: { speaker: 'Ali Baba', line: 'Having enough and being honest — that is true wealth.' } },
    ],
    vocabulary: [
      { word: 'cave', meaning: 'a large, natural hollow in the rock', emoji: '🕳️' },
      { word: 'treasure', meaning: 'a large amount of gold and precious things', emoji: '💎' },
      { word: 'greedy', meaning: 'someone who always wants more than they need', emoji: '😤' },
      { word: 'enough', meaning: 'just what you need — no more and no less', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'What magic words open the cave?', options: ['Open Sesame!', 'Shut the door!', 'Good morning!'], answerIndex: 0 },
    emotionalMoment: { feeling: 'content', prompt: 'Ali Baba only took what was needed. What thing you already have is just enough for you?' },
    rewardName: 'Secret Cave',
  },

  'aesops-fables': {
    title: 'The Hare and the Tortoise',
    summary: 'A speedy hare and a slow tortoise have a friendly race, and the tortoise shows everyone that never giving up wins the day.',
    theme: 'perseverance — slow and steady',
    scenes: [
      { text: 'In a sunny meadow, a speedy hare was always boasting about how fast he was.' },
      { text: 'The slow, calm tortoise suggested a race. The hare accepted with a laugh.', dialogue: { speaker: 'Hare', line: 'A race against you? Easy! I\'ll have a rest on the way.' } },
      { text: 'The tortoise moved step by step, steadily, never stopping.', dialogue: { speaker: 'Tortoise', line: 'Slow and steady, I will keep moving forward.' } },
      { text: 'The hare fell asleep under a tree, sure that the tortoise could never catch up.' },
      { text: 'When the hare woke up, the tortoise had already crossed the finish line. Perseverance always wins.', dialogue: { speaker: 'Tortoise', line: 'Step by step, you get further than you think.' } },
    ],
    vocabulary: [
      { word: 'hare', meaning: 'a large, wild rabbit that is very fast', emoji: '🐇' },
      { word: 'tortoise', meaning: 'a shelled animal that walks slowly but never stops', emoji: '🐢' },
      { word: 'steady', meaning: 'moving at the same pace without stopping', emoji: '⏱️' },
      { word: 'persevere', meaning: 'to keep trying even when it is hard', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Who won the race by never giving up?', options: ['the speedy hare', 'the slow, steady tortoise', 'the sleeping fox'], answerIndex: 1 },
    emotionalMoment: { feeling: 'determined', prompt: 'The tortoise kept going step by step. What do you keep trying at?' },
    rewardName: 'Persevering Tortoise',
  },
};
