// French fairy tale content for the Story Library feature.
//
// coverImage: public-domain illustrations from Wikimedia Commons
// All images pre-1927, sourced from Project Gutenberg / archive.org mirrors

// Wikimedia Commons thumb helper — stable CDN URLs
const WM = (path, w = 320) =>
  `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}/${w}px-${path.split('/').pop()}`;

export const CONTES = [
  {
    id: 'snow-white',
    coverImage: WM('f/f8/Snow-white-1882.jpg'),
    title: 'Blanche-Neige',
    summary: 'Une douce princesse a la peau blanche comme la neige trouve un foyer aupres de sept petits aides bienveillants et apprend que les vrais amis veillent les uns sur les autres.',
    theme: 'gentillesse et amitie',
    emoji: '🍎',
    palette: { primary: '#C0392B', accent: '#F8C8DC', background: '#FFF5F6' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Il y a longtemps, une petite princesse naquit avec la peau blanche comme la neige. Tout le monde l\'appelait Blanche-Neige.' },
      { text: 'Une reine jalouse possedait un miroir magique et lui posait la meme question chaque jour.', dialogue: { speaker: 'Reine', line: 'Miroir, miroir, qui est la plus gentille et la plus belle de toutes ?' } },
      { text: 'Blanche-Neige marcha au coeur de la foret. Sept petits mineurs bienveillants l\'accueillirent dans leur chaumiere douillette.', dialogue: { speaker: 'Un mineur', line: 'Tu es en securite ici, petite amie. Viens te reposer.' } },
      { text: 'La reine la trompa avec une pomme brillante, et Blanche-Neige tomba dans un sommeil tres, tres profond.' },
      { text: 'Une amie attentionnee la reveilla d\'un geste tout doux. Blanche-Neige sourit, et tous feterent leur courageuse amie.', dialogue: { speaker: 'Blanche-Neige', line: 'Vous ne m\'avez jamais quittee. Merci, mes amis !' } },
    ],
    vocabulary: [
      { word: 'la plus belle', meaning: 'la plus gentille et la plus jolie', emoji: '🌷' },
      { word: 'jalouse', meaning: 'fachee parce qu\'on veut ce qu\'un autre a', emoji: '😠' },
      { word: 'chaumiere', meaning: 'une petite maison toute douillette', emoji: '🏡' },
      { word: 'accueillir', meaning: 'rendre quelqu\'un heureux d\'etre arrive', emoji: '🤗' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de gentils petits mineurs ont accueilli Blanche-Neige ?', answer: 7, options: [6, 7, 8] },
    emotionalMoment: { feeling: 'entoure et protege', prompt: 'Les amis de Blanche-Neige veillaient sur elle. Qui veille sur toi ?' },
    rewardEmoji: '🪞',
    rewardName: 'Miroir bienveillant',
  },
  {
    id: 'cinderella',
    coverImage: WM('6/60/Cinderella_canziani.jpg'),
    title: 'Cendrillon',
    summary: 'Une fille travailleuse et au grand coeur recoit un peu d\'aide d\'une amie magique et decouvre qu\'etre gentille est une magie en soi.',
    theme: 'espoir et gentillesse',
    emoji: '👠',
    palette: { primary: '#6C5CE7', accent: '#A29BFE', background: '#F4F2FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Cendrillon faisait toutes les taches et ne perdait jamais son doux sourire, meme quand les autres etaient mechants.' },
      { text: 'Un soir, un grand bal fut annonce, mais Cendrillon n\'avait rien a se mettre.', dialogue: { speaker: 'Cendrillon', line: 'Si seulement je pouvais aller danser, juste une fois.' } },
      { text: 'Une gentille fee apparut et, d\'un coup de baguette, changea une citrouille en carrosse.', dialogue: { speaker: 'Fee amie', line: 'Rentre avant minuit, ma cherie — la magie s\'arrete alors.' } },
      { text: 'Au bal, Cendrillon dansa et rit. Mais quand l\'horloge se mit a sonner, elle dut courir.' },
      { text: 'La pantoufle lui allait parfaitement. Sa gentillesse s\'etait vue depuis toujours, et la joie remplit ses journees.', dialogue: { speaker: 'Cendrillon', line: 'Etre gentil ne coute rien.' } },
    ],
    vocabulary: [
      { word: 'taches', meaning: 'petits travaux pour aider a la maison', emoji: '🧹' },
      { word: 'carrosse', meaning: 'une voiture tiree pour transporter des gens', emoji: '🛞' },
      { word: 'minuit', meaning: 'douze heures de la nuit', emoji: '🕛' },
      { word: 'doux', meaning: 'tendre, calme et gentil', emoji: '🕊️' },
    ],
    miniGame: { type: 'count', prompt: 'A quelle heure Cendrillon doit-elle rentrer ? Compte les coups de l\'horloge !', answer: 12, options: [10, 11, 12] },
    emotionalMoment: { feeling: 'plein d\'espoir', prompt: 'Meme les jours difficiles, Cendrillon restait gentille. Qu\'est-ce qui t\'aide a garder espoir ?' },
    rewardEmoji: '👠',
    rewardName: 'Pantoufle de verre',
  },
  {
    id: 'little-red-riding-hood',
    coverImage: WM('c/c2/Carl_Larsson_-_Little_Red_Riding_Hood_1881.jpg'),
    title: 'Le Petit Chaperon rouge',
    summary: 'Une petite fille courageuse au chaperon rouge va chez sa grand-mere et apprend a ecouter ses sentiments sages en chemin.',
    theme: 'ecouter et rester en securite',
    emoji: '🧣',
    palette: { primary: '#E84855', accent: '#FFB3B3', background: '#FFF4F2' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Une petite fille portait partout un chaperon rouge vif ; alors tout le monde l\'appelait le Petit Chaperon rouge.' },
      { text: 'Sa maman lui donna un panier de pain pour mamie.', dialogue: { speaker: 'Maman', line: 'Reste sur le chemin et tout ira tres bien.' } },
      { text: 'Dans les bois, un loup ruse posa beaucoup de questions. Le Petit Chaperon sentit quelque chose de bizarre et continua a marcher.', dialogue: { speaker: 'Petit Chaperon', line: 'Je n\'ai pas a te repondre. Je le dirai a un adulte.' } },
      { text: 'Un gentil bucheron l\'entendit et marcha avec elle. Ensemble, ils arriverent chez mamie.' },
      { text: 'Mamie etait en securite, et le Petit Chaperon aussi. Ils partagerent du bon pain chaud et rirent tout l\'apres-midi.', dialogue: { speaker: 'Mamie', line: 'Tu as ecoute tes sentiments sages. Je suis fiere de toi.' } },
    ],
    vocabulary: [
      { word: 'chemin', meaning: 'une voie qui montre par ou aller en securite', emoji: '🛤️' },
      { word: 'panier', meaning: 'un porteur avec une anse pour transporter des choses', emoji: '🧺' },
      { word: 'ruse', meaning: 'qui fait des tours pour te tromper', emoji: '🦊' },
      { word: 'bucheron', meaning: 'une personne qui travaille parmi les arbres', emoji: '🪓' },
    ],
    miniGame: { type: 'choice', prompt: 'Un inconnu demande au Petit Chaperon ou elle va. Quel est le choix sur ?', options: ['Tout lui raconter', 'Continuer a marcher et prevenir un adulte', 'Le suivre entre les arbres'], answerIndex: 1 },
    emotionalMoment: { feeling: 'en securite', prompt: 'Le Petit Chaperon a ecoute sa sensation bizarre. Quand un sentiment t\'a-t-il aide a rester en securite ?' },
    rewardEmoji: '🧣',
    rewardName: 'Chaperon rouge',
  },
  {
    id: 'hansel-and-gretel',
    coverImage: WM('a/a4/Hansel_and_Gretel4.jpg'),
    title: 'Hansel et Gretel',
    summary: 'Un frere et une soeur se perdent dans les bois et utilisent un plan astucieux, et leur esprit d\'equipe, pour rentrer sains et saufs.',
    theme: 'astuce et rester ensemble',
    emoji: '✨',
    palette: { primary: '#B7791F', accent: '#FBD38D', background: '#FFFBF0' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Hansel et Gretel entrerent dans la grande foret, se tenant la main pour ne pas se perdre.' },
      { text: 'L\'astucieux Hansel laissa tomber de petits cailloux blancs et brillants, un a un, pour marquer le retour.', dialogue: { speaker: 'Hansel', line: 'Ces cailloux brilleront et nous rameneront a la maison.' } },
      { text: 'Ils trouverent une petite maison faite de friandises, mais une vieille femme rusee y habitait.' },
      { text: 'Les enfants etaient trop malins pour se laisser tromper. Ils se prirent la main et sortirent sur la pointe des pieds.', dialogue: { speaker: 'Gretel', line: 'Vite — ensemble, nous sommes plus courageux que seuls.' } },
      { text: 'Les cailloux brillants luisirent au clair de lune et les ramenerent droit a la maison, vers un calin tout chaud.' },
    ],
    vocabulary: [
      { word: 'cailloux', meaning: 'de petites pierres bien lisses', emoji: '🪨' },
      { word: 'astucieux', meaning: 'doue pour trouver des idees malines', emoji: '💡' },
      { word: 'sur la pointe des pieds', meaning: 'marcher tout doucement sur les orteils', emoji: '🦶' },
      { word: 'ensemble', meaning: 'l\'un avec l\'autre, cote a cote', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets le plan astucieux de Hansel dans l\'ordre !', steps: ['Laisser tomber les cailloux brillants', 'Suivre la piste qui scintille', 'Retrouver le chemin de la maison'] },
    emotionalMoment: { feeling: 'courageux ensemble', prompt: 'Les enfants etaient plus courageux en equipe. Qui te rend plus courageux ?' },
    rewardEmoji: '✨',
    rewardName: 'Caillou brillant',
  },
  {
    id: 'rapunzel',
    coverImage: WM('4/4e/Rapunzel_-_Vintage_Illustration.jpg'),
    title: 'Raiponce',
    summary: 'Une gentille fille aux tres longs cheveux vit dans une haute tour et apprend que la patience et un coeur plein d\'espoir peuvent ouvrir n\'importe quelle porte.',
    theme: 'patience et espoir',
    emoji: '👑',
    palette: { primary: '#9B59B6', accent: '#D7BDE2', background: '#FAF4FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Tout en haut d\'une grande tour vivait Raiponce, une fille avec la plus longue tresse doree du monde.' },
      { text: 'Chaque jour, Raiponce chantait aux oiseaux. Sa douce chanson flottait sur toute la foret.', dialogue: { speaker: 'Raiponce', line: 'Un jour, je verrai le monde la-bas, sous les arbres.' } },
      { text: 'Un gentil voyageur entendit sa chanson et lui cria : "Ta musique fait sourire la foret !"', dialogue: { speaker: 'Voyageur', line: 'Ta musique fait sourire toute la foret !' } },
      { text: 'Ils devinrent amis. Jour apres jour, avec patience, ils imaginerent une maniere maline de descendre.' },
      { text: 'Enfin, Raiponce posa le pied sur l\'herbe douce et tournoya au soleil, libre et heureuse.', dialogue: { speaker: 'Raiponce', line: 'Attendre etait dur, mais l\'espoir m\'a gardee forte.' } },
    ],
    vocabulary: [
      { word: 'tour', meaning: 'un batiment tres haut et etroit', emoji: '🗼' },
      { word: 'tresse', meaning: 'des cheveux tisses en une longue corde', emoji: '💇' },
      { word: 'patience', meaning: 'attendre calmement sans abandonner', emoji: '⏳' },
      { word: 'prairie', meaning: 'un champ d\'herbe plein de fleurs', emoji: '🌼' },
    ],
    miniGame: { type: 'find', prompt: 'Trouve ce que Raiponce a utilise pour descendre en securite.', target: 'l\'echelle en tresse doree', decoys: ['un cerf-volant en papier', 'une cuillere en bois', 'une petite tasse'] },
    emotionalMoment: { feeling: 'patient', prompt: 'Raiponce a attendu avec espoir. Quelle belle chose as-tu attendue longtemps ?' },
    rewardEmoji: '👑',
    rewardName: 'Tresse doree',
  },
  {
    id: 'the-ugly-duckling',
    coverImage: WM('9/97/The_Ugly_Duckling_-_Project_Gutenberg_etext_19993.jpg'),
    title: 'Le Vilain Petit Canard',
    summary: 'Un petit oiseau qui se sent different des autres grandit et decouvre qu\'il etait merveilleux exactement comme il etait, depuis toujours.',
    theme: 'appartenir et s\'aimer',
    emoji: '🦢',
    palette: { primary: '#3498DB', accent: '#AED6F1', background: '#EBF5FB' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Dans une mare ensoleillee, un petit oiseau ne ressemblait pas a ses freres et soeurs.' },
      { text: 'Les autres oiseaux se moquaient de lui, et au fond il se sentait seul et tres triste.', dialogue: { speaker: 'Petit oiseau', line: 'J\'aimerais que quelqu\'un me laisse jouer aussi.' } },
      { text: 'Une gentille grenouille s\'approcha en sautant et s\'assit pres de lui. "Tu es le bienvenu avec moi", dit-elle.', dialogue: { speaker: 'Grenouille', line: 'Tu es le bienvenu avec moi, mon ami.' } },
      { text: 'Les saisons passerent. Un matin lumineux, le petit oiseau vit son visage dans l\'eau calme.' },
      { text: 'Il etait devenu un magnifique cygne ! Il avait toujours ete special : tout simplement lui-meme.', dialogue: { speaker: 'Cygne', line: 'Je n\'avais pas besoin de changer. J\'avais juste besoin de grandir.' } },
    ],
    vocabulary: [
      { word: 'mare', meaning: 'une petite etendue d\'eau calme', emoji: '💧' },
      { word: 'seul', meaning: 'triste parce qu\'on se sent tout seul', emoji: '🥺' },
      { word: 'reflet', meaning: 'l\'image que tu vois dans l\'eau calme', emoji: '🪞' },
      { word: 'cygne', meaning: 'un grand oiseau d\'eau blanc et gracieux', emoji: '🦢' },
    ],
    miniGame: { type: 'choice', prompt: 'Un nouvel ami se sent mis a l\'ecart. Quelle chose gentille peux-tu dire ?', options: ['Tu n\'es pas a ta place ici', 'Tu peux jouer avec nous !', 'Va-t\'en'], answerIndex: 1 },
    emotionalMoment: { feeling: 'j\'ai ma place', prompt: 'Le petit oiseau etait special tel qu\'il etait. Qu\'est-ce qui fait de toi un merveilleux toi ?' },
    rewardEmoji: '🦢',
    rewardName: 'Cygne tout doux',
  },
  {
    id: 'the-little-mermaid',
    coverImage: WM('2/20/The_Little_Mermaid_-_Illustration_by_Edmund_Dulac.jpg'),
    title: 'La Petite Sirene',
    summary: 'Une jeune sirene curieuse a le courage d\'explorer un monde nouveau, et apprend qu\'un coeur gentil et genereux brille plus que tout.',
    theme: 'courage et bon coeur',
    emoji: '🐚',
    palette: { primary: '#1ABC9C', accent: '#A9DFBF', background: '#F0FBF7' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Au fond des vagues vivait une jeune sirene, la plus petite de six soeurs.' },
      { text: 'Elle adorait monter a la surface et regarder le monde lumineux au-dessus de l\'eau.', dialogue: { speaker: 'Sirene', line: 'Le monde d\'en haut est plein de choses que je veux apprendre !' } },
      { text: 'Une nuit de tempete, avec courage, elle aida un marin a rejoindre le rivage sain et sauf.' },
      { text: 'Elle ne resta pas pour etre remerciee. Aider quelqu\'un remplissait son coeur de chaleur.', dialogue: { speaker: 'Sirene', line: 'J\'ai aide par gentillesse, pas pour un merci.' } },
      { text: 'De retour chez elle, elle raconta son histoire courageuse, et son bon coeur fit briller toute la mer.' },
    ],
    vocabulary: [
      { word: 'sirene', meaning: 'une fille de la mer imaginaire, avec une queue de poisson', emoji: '🧜' },
      { word: 'vagues', meaning: 'l\'eau qui monte et descend sur la mer', emoji: '🌊' },
      { word: 'courageux', meaning: 'faire une chose difficile meme si elle fait peur', emoji: '💪' },
      { word: 'genereux', meaning: 'heureux de donner et d\'aider les autres', emoji: '💝' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de grandes soeurs avait la Petite Sirene ?', answer: 6, options: [5, 6, 7] },
    emotionalMoment: { feeling: 'au grand coeur', prompt: 'La sirene a aide juste par gentillesse. Quand as-tu aide sans qu\'on te le demande ?' },
    rewardEmoji: '🐚',
    rewardName: 'Perle de la mer',
  },
  {
    id: 'the-snow-queen',
    coverImage: WM('3/38/Edmund_Dulac_-_The_Snow_Queen.jpg'),
    title: 'La Reine des Neiges',
    summary: 'Quand le coeur de son meilleur ami devient froid, une fille fidele nommee Gerda voyage loin dans la neige pour le rechauffer avec amour.',
    theme: 'amitie fidele',
    emoji: '❄️',
    palette: { primary: '#5DADE2', accent: '#AED6F1', background: '#EBF5FB' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Gerda et Kai etaient les meilleurs amis et cultivaient des roses ensemble pres de leur fenetre.' },
      { text: 'Un tout petit eclat de givre toucha le coeur de Kai, et il devint froid et lointain.', dialogue: { speaker: 'Gerda', line: 'Attends... ou vas-tu, Kai ?' } },
      { text: 'La courageuse Gerda n\'abandonna pas. Elle partit a travers la neige chercher son ami.', dialogue: { speaker: 'Gerda', line: 'Je vais te retrouver, Kai. Les amis n\'abandonnent pas.' } },
      { text: 'Elle trouva Kai dans un palais de glace, assis, immobile et froid comme la pierre.' },
      { text: 'Gerda le serra dans ses bras et des larmes chaudes coulerent. Le givre fondit, et Kai sourit et se souvint.', dialogue: { speaker: 'Kai', line: 'Tu es venue jusqu\'ici pour moi. Merci, Gerda.' } },
    ],
    vocabulary: [
      { word: 'givre', meaning: 'une fine glace qui se forme quand il fait tres froid', emoji: '🌨️' },
      { word: 'fidele', meaning: 'toujours la pour ses amis', emoji: '🤲' },
      { word: 'palais', meaning: 'une maison tres grande et magnifique', emoji: '🏰' },
      { word: 'fondre', meaning: 'passer de la glace a l\'eau avec la chaleur', emoji: '💧' },
    ],
    miniGame: { type: 'choice', prompt: 'Comment Gerda a-t-elle fait fondre la glace dans le coeur de Kai ?', options: ['Avec un grand feu', 'Avec des larmes chaudes et un calin', 'Avec un marteau'], answerIndex: 1 },
    emotionalMoment: { feeling: 'fidele', prompt: 'Gerda n\'a jamais abandonne son ami. Comment montres-tu a un ami que tu tiens a lui ?' },
    rewardEmoji: '🌹',
    rewardName: 'Rose toute chaude',
  },
  {
    id: 'puss-in-boots',
    coverImage: WM('d/d4/Puss_in_boots_briton_riviere.jpg'),
    title: 'Le Chat botte',
    summary: 'Un chat malin aux belles bottes utilise sa vivacite d\'esprit, et son grand coeur fidele, pour aider son gentil ami a trouver le bonheur.',
    theme: 'astuce et loyaute',
    emoji: '🐱',
    palette: { primary: '#E67E22', accent: '#FAD7A0', background: '#FFFAF0' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Un chat malin enfila de belles bottes et un chapeau a plume, pret pour l\'aventure.' },
      { text: 'Son ami etait pauvre mais gentil, alors le chat imagina un plan malin pour l\'aider.', dialogue: { speaker: 'Le Chat', line: 'Fais-moi confiance, mon ami. Une idee maline arrive !' } },
      { text: 'Le chat salua le roi avec politesse et offrit des cadeaux, faisant sourire tout le monde.' },
      { text: 'Avec de l\'esprit plutot que des ruses, le chat aida son ami a gagner un grand chateau au bord de la riviere.', dialogue: { speaker: 'Le Chat', line: 'Les bonnes idees ouvrent plus de portes que les grands rugissements.' } },
      { text: 'Son ami fut enfin heureux, et le chat se pelotonna pres du feu, le chat le plus fidele de tous.' },
    ],
    vocabulary: [
      { word: 'malin', meaning: 'doue pour trouver des idees astucieuses', emoji: '🧠' },
      { word: 'bottes', meaning: 'des chaussures qui montent haut sur les jambes', emoji: '🥾' },
      { word: 'poli', meaning: 'gentil et doux avec ses mots', emoji: '🙏' },
      { word: 'fidele', meaning: 'toujours la pour ses amis', emoji: '🤝' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets le plan malin du Chat dans l\'ordre !', steps: ['Enfiler les belles bottes', 'Saluer le roi avec politesse', 'Aider son ami a gagner la journee'] },
    emotionalMoment: { feeling: 'serviable', prompt: 'Le Chat a use d\'idees malines pour aider un ami. De quelle facon astucieuse as-tu deja aide quelqu\'un ?' },
    rewardEmoji: '🥾',
    rewardName: 'Belles bottes',
  },
  {
    id: 'pinocchio',
    coverImage: WM('c/c8/Carlo_Chiostri-Pinocchio_1901-p214.jpg'),
    title: 'Pinocchio',
    summary: 'Une marionnette de bois qui reve d\'etre un vrai garcon apprend que dire la verite, c\'est ce qui fait grandir un bon coeur.',
    theme: 'honnetete',
    emoji: '🪵',
    palette: { primary: '#27AE60', accent: '#A9DFBF', background: '#F0FBF5' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Il etait une fois une petite marionnette de bois nommee Pinocchio, qui revait de devenir un vrai garcon.' },
      { text: 'Chaque fois que Pinocchio disait un mensonge, son nez s\'allongeait comme une branche.', dialogue: { speaker: 'Pinocchio', line: 'Ce n\'est pas moi ! Je promets !' } },
      { text: 'Son ami grillon essayait de lui apprendre a toujours dire la verite.', dialogue: { speaker: 'Grillon', line: 'Dire la verite te rendra leger comme une plume.' } },
      { text: 'Pinocchio fit une grosse erreur et se retrouva perdu. Il apprit alors que l\'honnetete etait son seul guide.' },
      { text: 'Quand Pinocchio dit enfin la verite, son coeur grandit, et son voeu le plus cher se realisa.', dialogue: { speaker: 'Pinocchio', line: 'La verite, c\'est la magie la plus puissante de toutes.' } },
    ],
    vocabulary: [
      { word: 'marionnette', meaning: 'une poupee que l\'on fait bouger', emoji: '🎭' },
      { word: 'verite', meaning: 'dire exactement ce qui s\'est passe', emoji: '✅' },
      { word: 'mensonge', meaning: 'dire quelque chose qui n\'est pas vrai', emoji: '❌' },
      { word: 'honnete', meaning: 'quelqu\'un qui dit toujours la verite', emoji: '🌟' },
    ],
    miniGame: { type: 'choice', prompt: 'Quand le nez de Pinocchio s\'allonge-t-il ?', options: ['Quand il dit la verite', 'Quand il dit un mensonge', 'Quand il chante une chanson'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honnete', prompt: 'Dire la verite a rendu Pinocchio leger. Que ressens-tu quand tu dis la verite ?' },
    rewardEmoji: '🦗',
    rewardName: 'Grillon de la verite',
  },
  {
    id: 'peter-pan',
    coverImage: WM('6/6d/Peter_Pan_1915_poster.jpg'),
    title: 'Peter Pan',
    summary: 'Un garcon qui ne grandit jamais emmene de nouveaux amis dans une aventure volante ou les pensees heureuses et un peu de courage menent partout.',
    theme: 'imagination et courage',
    emoji: '🧚',
    palette: { primary: '#16A085', accent: '#A2D9CE', background: '#F0F9F8' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Dans une chambre pleine d\'etoiles, un garcon nomme Peter Pan apprit aux enfants a voler.' },
      { text: 'Peter dit a Wendy le secret : il fallait penser a quelque chose de tres heureux.', dialogue: { speaker: 'Peter Pan', line: 'Pense a ta chose la plus heureuse — et hop, tu t\'envoles !' } },
      { text: 'Ensemble, ils s\'envolerent vers le Pays Imaginaire, une ile magique pleine d\'aventures.' },
      { text: 'Meme face au mechant capitaine, Peter n\'eut pas peur. Il affronta le danger avec un grand sourire.', dialogue: { speaker: 'Peter Pan', line: 'Etre courageux, c\'est essayer quand meme.' } },
      { text: 'Les enfants rentrerent chez eux avec des souvenirs plein le coeur et un zeste de magie pour toujours.' },
    ],
    vocabulary: [
      { word: 'chambre', meaning: 'la piece ou l\'on dort et ou l\'on reve', emoji: '🛏️' },
      { word: 'ombre', meaning: 'la forme sombre que ton corps fait sur le sol', emoji: '👤' },
      { word: 'imaginer', meaning: 'creer des choses belles dans sa tete', emoji: '💭' },
      { word: 'courage', meaning: 'essayer meme quand on a peur', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Qu\'est-ce qui a aide les enfants a voler ?', options: ['Des pensees heureuses et de la poudre de fee', 'Des bottes lourdes', 'Crier tres fort'], answerIndex: 0 },
    emotionalMoment: { feeling: 'courageux', prompt: 'Peter dit qu\'etre courageux, c\'est essayer quand meme. Quelle chose courageuse aimerais-tu essayer ?' },
    rewardEmoji: '✨',
    rewardName: 'Poudre de fee',
  },
  {
    id: 'alice-in-wonderland',
    coverImage: WM('a/a5/Alice_in_Wonderland_-_Lewis_Carroll_-_Alices_Adventures_in_Wonderland_1865.jpg'),
    title: 'Alice au pays des merveilles',
    summary: 'Une fille curieuse suit un lapin presse dans un monde sens dessus dessous et apprend que poser des questions, c\'est une sorte de magie.',
    theme: 'curiosite',
    emoji: '🐇',
    palette: { primary: '#8E44AD', accent: '#D2B4DE', background: '#F9F0FF' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Alice vit un lapin blanc presse sauter dans un terrier et, tres curieuse, elle le suivit.' },
      { text: 'Elle tomba dans un long couloir magique et trouva une toute petite porte dans un jardin.', dialogue: { speaker: 'Alice', line: 'Comme c\'est etrange ! Je me demande ce qui se passe ici.' } },
      { text: 'Alice but une petite bouteille et rapetissa, puis mangea un gateau et grandit tres vite.', dialogue: { speaker: 'Alice', line: 'Les questions sont la cle de toutes les merveilles !' } },
      { text: 'Elle rencontra un chat souriant, une reine colereuse et un grand chapelier fou.' },
      { text: 'Alice se reveilla et sourit. Poser des questions l\'avait menee dans le plus beau des reves.', dialogue: { speaker: 'Alice', line: 'La curiosite est la plus grande aventure.' } },
    ],
    vocabulary: [
      { word: 'curieuse', meaning: 'quelqu\'un qui aime decouvrir de nouvelles choses', emoji: '🔍' },
      { word: 'terrier', meaning: 'un tunnel creuse dans la terre par un animal', emoji: '🕳️' },
      { word: 'rapetisser', meaning: 'devenir plus petit', emoji: '🔻' },
      { word: 'merveille', meaning: 'quelque chose d\'incroyable et de tres surprenant', emoji: '😲' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets l\'aventure d\'Alice dans l\'ordre !', steps: ['Boire la bouteille et rapetisser', 'Manger le gateau et grandir', 'Trouver la petite porte du jardin'] },
    emotionalMoment: { feeling: 'curieux', prompt: 'Alice adorait poser des questions. Qu\'est-ce qui te rend curieux aujourd\'hui ?' },
    rewardEmoji: '⏰',
    rewardName: 'Horloge curieuse',
  },
  {
    id: 'the-wizard-of-oz',
    coverImage: WM('8/81/The_Wonderful_Wizard_of_Oz_cover_art.jpg'),
    title: 'Le Magicien d\'Oz',
    summary: 'Une fille et trois nouveaux amis suivent une route doree et decouvrent que les cadeaux qu\'ils cherchaient etaient en eux depuis le debut.',
    theme: 'tu as deja ce qu\'il te faut',
    emoji: '🌈',
    palette: { primary: '#F39C12', accent: '#FAD7A0', background: '#FFFBF0' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 8,
    scenes: [
      { text: 'Un grand tourbillon emporta Dorothee et son petit chien Toto dans le pays magique d\'Oz.' },
      { text: 'Sur la route doree, Dorothee rencontra un epouvantail, un homme de fer-blanc et un lion.', dialogue: { speaker: 'Epouvantail', line: 'Je veux juste un cerveau malin !' } },
      { text: 'Ensemble, ils marchererent vers la ville d\'Emeraude pour trouver le grand Magicien.', dialogue: { speaker: 'Dorothee', line: 'Si nous sommes ensemble, nous pouvons tout faire.' } },
      { text: 'Le Magicien leur revela un grand secret : ils possedaient deja tout ce qu\'ils desiraient.' },
      { text: 'Dorothee appuya trois fois ses souliers et retrouva sa maison. Chacun avait trouve son cadeau.', dialogue: { speaker: 'Dorothee', line: 'Il n\'y a nulle part de mieux que chez soi.' } },
    ],
    vocabulary: [
      { word: 'tourbillon', meaning: 'un vent tres fort qui tourne en rond', emoji: '🌪️' },
      { word: 'epouvantail', meaning: 'une grande poupee de paille pour effrayer les oiseaux', emoji: '🌾' },
      { word: 'courage', meaning: 'continuer meme quand on a peur', emoji: '💪' },
      { word: 'voyage', meaning: 'une longue marche ou aventure vers un endroit nouveau', emoji: '🗺️' },
    ],
    miniGame: { type: 'choice', prompt: 'Quel ami avait deja du courage depuis le debut ?', options: ['L\'epouvantail', 'L\'homme de fer-blanc', 'Le lion'], answerIndex: 2 },
    emotionalMoment: { feeling: 'capable', prompt: 'Les amis avaient deja leurs cadeaux en eux. Quel cadeau as-tu deja en toi ?' },
    rewardEmoji: '👟',
    rewardName: 'Souliers scintillants',
  },
  {
    id: 'robin-hood',
    coverImage: WM('1/14/Robin_Hood_and_Maid_Marian_cropped.jpg'),
    title: 'Robin des Bois',
    summary: 'Un gentil archer de la foret verte partage avec ceux qui ont tres peu et apprend a ses amis que la justice rend tout le monde plus heureux.',
    theme: 'justice et generosite',
    emoji: '🏹',
    palette: { primary: '#27AE60', accent: '#A9DFBF', background: '#F0FBF5' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Dans une grande foret verte vivait Robin des Bois, le meilleur archer du pays.' },
      { text: 'Il vit que beaucoup de gens etaient tres pauvres pendant que d\'autres avaient tout.', dialogue: { speaker: 'Robin', line: 'Partager, c\'est le plus beau des cadeaux.' } },
      { text: 'Avec ses amis joyeux, Robin devisa un plan pour aider ceux dans le besoin.', dialogue: { speaker: 'Petit Jean', line: 'Ensemble, nous sommes la force de la foret !' } },
      { text: 'Robin distribua ce dont les gens avaient besoin, et des sourires fleurirent partout.' },
      { text: 'La foret bourdonnait de bonheur. Robin avait appris que la generosite est la vraie victoire.', dialogue: { speaker: 'Robin', line: 'La generosite rend tout le monde plus riche.' } },
    ],
    vocabulary: [
      { word: 'archer', meaning: 'quelqu\'un qui tire des fleches avec un arc', emoji: '🎯' },
      { word: 'foret', meaning: 'un grand endroit plein d\'arbres et d\'animaux', emoji: '🌳' },
      { word: 'juste', meaning: 'traiter tout le monde de la meme facon', emoji: '⚖️' },
      { word: 'genereux', meaning: 'qui aime donner et partager', emoji: '🎁' },
    ],
    miniGame: { type: 'choice', prompt: 'Robin des Bois partageait avec des gens qui etaient...', options: ['affames et dans le besoin', 'deja tres riches', 'mechants avec les autres'], answerIndex: 0 },
    emotionalMoment: { feeling: 'juste', prompt: 'Robin adorait partager. Que pourrais-tu partager pour faire sourire un ami ?' },
    rewardEmoji: '🏹',
    rewardName: 'Arc amical',
  },
  {
    id: 'goldilocks',
    coverImage: WM('c/cb/Goldilocks_and_the_Three_Bears_-_Project_Gutenberg_etext_17034.jpg'),
    title: 'Boucle d\'or et les trois ours',
    summary: 'Une fille curieuse entre dans la chaumiere douillette des ours et apprend qu\'il vaut mieux demander d\'abord et prendre soin des affaires des autres.',
    theme: 'le respect des autres',
    emoji: '🐻',
    palette: { primary: '#D4A017', accent: '#FAD7A0', background: '#FFFBF0' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Une petite fille aux boucles dorees se promenait dans la foret quand elle trouva une jolie chaumiere.' },
      { text: 'Elle entra et gouta trois bols de bouillie. Celui du bebe ours etait parfait.', dialogue: { speaker: 'Boucle d\'or', line: 'Oh ! Ce bol est parfait, ni trop chaud ni trop froid !' } },
      { text: 'Elle essaya trois chaises, puis trois lits. Elle s\'endormit dans le plus douillet.' },
      { text: 'Les trois ours rentrerent et trouverent leur maison bousculee.', dialogue: { speaker: 'Bebe ours', line: 'Quelqu\'un a mange dans mon bol !' } },
      { text: 'Boucle d\'or se reveilla, s\'excusa et apprit que demander d\'abord est la politesse la plus douce.', dialogue: { speaker: 'Boucle d\'or', line: 'Pardon. Je demanderai toujours avant d\'entrer.' } },
    ],
    vocabulary: [
      { word: 'bouillie', meaning: 'une nourriture chaude et douce, comme la cereale du matin', emoji: '🥣' },
      { word: 'chaumiere', meaning: 'une petite maison douillette dans la foret', emoji: '🏡' },
      { word: 'respect', meaning: 'prendre soin des affaires et des sentiments des autres', emoji: '🙏' },
      { word: 'desole', meaning: 'ce qu\'on dit quand on regrette quelque chose', emoji: '💙' },
    ],
    miniGame: { type: 'count', prompt: 'Combien d\'ours vivaient dans la chaumiere douillette ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'respectueux', prompt: 'Boucle d\'or a appris a demander d\'abord. Quand est-ce gentil de demander avant d\'emprunter quelque chose ?' },
    rewardEmoji: '🥣',
    rewardName: 'Bol parfait',
  },
  {
    id: 'three-little-pigs',
    coverImage: WM('9/93/Three-pigs-1.jpg'),
    title: 'Les Trois Petits Cochons',
    summary: 'Trois petits cochons construisent trois maisons differentes et apprennent qu\'un travail soigneux et applique garde tout le monde en securite et au chaud.',
    theme: 'travail et organisation',
    emoji: '🐷',
    palette: { primary: '#E74C3C', accent: '#FADBD8', background: '#FFF5F4' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Trois petits cochons partirent dans le monde pour construire leur maison.' },
      { text: 'Le premier construisit vite une maison de paille. Le deuxieme, une maison de bois.', dialogue: { speaker: 'Premier cochon', line: 'Vite fait, bien fait ! Je veux aller jouer !' } },
      { text: 'Le troisieme cochon travailla dur et construisit une maison solide de briques, pierre par pierre.', dialogue: { speaker: 'Troisieme cochon', line: 'Je prends mon temps pour que ma maison soit solide.' } },
      { text: 'Le grand mechant loup souffla sur les maisons de paille et de bois, et elles s\'ecroulerent.' },
      { text: 'Mais la maison de briques resta solide. Les trois cochons etaient en securite, et tout le monde apprit que travailler avec soin protege.', dialogue: { speaker: 'Troisieme cochon', line: 'Un bon travail prend du temps, mais ca en vaut la peine !' } },
    ],
    vocabulary: [
      { word: 'paille', meaning: 'des tiges seches de plantes, faciles a casser', emoji: '🌾' },
      { word: 'briques', meaning: 'des blocs de terre cuite tres solides', emoji: '🧱' },
      { word: 'resistante', meaning: 'tres solide, pas facile a casser', emoji: '💪' },
      { word: 'planifier', meaning: 'reflechir avant de commencer quelque chose', emoji: '📋' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de petits cochons construisirent des maisons ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'fier de mon travail', prompt: 'Le troisieme cochon a travaille dur et est reste en securite. Sur quoi as-tu travaille dur, toi ?' },
    rewardEmoji: '🧱',
    rewardName: 'Brique solide',
  },
  {
    id: 'aladdin',
    coverImage: WM('7/7e/Aladdin_and_the_Wonderful_Lamp_p58.jpg'),
    title: 'Aladin et la lampe merveilleuse',
    summary: 'Un garcon ordinaire et gentil trouve une lampe magique et apprend que ce que tu souhaites compte moins que le bien que tu fais aux autres.',
    theme: 'honnetete et coeur humble',
    emoji: '🪔',
    palette: { primary: '#F39C12', accent: '#FAD7A0', background: '#FFFBF0' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Dans un marche anime vivait Aladin, un garcon pauvre mais au coeur d\'or.' },
      { text: 'Il trouva une vieille lampe et, en la frottant, un grand genie en sortit !', dialogue: { speaker: 'Genie', line: 'Je t\'accorde trois souhaits. Choisis avec soin !' } },
      { text: 'Aladin souhaiita d\'abord aider sa famille, puis les gens pauvres de son quartier.', dialogue: { speaker: 'Aladin', line: 'Je veux que personne dans ce marche ne soit affame.' } },
      { text: 'Son humilite et sa generosite lui gagnererent de vrais amis et beaucoup de bonheur.' },
      { text: 'Aladin apprit que les meilleurs souhaits sont ceux que l\'on fait pour les autres.', dialogue: { speaker: 'Aladin', line: 'Un coeur genereux est le plus grand des tresors.' } },
    ],
    vocabulary: [
      { word: 'marche', meaning: 'un endroit anime ou les gens vendent et achetent', emoji: '🏪' },
      { word: 'lampe', meaning: 'un objet qui donne de la lumiere ou garde un genie', emoji: '🪔' },
      { word: 'humble', meaning: 'quelqu\'un qui ne se vante pas de lui-meme', emoji: '🙏' },
      { word: 'souhait', meaning: 'quelque chose que tu desires tres fort', emoji: '⭐' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de souhaits le genie a-t-il donnes a Aladin ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'genereux', prompt: 'Aladin a souhaite aider les autres. Si tu avais un souhait gentil, lequel serait-ce ?' },
    rewardEmoji: '🪔',
    rewardName: 'Lampe a souhaits',
  },
  {
    id: 'ali-baba',
    coverImage: WM('9/9a/Ali_Baba_Forty_Thieves_Cassim.jpg'),
    title: 'Ali Baba et les quarante voleurs',
    summary: 'Un doux bucheron decouvre une grotte secrete et apprend qu\'etre honnete et prudent vaut bien mieux qu\'etre avide.',
    theme: 'l\'honnetete plutot que l\'avidite',
    emoji: '💎',
    palette: { primary: '#8E44AD', accent: '#D2B4DE', background: '#F9F0FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 8,
    scenes: [
      { text: 'Ali Baba etait un bucheron doux qui vivait simplement et contenment.' },
      { text: 'Un jour dans la foret, il entendit des voleurs dire les mots magiques devant un grand rocher.', dialogue: { speaker: 'Voleurs', line: 'Sesame, ouvre-toi !' } },
      { text: 'Ali Baba entra dans la grotte et vit des tresors etincelants de toutes les couleurs.', dialogue: { speaker: 'Ali Baba', line: 'Je prendrai juste ce qu\'il nous faut, pas plus.' } },
      { text: 'Son frere avide prit trop et fut surpris par les voleurs. Ali Baba comprit la lecon.' },
      { text: 'Ali Baba partagea sa bonne fortune avec les autres et vecut simplement et heureusement.', dialogue: { speaker: 'Ali Baba', line: 'Avoir assez et etre honnete, c\'est la vraie richesse.' } },
    ],
    vocabulary: [
      { word: 'grotte', meaning: 'une grande cavite naturelle dans la roche', emoji: '🕳️' },
      { word: 'tresor', meaning: 'une grande quantite d\'or et de choses precieuses', emoji: '💎' },
      { word: 'avide', meaning: 'quelqu\'un qui veut toujours plus que ce qu\'il lui faut', emoji: '😤' },
      { word: 'assez', meaning: 'juste ce dont on a besoin, ni plus ni moins', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Quels sont les mots magiques qui ouvrent la grotte ?', options: ['Sesame, ouvre-toi !', 'Ferme la porte !', 'Bonjour !'], answerIndex: 0 },
    emotionalMoment: { feeling: 'content', prompt: 'Ali Baba n\'a pris que ce qu\'il fallait. Quelle chose que tu as deja est juste suffisante pour toi ?' },
    rewardEmoji: '🗝️',
    rewardName: 'Grotte secrete',
  },
  {
    id: 'aesops-fables',
    coverImage: WM('a/a8/The-hare-and-the-tortoise.jpg'),
    title: 'Fables d\'Esope : Le Lievre et la Tortue',
    summary: 'Un lievre rapide et une tortue lente font une course amicale, et la tortue apprend a tous que ne jamais abandonner gagne la journee.',
    theme: 'perseverance — doucement mais surement',
    emoji: '🐢',
    palette: { primary: '#27AE60', accent: '#A9DFBF', background: '#F0FBF5' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Dans une prairie ensoleilee, un lievre rapide se vantait toujours de sa vitesse.' },
      { text: 'La tortue lente et calme proposa un defi. Le lievre accepta en riant.', dialogue: { speaker: 'Lievre', line: 'Une course contre toi ? Facile ! Je vais me reposer en chemin.' } },
      { text: 'La tortue avanca pas a pas, regulierement, sans jamais s\'arreter.', dialogue: { speaker: 'Tortue', line: 'Doucement mais surement, j\'avancerai.' } },
      { text: 'Le lievre s\'endormit sous un arbre, sur que la tortue ne pourrait jamais le rattraper.' },
      { text: 'Quand le lievre se reveilla, la tortue avait deja franchi la ligne d\'arrivee. Perseverer gagne toujours.', dialogue: { speaker: 'Tortue', line: 'Pas a pas, on arrive plus loin qu\'on ne croit.' } },
    ],
    vocabulary: [
      { word: 'lievre', meaning: 'un grand lapin sauvage tres rapide', emoji: '🐇' },
      { word: 'tortue', meaning: 'un animal a carapace qui marche lentement mais sans s\'arreter', emoji: '🐢' },
      { word: 'regulier', meaning: 'avancer au meme rythme, sans s\'arretere', emoji: '⏱️' },
      { word: 'perseverer', meaning: 'continuer a essayer meme quand c\'est difficile', emoji: '💪' },
    ],
    miniGame: { type: 'choice', prompt: 'Qui a gagne la course en n\'abandonnant jamais ?', options: ['le lievre rapide', 'la tortue lente et reguliere', 'le renard endormi'], answerIndex: 1 },
    emotionalMoment: { feeling: 'determine', prompt: 'La tortue a continue pas apres pas. Sur quoi continues-tu d\'essayer, toi ?' },
    rewardEmoji: '🐢',
    rewardName: 'Tortue perseverante',
  },
  {
    id: 'sleeping-beauty',
    coverImage: null,
    title: 'La Belle au Bois Dormant',
    summary: 'Une belle princesse tombe dans un sommeil magique et attend le vrai amour.',
    theme: 'patience et esperance',
    emoji: '🌹',
    palette: { primary: '#e91e8c', accent: '#f8bbd9', background: '#1a0026' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Un roi et une reine heureux eurent enfin une petite fille. Ils inviterent toutes les fees du royaume pour la baptiser.' },
      { text: 'Les bonnes fees offrirent leurs dons a la princesse : beaute, grace, douceur. Mais une mauvaise fee arriva en colere.', dialogue: { speaker: 'Mauvaise fee', line: 'Quand elle aura seize ans, elle se piquera au fuseau et tombera morte !' } },
      { text: 'La derniere bonne fee n\'avait pas encore parle. Elle adoucit le sort : la princesse ne mourrait pas, elle dormirait cent ans.', dialogue: { speaker: 'Bonne fee', line: 'Elle dormira, mais l\'amour la reveillera.' } },
      { text: 'A seize ans, la princesse trouva une vieille femme qui filait. Elle toucha le fuseau et tomba dans un profond sommeil. Tout le chateau s\'endormit avec elle.' },
      { text: 'Un prince entendit parler du chateau endormi cache derriere une foret de roses. Il coupa les ronces et penetra dans le chateau silencieux.', dialogue: { speaker: 'Prince', line: 'Comme elle est belle ! Je vais la reveiller.' } },
      { text: 'Le prince s\'approcha de la belle princesse et lui donna un doux baiser. Elle ouvrit les yeux et sourit. Tout le chateau se reveilla en meme temps, et ils vecurent heureux.', dialogue: { speaker: 'Princesse', line: 'J\'ai attendu si longtemps. Enfin tu es arrive !' } },
    ],
    vocabulary: [
      { word: 'fuseau', meaning: 'un outil pour filer la laine, avec une pointe', emoji: '🧵' },
      { word: 'malefique', meaning: 'qui fait du mal avec de la magie mechante', emoji: '🧙' },
      { word: 'enchante', meaning: 'transforme par une magie speciale', emoji: '✨' },
      { word: 'rosier', meaning: 'un buisson qui fait pousser de belles roses', emoji: '🌹' },
    ],
    miniGame: { type: 'choice', prompt: 'Quelle mauvaise fee lance le sort sur la princesse ?', options: ['Une fee qui n\'etait pas invitee', 'La fee du palais', 'La fee de la foret'], answerIndex: 0 },
    emotionalMoment: { feeling: 'espoir', prompt: 'As-tu deja attendu quelque chose avec impatience ? Comment tu te sentais ?' },
    rewardEmoji: '🌹',
    rewardName: 'Rose Enchantee',
  },
  {
    id: 'beauty-and-the-beast',
    coverImage: null,
    title: 'La Belle et la Bete',
    summary: 'Belle apprend que la vraie beaute se trouve dans le coeur, pas dans l\'apparence.',
    theme: 'gentillesse et amour vrai',
    emoji: '🌺',
    palette: { primary: '#d4af37', accent: '#8b0000', background: '#0d0005' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Un marchand se perdit dans la foret pendant une tempete. Il trouva un grand chateau mysterieux et s\'y abrita pour la nuit.' },
      { text: 'En repartant, le marchand cueillit une rose pour sa fille Belle. Une Bete terrifiante surgit alors.', dialogue: { speaker: 'Bete', line: 'Tu as vole ma rose ! Tu es mon prisonnier !' } },
      { text: 'Le marchand supplia la Bete de le laisser dire au revoir a ses enfants. La Bete accepta, a condition qu\'une de ses filles revienne a sa place.', dialogue: { speaker: 'Belle', line: 'Papa, je vais y aller. Je n\'ai pas peur.' } },
      { text: 'Belle vecut au chateau. La Bete etait laide mais douce et gentille. Chaque soir, ils parlaient et riaient ensemble.' },
      { text: 'Belle demanda a rentrer chez elle voir son pere malade. La Bete accepta tristement.', dialogue: { speaker: 'Bete', line: 'Tu me manqueras, Belle. Mais ton bonheur passe avant le mien.' } },
      { text: 'Belle, loin du chateau, realisa qu\'elle aimait la Bete. Elle courut la retrouver. En confessant son amour, la Bete se transforma en beau prince.', dialogue: { speaker: 'Belle', line: 'Je t\'aime, non pour ton visage, mais pour ton coeur.' } },
      { text: 'Le prince expliqua qu\'une sorciere l\'avait enchante. Seul l\'amour sincere pouvait le liberer. Belle et le prince vecurent heureux pour toujours.' },
    ],
    vocabulary: [
      { word: 'bete', meaning: 'un grand animal effrayant, ici un monstre enchante', emoji: '🐾' },
      { word: 'prisonnier', meaning: 'quelqu\'un qui ne peut pas partir librement', emoji: '🔒' },
      { word: 'apparence', meaning: 'ce qu\'on voit de quelqu\'un de l\'exterieur', emoji: '👁️' },
      { word: 'transformation', meaning: 'changer completement de forme ou d\'aspect', emoji: '✨' },
    ],
    miniGame: { type: 'choice', prompt: 'Pourquoi le pere de Belle va-t-il au chateau ?', options: ['Il cherche un tresor', 'Il s\'abrite de la tempete et cueille une rose', 'Il rend visite a la Bete'], answerIndex: 1 },
    emotionalMoment: { feeling: 'gentillesse', prompt: 'As-tu deja juge quelqu\'un sur son apparence avant de le connaitre ?' },
    rewardEmoji: '🌺',
    rewardName: 'Rose Magique',
  },
  {
    id: 'little-thumb',
    coverImage: null,
    title: 'Le Petit Poucet',
    summary: 'Le plus petit des sept freres utilise son intelligence pour sauver sa famille.',
    theme: 'courage et intelligence',
    emoji: '👣',
    palette: { primary: '#2e7d32', accent: '#a5d6a7', background: '#001209' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Un pauvre bucheron et sa femme avaient sept fils. Le plus petit s\'appelait le Petit Poucet. Il etait minuscule mais tres intelligent.' },
      { text: 'Un soir, le pere et la mere, trop pauvres pour nourrir leurs enfants, les abandonnerent dans la foret.', dialogue: { speaker: 'Petit Poucet', line: 'Je savais qu\'ils allaient faire ca. Je suis pret.' } },
      { text: 'Le Petit Poucet avait prevu le coup : il avait rempli ses poches de petits cailloux blancs. Il en sema tout le long du chemin, et les enfants retrouverent la maison grace a eux.' },
      { text: 'Une deuxieme fois abandonnes, le Petit Poucet n\'avait que du pain pour semer des miettes. Les oiseaux les mangerent et les freres se perdirent pour de bon.' },
      { text: 'Perdus, ils arriverent a la maison d\'un ogre. La femme de l\'ogre les cacha, mais l\'ogre les trouva.', dialogue: { speaker: 'Ogre', line: 'Je sens la chair fraiche ! Ou sont-ils caches ?' } },
      { text: 'Le Petit Poucet eut une idee brillante : il echangea les bonnets de ses freres avec les couronnes des filles de l\'ogre. L\'ogre se trompa dans l\'obscurite.' },
      { text: 'Le Petit Poucet vola les bottes de sept lieues de l\'ogre endormi. En quelques pas, il put ramener de l\'or et sauver toute sa famille.', dialogue: { speaker: 'Petit Poucet', line: 'L\'intelligence vaut mieux que la force !' } },
    ],
    vocabulary: [
      { word: 'cailloux', meaning: 'de petites pierres lisses qu\'on peut semer en chemin', emoji: '🪨' },
      { word: 'ogre', meaning: 'un grand monstre qui mange les enfants dans les contes', emoji: '👹' },
      { word: 'lieue', meaning: 'une grande distance, comme plusieurs kilometres', emoji: '🗺️' },
      { word: 'ruse', meaning: 'une idee maline pour tromper quelqu\'un', emoji: '💡' },
    ],
    miniGame: { type: 'sequence', prompt: 'Remets les etapes dans l\'ordre !', steps: ['Semer les cailloux blancs pour retrouver le chemin', 'Arriver chez l\'ogre dans la foret', 'Voler les bottes de sept lieues'] },
    emotionalMoment: { feeling: 'courage', prompt: 'As-tu deja eu peur mais tu as quand meme continue ? Qu\'est-ce qui t\'a aide ?' },
    rewardEmoji: '👟',
    rewardName: 'Bottes de Sept Lieues',
  },
  {
    id: 'jack-beanstalk',
    coverImage: null,
    title: 'Jack et le Haricot Magique',
    summary: 'Jack echange sa vache contre des haricots magiques et decouvre un chateau dans les nuages.',
    theme: 'aventure et curiosite',
    emoji: '🌱',
    palette: { primary: '#33691e', accent: '#c5e1a5', background: '#001000' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Jack et sa mere etaient tres pauvres. Un jour, la mere envoya Jack vendre leur vieille vache au marche.' },
      { text: 'Sur la route, un vieux monsieur proposa a Jack des haricots magiques en echange de la vache. Jack accepta.', dialogue: { speaker: 'Jack', line: 'Des haricots magiques ! C\'est une bonne affaire !' } },
      { text: 'La mere de Jack fut tres en colere et jeta les haricots par la fenetre. Mais pendant la nuit, une enorme tige de haricot poussa jusqu\'aux nuages.' },
      { text: 'Jack grimpa le long de la tige et decouvrit un immense chateau dans les nuages. Un geant terrible y vivait.', dialogue: { speaker: 'Geant', line: 'Fe, fi, fo, fum ! Je sens le sang d\'un homme !' } },
      { text: 'La femme du geant aida Jack a se cacher. Jack profita que le geant dormait pour voler la poule aux oeufs d\'or et la harpe enchantee.' },
      { text: 'Jack devala la tige en courant. Le geant le poursuivit. Jack saisit sa hache et coupa la tige. Le geant tomba loin, tres loin.', dialogue: { speaker: 'Jack', line: 'Maman ! Nous serons riches ! Plus jamais faim !' } },
    ],
    vocabulary: [
      { word: 'haricot', meaning: 'une petite graine qui peut pousser tres haut', emoji: '🫘' },
      { word: 'geant', meaning: 'un etre imaginaire enormement grand et fort', emoji: '🦣' },
      { word: 'nuages', meaning: 'les grandes formes blanches ou grises dans le ciel', emoji: '☁️' },
      { word: 'tresor', meaning: 'des objets precieux comme de l\'or ou des bijoux', emoji: '🪙' },
    ],
    miniGame: { type: 'choice', prompt: 'Contre quoi Jack echange-t-il sa vache ?', options: ['Des pieces d\'or', 'Des haricots magiques', 'Une harpe'], answerIndex: 1 },
    emotionalMoment: { feeling: 'curiosite', prompt: 'As-tu deja decouvert quelque chose de surprenant ? Que ressentais-tu ?' },
    rewardEmoji: '🪙',
    rewardName: 'Tresor du Geant',
  },
  {
    id: 'thumbelina',
    coverImage: null,
    title: 'Poucette',
    summary: 'Poucette, une toute petite fille, cherche sa place dans un monde trop grand pour elle.',
    theme: 'identite et appartenance',
    emoji: '🌸',
    palette: { primary: '#e91e63', accent: '#f8bbd0', background: '#1a0010' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Une femme qui souhaitait avoir un enfant planta une graine magique. Une fleur poussa et, a l\'interieur, dormait une toute petite fille. Elle s\'appelait Poucette.' },
      { text: 'Un soir, une vilaine grenouille enleva Poucette pour la marier a son fils. Poucette pleurait sur son nenuphare.', dialogue: { speaker: 'Poucette', line: 'Je ne veux pas rester ici. Je veux trouver ma vraie maison.' } },
      { text: 'Des poissons amicaux rongerent la tige du nenuphare et Poucette s\'echappa. Elle voyagea a travers pres et forets, toujours trop petite pour les autres.' },
      { text: 'En hiver, Poucette trouva refugie chez une souris des champs. Mais la souris voulait la marier a une vieille taupe aveugle.' },
      { text: 'Poucette trouva une hirondelle blessee et la soigna toute l\'hiver avec tendresse.', dialogue: { speaker: 'Hirondelle', line: 'Tu m\'as sauvee. Quand le printemps reviendra, je t\'emmenerai loin d\'ici.' } },
      { text: 'Au printemps, l\'hirondelle emporta Poucette vers un pays chaud et fleuri. La, elle rencontra un tout petit prince des fleurs. Elle avait enfin trouve sa place.', dialogue: { speaker: 'Prince des fleurs', line: 'Tu es la bienvenue ici. Veux-tu etre notre reine ?' } },
    ],
    vocabulary: [
      { word: 'minuscule', meaning: 'extremement petit, beaucoup plus petit que tout le monde', emoji: '🔬' },
      { word: 'kidnapper', meaning: 'emmener quelqu\'un de force sans sa permission', emoji: '😨' },
      { word: 'hirondelle', meaning: 'un petit oiseau rapide qui voyage vers les pays chauds', emoji: '🐦' },
      { word: 'fee', meaning: 'un etre magique avec des ailes, qui aide les autres', emoji: '🧚' },
    ],
    miniGame: { type: 'find', prompt: 'Trouve la fleur ou dort Poucette !', target: 'la grande fleur rose', decoys: ['un nenuphar vert', 'une feuille seche', 'un champignon'] },
    emotionalMoment: { feeling: 'appartenance', prompt: 'As-tu deja eu l\'impression de ne pas etre a ta place ? Comment tu as trouve ta place ?' },
    rewardEmoji: '🦋',
    rewardName: 'Ailes de Fee',
  },
  {
    id: 'twelve-dancing-princesses',
    coverImage: null,
    title: 'Les Douze Princesses Danseuses',
    summary: 'Chaque nuit, douze princesses secretement usent leurs souliers en dansant. Un soldat decouvre leur mystere.',
    theme: 'mystere et perseverance',
    emoji: '👠',
    palette: { primary: '#6a1b9a', accent: '#e040fb', background: '#0d0017' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 10,
    scenes: [
      { text: 'Un roi avait douze filles. Chaque matin, leurs souliers etaient troues comme si elles avaient danse toute la nuit. Mais personne ne savait pourquoi.' },
      { text: 'Le roi annonca que celui qui decouvrirait le secret epouserait une de ses filles. Des princes essayerent, mais tous s\'endormaient mysterieusement.', dialogue: { speaker: 'Roi', line: 'Qui percera ce mystere ? Ses souliers sont troues encore !' } },
      { text: 'Un vieux soldat revenant de la guerre rencontra une sage vieille femme qui lui donna une cape d\'invisibilite.', dialogue: { speaker: 'Vieille femme', line: 'Ne bois pas le breuvage qu\'on t\'offrira. Et prends garde !' } },
      { text: 'Le soldat fit semblant de dormir. A minuit, les princesses se leverent. Il les suivit, invisible, par un passage secret sous le sol.' },
      { text: 'Sous la terre, il decouvrit un lac avec des bateaux, une foret aux arbres d\'argent et d\'or, et un chateau illumine ou douze princes attendaient les princesses pour danser.' },
      { text: 'Le soldat cueillit secrettement une branche argentee pour prouver sa decouverte. La princesse ainee entendit un bruit.', dialogue: { speaker: 'Princesse ainee', line: 'Quelque chose ne va pas ce soir. J\'ai peur.' } },
      { text: 'Le lendemain, le soldat presenta la branche au roi et raconta tout. Le roi reconnut la verite. Le soldat choisit d\'epouser la princesse ainee et le mystere fut leve pour toujours.', dialogue: { speaker: 'Soldat', line: 'La verite vaut mieux que tous les secrets.' } },
    ],
    vocabulary: [
      { word: 'mystere', meaning: 'quelque chose de cache qu\'on ne comprend pas encore', emoji: '🔍' },
      { word: 'invisible', meaning: 'qu\'on ne peut pas voir, meme s\'il est la', emoji: '👻' },
      { word: 'soulier', meaning: 'une chaussure elegante, souvent pour danser', emoji: '👠' },
      { word: 'souterrain', meaning: 'qui se trouve sous la terre, cache en dessous', emoji: '🕳️' },
    ],
    miniGame: { type: 'match', prompt: 'Associe chaque princesse a son prince danseur !', pairs: [{ left: 'Princesse Rose', right: 'Prince Dorian' }, { left: 'Princesse Lune', right: 'Prince Silvain' }, { left: 'Princesse Etoile', right: 'Prince Aurele' }, { left: 'Princesse Violette', right: 'Prince Florian' }] },
    emotionalMoment: { feeling: 'mystere', prompt: 'As-tu un secret ? Comment ca fait de garder un secret ?' },
    rewardEmoji: '👑',
    rewardName: 'Couronne du Mystere',
  },
  {
    id: 'rumpelstiltskin',
    coverImage: null,
    title: 'Rumpelstiltskin',
    summary: 'Un petit homme mysterieux aide une jeune fille a filer de la paille en or — mais a quel prix ?',
    theme: 'promesses et honnetete',
    emoji: '🧵',
    palette: { primary: '#f9a825', accent: '#ffe082', background: '#1a1000' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Un meunier voulut impressionner le roi et dit un gros mensonge : "Ma fille peut filer de la paille en or !" Le roi enferma la jeune fille dans une tour remplie de paille.' },
      { text: 'La fille pleurait quand un petit homme etrange apparut.', dialogue: { speaker: 'Rumpelstiltskin', line: 'Que donneras-tu si je file toute cette paille en or pour toi ?' } },
      { text: 'Elle lui donna son collier. Le petit homme fila toute la paille en or. Le roi, emerveille, la mit dans une salle encore plus grande.' },
      { text: 'La troisieme nuit, la fille n\'avait plus rien a donner. Elle promit son premier enfant. Le roi l\'epousa et elle devint reine.' },
      { text: 'Un an plus tard, le petit homme revint reclamer l\'enfant. La reine supplia. Il lui donna trois jours pour deviner son nom.', dialogue: { speaker: 'Rumpelstiltskin', line: 'Si tu trouves mon nom, tu garderas l\'enfant !' } },
      { text: 'Un messager entendit le petit homme danser en chantant son nom dans la foret. Il revint en courir l\'annoncer a la reine.', dialogue: { speaker: 'Messager', line: 'Il s\'appelle Rumpelstiltskin ! Je l\'ai entendu chanter !' } },
    ],
    vocabulary: [
      { word: 'paille', meaning: 'des tiges seches de cereales, jaunes et legeres', emoji: '🌾' },
      { word: 'filer', meaning: 'transformer des fibres en fil avec un rouet', emoji: '🧶' },
      { word: 'promesse', meaning: 'ce qu\'on dit qu\'on va faire et qu\'on doit tenir', emoji: '🤝' },
      { word: 'devinette', meaning: 'une question avec une reponse cachee a trouver', emoji: '❓' },
    ],
    miniGame: { type: 'choice', prompt: 'Comment la reine devine-t-elle le nom du lutin ?', options: ['Un messager l\'a entendu chanter dans la foret', 'Elle l\'a lu dans un livre', 'Le lutin le lui a dit lui-meme'], answerIndex: 0 },
    emotionalMoment: { feeling: 'honnetete', prompt: 'Est-ce qu\'il est important de tenir ses promesses ? Pourquoi ?' },
    rewardEmoji: '🥇',
    rewardName: 'Fil d\'Or',
  },
  {
    id: 'emperor-new-clothes',
    coverImage: null,
    title: 'Les Habits Neufs de l\'Empereur',
    summary: 'Deux escrocs font croire a un empereur vaniteux qu\'ils lui font des habits invisibles pour les sots.',
    theme: 'honnetete et courage',
    emoji: '👑',
    palette: { primary: '#1565c0', accent: '#90caf9', background: '#000d1a' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Il etait une fois un empereur qui adorait les beaux habits par-dessus tout. Il changeait de tenue plusieurs fois par jour.' },
      { text: 'Deux escrocs se presenterent comme les meilleurs tisseurs du monde. Ils pretendirent tisser un tissu magique : invisible pour les sots et les incompetents.', dialogue: { speaker: 'Escroc', line: 'Seules les personnes vraiment intelligentes peuvent voir ces habits !' } },
      { text: 'Les ministres furent envoyes voir l\'avancement. Ils ne voyaient rien, mais n\'osaient pas le dire de peur de paraitre stupides.', dialogue: { speaker: 'Ministre', line: 'C\'est magnifique... absolument magnifique.' } },
      { text: 'Les escrocs remirent a l\'Empereur ses habits neufs imaginaires. L\'Empereur ne voyait rien non plus, mais il fit semblant.' },
      { text: 'L\'Empereur defila dans les rues. Tout le monde applaudit, craignant de paraitre sot.' },
      { text: 'Soudain, un petit enfant cria la verite.', dialogue: { speaker: 'Enfant', line: 'Mais il n\'a rien sur lui ! L\'Empereur est tout nu !' } },
    ],
    vocabulary: [
      { word: 'vaniteux', meaning: 'quelqu\'un qui pense trop a son apparence et se croit beau', emoji: '🪞' },
      { word: 'escroc', meaning: 'quelqu\'un qui ment pour voler ou tromper les autres', emoji: '🎭' },
      { word: 'invisible', meaning: 'qu\'on ne peut pas voir de ses yeux', emoji: '👻' },
      { word: 'verite', meaning: 'ce qui est reellement vrai, meme si ca derange', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Qui dit la verite en premier ?', options: ['Un petit enfant', 'Un ministre', 'L\'Empereur lui-meme'], answerIndex: 0 },
    emotionalMoment: { feeling: 'courage', prompt: 'As-tu deja eu le courage de dire une verite difficile ?' },
    rewardEmoji: '🪡',
    rewardName: 'Courage de la Verite',
  },
  {
    id: 'steadfast-tin-soldier',
    coverImage: null,
    title: 'Le Soldat de Plomb',
    summary: 'Un brave petit soldat de plomb vit une grande aventure et prouve que le courage vient du coeur.',
    theme: 'courage et fidelite',
    emoji: '🪖',
    palette: { primary: '#455a64', accent: '#90a4ae', background: '#060a0d' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Parmi une boite de soldats de plomb, l\'un d\'eux n\'avait qu\'une seule jambe. Mais il se tenait droit et fier comme les autres.' },
      { text: 'Sur une etagere en face, une petite danseuse en papier levait une jambe. Le soldat crut qu\'elle etait comme lui, et en tomba amoureux.', dialogue: { speaker: 'Soldat', line: 'Elle est si belle. Je voudrais rester pres d\'elle pour toujours.' } },
      { text: 'Un diablotin jaloux dans une boite cria que le soldat ne devait pas regarder la danseuse. Le lendemain, le soldat tomba d\'une fenetre.' },
      { text: 'Dans la rue, des enfants le trouverent et le mirent dans un bateau en papier. Il naviga dans le caniveau sous la pluie, puis fut avale par un gros poisson.' },
      { text: 'Le poisson fut peche et finit a la cuisine. La cuisiniere l\'ouvrit et trouva le soldat de plomb intact, toujours droit.', dialogue: { speaker: 'Cuisiniere', line: 'Mais comment as-tu pu survivre a tout ca !' } },
      { text: 'Le soldat fut rendu a l\'enfant. Mais le diablotin jaloux poussa le soldat dans le feu. La petite danseuse tomba aussi par le vent. Il ne resta du soldat qu\'un petit coeur de metal en forme de coeur, symbole de sa fidelite eternelle.', dialogue: { speaker: 'Soldat', line: 'Je suis reste vaillant jusqu\'au bout.' } },
    ],
    vocabulary: [
      { word: 'plomb', meaning: 'un metal gris tres lourd, utilise pour faire des jouets autrefois', emoji: '⚙️' },
      { word: 'vaillant', meaning: 'courageux et fort face au danger', emoji: '🛡️' },
      { word: 'torrent', meaning: 'un courant d\'eau fort et rapide', emoji: '🌊' },
      { word: 'fidelite', meaning: 'rester loyal a quelqu\'un qu\'on aime, quoi qu\'il arrive', emoji: '💙' },
    ],
    miniGame: { type: 'choice', prompt: 'De quoi le soldat de plomb tombe-t-il amoureux ?', options: ['D\'une petite danseuse en papier', 'D\'une princesse au chateau', 'D\'une fee magique'], answerIndex: 0 },
    emotionalMoment: { feeling: 'fidelite', prompt: 'As-tu quelqu\'un ou quelque chose a qui tu es tres fidele ? Qu\'est-ce que ca signifie pour toi ?' },
    rewardEmoji: '🎖️',
    rewardName: 'Medaille du Courage',
  },
  // ── 10 nouveaux contes ──────────────────────────────────────────────────
  {
    id: 'musicians-of-bremen',
    coverImage: null,
    title: 'Les musiciens de Breme',
    summary: 'Un ane, un chien, un chat et un coq trop vieux pour travailler partent ensemble vers Breme et decouvrent que l\'amitie et le courage valent mieux que la force.',
    theme: 'amitie et courage',
    emoji: '🎺',
    palette: { primary: '#D97706', accent: '#FCD34D', background: '#FFFBEB' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Un vieux ane, trop fatigue pour travailler a la ferme, decidait de partir vers la grande ville de Breme pour devenir musicien.' },
      { text: 'En chemin il rencontra un chien, puis un chat, puis un coq — tous trop vieux pour leurs maitres. Ensemble ils marcherent.', dialogue: { speaker: 'L\'ane', line: 'Venez avec moi ! A Breme, nous ferons de la belle musique ensemble !' } },
      { text: 'La nuit tombee, ils trouverent une maison ou vivaient des brigands. Les quatre amis grimperent les uns sur les autres pres de la fenetre.' },
      { text: 'Ils se mirent a chanter tous en meme temps. Les brigands, terrifies par ce bruit etrange, s\'enfuirent dans la foret.', dialogue: { speaker: 'Coq', line: 'Cocorico ! Notre musique est si belle qu\'elle fait fuir les mechants !' } },
      { text: 'Les quatre amis s\'installerent dans la maison, si heureux ensemble qu\'ils n\'eurent jamais besoin d\'aller a Breme.' },
    ],
    vocabulary: [
      { word: 'musicien', meaning: 'quelqu\'un qui joue de la musique', emoji: '🎵' },
      { word: 'brigand', meaning: 'un voleur qui fait peur aux gens', emoji: '😈' },
      { word: 'terrifier', meaning: 'faire tres tres peur', emoji: '😱' },
      { word: 'ensemble', meaning: 'tous les uns avec les autres', emoji: '🤝' },
    ],
    miniGame: { type: 'count', prompt: 'Combien d\'animaux partent vers Breme ?', answer: 4, options: [3, 4, 5] },
    emotionalMoment: { feeling: 'amitie', prompt: 'Les animaux etaient plus forts ensemble. Quand tes amis t\'ont-ils aide a etre courageux ?' },
    rewardEmoji: '🎺',
    rewardName: 'Trompette de Breme',
  },
  {
    id: 'pied-piper',
    coverImage: WM('7/7c/The_pied_piper_of_Hamelin2.jpg'),
    title: 'Le Joueur de flute de Hamelin',
    summary: 'Dans la ville de Hamelin envahie de rats, un joueur de flute magique promet de resoudre le probleme — et apprend que les promesses doivent toujours etre tenues.',
    theme: 'honnetet et promesses',
    emoji: '🎶',
    palette: { primary: '#7C3AED', accent: '#C4B5FD', background: '#F5F3FF' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'La ville de Hamelin etait envahie de rats. Les habitants etaient desesperes et ne savaient que faire.' },
      { text: 'Un joueur de flute aux habits colores arriva et promit de chasser tous les rats pour une recompense.', dialogue: { speaker: 'Joueur de flute', line: 'Je peux chasser vos rats. Mais vous devez tenir votre promesse de me payer.' } },
      { text: 'Il joua une melodie magique. Tous les rats le suivirent jusqu\'au bord de la riviere et disparurent.' },
      { text: 'Mais les habitants refuserent de le payer. Le joueur de flute joua une autre melodie — pour les enfants cette fois.', dialogue: { speaker: 'Maire', line: 'Nous ne te paierons pas. Va-t\'en !' } },
      { text: 'Les enfants suivirent la musique dans la montagne. Ce jour-la, toute la ville apprit que les promesses doivent etre tenues.' },
    ],
    vocabulary: [
      { word: 'flute', meaning: 'un instrument de musique qu\'on souffle', emoji: '🎵' },
      { word: 'melodie', meaning: 'une suite de notes qui font une belle musique', emoji: '🎼' },
      { word: 'promesse', meaning: 'dire qu\'on va faire quelque chose et le faire vraiment', emoji: '🤝' },
      { word: 'recompense', meaning: 'quelque chose qu\'on donne en echange d\'un service', emoji: '🏆' },
    ],
    miniGame: { type: 'choice', prompt: 'Qu\'est-ce qui arrive quand on ne tient pas sa promesse ?', options: ['Rien du tout', 'On perd la confiance des autres', 'Les autres sont contents'], answerIndex: 1 },
    emotionalMoment: { feeling: 'honnete', prompt: 'As-tu deja tenu une promesse difficile ? Comment tu t\'es senti apres ?' },
    rewardEmoji: '🎶',
    rewardName: 'Flute magique',
  },
  {
    id: 'little-match-girl',
    coverImage: WM('f/f2/Edmund_Dulac_-_The_Little_Match_Girl.jpg'),
    title: 'La Petite Fille aux allumettes',
    summary: 'Par une nuit froide, une petite fille pauvre allume des allumettes qui lui montrent de beaux reves de chaleur et d\'amour.',
    theme: 'espoir et bonte',
    emoji: '🕯️',
    palette: { primary: '#F59E0B', accent: '#FDE68A', background: '#FFFBEB' },
    difficulty: 'doux',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Le soir du Nouvel An, par un froid terrible, une petite fille marchait pieds nus dans la neige en vendant des allumettes.' },
      { text: 'Personne ne lui achetait rien. Elle se blottit dans un coin et alluma une allumette pour se rechauffer les doigts.', dialogue: { speaker: 'Petite fille', line: 'Juste une allumette pour avoir un peu chaud...' } },
      { text: 'Dans la flamme elle vit un grand poele chaud, puis une belle table couverte de nourriture.' },
      { text: 'Elle alluma une autre allumette et vit son ancienne grand-mere, douce et aimante, qui lui souriait.', dialogue: { speaker: 'Grand-mere', line: 'Je suis la, ma cherie. Viens avec moi dans un endroit tout chaud.' } },
      { text: 'Le lendemain matin, les passants trouverent la petite fille endormie avec un sourire paisible. Elle avait vu de beaux reves de chaleur et d\'amour.' },
    ],
    vocabulary: [
      { word: 'allumette', meaning: 'un petit baton qui fait du feu quand on le frotte', emoji: '🔥' },
      { word: 'blottir', meaning: 'se mettre en boule dans un coin pour avoir chaud', emoji: '🤗' },
      { word: 'poele', meaning: 'un appareil qui chauffe une piece', emoji: '🔥' },
      { word: 'paisible', meaning: 'calme et serein, sans peur', emoji: '😌' },
    ],
    miniGame: { type: 'choice', prompt: 'Que voit la petite fille dans la flamme de sa premiere allumette ?', options: ['Un grand poele chaud', 'Sa grand-mere', 'Un arbre de Noel'], answerIndex: 0 },
    emotionalMoment: { feeling: 'espoir', prompt: 'Meme dans les moments difficiles, la petite fille gardait espoir. Qu\'est-ce qui te donne de l\'espoir quand tout va mal ?' },
    rewardEmoji: '🕯️',
    rewardName: 'Lumiere d\'espoir',
  },
  {
    id: 'princess-pea',
    coverImage: WM('1/1a/Hans_Christian_Andersen_-_The_Real_Princess.jpg'),
    title: 'La Princesse au petit pois',
    summary: 'Une vraie princesse est reconnue grace a sa grande sensibilite — une fable amusante sur l\'importance d\'etre soi-meme.',
    theme: 'etre soi-meme',
    emoji: '👸',
    palette: { primary: '#EC4899', accent: '#FBCFE8', background: '#FFF0F6' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Un prince cherchait une vraie princesse a epouser. Mais comment savoir si une princesse etait vraiment vraie ?' },
      { text: 'Par une nuit de tempete, une jeune fille toute mouilee frappa a la porte du chateau et dit qu\'elle etait une princesse.', dialogue: { speaker: 'Jeune fille', line: 'Je suis une vraie princesse, je vous l\'assure !' } },
      { text: 'La vieille reine eut une idee maligne. Elle posa un petit pois sous vingt matelas et vingt couvertures en duvet.' },
      { text: 'Le lendemain matin, on demanda a la jeune fille comment elle avait dormi.', dialogue: { speaker: 'Jeune fille', line: 'Oh, tres mal ! J\'ai senti quelque chose de dur toute la nuit. Je suis toute couverte de bleus !' } },
      { text: 'Seule une vraie princesse pouvait sentir un tout petit pois a travers tant de matelas. Le prince l\'epousa et ils furent tres heureux.' },
    ],
    vocabulary: [
      { word: 'princesse', meaning: 'la fille d\'un roi ou d\'une reine', emoji: '👸' },
      { word: 'matelas', meaning: 'la partie douce du lit sur laquelle on dort', emoji: '🛏️' },
      { word: 'sensible', meaning: 'qui ressent les choses tres fort', emoji: '💝' },
      { word: 'tempete', meaning: 'un temps tres mauvais avec vent et pluie', emoji: '⛈️' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de matelas la reine a-t-elle empiles ?', answer: 20, options: [10, 15, 20] },
    emotionalMoment: { feeling: 'soi-meme', prompt: 'La princesse etait reconnue pour ce qu\'elle etait vraiment. Qu\'est-ce qui te rend unique ?' },
    rewardEmoji: '👸',
    rewardName: 'Couronne de sensibilite',
  },
  {
    id: 'wild-swans',
    coverImage: null,
    title: 'Les Cygnes Sauvages',
    summary: 'Une courageuse princesse travaille en silence pendant des annees pour briser le sort qui a transforme ses onze freres en cygnes.',
    theme: 'courage silencieux et amour',
    emoji: '🦢',
    palette: { primary: '#0EA5E9', accent: '#BAE6FD', background: '#F0F9FF' },
    difficulty: 'aventure',
    ageMin: 6,
    ageMax: 10,
    scenes: [
      { text: 'Elise avait onze freres que la mechante belle-mere avait transformes en cygnes sauvages grace a un sort terrible.' },
      { text: 'Une fee lui dit le secret : elle devait tricoter onze manteaux d\'orties sans jamais prononcer un seul mot.', dialogue: { speaker: 'Fee', line: 'Tu dois travailler en silence. Un seul mot et tes freres resteront cygnes pour toujours.' } },
      { text: 'Elise tricotat sans s\'arreter, meme quand ses mains saignaient, meme quand les gens la regardaient d\'un mauvais oeil.' },
      { text: 'Des annees passerent. Enfin, dans un grand effort, elle jeta les manteaux sur les cygnes.', dialogue: { speaker: 'Elise', line: 'Mes freres ! Je vous ai attendus si longtemps !' } },
      { text: 'Les cygnes redevinrent ses freres, grands et beaux. Elise put enfin parler et leur dire tout son amour.' },
    ],
    vocabulary: [
      { word: 'sort', meaning: 'une magie qui transforme quelqu\'un', emoji: '✨' },
      { word: 'ortie', meaning: 'une plante aux feuilles qui piquent', emoji: '🌿' },
      { word: 'tricoter', meaning: 'faire des vetements avec des fils et des aiguilles', emoji: '🧶' },
      { word: 'silence', meaning: 'quand on ne dit pas un seul mot', emoji: '🤫' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de freres Elise doit-elle sauver ?', answer: 11, options: [7, 9, 11] },
    emotionalMoment: { feeling: 'determination', prompt: 'Elise a travaille en silence pendant des annees pour aider ses freres. Qu\'est-ce que tu ferais pour quelqu\'un que tu aimes ?' },
    rewardEmoji: '🦢',
    rewardName: 'Plume de cygne',
  },
  {
    id: 'chevre-monsieur-seguin',
    coverImage: null,
    title: 'La Chevre de Monsieur Seguin',
    summary: 'La petite chevre Blanquette veut la liberte et s\'enfuit dans la montagne, mais elle decouvre que la vraie liberte s\'accompagne de responsabilite.',
    theme: 'liberte et prudence',
    emoji: '🐐',
    palette: { primary: '#65A30D', accent: '#D9F99D', background: '#F7FEE7' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Monsieur Seguin avait une belle petite chevre blanche qu\'il appelait Blanquette. Mais Blanquette voulait la liberte de la montagne.' },
      { text: 'Monsieur Seguin la supplia de rester.', dialogue: { speaker: 'M. Seguin', line: 'Blanquette, reste ! Dans la montagne il y a un grand loup qui mange toutes les chevres !' } },
      { text: 'Blanquette n\'ecouta pas. Elle sauta par-dessus la clôture et s\'elanca vers les pres de la montagne, tout heureuse.' },
      { text: 'Toute la journee elle gambada, mangea de belles herbes et respira l\'air frais. Mais le soir, le grand loup arriva.', dialogue: { speaker: 'Blanquette', line: 'Je vais me battre jusqu\'a l\'aube ! Je ne capitulerai pas !' } },
      { text: 'Blanquette se battit courageusement toute la nuit. Quand l\'aube arriva, epuisee, elle avait appris que la liberte demande aussi de la prudence.' },
    ],
    vocabulary: [
      { word: 'chevre', meaning: 'un animal de ferme avec des cornes qui donne du lait', emoji: '🐐' },
      { word: 'gambader', meaning: 'sauter et courir librement comme par jeu', emoji: '🦘' },
      { word: 'capitulier', meaning: 'abandonner et admettre qu\'on a perdu', emoji: '🏳️' },
      { word: 'aube', meaning: 'le premier moment du matin quand le soleil se leve', emoji: '🌅' },
    ],
    miniGame: { type: 'choice', prompt: 'Pourquoi Monsieur Seguin veut-il garder Blanquette ?', options: ['Pour avoir du lait', 'Pour la proteger du loup', 'Pour ne pas etre seul'], answerIndex: 1 },
    emotionalMoment: { feeling: 'liberte et prudence', prompt: 'Blanquette voulait etre libre mais n\'etait pas prudente. Comment peut-on etre libre et en securite en meme temps ?' },
    rewardEmoji: '🐐',
    rewardName: 'Clochette de montagne',
  },
  {
    id: 'sinbad',
    coverImage: null,
    title: 'Sinbad le Marin',
    summary: 'Le courageux marin Sinbad voyage sur les mers du monde entier, affronte des monstres et des tempetes, et revient toujours plus sage qu\'il n\'etait parti.',
    theme: 'courage et sagesse',
    emoji: '⛵',
    palette: { primary: '#0284C7', accent: '#7DD3FC', background: '#F0F9FF' },
    difficulty: 'explorateur',
    ageMin: 6,
    ageMax: 10,
    scenes: [
      { text: 'Sinbad etait un riche marchand de Bagdad qui adorait les aventures. Il avait fait sept grands voyages sur les mers du monde.' },
      { text: 'Lors de son premier voyage, son bateau s\'echoua sur ce qu\'il croyait etre une ile — mais c\'etait un enorme poisson endormi !', dialogue: { speaker: 'Sinbad', line: 'Ce n\'est pas une ile... c\'est une creature vivante ! Fuyons !' } },
      { text: 'A chaque voyage, Sinbad affrontait des perils nouveaux : un geant borgne, un roi des oiseaux, un serpent de mer. Il surmontait tout grace a son esprit.' },
      { text: 'Il rapportait toujours des tresors, mais surtout des histoires et de la sagesse.', dialogue: { speaker: 'Sinbad', line: 'Les vraies richesses ne sont pas les pierreries, mais ce qu\'on apprend dans ses voyages.' } },
      { text: 'A Bagdad, les gens l\'ecoutaient des heures entdentierement. Chaque voyage lui avait appris quelque chose de nouveau sur le monde et sur lui-meme.' },
    ],
    vocabulary: [
      { word: 'marin', meaning: 'quelqu\'un qui voyage et travaille sur la mer', emoji: '⚓' },
      { word: 'echouer', meaning: 'quand un bateau s\'arrete sur le fond ou sur une plage', emoji: '🏖️' },
      { word: 'peril', meaning: 'un grand danger', emoji: '⚠️' },
      { word: 'sagesse', meaning: 'la connaissance qu\'on gagne avec l\'experience', emoji: '🦉' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de grands voyages Sinbad a-t-il faits en tout ?', answer: 7, options: [5, 7, 9] },
    emotionalMoment: { feeling: 'aventure et sagesse', prompt: 'Sinbad apprenait quelque chose a chaque voyage. Qu\'est-ce que tu as appris lors d\'un voyage ou d\'une nouvelle experience ?' },
    rewardEmoji: '⛵',
    rewardName: 'Boussole du voyageur',
  },
  {
    id: 'tinder-box',
    coverImage: null,
    title: 'Le Briquet magique',
    summary: 'Un soldat trouve un briquet magique qui commande trois chiens enormes. Une histoire sur la generosit\'e, la bonte et la valeur de l\'amitie.',
    theme: 'generosite et amitie',
    emoji: '🔦',
    palette: { primary: '#F59E0B', accent: '#FDE68A', background: '#FFFBEB' },
    difficulty: 'aventure',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Un soldat revenait de la guerre quand une vieille sorciere lui proposa un marche : entrer dans un arbre creux et lui rapporter un briquet.' },
      { text: 'Dans l\'arbre, le soldat trouva trois chiens enormes aux yeux comme des soucoupes, gardant des coffres pleins de pices d\'or.', dialogue: { speaker: 'Soldat', line: 'Ces chiens sont enormes... mais tant que je tiens le briquet, ils obeissent !' } },
      { text: 'Le soldat prit le briquet et beaucoup d\'or. Il devint riche et genereux — il donnait a manger a tous les pauvres de la ville.' },
      { text: 'Un soir il alluma le briquet et les chiens apparurent. Ils accomplissaient tous ses voeux, mais il leur demandait toujours des choses gentilles.', dialogue: { speaker: 'Soldat', line: 'Allez, mes bons amis ! Apportez de la nourriture pour tout le village !' } },
      { text: 'Grace a sa bonte, le soldat gagna l\'amour de tous. Il apprit que la vraie magie, c\'est un coeur genereux.' },
    ],
    vocabulary: [
      { word: 'briquet', meaning: 'un petit objet qui fait du feu', emoji: '🔥' },
      { word: 'sorciere', meaning: 'une personne qui fait de la magie, parfois mechamment', emoji: '🧙' },
      { word: 'coffre', meaning: 'une grande boite solide pour garder des tresors', emoji: '📦' },
      { word: 'genereux', meaning: 'qui aime donner et partager avec les autres', emoji: '🎁' },
    ],
    miniGame: { type: 'count', prompt: 'Combien de chiens magiques gardent les tresors ?', answer: 3, options: [2, 3, 4] },
    emotionalMoment: { feeling: 'generosite', prompt: 'Le soldat partageait sa richesse avec les pauvres. As-tu partage quelque chose que tu aimais ? Comment tu t\'es senti ?' },
    rewardEmoji: '🔦',
    rewardName: 'Briquet de bonte',
  },
  {
    id: 'blue-bird',
    coverImage: null,
    title: 'L\'Oiseau Bleu',
    summary: 'Deux enfants, Tyltyl et Mytyl, partent a la recherche de l\'Oiseau Bleu du bonheur et decouvrent que le bonheur se trouve souvent tout pres de chez soi.',
    theme: 'bonheur et gratitude',
    emoji: '🐦',
    palette: { primary: '#3B82F6', accent: '#BFDBFE', background: '#EFF6FF' },
    difficulty: 'explorateur',
    ageMin: 5,
    ageMax: 9,
    scenes: [
      { text: 'Tyltyl et Mytyl, deux enfants pauvres mais joyeux, vivaient avec leurs parents dans une petite maison au bord de la foret.' },
      { text: 'La fee Berylune leur apparut et leur demanda de trouver l\'Oiseau Bleu du bonheur pour guerir sa petite-fille malade.', dialogue: { speaker: 'Fee Berylune', line: 'Partez chercher l\'Oiseau Bleu ! Il est quelque part dans le monde.' } },
      { text: 'Les enfants voyagerent dans le Pays du Souvenir, le Palais de la Nuit et le Jardin des Bonheurs Futurs. Partout ils cherchaient l\'oiseau.' },
      { text: 'Partout les oiseaux bleus qu\'ils trouvaient mouraient ou changeaient de couleur. Decourages, ils rentrerent chez eux.', dialogue: { speaker: 'Tyltyl', line: 'Nous avons cherche partout... l\'Oiseau Bleu n\'existe peut-etre pas ?' } },
      { text: 'De retour a la maison, Tyltyl remarqua que son pigeon — qu\'il avait depuis toujours — avait des plumes d\'un bleu magnifique. Le bonheur etait la, tout pres.' },
    ],
    vocabulary: [
      { word: 'bonheur', meaning: 'un sentiment de joie et de satisfaction profonde', emoji: '😊' },
      { word: 'guerir', meaning: 'aller mieux apres avoir ete malade', emoji: '💊' },
      { word: 'souvenir', meaning: 'une image ou un sentiment qu\'on garde dans sa memoire', emoji: '💭' },
      { word: 'gratitude', meaning: 'etre reconnaissant et content de ce qu\'on a', emoji: '🙏' },
    ],
    miniGame: { type: 'choice', prompt: 'Ou Tyltyl trouve-t-il finalement l\'Oiseau Bleu ?', options: ['Dans un chateau lointain', 'Dans sa propre maison', 'Au fond de la mer'], answerIndex: 1 },
    emotionalMoment: { feeling: 'gratitude', prompt: 'Le bonheur etait tout pres de chez eux depuis le debut. Quelles belles choses as-tu deja qui te rendent heureux ?' },
    rewardEmoji: '🐦',
    rewardName: 'Plume de bonheur',
  },
  {
    id: 'renart-goupil',
    coverImage: null,
    title: 'Renart le Goupil',
    summary: 'Le rusé renard Renart utilise son intelligence pour se sortir de toutes les situations — une serie de fables medievales sur la ruse et ses limites.',
    theme: 'intelligence et humilite',
    emoji: '🦊',
    palette: { primary: '#DC2626', accent: '#FCA5A5', background: '#FFF5F5' },
    difficulty: 'aventure',
    ageMin: 6,
    ageMax: 10,
    scenes: [
      { text: 'Au Moyen Age, dans la grande foret, vivait Renart le Goupil, le renard le plus ruse de tous les animaux.' },
      { text: 'Un jour, Renart vola un beau poulet a Chantecler le coq. Mais Chantecler avait un plan.', dialogue: { speaker: 'Chantecler', line: 'Renart, tu es si beau ! Montre-moi comment tu chantes quand tu es fier !' } },
      { text: 'Renart, flatte, ouvrit la gueule pour chanter — et le poulet s\'echappa. La ruse avait ete retournee contre lui !' },
      { text: 'Renart essaya de voler le fromage d\'Ysengrin le loup. Cette fois, c\'est le loup qui le battit de vitesse.', dialogue: { speaker: 'Ysengrin', line: 'Tu n\'es pas le seul a pouvoir etre ruse, Renart !' } },
      { text: 'Renart apprit que meme le renard le plus ruse peut etre attrape. Il vaut mieux parfois etre honnete plutot que tricher.' },
    ],
    vocabulary: [
      { word: 'goupil', meaning: 'l\'ancien mot francais pour renard', emoji: '🦊' },
      { word: 'ruse', meaning: 'tres habile pour tromper les autres par des astuces', emoji: '🎭' },
      { word: 'flatter', meaning: 'dire trop de compliments pour obtenir quelque chose', emoji: '😏' },
      { word: 'honnete', meaning: 'qui dit la verite et ne triche pas', emoji: '✅' },
    ],
    miniGame: { type: 'choice', prompt: 'Comment Chantecler recupere-t-il son poulet ?', options: ['En courant plus vite', 'En flattant Renart pour qu\'il ouvre la gueule', 'En appelant d\'autres animaux'], answerIndex: 1 },
    emotionalMoment: { feeling: 'humilite', prompt: 'Renart pensait etre le plus ruse mais il s\'est fait avoir. As-tu deja appris quelque chose d\'important en te trompant ?' },
    rewardEmoji: '🦊',
    rewardName: 'Queue de Renart',
  },
  // ── Fin des nouveaux contes ─────────────────────────────────────────────
  {
    id: 'la-fontaine-crow-fox',
    coverImage: null,
    title: 'Le Corbeau et le Renard',
    summary: 'Un renard tres ruse flatte un corbeau pour lui voler son fromage. Une fable sur la vanite.',
    theme: 'ruse et humilite',
    emoji: '🦊',
    palette: { primary: '#4a148c', accent: '#ce93d8', background: '#0d0014' },
    difficulty: 'doux',
    ageMin: 4,
    ageMax: 8,
    scenes: [
      { text: 'Un corbeau etait perche sur une branche, tenant dans son bec un beau morceau de fromage bien parfume.' },
      { text: 'Un renard tres ruse passa par la et sentit le fromage. Il decida de le lui voler par la flatterie.', dialogue: { speaker: 'Renard', line: 'Oh Monsieur le Corbeau, que vous etes beau ! Que votre plumage est magnifique !' } },
      { text: 'Le corbeau, tout fier des compliments, gonflait ses plumes de plaisir. Le renard continua.', dialogue: { speaker: 'Renard', line: 'Si votre voix est aussi belle que vos plumes, vous etes le roi des oiseaux !' } },
      { text: 'Le corbeau, trop flatte, ouvrit grand le bec pour chanter. Le fromage tomba.' },
      { text: 'Le renard attrapa le fromage en riant et dit la morale de la fable.', dialogue: { speaker: 'Renard', line: 'Tout flatteur vit aux depens de celui qui l\'ecoute. Cette lecon vaut bien un fromage !' } },
    ],
    vocabulary: [
      { word: 'corbeau', meaning: 'un grand oiseau noir avec un fort bec courbe', emoji: '🐦‍⬛' },
      { word: 'flatteur', meaning: 'quelqu\'un qui dit trop de compliments pour obtenir quelque chose', emoji: '😏' },
      { word: 'fromage', meaning: 'un aliment fait avec du lait, souvent jaune ou blanc', emoji: '🧀' },
      { word: 'morale', meaning: 'la lecon qu\'on apprend a la fin d\'une fable', emoji: '📜' },
    ],
    miniGame: { type: 'choice', prompt: 'Comment le renard obtient-il le fromage ?', options: ['En flattant le corbeau pour qu\'il ouvre le bec', 'En grimpant a l\'arbre', 'En demandant poliment'], answerIndex: 0 },
    emotionalMoment: { feeling: 'humilite', prompt: 'As-tu deja ete flatte et fait quelque chose de stupide ? Qu\'as-tu appris ?' },
    rewardEmoji: '📜',
    rewardName: 'Sagesse de la Fable',
  },
];

export function getConteById(id) {
  return CONTES.find((c) => c.id === id) || null;
}
