import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade3Modules = [
  createModule({
    id: 'math-g3-large-numbers',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'large-numbers',
    domainLabel: 'Nombres a trois chiffres',
    title: 'Lire, decomposer et ordonner',
    summary: 'Travailler centaines, dizaines et unites avec des nombres plus grands.',
    goal: 'Lire et decomposer avant d ordonner ou calculer.',
    demo: 'Une demonstration montre comment casser un nombre en centaines, dizaines et unites.',
    guidedActivityIds: ['large-numbers-p3', 'generated-comparison-p3', 'generated-place-value-p3'],
    independentActivityIds: ['generated-classification-p3'],
    challengeActivityId: 'place-value',
    examActivityId: 'generated-comparison-p3',
    suggestedReviewIds: ['large-numbers-p3'],
    missionTitle: 'Mission nombres P3',
    missionSummary: 'Comparer et ordonner des nombres a trois chiffres.'
  }),
  createModule({
    id: 'math-g3-operations',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'operations',
    domainLabel: 'Operations',
    title: 'Addition, soustraction et calcul mental',
    summary: 'Calculer avec des nombres plus grands et verifier son resultat.',
    goal: 'Construire des automatismes plus solides sur les operations.',
    demo: 'On montre comment reperer les dizaines et les centaines utiles.',
    guidedActivityIds: ['generated-addition-p3', 'generated-subtraction-p3'],
    independentActivityIds: ['generated-mental-math-p3'],
    challengeActivityId: 'number-line',
    examActivityId: 'generated-subtraction-p3',
    suggestedReviewIds: ['generated-addition-p3'],
    missionTitle: 'Mission operations P3',
    missionSummary: 'Addition, soustraction et calcul mental plus ambitieux.'
  }),
  createModule({
    id: 'math-g3-patterns',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'patterns',
    domainLabel: 'Suites et patrons',
    title: 'Suites, patrons et classement',
    summary: 'Continuer une suite, trouver une regle et classer plusieurs elements.',
    goal: 'Installer une logique plus strategique et plus autonome.',
    demo: 'On montre comment tester une regle puis la verifier sur toute la suite.',
    guidedActivityIds: ['generated-patterns-p3', 'generated-logic-sequences'],
    independentActivityIds: ['generated-classification-p3'],
    challengeActivityId: 'geometry-p3',
    examActivityId: 'generated-patterns-p3',
    suggestedReviewIds: ['generated-comparison-p3'],
    missionTitle: 'Mission suites P3',
    missionSummary: 'Patrons, sequences et classements a trois chiffres.'
  }),
  createModule({
    id: 'math-g3-multiplication',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'multiplication',
    domainLabel: 'Multiplication',
    title: 'Tables et paquets egaux',
    summary: 'Automatiser les tables utiles et reconnaitre des groupes egaux.',
    goal: 'Passer a une multiplication rapide et comprise.',
    demo: 'Une demonstration montre les paquets egaux et la suite des resultats.',
    guidedActivityIds: ['multiplication-table-2', 'generated-multiplication-p3', 'multiplication-table-6'],
    independentActivityIds: ['mult-div-families', 'multiplication-table-7', 'multiplication-table-8'],
    challengeActivityId: 'word-problems',
    examActivityId: 'multiplication-table-12',
    suggestedReviewIds: ['multiplication-table-9', 'multiplication-table-10', 'multiplication-table-11'],
    missionTitle: 'Mission multiplications P3',
    missionSummary: 'Tables, familles d operations et groupes egaux.'
  }),
  createModule({
    id: 'math-g3-division',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'division',
    domainLabel: 'Division',
    title: 'Partager, verifier et relier aux tables',
    summary: 'Partager en groupes egaux, verifier un quotient et faire le lien avec la multiplication.',
    goal: 'Installer les premieres divisions comme une operation comprise.',
    demo: 'Une demonstration montre comment repartir puis verifier avec la multiplication.',
    guidedActivityIds: ['generated-division-p3', 'mult-div-families', 'division-table-6'],
    independentActivityIds: ['generated-multiplication-p3', 'division-table-7', 'division-table-8'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'division-table-12',
    suggestedReviewIds: ['division-table-9', 'division-table-10', 'division-table-11'],
    missionTitle: 'Mission divisions P3',
    missionSummary: 'Partager, verifier et utiliser les liens entre multiplication et division.'
  }),
  createModule({
    id: 'math-g3-time-geometry',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'time-geometry',
    domainLabel: 'Heure et geometrie',
    title: 'Heure, figures et symetrie',
    summary: 'Ateliers utiles de lecture de l heure et de geometrie simple maintenant visibles dans le grade.',
    goal: 'Ne pas laisser ces jeux jouables caches hors du parcours principal.',
    demo: 'Une demonstration montre comment lire l heure puis comparer les proprietes des figures.',
    guidedActivityIds: ['read-time-p2', 'generated-time-p3', 'shapes-symmetry-p2'],
    independentActivityIds: ['geometry-p3', 'generated-money-p3', 'generated-geometry-p3'],
    challengeActivityId: 'money-simple',
    examActivityId: 'generated-geometry-p3',
    suggestedReviewIds: ['read-time-p2'],
    missionTitle: 'Mission heure et geometrie P3',
    missionSummary: 'Lire l heure, reconnaitre des figures et renforcer la symetrie.'
  }),
  createModule({
    id: 'math-g3-table-fluency',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'table-fluency',
    domainLabel: 'Fluence des tables',
    title: 'Consolider les tables 2 a 5',
    summary: 'Revoir les tables utiles du debut de parcours pour ne rien laisser cache.',
    goal: 'Rendre visibles et rejouables toutes les premieres tables de multiplication et de division.',
    demo: 'Une demonstration relie multiplication, division et familles d operations.',
    guidedActivityIds: ['multiplication-table-3', 'multiplication-table-4', 'multiplication-table-5'],
    independentActivityIds: ['division-table-2', 'division-table-3', 'division-table-4', 'division-table-5'],
    challengeActivityId: 'mult-div-families',
    examActivityId: 'generated-division-p3',
    suggestedReviewIds: ['generated-multiplication-p3'],
    missionTitle: 'Mission tables 2 a 5 P3',
    missionSummary: 'Consolider les premieres tables avant les plus grandes automatisations.'
  }),
  createModule({
    id: 'math-g3-problems',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'problems',
    domainLabel: 'Problemes',
    title: 'Problemes en une ou deux etapes',
    summary: 'Lire, trier les informations et choisir la bonne operation.',
    goal: 'Rendre les problemes lisibles et strategiques.',
    demo: 'Une demonstration visuelle isole les informations utiles avant de calculer.',
    guidedActivityIds: ['word-problems', 'generated-word-problems'],
    independentActivityIds: ['money-simple'],
    challengeActivityId: 'generated-mental-math-p3',
    examActivityId: 'generated-word-problems',
    suggestedReviewIds: ['generated-subtraction-p3'],
    missionTitle: 'Mission problemes P3',
    missionSummary: 'Passer de la lecture du probleme au bon calcul.'
  })
];
