import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade3Modules = [
  createModule({
    id: 'math-g3-large-numbers',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'large-numbers',
    domainLabel: 'Nombres a trois chiffres',
    title: 'Lire, decomposer et ordonner',
    summary: 'Travailler centaines, dizaines et unites avec des nombres plus grands.',
    goal: 'Lire et decomposer avant d ordonner ou calculer.',
    demo: 'Une demonstration montre comment casser un nombre en centaines, dizaines et unites.',
    guidedActivityIds: ['large-numbers-p3', 'generated-comparison-p3'],
    independentActivityIds: ['generated-classification-p3'],
    challengeActivityId: 'place-value',
    examActivityId: 'generated-comparison-p3',
    suggestedReviewIds: ['large-numbers-p3'],
    missionTitle: 'Mission nombres P3',
    missionSummary: 'Comparer et ordonner des nombres a trois chiffres.'
  }),
  createModule({
    id: 'math-g3-operations',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'operations',
    domainLabel: 'Operations',
    title: 'Addition, soustraction et calcul mental',
    summary: 'Calculer avec des nombres plus grands et verifier son resultat.',
    goal: 'Construire des automatismes plus solides sur les operations.',
    demo: 'On montre comment reperer les dizaines et les centaines utiles.',
    guidedActivityIds: ['generated-addition-p3', 'generated-subtraction-p3'],
    independentActivityIds: ['generated-mental-math-p3'],
    challengeActivityId: 'number-line',
    examActivityId: 'generated-subtraction-p3',
    suggestedReviewIds: ['generated-addition-p3'],
    missionTitle: 'Mission operations P3',
    missionSummary: 'Addition, soustraction et calcul mental plus ambitieux.'
  }),
  createModule({
    id: 'math-g3-patterns',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'patterns',
    domainLabel: 'Suites et patrons',
    title: 'Suites, patrons et classement',
    summary: 'Continuer une suite, trouver une regle et classer plusieurs elements.',
    goal: 'Installer une logique plus strategique et plus autonome.',
    demo: 'On montre comment tester une regle puis la verifier sur toute la suite.',
    guidedActivityIds: ['generated-patterns-p3', 'generated-logic-sequences'],
    independentActivityIds: ['generated-classification-p3'],
    challengeActivityId: 'geometry-p3',
    examActivityId: 'generated-patterns-p3',
    suggestedReviewIds: ['generated-comparison-p3'],
    missionTitle: 'Mission suites P3',
    missionSummary: 'Patrons, sequences et classements a trois chiffres.'
  }),
  createModule({
    id: 'math-g3-multiplication',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'multiplication',
    domainLabel: 'Multiplication',
    title: 'Tables et paquets egaux',
    summary: 'Automatiser les tables utiles et reconnaitre des groupes egaux.',
    goal: 'Passer a une multiplication rapide et comprise.',
    demo: 'Une demonstration montre les paquets egaux et la suite des resultats.',
    guidedActivityIds: ['multiplication-table-2', 'generated-multiplication-p3'],
    independentActivityIds: ['mult-div-families'],
    challengeActivityId: 'word-problems',
    examActivityId: 'generated-multiplication-p3',
    suggestedReviewIds: ['multiplication-table-2'],
    missionTitle: 'Mission multiplications P3',
    missionSummary: 'Tables, familles d operations et groupes egaux.'
  }),
  createModule({
    id: 'math-g3-division',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'division',
    domainLabel: 'Division',
    title: 'Partager, verifier et relier aux tables',
    summary: 'Partager en groupes egaux, verifier un quotient et faire le lien avec la multiplication.',
    goal: 'Installer les premieres divisions comme une operation comprise.',
    demo: 'Une demonstration montre comment repartir puis verifier avec la multiplication.',
    guidedActivityIds: ['generated-division-p3', 'mult-div-families'],
    independentActivityIds: ['generated-multiplication-p3'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'generated-division-p3',
    suggestedReviewIds: ['generated-multiplication-p3'],
    missionTitle: 'Mission divisions P3',
    missionSummary: 'Partager, verifier et utiliser les liens entre multiplication et division.'
  }),
  createModule({
    id: 'math-g3-problems',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'problems',
    domainLabel: 'Problemes',
    title: 'Problemes en une ou deux etapes',
    summary: 'Lire, trier les informations et choisir la bonne operation.',
    goal: 'Rendre les problemes lisibles et strategiques.',
    demo: 'Une demonstration visuelle isole les informations utiles avant de calculer.',
    guidedActivityIds: ['word-problems', 'generated-word-problems'],
    independentActivityIds: ['money-simple'],
    challengeActivityId: 'generated-mental-math-p3',
    examActivityId: 'generated-word-problems',
    suggestedReviewIds: ['generated-subtraction-p3'],
    missionTitle: 'Mission problemes P3',
    missionSummary: 'Passer de la lecture du probleme au bon calcul.'
  })
];
