import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade3Modules = [
  createModule({
    id: 'math-g3-large-numbers',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'large-numbers',
    domainLabel: 'Grands nombres',
    title: 'Lire, decomposer et comparer',
    summary: 'Stabiliser centaines, dizaines et unites avec des nombres plus grands.',
    goal: 'Lire et decomposer avant d ordonner ou calculer.',
    demo: 'Une demonstration montre comment casser un nombre en centaines, dizaines et unites.',
    guidedActivityIds: ['large-numbers-p3', 'place-value'],
    independentActivityIds: ['generated-comparison-p3'],
    challengeActivityId: 'large-numbers-p3',
    examActivityId: 'generated-comparison-p3',
    suggestedReviewIds: ['build-number']
  }),
  createModule({
    id: 'math-g3-add-sub',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'operations',
    domainLabel: 'Operations',
    title: 'Additions et soustractions plus grandes',
    summary: 'Calculer avec des nombres plus larges puis relire son resultat.',
    goal: 'Passer a des operations plus ambitieuses sans perdre le sens.',
    demo: 'On montre comment reperer les dizaines et les centaines utiles.',
    guidedActivityIds: ['generated-addition-p3', 'generated-subtraction-p3'],
    independentActivityIds: ['number-line'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'generated-subtraction-p3',
    suggestedReviewIds: ['generated-addition-p3']
  }),
  createModule({
    id: 'math-g3-tables-a',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'tables',
    domainLabel: 'Tables',
    title: 'Tables 2 a 5',
    summary: 'Reviser les tables de base et aller plus vite.',
    goal: 'Automatiser les produits de base.',
    demo: 'Une demonstration montre les paquets egaux et la suite des resultats.',
    guidedActivityIds: ['multiplication-table-2', 'multiplication-table-3', 'multiplication-table-4'],
    independentActivityIds: ['multiplication-table-5'],
    challengeActivityId: 'generated-multiplication-p3',
    examActivityId: 'multiplication-table-4',
    suggestedReviewIds: ['multiplication-table-2']
  }),
  createModule({
    id: 'math-g3-tables-b',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'tables',
    domainLabel: 'Tables',
    title: 'Tables 6 a 10',
    summary: 'Enchainer les produits plus difficiles et garder le rythme.',
    goal: 'Monter en puissance sur les tables usuelles.',
    demo: 'On montre comment reconnaitre les produits connus dans une nouvelle table.',
    guidedActivityIds: ['multiplication-table-6', 'multiplication-table-7', 'multiplication-table-8'],
    independentActivityIds: ['multiplication-table-9', 'multiplication-table-10'],
    challengeActivityId: 'generated-multiplication-p3',
    examActivityId: 'multiplication-table-8',
    suggestedReviewIds: ['multiplication-table-6']
  }),
  createModule({
    id: 'math-g3-tables-c',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'tables',
    domainLabel: 'Tables avancees',
    title: 'Tables 11 a 20',
    summary: 'Decouvrir des tables plus ambitieuses avec repères et rythme.',
    goal: 'Construire une reserve d automatismes plus large.',
    demo: 'Une demonstration montre comment reutiliser les produits deja connus.',
    guidedActivityIds: ['multiplication-table-11', 'multiplication-table-12', 'multiplication-table-15'],
    independentActivityIds: ['multiplication-table-20'],
    challengeActivityId: 'generated-multiplication-p3',
    examActivityId: 'multiplication-table-12',
    suggestedReviewIds: ['multiplication-table-11']
  }),
  createModule({
    id: 'math-g3-division',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'division',
    domainLabel: 'Division',
    title: 'Divisions simples et familles',
    summary: 'Partager, regrouper et retrouver les familles multiplication division.',
    goal: 'Faire le lien entre partager et multiplier.',
    demo: 'On montre d abord une famille d operations complete.',
    guidedActivityIds: ['generated-division-p3', 'mult-div-families'],
    independentActivityIds: ['generated-multiplication-p3'],
    challengeActivityId: 'word-problems',
    examActivityId: 'generated-division-p3',
    suggestedReviewIds: ['mult-div-families']
  }),
  createModule({
    id: 'math-g3-problems',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'problems',
    domainLabel: 'Problemes',
    title: 'Problemes en une ou plusieurs etapes',
    summary: 'Lire, trier les informations et choisir la bonne question.',
    goal: 'Rendre les problemes lisibles et strategiques.',
    demo: 'Une demonstration visuelle isole les informations utiles avant de calculer.',
    guidedActivityIds: ['word-problems', 'generated-word-problems'],
    independentActivityIds: ['generated-logic-sequences'],
    challengeActivityId: 'word-problems',
    examActivityId: 'generated-word-problems',
    suggestedReviewIds: ['generated-subtraction-p3']
  }),
  createModule({
    id: 'math-g3-money-time',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'measures',
    domainLabel: 'Mesures, heure et monnaie',
    title: 'Monnaie, masses et heure',
    summary: 'Comparer des prix, lire l heure et garder des reperes concrets.',
    goal: 'Appliquer les maths dans les situations du quotidien.',
    demo: 'On montre comment lire une somme, une heure et une mesure simple.',
    guidedActivityIds: ['money-simple', 'read-time-p2'],
    independentActivityIds: ['generated-word-problems'],
    challengeActivityId: 'money-simple',
    examActivityId: 'read-time-p2',
    suggestedReviewIds: ['money-simple']
  }),
  createModule({
    id: 'math-g3-geometry',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'geometry',
    domainLabel: 'Geometrie',
    title: 'Droites, polygones et symetrie',
    summary: 'Reconnaitre les polygones, la symetrie et l angle droit.',
    goal: 'Observer les proprietes d une figure avant de repondre.',
    demo: 'Une demonstration montre les bons indices sur une figure.',
    guidedActivityIds: ['geometry-p3', 'shapes-symmetry-p2'],
    independentActivityIds: ['generated-logic-sequences'],
    challengeActivityId: 'geometry-p3',
    examActivityId: 'geometry-p3',
    suggestedReviewIds: ['shapes-symmetry-p2']
  }),
  createModule({
    id: 'math-g3-reasoning',
    subjectId: 'mathematics',
    gradeId: 'P3',
    domainId: 'reasoning',
    domainLabel: 'Raisonnement mathematique',
    title: 'Suites, logique et strategie',
    summary: 'Repeter une regle, choisir les informations utiles et raisonner.',
    goal: 'Developper une vraie strategie de resolution.',
    demo: 'On montre d abord comment chercher une regle ou un indice utile.',
    guidedActivityIds: ['generated-logic-sequences', 'mult-div-families'],
    independentActivityIds: ['generated-word-problems'],
    challengeActivityId: 'generated-logic-sequences',
    examActivityId: 'generated-word-problems',
    suggestedReviewIds: ['generated-comparison-p3']
  })
];
