// Each lesson is a sequence of slides.
// Slide types: 'info', 'question' (choice), 'activity' (prompt with text input or tap)
export const LESSONS_CATALOG = [
  {
    id: 'la-regle',
    title: 'La règle 📏',
    subtitle: 'Apprends à mesurer comme un grand !',
    subject: 'mathematics',
    grade: ['P2', 'P3'],
    lang: 'fr',
    color: '#f59e0b',
    shadow: '#b45309',
    bg: 'linear-gradient(145deg,#fde68a,#f59e0b)',
    emoji: '📏',
    duration: '5 min',
    slides: [
      {
        id: 's1',
        type: 'info',
        emoji: '📏',
        title: 'La règle, c\'est quoi ?',
        body: 'La règle, c\'est un long bâton plat.\nElle est **droite** et elle a des **chiffres** dessus.\nTu la vois dans ta trousse ! 😊',
        tip: 'Regarde ta règle. Tu vois des petits traits partout ?',
      },
      {
        id: 's2',
        type: 'info',
        emoji: '🧩',
        title: 'À quoi ça sert ?',
        body: 'La règle sert à **deux choses** :\n\n1️⃣ **Mesurer** — savoir combien une chose est longue.\n2️⃣ **Tracer** — dessiner une ligne bien droite. ✏️',
        tip: 'Comme un super outil magique !',
      },
      {
        id: 's3',
        type: 'info',
        emoji: '📐',
        title: 'Les centimètres (cm)',
        body: 'Sur ta règle, tu vois des **grands chiffres** : 1, 2, 3, 4…\n\nEntre deux grands chiffres, il y a **1 centimètre**.\n\nOn écrit **cm** pour centimètre.',
        tip: 'Exemple : ton pouce mesure environ 1 cm ! 👍',
      },
      {
        id: 's4',
        type: 'question',
        emoji: '🤔',
        title: 'Petite question !',
        question: 'Comment écrit-on centimètre en abrégé ?',
        choices: ['cm', 'mm', 'km', 'dm'],
        correct: 0,
        feedback: {
          correct: 'Bravo ! 🎉 cm = centimètre. Super !',
          wrong: 'Presque ! C\'est **cm** pour centimètre. mm c\'est pour millimètre — on va voir ça juste après !',
        },
      },
      {
        id: 's5',
        type: 'info',
        emoji: '🔍',
        title: 'Les millimètres (mm)',
        body: 'Entre les grands chiffres, tu vois des **tout petits traits**.\n\nChaque petit trait = **1 millimètre** (mm).\n\nLes millimètres sont **très petits** — plus petits qu\'un grain de riz ! 🍚',
        tip: 'Compte les petits traits entre 0 et 1 cm… tu en trouves 10 !',
      },
      {
        id: 's6',
        type: 'info',
        emoji: '⚡',
        title: '1 cm = 10 mm',
        body: 'C\'est la règle la plus importante !\n\n**1 centimètre = 10 millimètres**\n\nComme 1 euro = 10 pièces de 10 centimes. 🪙',
        tip: 'Essaie de compter les petits traits sur ta règle !',
        highlight: true,
      },
      {
        id: 's7',
        type: 'question',
        emoji: '🧠',
        title: 'À toi de jouer !',
        question: 'Combien y a-t-il de millimètres dans 1 cm ?',
        choices: ['5', '10', '100', '2'],
        correct: 1,
        feedback: {
          correct: 'Excellent ! 🌟 1 cm = 10 mm. Tu es fort(e) !',
          wrong: 'Ce n\'est pas ça… La bonne réponse c\'est **10** ! 1 cm = 10 mm. Retiens bien ça !',
        },
      },
      {
        id: 's8',
        type: 'info',
        emoji: '👆',
        title: 'Comment placer la règle ?',
        body: '1. Pose ta règle sur la feuille.\n2. Mets le **0** au début de ce que tu veux mesurer.\n3. La règle doit être **bien droite** — ne la bouge pas ! ✋',
        tip: 'Le 0 est tout au bout de la règle. C\'est le point de départ !',
      },
      {
        id: 's9',
        type: 'activity',
        emoji: '📏',
        title: 'Comment mesurer une ligne ?',
        body: '1. Place le **0** de ta règle au début de la ligne.\n2. Regarde où la ligne se termine.\n3. Lis le chiffre. C\'est la **longueur** ! 🎯',
        activityPrompt: 'Essaie chez toi : prends ta règle et mesure ton crayon. Combien fait-il ?',
        activityPlaceholder: 'Ex : mon crayon fait 15 cm',
      },
      {
        id: 's10',
        type: 'info',
        emoji: '✏️',
        title: 'Comment tracer une ligne droite ?',
        body: '1. Pose ta règle sur la feuille.\n2. Tiens-la bien avec une main.\n3. Pose ton crayon contre le bord de la règle.\n4. Glisse doucement le crayon le long de la règle. 🐛',
        tip: 'Ne lève pas ton crayon ! Trace en une seule fois.',
      },
      {
        id: 's11',
        type: 'question',
        emoji: '🏁',
        title: 'Dernière question !',
        question: 'Pour mesurer une ligne, où dois-tu mettre le 0 de ta règle ?',
        choices: [
          'Au milieu de la ligne',
          'Au début de la ligne',
          'À la fin de la ligne',
          'N\'importe où',
        ],
        correct: 1,
        feedback: {
          correct: 'Parfait ! 🎊 Le 0 se place toujours au **début** de la ligne. Très bien !',
          wrong: 'Presque ! Il faut mettre le **0 au début** de la ligne. C\'est comme ça qu\'on mesure correctement !',
        },
      },
      {
        id: 's12',
        type: 'info',
        emoji: '🏆',
        title: 'Bravo, tu es un champion !',
        body: 'Tu sais maintenant :\n✅ Ce qu\'est une règle\n✅ Mesurer en **cm** et **mm**\n✅ Que 1 cm = 10 mm\n✅ Comment placer la règle\n✅ Comment mesurer et tracer\n\n**Tu peux utiliser ta règle tout seul !** 🌟',
        tip: 'Pratique avec ton crayon, un livre, ta trousse…',
        isEnd: true,
      },
    ],
  },
];

export function getLessonById(id) {
  return LESSONS_CATALOG.find(l => l.id === id) || null;
}
