export const sciencesSubject = {
  id: 'sciences',
  label: 'Sciences',
  description: 'Le corps humain, les animaux, les plantes et les phenomenes naturels.',
  color: '#22c55e',
  accent: '#bbf7d0',
  grades: ['P2', 'P3', 'P4', 'P5', 'P6'],
  roadmap: [
    'Le corps humain et les 5 sens',
    'Les animaux et leur milieu',
    'Les plantes et la photosynthese',
    'La matiere, l\'eau et l\'air',
    'Les forces et l\'energie',
  ],
};

export const sciencesActivities = [
  // ── sci-body-p2 ────────────────────────────────────────────────────────────
  {
    id: 'sci-body-p2',
    slug: 'corps-humain-p2',
    title: 'Le corps humain P2',
    subject: 'sciences',
    subskill: 'body',
    gradeBand: ['P2'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Les parties du corps et les 5 sens.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Toucher, vue, odorat, ouie, gout.'],
    tags: ['sciences', 'body'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'b2-1', prompt: 'Combien de sens a l\'etre humain ?', choices: ['3', '4', '5', '6'], answer: '5', explanation: 'Les 5 sens : vue, ouie, odorat, gout, toucher.' },
          { id: 'b2-2', prompt: 'Quel organe nous permet de voir ?', choices: ['Le nez', 'Les oreilles', 'Les yeux', 'La bouche'], answer: 'Les yeux' },
          { id: 'b2-3', prompt: 'Quel organe nous permet d\'entendre ?', choices: ['Les yeux', 'Les oreilles', 'Le nez', 'La main'], answer: 'Les oreilles' },
          { id: 'b2-4', prompt: 'Avec quel organe sent-on les odeurs ?', choices: ['La bouche', 'Les yeux', 'Les oreilles', 'Le nez'], answer: 'Le nez' },
          { id: 'b2-5', prompt: 'Combien de doigts a une main humaine ?', choices: ['4', '5', '6', '8'], answer: '5' },
          { id: 'b2-6', prompt: 'Quelle partie du corps pompe le sang ?', choices: ['Le poumon', 'Le foie', 'Le coeur', 'L\'estomac'], answer: 'Le coeur' },
          { id: 'b2-7', prompt: 'Avec quoi respirons-nous ?', choices: ['Le coeur', 'Les poumons', 'Le foie', 'L\'estomac'], answer: 'Les poumons' },
          { id: 'b2-8', prompt: 'Quel sens utilise-t-on pour gouter ?', choices: ['La vue', 'Le toucher', 'Le gout', 'L\'ouie'], answer: 'Le gout' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'b2-9', prompt: 'Comment s\'appelle l\'os qui protege le cerveau ?', choices: ['Le sternum', 'Le crane', 'La cote', 'Le bassin'], answer: 'Le crane' },
          { id: 'b2-10', prompt: 'Combien de dents de lait a un enfant ?', choices: ['10', '16', '20', '28'], answer: '20' },
          { id: 'b2-11', prompt: 'Comment s\'appelle le liquide rouge dans nos veines ?', choices: ['L\'eau', 'Le lait', 'Le sang', 'La lymphe'], answer: 'Le sang' },
          { id: 'b2-12', prompt: 'Quel organe nous permet de toucher ?', choices: ['Le nez', 'Les yeux', 'La peau', 'Les oreilles'], answer: 'La peau' },
        ],
      },
    ],
  },

  // ── sci-animals-p2 ─────────────────────────────────────────────────────────
  {
    id: 'sci-animals-p2',
    slug: 'animaux-p2',
    title: 'Les animaux P2',
    subject: 'sciences',
    subskill: 'animals',
    gradeBand: ['P2'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Reconnaitre les animaux et leur nourriture.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Herbivore, carnivore ou omnivore ?'],
    tags: ['sciences', 'animals'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'a2-1', prompt: 'Comment appelle-t-on un animal qui mange uniquement des plantes ?', choices: ['Carnivore', 'Omnivore', 'Herbivore', 'Insectivore'], answer: 'Herbivore' },
          { id: 'a2-2', prompt: 'Comment appelle-t-on un animal qui mange uniquement de la viande ?', choices: ['Herbivore', 'Carnivore', 'Omnivore', 'Granivore'], answer: 'Carnivore' },
          { id: 'a2-3', prompt: 'Comment appelle-t-on un animal qui mange des plantes et de la viande ?', choices: ['Herbivore', 'Carnivore', 'Omnivore', 'Frugivore'], answer: 'Omnivore' },
          { id: 'a2-4', prompt: 'La vache est un animal...', choices: ['Carnivore', 'Omnivore', 'Herbivore', 'Insectivore'], answer: 'Herbivore' },
          { id: 'a2-5', prompt: 'Le lion est un animal...', choices: ['Herbivore', 'Carnivore', 'Omnivore', 'Frugivore'], answer: 'Carnivore' },
          { id: 'a2-6', prompt: 'L\'ours est un animal...', choices: ['Herbivore', 'Carnivore', 'Omnivore', 'Granivore'], answer: 'Omnivore' },
          { id: 'a2-7', prompt: 'Quel animal pond des oeufs ?', choices: ['Le chien', 'Le chat', 'La poule', 'La vache'], answer: 'La poule' },
          { id: 'a2-8', prompt: 'Quel animal vit dans l\'eau ?', choices: ['Le lion', 'Le poisson', 'Le cheval', 'L\'elephant'], answer: 'Le poisson' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'a2-9', prompt: 'Comment appelle-t-on les petits de la vache ?', choices: ['Poulain', 'Veau', 'Agneau', 'Chevreau'], answer: 'Veau' },
          { id: 'a2-10', prompt: 'Quel oiseau ne peut pas voler ?', choices: ['L\'aigle', 'Le moineau', 'Le pingouin', 'Le canard'], answer: 'Le pingouin' },
          { id: 'a2-11', prompt: 'Quel animal fabrique du miel ?', choices: ['Le papillon', 'La fourmi', 'L\'abeille', 'La mouche'], answer: 'L\'abeille' },
          { id: 'a2-12', prompt: 'Le lapin est un animal...', choices: ['Carnivore', 'Omnivore', 'Herbivore', 'Insectivore'], answer: 'Herbivore' },
        ],
      },
    ],
  },

  // ── sci-plants-p3 ──────────────────────────────────────────────────────────
  {
    id: 'sci-plants-p3',
    slug: 'plantes-p3',
    title: 'Les plantes P3',
    subject: 'sciences',
    subskill: 'plants',
    gradeBand: ['P3'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Les parties d\'une plante et la photosynthese.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Racine, tige, feuille, fleur.'],
    tags: ['sciences', 'plants'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'p3-1', prompt: 'Quelle partie de la plante absorbe l\'eau du sol ?', choices: ['La tige', 'Les feuilles', 'Les racines', 'La fleur'], answer: 'Les racines' },
          { id: 'p3-2', prompt: 'Quelle partie de la plante transporte l\'eau vers les feuilles ?', choices: ['La racine', 'La tige', 'La fleur', 'Le fruit'], answer: 'La tige' },
          { id: 'p3-3', prompt: 'Ou se passe la photosynthese ?', choices: ['Dans les racines', 'Dans la tige', 'Dans les feuilles', 'Dans la fleur'], answer: 'Dans les feuilles' },
          { id: 'p3-4', prompt: 'De quoi la plante a-t-elle besoin pour faire la photosynthese ?', choices: ['De la pluie et du vent', 'Du soleil, de l\'eau et de CO2', 'De la terre et du sel', 'De l\'oxygene et de la lumiere'], answer: 'Du soleil, de l\'eau et de CO2' },
          { id: 'p3-5', prompt: 'Quel gaz la plante produit-elle grace a la photosynthese ?', choices: ['Du CO2', 'De l\'azote', 'De l\'oxygene', 'De la vapeur d\'eau'], answer: 'De l\'oxygene' },
          { id: 'p3-6', prompt: 'Comment s\'appelle la partie coloree de la fleur qui attire les insectes ?', choices: ['Le pistil', 'Le petale', 'Le sepale', 'L\'etamine'], answer: 'Le petale' },
          { id: 'p3-7', prompt: 'Comment s\'appelle le processus par lequel les plantes fabriquent leur nourriture ?', choices: ['La respiration', 'La photosynthese', 'La germination', 'La floraison'], answer: 'La photosynthese' },
          { id: 'p3-8', prompt: 'Que devient une graine quand on la plante et qu\'on l\'arrose ?', choices: ['Elle pourrit', 'Elle germe', 'Elle fleurit', 'Elle fruit'], answer: 'Elle germe' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'p3-9', prompt: 'Quelle couleur donne aux feuilles leur couleur verte ?', choices: ['La carotene', 'La chlorophylle', 'La melanine', 'La xanthophylle'], answer: 'La chlorophylle' },
          { id: 'p3-10', prompt: 'Comment appelle-t-on le transport du pollen d\'une fleur a une autre ?', choices: ['La germination', 'La photosynthese', 'La pollinisation', 'La floraison'], answer: 'La pollinisation' },
          { id: 'p3-11', prompt: 'Quelle plante produit des tomates ?', choices: ['Le rosier', 'Le pommier', 'Le tomatier', 'Le poirier'], answer: 'Le tomatier' },
          { id: 'p3-12', prompt: 'Ou les graines se forment-elles ?', choices: ['Dans les racines', 'Dans la tige', 'Dans les feuilles', 'Dans le fruit'], answer: 'Dans le fruit' },
        ],
      },
    ],
  },

  // ── sci-water-p3 ───────────────────────────────────────────────────────────
  {
    id: 'sci-water-p3',
    slug: 'eau-p3',
    title: 'L\'eau P3',
    subject: 'sciences',
    subskill: 'water',
    gradeBand: ['P3'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Le cycle de l\'eau et ses etats.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Solide, liquide, gazeux.'],
    tags: ['sciences', 'water'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'w3-1', prompt: 'Combien d\'etats possede l\'eau ?', choices: ['1', '2', '3', '4'], answer: '3' },
          { id: 'w3-2', prompt: 'Comment s\'appelle l\'etat solide de l\'eau ?', choices: ['La vapeur', 'Le brouillard', 'La glace', 'La buee'], answer: 'La glace' },
          { id: 'w3-3', prompt: 'A quelle temperature l\'eau se transforme-t-elle en glace ?', choices: ['10 degres', '0 degre', '-10 degres', '100 degres'], answer: '0 degre' },
          { id: 'w3-4', prompt: 'A quelle temperature l\'eau bout-elle ?', choices: ['50 degres', '80 degres', '100 degres', '120 degres'], answer: '100 degres' },
          { id: 'w3-5', prompt: 'Comment s\'appelle le passage de l\'etat liquide a l\'etat gazeux ?', choices: ['La condensation', 'L\'evaporation', 'La solidification', 'La fusion'], answer: 'L\'evaporation' },
          { id: 'w3-6', prompt: 'Comment s\'appelle le passage de l\'etat solide a l\'etat liquide ?', choices: ['La congelation', 'L\'evaporation', 'La fusion', 'La condensation'], answer: 'La fusion' },
          { id: 'w3-7', prompt: 'D\'ou vient l\'eau de pluie ?', choices: ['Des rivieres', 'Des nuages', 'De la mer uniquement', 'Du robinet'], answer: 'Des nuages' },
          { id: 'w3-8', prompt: 'Comment l\'eau des mers monte-t-elle dans les nuages ?', choices: ['Par le vent', 'Par evaporation', 'Par filtration', 'Par conduction'], answer: 'Par evaporation' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'w3-9', prompt: 'Comment appelle-t-on le cycle complet de l\'eau dans la nature ?', choices: ['Le cycle de vie', 'Le cycle de l\'eau', 'Le cycle des saisons', 'Le cycle lunaire'], answer: 'Le cycle de l\'eau' },
          { id: 'w3-10', prompt: 'Quand la vapeur d\'eau refroidit, elle forme...', choices: ['De la glace', 'Des nuages', 'De la pluie', 'De la neige'], answer: 'Des nuages' },
          { id: 'w3-11', prompt: 'Comment appelle-t-on l\'eau qui tombe sous forme solide ?', choices: ['La pluie', 'La bruine', 'La neige', 'La rosee'], answer: 'La neige' },
          { id: 'w3-12', prompt: 'L\'eau est indispensable pour...', choices: ['Les roches', 'La vie des etres vivants', 'L\'air sec', 'Le feu'], answer: 'La vie des etres vivants' },
        ],
      },
    ],
  },

  // ── sci-matter-p4 ──────────────────────────────────────────────────────────
  {
    id: 'sci-matter-p4',
    slug: 'matiere-p4',
    title: 'La matiere P4',
    subject: 'sciences',
    subskill: 'matter',
    gradeBand: ['P4'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Les etats de la matiere et les changements physiques.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Fusion, evaporation, solidification.'],
    tags: ['sciences', 'matter'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'm4-1', prompt: 'Combien d\'etats de la matiere connait-on principalement ?', choices: ['2', '3', '4', '5'], answer: '3' },
          { id: 'm4-2', prompt: 'Dans quel etat le bois se trouve-t-il ?', choices: ['Liquide', 'Gazeux', 'Solide', 'Plasma'], answer: 'Solide' },
          { id: 'm4-3', prompt: 'Dans quel etat le jus d\'orange se trouve-t-il ?', choices: ['Solide', 'Liquide', 'Gazeux', 'Plasma'], answer: 'Liquide' },
          { id: 'm4-4', prompt: 'Dans quel etat la vapeur d\'eau se trouve-t-elle ?', choices: ['Solide', 'Liquide', 'Gazeux', 'Plasma'], answer: 'Gazeux' },
          { id: 'm4-5', prompt: 'Comment appelle-t-on le passage du solide au liquide ?', choices: ['La solidification', 'La congelation', 'La fusion', 'L\'evaporation'], answer: 'La fusion' },
          { id: 'm4-6', prompt: 'Comment appelle-t-on le passage du liquide au solide ?', choices: ['La fusion', 'La solidification', 'L\'evaporation', 'La condensation'], answer: 'La solidification' },
          { id: 'm4-7', prompt: 'Un changement d\'etat de la matiere est-il un changement chimique ?', choices: ['Oui, toujours', 'Non, c\'est un changement physique', 'Parfois', 'On ne sait pas'], answer: 'Non, c\'est un changement physique' },
          { id: 'm4-8', prompt: 'Le fer peut-il passer a l\'etat liquide ?', choices: ['Non, jamais', 'Oui, a tres haute temperature', 'Seulement dans l\'eau', 'Oui, a 0 degre'], answer: 'Oui, a tres haute temperature' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'm4-9', prompt: 'La cire d\'une bougie qui fond est un exemple de...', choices: ['Solidification', 'Evaporation', 'Fusion', 'Condensation'], answer: 'Fusion' },
          { id: 'm4-10', prompt: 'Quand on refroidit un gaz, il peut devenir...', choices: ['Plus gazeux', 'Liquide', 'Solide', 'Invisible'], answer: 'Liquide' },
          { id: 'm4-11', prompt: 'La matiere est tout ce qui a...', choices: ['Une couleur', 'Une masse et occupe un volume', 'Un gout', 'Une odeur'], answer: 'Une masse et occupe un volume' },
          { id: 'm4-12', prompt: 'Quel changement d\'etat se produit quand l\'eau bout ?', choices: ['Fusion', 'Solidification', 'Evaporation', 'Condensation'], answer: 'Evaporation' },
        ],
      },
    ],
  },

  // ── sci-ecosystems-p4 ─────────────────────────────────────────────────────
  {
    id: 'sci-ecosystems-p4',
    slug: 'ecosystemes-p4',
    title: 'Les ecosystemes P4',
    subject: 'sciences',
    subskill: 'ecosystems',
    gradeBand: ['P4'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Chaines alimentaires et milieux de vie.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Producteur -> consommateur -> decomposeur.'],
    tags: ['sciences', 'ecosystems'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'e4-1', prompt: 'Comment s\'appelle l\'ensemble des etres vivants et leur milieu naturel ?', choices: ['Un habitat', 'Un ecosysteme', 'Une espece', 'Une chaine'], answer: 'Un ecosysteme' },
          { id: 'e4-2', prompt: 'Dans une chaine alimentaire, qui est le producteur ?', choices: ['Un animal', 'Un champignon', 'Une plante', 'Un decomposeur'], answer: 'Une plante' },
          { id: 'e4-3', prompt: 'Dans la chaine herbe -> lapin -> renard, le renard est...', choices: ['Un producteur', 'Un consommateur de 1er ordre', 'Un consommateur de 2eme ordre', 'Un decomposeur'], answer: 'Un consommateur de 2eme ordre' },
          { id: 'e4-4', prompt: 'Que font les decomposeurs dans un ecosysteme ?', choices: ['Ils produisent de l\'oxygene', 'Ils chassent les proies', 'Ils degradent la matiere organique morte', 'Ils photosynthetisent'], answer: 'Ils degradent la matiere organique morte' },
          { id: 'e4-5', prompt: 'Comment s\'appelle une suite d\'etres vivants dont chacun mange le precedent ?', choices: ['Une chaine alimentaire', 'Un reseau trophique', 'Un habitat', 'Un ecosysteme'], answer: 'Une chaine alimentaire' },
          { id: 'e4-6', prompt: 'Le ver de terre est un exemple de...', choices: ['Producteur', 'Consommateur', 'Decomposeur', 'Predateur'], answer: 'Decomposeur' },
          { id: 'e4-7', prompt: 'Comment appelle-t-on un animal qui mange d\'autres animaux ?', choices: ['Un herbivore', 'Un producteur', 'Un predateur', 'Un parasite'], answer: 'Un predateur' },
          { id: 'e4-8', prompt: 'La foret, la mer et le desert sont des exemples de...', choices: ['Chaines alimentaires', 'Ecosystemes', 'Especes', 'Habitats isoles'], answer: 'Ecosystemes' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'e4-9', prompt: 'Que se passe-t-il si une espece disparait dans une chaine alimentaire ?', choices: ['Rien ne change', 'L\'equilibre de la chaine est perturbe', 'Les autres especes doublent', 'La plante disparait aussi'], answer: 'L\'equilibre de la chaine est perturbe' },
          { id: 'e4-10', prompt: 'Un reseau trophique est...', choices: ['Une seule chaine alimentaire', 'Plusieurs chaines alimentaires reliees', 'Une liste d\'especes', 'Un milieu naturel'], answer: 'Plusieurs chaines alimentaires reliees' },
          { id: 'e4-11', prompt: 'Le soleil est la source d\'energie de depart pour...', choices: ['Les animaux uniquement', 'Les decomposeurs', 'Toutes les chaines alimentaires', 'Les carnivores'], answer: 'Toutes les chaines alimentaires' },
          { id: 'e4-12', prompt: 'Comment appelle-t-on l\'endroit ou vit un animal ?', choices: ['Son espece', 'Son habitat', 'Sa proie', 'Sa niche'], answer: 'Son habitat' },
        ],
      },
    ],
  },

  // ── sci-forces-p5 ─────────────────────────────────────────────────────────
  {
    id: 'sci-forces-p5',
    slug: 'forces-p5',
    title: 'Forces et mouvements P5',
    subject: 'sciences',
    subskill: 'forces',
    gradeBand: ['P5'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Gravite, frottement et forces simples.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['La gravite attire les objets vers le bas.'],
    tags: ['sciences', 'forces'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'f5-1', prompt: 'Quelle force attire les objets vers le sol ?', choices: ['La force magnetique', 'La gravite', 'Le frottement', 'L\'electricite'], answer: 'La gravite' },
          { id: 'f5-2', prompt: 'Que mesure-t-on avec un dynamometre ?', choices: ['La masse', 'La temperature', 'Une force', 'Le volume'], answer: 'Une force' },
          { id: 'f5-3', prompt: 'Quelle est l\'unite de mesure d\'une force ?', choices: ['Le kilogramme', 'Le metre', 'Le newton', 'Le joule'], answer: 'Le newton' },
          { id: 'f5-4', prompt: 'Comment appelle-t-on la force qui s\'oppose au mouvement d\'un objet ?', choices: ['La gravite', 'Le frottement', 'La poussee', 'La traction'], answer: 'Le frottement' },
          { id: 'f5-5', prompt: 'Pourquoi une bille lancee sur de l\'herbe s\'arrete-t-elle ?', choices: ['A cause de la gravite', 'A cause du frottement', 'A cause du vent', 'A cause de l\'air'], answer: 'A cause du frottement' },
          { id: 'f5-6', prompt: 'Un objet est en equilibre quand...', choices: ['Il est lourd', 'Les forces qui s\'exercent sur lui se compensent', 'Il est immobile depuis longtemps', 'Il est sur une surface plane'], answer: 'Les forces qui s\'exercent sur lui se compensent' },
          { id: 'f5-7', prompt: 'La Lune tourne autour de la Terre grace a...', choices: ['Le frottement', 'La gravite terrestre', 'Le soleil', 'L\'atmosphere'], answer: 'La gravite terrestre' },
          { id: 'f5-8', prompt: 'Sur la Lune, votre poids serait...', choices: ['Le meme que sur Terre', 'Plus lourd', 'Plus leger', 'Nul'], answer: 'Plus leger' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'f5-9', prompt: 'Quelle est la difference entre la masse et le poids ?', choices: ['Ce sont la meme chose', 'La masse est une quantite de matiere, le poids est une force', 'Le poids se mesure en kg', 'La masse depend de la gravite'], answer: 'La masse est une quantite de matiere, le poids est une force' },
          { id: 'f5-10', prompt: 'Une surface lisse ou rugueuse cree-t-elle plus de frottement ?', choices: ['Lisse', 'Rugueuse', 'Les deux pareille', 'Aucune des deux'], answer: 'Rugueuse' },
          { id: 'f5-11', prompt: 'Que se passe-t-il quand on lache un objet dans l\'air ?', choices: ['Il reste en l\'air', 'Il monte', 'Il tombe a cause de la gravite', 'Il flotte'], answer: 'Il tombe a cause de la gravite' },
          { id: 'f5-12', prompt: 'Les freins d\'un velo utilisent quel principe pour arreter la roue ?', choices: ['La gravite', 'Le magnetisme', 'Le frottement', 'L\'electricite'], answer: 'Le frottement' },
        ],
      },
    ],
  },

  // ── sci-human-body-p5 ─────────────────────────────────────────────────────
  {
    id: 'sci-human-body-p5',
    slug: 'systemes-corps-p5',
    title: 'Systemes du corps P5',
    subject: 'sciences',
    subskill: 'body-systems',
    gradeBand: ['P5'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Appareil digestif, circulatoire et respiratoire.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Le coeur pompe le sang.'],
    tags: ['sciences', 'body-systems'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'hb5-1', prompt: 'Quel organe est le moteur du systeme circulatoire ?', choices: ['Le poumon', 'Le foie', 'Le coeur', 'Le rein'], answer: 'Le coeur' },
          { id: 'hb5-2', prompt: 'Quel organe purifie le sang en filtrant les dechets ?', choices: ['Le coeur', 'Le foie', 'Le rein', 'L\'estomac'], answer: 'Le rein' },
          { id: 'hb5-3', prompt: 'Ou la digestion commence-t-elle ?', choices: ['Dans l\'estomac', 'Dans la bouche', 'Dans l\'intestin', 'Dans le foie'], answer: 'Dans la bouche' },
          { id: 'hb5-4', prompt: 'Quel organe absorbe les nutriments dans le sang ?', choices: ['L\'estomac', 'Le foie', 'L\'intestin grele', 'Le colon'], answer: 'L\'intestin grele' },
          { id: 'hb5-5', prompt: 'Quel gaz les poumons eliminent-ils a chaque expiration ?', choices: ['De l\'oxygene', 'De l\'azote', 'Du CO2', 'De la vapeur d\'eau'], answer: 'Du CO2' },
          { id: 'hb5-6', prompt: 'Quel gaz les poumons absorbent-ils a chaque inspiration ?', choices: ['Du CO2', 'De l\'oxygene', 'De l\'azote', 'De l\'hydrogene'], answer: 'De l\'oxygene' },
          { id: 'hb5-7', prompt: 'Comment s\'appelle le liquide qui transporte l\'oxygene dans le corps ?', choices: ['La lymphe', 'L\'urine', 'Le sang', 'La bile'], answer: 'Le sang' },
          { id: 'hb5-8', prompt: 'Quel organe produit la bile qui aide a digerer les graisses ?', choices: ['L\'estomac', 'Le rein', 'Le foie', 'L\'intestin'], answer: 'Le foie' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'hb5-9', prompt: 'Combien de poumons a un etre humain ?', choices: ['1', '2', '3', '4'], answer: '2' },
          { id: 'hb5-10', prompt: 'Comment appelle-t-on les petits vaisseaux qui portent le sang dans tout le corps ?', choices: ['Les veines', 'Les arteres', 'Les capillaires', 'Les bronches'], answer: 'Les capillaires' },
          { id: 'hb5-11', prompt: 'Combien de temps met un repas a etre entierement digere ?', choices: ['1 heure', '6 a 8 heures', '24 heures', '3 jours'], answer: '24 heures' },
          { id: 'hb5-12', prompt: 'Comment s\'appelle le mouvement du diaphragme qui permet de respirer ?', choices: ['La circulation', 'La digestion', 'La contraction et la relaxation', 'La filtration'], answer: 'La contraction et la relaxation' },
        ],
      },
    ],
  },

  // ── sci-energy-p6 ─────────────────────────────────────────────────────────
  {
    id: 'sci-energy-p6',
    slug: 'energie-p6',
    title: 'L\'energie P6',
    subject: 'sciences',
    subskill: 'energy',
    gradeBand: ['P6'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Formes d\'energie: electrique, thermique, lumineuse.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['L\'energie peut se transformer mais pas disparaitre.'],
    tags: ['sciences', 'energy'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'en6-1', prompt: 'Qu\'est-ce que l\'energie ?', choices: ['Une matiere', 'La capacite de produire un travail ou un effet', 'Une force uniquement', 'Un mouvement'], answer: 'La capacite de produire un travail ou un effet' },
          { id: 'en6-2', prompt: 'Quelle forme d\'energie utilise une lampe electrique ?', choices: ['Energie thermique', 'Energie cinetique', 'Energie electrique', 'Energie chimique'], answer: 'Energie electrique' },
          { id: 'en6-3', prompt: 'Quelle forme d\'energie produit la chaleur ?', choices: ['Energie lumineuse', 'Energie thermique', 'Energie cinetique', 'Energie nucleaire'], answer: 'Energie thermique' },
          { id: 'en6-4', prompt: 'L\'energie d\'un objet en mouvement est une energie...', choices: ['Potentielle', 'Thermique', 'Cinetique', 'Chimique'], answer: 'Cinetique' },
          { id: 'en6-5', prompt: 'L\'energie solaire est une source d\'energie...', choices: ['Fossile', 'Nucleaire', 'Renouvelable', 'Chimique'], answer: 'Renouvelable' },
          { id: 'en6-6', prompt: 'Le petrole est une source d\'energie...', choices: ['Renouvelable', 'Fossile', 'Solaire', 'Hydraulique'], answer: 'Fossile' },
          { id: 'en6-7', prompt: 'Une centrale eolienne transforme quelle forme d\'energie en electricite ?', choices: ['L\'energie solaire', 'L\'energie du vent', 'L\'energie de l\'eau', 'L\'energie thermique'], answer: 'L\'energie du vent' },
          { id: 'en6-8', prompt: 'L\'energie peut-elle disparaitre ?', choices: ['Oui, toujours', 'Non, elle se transforme mais ne disparait pas', 'Oui, quand on l\'utilise', 'Seulement dans l\'espace'], answer: 'Non, elle se transforme mais ne disparait pas' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'en6-9', prompt: 'Quelle source d\'energie pollue le moins ?', choices: ['Le charbon', 'Le petrole', 'L\'energie solaire', 'Le gaz naturel'], answer: 'L\'energie solaire' },
          { id: 'en6-10', prompt: 'Quand tu manges, ton corps transforme l\'energie chimique des aliments en...', choices: ['Energie nucleaire', 'Energie cinetique et thermique', 'Energie solaire', 'Energie electrique'], answer: 'Energie cinetique et thermique' },
          { id: 'en6-11', prompt: 'Comment appelle-t-on les sources d\'energie qui se regenerent naturellement ?', choices: ['Fossiles', 'Nucleaires', 'Renouvelables', 'Chimiques'], answer: 'Renouvelables' },
          { id: 'en6-12', prompt: 'Une pile transforme l\'energie chimique en...', choices: ['Energie thermique', 'Energie electrique', 'Energie lumineuse', 'Energie cinetique'], answer: 'Energie electrique' },
        ],
      },
    ],
  },

  // ── sci-environment-p6 ────────────────────────────────────────────────────
  {
    id: 'sci-environment-p6',
    slug: 'environnement-p6',
    title: 'Environnement et ecologie P6',
    subject: 'sciences',
    subskill: 'environment',
    gradeBand: ['P6'],
    language: 'fr',
    difficulty: 'progressive',
    estimatedDurationMin: 10,
    instructions: 'Developpement durable, pollution et solutions.',
    correctionType: 'multiple-choice',
    engineType: 'multiple-choice',
    hints: ['Reduire, reutiliser, recycler.'],
    tags: ['sciences', 'environment'],
    sections: [
      {
        id: 'practice',
        title: 'Decouverte',
        kind: 'practice',
        lessons: [
          { id: 'ev6-1', prompt: 'Que signifie "developper durablement" ?', choices: ['Construire beaucoup de routes', 'Repondre aux besoins presents sans compromettre les generations futures', 'Utiliser toutes les ressources disponibles', 'Augmenter la production industrielle'], answer: 'Repondre aux besoins presents sans compromettre les generations futures' },
          { id: 'ev6-2', prompt: 'Quelle est la "regle des 3 R" ?', choices: ['Reparer, Rincer, Rouler', 'Reduire, Reutiliser, Recycler', 'Refroidir, Ranger, Revendre', 'Ranger, Reculer, Remplir'], answer: 'Reduire, Reutiliser, Recycler' },
          { id: 'ev6-3', prompt: 'Que produit la combustion des energies fossiles qui rechauffent la planete ?', choices: ['De l\'oxygene', 'Du CO2 et autres gaz a effet de serre', 'De l\'azote', 'De la vapeur pure'], answer: 'Du CO2 et autres gaz a effet de serre' },
          { id: 'ev6-4', prompt: 'Comment appelle-t-on le rechauffement progressif de la planete ?', choices: ['La pollution', 'Le rechauffement climatique', 'La deforestation', 'L\'effet de serre naturel'], answer: 'Le rechauffement climatique' },
          { id: 'ev6-5', prompt: 'Que peut-on faire pour reduire ses dechets plastiques ?', choices: ['Acheter plus d\'emballages', 'Utiliser des sacs reutilisables', 'Jeter dans la nature', 'Bruler les plastiques'], answer: 'Utiliser des sacs reutilisables' },
          { id: 'ev6-6', prompt: 'La deforestation contribue au rechauffement climatique car...', choices: ['Les arbres produisent du CO2', 'Les arbres absorbent moins de CO2', 'Les arbres chauffent l\'atmosphere', 'Les arbres polluent l\'eau'], answer: 'Les arbres absorbent moins de CO2' },
          { id: 'ev6-7', prompt: 'Quelle action aide a preserver l\'eau douce ?', choices: ['Laisser couler l\'eau inutilement', 'Fermer le robinet quand on se brosse les dents', 'Arroser les jardins a midi', 'Prendre de longs bains chaque jour'], answer: 'Fermer le robinet quand on se brosse les dents' },
          { id: 'ev6-8', prompt: 'Comment appelle-t-on la destruction des forets tropicales ?', choices: ['La reforestation', 'La deforestation', 'La carbonisation', 'L\'urbanisation'], answer: 'La deforestation' },
        ],
      },
      {
        id: 'exam',
        title: 'Mini quiz',
        kind: 'exam',
        lessons: [
          { id: 'ev6-9', prompt: 'Quel gaz est responsable de la couche d\'ozone qui nous protege des UV ?', choices: ['Le CO2', 'L\'azote', 'L\'ozone (O3)', 'L\'oxygene (O2)'], answer: 'L\'ozone (O3)' },
          { id: 'ev6-10', prompt: 'Pourquoi trier ses dechets est-il important ?', choices: ['Pour faire plaisir aux voisins', 'Pour permettre le recyclage et reduire les dechets', 'Parce que c\'est obligatoire partout', 'Pour gagner de l\'argent'], answer: 'Pour permettre le recyclage et reduire les dechets' },
          { id: 'ev6-11', prompt: 'Quelle energie renouvelable utilise la force de l\'eau ?', choices: ['L\'energie eolienne', 'L\'energie solaire', 'L\'energie hydraulique', 'L\'energie nucleaire'], answer: 'L\'energie hydraulique' },
          { id: 'ev6-12', prompt: 'Comment appelle-t-on la biodiversite ?', choices: ['La diversite des paysages', 'La variete des especes vivantes sur Terre', 'La diversite des energies', 'La variete des mineraux'], answer: 'La variete des especes vivantes sur Terre' },
        ],
      },
    ],
  },
];
