import { createModule } from '../../curriculum/moduleTemplate.js';

export const frenchGrade2Modules = [
  createModule({
    id: 'french-g2-vocabulary',
    subjectId: 'french',
    gradeId: 'P2',
    domainId: 'vocabulary',
    domainLabel: 'Vocabulaire',
    title: 'Mot, image et categorie',
    summary: 'Associer des mots frequents, des images et des categories simples.',
    goal: 'Installer des reperes visuels et lexicaux stables.',
    demo: 'Une demonstration montre comment relier image, mot et categorie.',
    guidedActivityIds: ['associe-image-mot', 'generated-french-vocabulary-p2'],
    independentActivityIds: ['generated-french-vocabulary'],
    challengeActivityId: 'intrus-lecture',
    examActivityId: 'associe-image-mot',
    suggestedReviewIds: ['associe-image-mot'],
    missionTitle: 'Mission vocabulaire P2',
    missionSummary: 'Nommer, associer et classer des mots tres frequents.'
  }),
  createModule({
    id: 'french-g2-sentences',
    subjectId: 'french',
    gradeId: 'P2',
    domainId: 'sentences',
    domainLabel: 'Phrases simples',
    title: 'Construire et completer une phrase',
    summary: 'Lire des phrases tres courtes et choisir le mot qui convient.',
    goal: 'Comprendre d abord, completer ensuite.',
    demo: 'Un modele montre comment lire la phrase entiere avant de choisir.',
    guidedActivityIds: ['phrase-a-trous', 'generated-french-sentences-p2'],
    independentActivityIds: ['generated-french-sentences', 'generated-french-conjugation-p2'],
    challengeActivityId: 'phrase-a-trous',
    examActivityId: 'generated-french-sentences-p2',
    suggestedReviewIds: ['generated-french-vocabulary-p2', 'possessives'],
    missionTitle: 'Mission phrases P2',
    missionSummary: 'Choisir le bon mot et garder une phrase simple correcte.'
  }),
  createModule({
    id: 'french-g2-grammar-verbs',
    subjectId: 'french',
    gradeId: 'P2',
    domainId: 'grammar-verbs',
    domainLabel: 'Grammaire douce',
    title: 'Possessifs et verbes utiles',
    summary: 'Premiers verbes frequents et determinants possessifs dans des phrases tres simples.',
    goal: 'Rendre visibles les activites de grammaire et de conjugaison deja jouables.',
    demo: 'Une demonstration montre comment regarder le sujet ou le nom avant de choisir.',
    guidedActivityIds: ['generated-french-conjugation-p2', 'possessives'],
    independentActivityIds: ['generated-french-sentences-p2'],
    challengeActivityId: 'generated-french-conjugation-p2',
    examActivityId: 'possessives',
    suggestedReviewIds: ['phrase-a-trous'],
    missionTitle: 'Mission verbes et possessifs P2',
    missionSummary: 'Travailler des verbes tres utiles et les possessifs sans les laisser caches.'
  }),
  createModule({
    id: 'french-g2-reading',
    subjectId: 'french',
    gradeId: 'P2',
    domainId: 'reading',
    domainLabel: 'Lecture',
    title: 'Lecture guidee et comprehension de base',
    summary: 'Lire des mots puis de tres petits textes avec questions directes.',
    goal: 'Faire grandir la lecture sans surcharger la comprehension.',
    demo: 'Une demonstration montre comment retrouver la phrase qui repond a la question.',
    guidedActivityIds: ['generated-french-reading-p2', 'associe-image-mot'],
    independentActivityIds: ['intrus-lecture'],
    challengeActivityId: 'generated-french-reading',
    examActivityId: 'generated-french-reading-p2',
    suggestedReviewIds: ['phrase-a-trous'],
    missionTitle: 'Mission lecture P2',
    missionSummary: 'Lire des mots et des phrases courtes pour comprendre une idee simple.'
  }),
  createModule({
    id: 'french-g2-stories',
    subjectId: 'french',
    gradeId: 'P2',
    domainId: 'stories',
    domainLabel: 'Contes et recits',
    title: 'Petites histoires a lire',
    summary: 'Entrer dans de petits recits avec personnages, lieux et actions faciles a suivre.',
    goal: 'Lire une histoire courte et retrouver une information claire.',
    demo: 'Une demonstration montre comment reperer qui fait quoi dans un petit recit.',
    guidedActivityIds: ['generated-french-stories-p2', 'generated-french-reading-p2'],
    independentActivityIds: ['generated-french-reading'],
    challengeActivityId: 'generated-french-stories-p2',
    examActivityId: 'generated-french-reading-p2',
    suggestedReviewIds: ['generated-french-sentences-p2'],
    missionTitle: 'Mission recits P2',
    missionSummary: 'Lire une petite histoire, suivre les personnages et comprendre l idee principale.'
  })
];
