import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade4Modules = [
  createModule({
    id: 'math-g4-addition-subtraction',
    subjectId: 'mathematics',
    gradeId: 'P4',
    domainId: 'operations',
    domainLabel: 'Operations',
    title: 'Additions et soustractions avancees',
    summary: 'Additions et soustractions a 3 chiffres avec retenues et emprunts.',
    goal: 'Maitriser les operations posees sur grands nombres.',
    demo: 'Demo des techniques de retenue et emprunt.',
    guidedActivityIds: ['generated-addition-p4'],
    independentActivityIds: ['generated-subtraction-p4'],
    challengeActivityId: 'generated-addition-p4',
    examActivityId: 'generated-subtraction-p4',
    missionTitle: 'Mission Calcul Avance P4',
    levelTitles: {
      'generated-addition-p4': 'Additions avec retenue',
      'generated-subtraction-p4': 'Soustractions avec emprunt',
    },
  }),
  createModule({
    id: 'math-g4-tables-advanced',
    subjectId: 'mathematics',
    gradeId: 'P4',
    domainId: 'multiplication-division',
    domainLabel: 'Tables 6 a 10',
    title: 'Maitriser les grandes tables',
    summary: 'Consolider les tables de 6 a 10 et la multiplication posee.',
    goal: 'Acquerir une fluence parfaite en calcul mental avance.',
    demo: 'Demo sur les tables superieures.',
    guidedActivityIds: ['generated-multiplication-p4'],
    independentActivityIds: ['multiplication-table-9', 'division-table-9'],
    challengeActivityId: 'multiplication-table-10',
    examActivityId: 'generated-division-p4',
    missionTitle: 'Mission Tables Avancees P4',
    levelTitles: {
      'generated-multiplication-p4': 'Multiplication posee',
      'multiplication-table-9': 'Table de 9',
      'division-table-9': 'Division par 9',
      'multiplication-table-10': 'Table de 10',
      'generated-division-p4': 'Divisions',
    },
  }),
  createModule({
    id: 'math-g4-divisions-fractions',
    subjectId: 'mathematics',
    gradeId: 'P4',
    domainId: 'fractions',
    domainLabel: 'Fractions',
    title: 'Decouvrir les fractions',
    summary: 'Lien entre le partage et la representation fractionnaire.',
    goal: 'Visualiser une fraction comme une part d\'un tout.',
    demo: 'Demo avec des parts de pizza ou de gateau.',
    guidedActivityIds: ['generated-fractions-p4'],
    independentActivityIds: ['generated-division-p4'],
    challengeActivityId: 'generated-fractions-p4',
    examActivityId: 'generated-fractions-p4',
    missionTitle: 'Mission Fractions P4',
    levelTitles: {
      'generated-fractions-p4': 'Premieres fractions',
      'generated-division-p4': 'Division et partage',
    },
  }),
  createModule({
    id: 'math-g4-geometry-time',
    subjectId: 'mathematics',
    gradeId: 'P4',
    domainId: 'geometry-time',
    domainLabel: 'Geometrie et Mesures',
    title: 'Figures et durees',
    summary: 'Reconnaitre les figures geometriques et calculer des durees.',
    goal: 'Calculer des perimetres et lire des horaires.',
    demo: 'Demo sur les formes et les horloges.',
    guidedActivityIds: ['generated-geometry-p4'],
    independentActivityIds: ['generated-time-p4'],
    challengeActivityId: 'generated-geometry-p4',
    examActivityId: 'generated-time-p4',
    missionTitle: 'Mission Geometrie P4',
    levelTitles: {
      'generated-geometry-p4': 'Figures et perimetre',
      'generated-time-p4': 'Durees et horaires',
    },
  }),
];
