// ─────────────────────────────────────────────────────────────────────────────
// Exam content registry — lazy-loading split edition.
//
// The manifest (manifest.json) is a small, eagerly-bundled index that contains
// category metadata and per-exam stubs (id, title, emoji, order, levelKeys,
// passPercent). It is generated by `scripts/build-manifest.mjs` and committed.
//
// Full exam JSON files (with questions) are loaded on demand via dynamic import
// so they are NOT included in the initial bundle — each category/exam is a
// separate chunk produced by Vite at build time.
//
// Public API
// ----------
//   getCategories()                 — sync, returns category list with exam stubs
//   getExamsByCategory(categoryId)  — async Promise<examStub[]>  (stubs only)
//   getExam(examId)                 — async Promise<fullExam>
//   getExamLevel(examId, levelKey)  — async Promise<{exam, level, levelKey}|null>
//
// The legacy sync exports ALL_EXAMS and getExamById are removed; use the async
// API instead.
// ─────────────────────────────────────────────────────────────────────────────

import manifestData from './manifest.json';

/** Lazy glob — Vite will split every JSON into its own chunk. */
const lazyModules = import.meta.glob('./**/*.json');

/** Difficulty levels in display order. */
export const DIFFICULTY_LEVELS = [
  { key: 'facile', label: 'Facile', emoji: '🟢' },
  { key: 'moyen', label: 'Moyen', emoji: '🟠' },
  { key: 'difficile', label: 'Difficile', emoji: '🔴' },
];

// ─── In-flight / resolved cache so we never double-fetch ─────────────────────
const examCache = new Map(); // examId  -> Promise<fullExam>

// ─── Sync manifest access ────────────────────────────────────────────────────

/**
 * Returns all categories with lightweight exam stubs (no questions/levels
 * content). Fully synchronous — reads from the eagerly-imported manifest.
 *
 * Each category object: { id, label, emoji, order, exams[] }
 * Each exam stub:        { id, title, emoji, order, levelKeys[], levelPassPercent{}, _path }
 */
export function getCategories() {
  return manifestData.categories;
}

// ─── Async exam loading ───────────────────────────────────────────────────────

/**
 * Resolves the exam stubs for one category (no full JSON needed — stubs are in
 * the manifest). Returns a Promise so call sites can treat it uniformly with
 * getExam() but it resolves instantly from the manifest.
 */
export async function getExamsByCategory(categoryId) {
  const cat = manifestData.categories.find((c) => c.id === categoryId);
  return cat ? cat.exams : [];
}

/**
 * Loads and returns the full exam JSON (including questions) for one exam.
 * Results are cached so repeated calls for the same exam are free.
 */
export async function getExam(examId) {
  if (examCache.has(examId)) return examCache.get(examId);

  // Find the path from the manifest
  let path = null;
  outer: for (const cat of manifestData.categories) {
    for (const stub of cat.exams) {
      if (stub.id === examId) { path = stub._path; break outer; }
    }
  }

  if (!path) return null;

  const promise = lazyModules[path]().then((mod) => mod.default ?? mod);
  examCache.set(examId, promise);
  return promise;
}

/** Ordered difficulty keys — lower index = easier. */
const LEVEL_ORDER = ['facile', 'moyen', 'difficile'];

/**
 * Async equivalent of the old sync getExamLevel(). Returns
 * { exam, level, levelKey } or null.
 *
 * Questions are deduplicated against all lower-difficulty levels so a prompt
 * that already appeared in "facile" is never shown again in "moyen" or
 * "difficile", and so on.
 */
export async function getExamLevel(examId, levelKey) {
  const exam = await getExam(examId);
  if (!exam) return null;
  const level = exam.levels?.[levelKey];
  if (!level) return null;

  // Collect prompts already seen in easier levels
  const seenPrompts = new Set();
  const myIdx = LEVEL_ORDER.indexOf(levelKey);
  if (myIdx > 0) {
    for (let i = 0; i < myIdx; i++) {
      const lowerLevel = exam.levels?.[LEVEL_ORDER[i]];
      if (lowerLevel?.questions) {
        for (const q of lowerLevel.questions) {
          seenPrompts.add(String(q.prompt ?? '').trim().toLowerCase());
        }
      }
    }
  }

  // Filter out duplicates (return a shallow copy so we don't mutate the cache)
  const filteredQuestions = seenPrompts.size === 0
    ? level.questions
    : level.questions.filter(
        (q) => !seenPrompts.has(String(q.prompt ?? '').trim().toLowerCase())
      );

  const filteredLevel = filteredQuestions === level.questions
    ? level
    : { ...level, questions: filteredQuestions };

  return { exam, level: filteredLevel, levelKey };
}

// Keep the old sync name as an alias so any direct callers of getExamById get a
// clear error pointing them to the async API instead of a silent undefined.
export function getExamById(examId) {
  throw new Error(
    'getExamById() is synchronous and has been removed. ' +
    'Use `await getExam("' + examId + '")` instead.'
  );
}
