export const FUN_ITEMS = [

  /* ══════════════════════════════════════════════════
     BLAGUES
  ══════════════════════════════════════════════════ */
  {
    id: 'b01', type: 'blague', emoji: '😂', theme: 'animals',
    title: 'L\'escargot sur la tortue',
    content: 'Que dit un escargot sur le dos d\'une tortue ?',
    answer: '« Youhouuuu !!! »  🐢💨',
    age: [5, 12],
  },
  {
    id: 'b02', type: 'blague', emoji: '😂', theme: 'animals',
    title: 'Le crocodile à l\'aéroport',
    content: 'Qu\'est-ce qu\'un crocodile qui surveille les valises à l\'aéroport ?',
    answer: 'Un sac à dents ! 🧳🦷',
    age: [5, 12],
  },
  {
    id: 'b03', type: 'blague', emoji: '😂', theme: 'adventure',
    title: 'Les plongeurs',
    content: 'Pourquoi les plongeurs plongent-ils toujours en arrière et jamais en avant ?',
    answer: 'Parce que sinon ils tomberaient dans le bateau ! 🚢😄',
    age: [7, 12],
  },
  {
    id: 'b04', type: 'blague', emoji: '😂', theme: 'spooky',
    title: 'Le squelette au bar',
    content: 'Un squelette entre dans un café et demande quelque chose au serveur.\nQue commande-t-il ?',
    answer: 'Un verre d\'eau et une serpillière ! 💀😂',
    age: [7, 12],
  },
  {
    id: 'b05', type: 'blague', emoji: '😂', theme: 'animals',
    title: 'Les poissons jouent aux cartes',
    content: 'Pourquoi les poissons n\'aiment pas jouer aux cartes dans l\'océan ?',
    answer: 'Parce qu\'il y a trop de requins ! 🦈🃏',
    age: [6, 12],
  },
  {
    id: 'b06', type: 'blague', emoji: '😂', theme: 'food',
    title: 'Bonjour, j\'ai faim !',
    content: 'Un homme frappe à la porte. Une femme ouvre. Il dit : « Bonjour, je suis le voisin du dessus. »\nElle répond : « Enchanté, moi c\'est Marie. »\nIl dit : « Enchanté, moi c\'est… »\nQue dit-il ?',
    answer: '« Moi c\'est Faim ! » 🍽️ (sous-entendu : "Bonjour, j\'ai faim !")',
    age: [7, 12],
  },
  {
    id: 'b07', type: 'blague', emoji: '😂', theme: 'school',
    title: 'Le prof de maths',
    content: 'Le professeur demande à Léo : « Si tu as 12 bonbons et que tu en donnes 5 à Emma, qu\'est-ce qu\'il te reste ? »\nLéo répond : « … »\nQue répond Léo ?',
    answer: '« 12 bonbons ET une raison de ne pas aimer Emma ! » 🍬😅',
    age: [6, 12],
  },
  {
    id: 'b08', type: 'blague', emoji: '😂', theme: 'animals',
    title: 'La vache savante',
    content: 'Qu\'est-ce qu\'une vache qui lit beaucoup ?',
    answer: 'Une vache très cultivée ! 🐄📚 (Cultivée = qui cultive les champs, ET instruite !)',
    age: [7, 12],
  },
  {
    id: 'b09', type: 'blague', emoji: '😂', theme: 'school',
    title: 'Le génie de la classe',
    content: 'La maîtresse demande : « Qui peut me donner un exemple de phrase avec le mot "dix" ? »\nPaul lève la main et dit… quoi ?',
    answer: '« Ma sœur fait de la DISE ! » (danse → "dix-se") 💃😂',
    age: [6, 11],
  },
  {
    id: 'b10', type: 'blague', emoji: '😂', theme: 'animals',
    title: 'Le chat de Noël',
    content: 'Qu\'est-ce qu\'un chat qui tombe dans un pot de peinture rouge le soir de Noël ?',
    answer: 'Un chat-peint de Noël ! 🎄🐱 (= un Saint Nicolas pour les chats !)',
    age: [5, 11],
  },

  /* ══════════════════════════════════════════════════
     DEVINETTES
  ══════════════════════════════════════════════════ */
  {
    id: 'd01', type: 'devinette', emoji: '🤔', theme: 'nature',
    title: 'Je cours sans jambes',
    content: 'Je n\'ai pas de jambes, mais je cours très vite.\nJe n\'ai pas de bouche, mais je fais beaucoup de bruit.\nQui suis-je ?',
    answer: 'Le vent ! 💨',
    age: [5, 10],
  },
  {
    id: 'd02', type: 'devinette', emoji: '🤔', theme: 'home',
    title: 'Plus je sèche…',
    content: 'Plus je sèche, plus je suis mouillée.\nOn m\'utilise après le bain.\nQui suis-je ?',
    answer: 'Une serviette ! 🛁',
    age: [5, 10],
  },
  {
    id: 'd03', type: 'devinette', emoji: '🤔', theme: 'nature',
    title: 'Des aiguilles sans fil',
    content: 'J\'ai des aiguilles mais je ne couds pas.\nJ\'ai des branches mais je ne fleuris pas.\nEn hiver, on m\'illumine.\nQui suis-je ?',
    answer: 'Un sapin ! 🌲',
    age: [5, 10],
  },
  {
    id: 'd04', type: 'devinette', emoji: '🤔', theme: 'school',
    title: 'J\'amincis en travaillant',
    content: 'Plus on m\'utilise, plus j\'ai la taille fine.\nOn m\'efface et on me taille.\nQui suis-je ?',
    answer: 'Un crayon ! ✏️',
    age: [5, 10],
  },
  {
    id: 'd05', type: 'devinette', emoji: '🤔', theme: 'home',
    title: 'Je monte quand il fait froid',
    content: 'Je monte quand il fait froid et je descends quand il fait chaud.\nJe suis ton ami par tous les temps.\nQui suis-je ?',
    answer: 'Un thermomètre ! 🌡️ (La colonne monte quand c\'est CHAUD, contrairement à ce qu\'on croit !)',
    age: [7, 12],
  },
  {
    id: 'd06', type: 'devinette', emoji: '🤔', theme: 'home',
    title: 'Je pleure en brûlant',
    content: 'Je donne de la lumière mais je pleure en brûlant.\nJe disparais petit à petit.\nQui suis-je ?',
    answer: 'Une bougie ! 🕯️',
    age: [5, 10],
  },
  {
    id: 'd07', type: 'devinette', emoji: '🤔', theme: 'school',
    title: 'Je montre le monde entier',
    content: 'Je suis rond, je tourne sur moi-même.\nJe montre tous les pays du monde sans bouger de la classe.\nQui suis-je ?',
    answer: 'Un globe terrestre ! 🌍',
    age: [6, 10],
  },
  {
    id: 'd08', type: 'devinette', emoji: '🤔', theme: 'school',
    title: 'On m\'efface chaque soir',
    content: 'Je suis blanc le matin, couvert d\'écriture le soir.\nLe professeur me parle toute la journée.\nQui suis-je ?',
    answer: 'Le tableau de la classe ! 🖊️',
    age: [5, 9],
  },
  {
    id: 'd09', type: 'devinette', emoji: '🤔', theme: 'adventure',
    title: 'Je voyage sans bouger',
    content: 'Je voyage partout dans le monde sans jamais bouger.\nJe suis collé sur une enveloppe.\nQui suis-je ?',
    answer: 'Un timbre ! 📮',
    age: [6, 11],
  },
  {
    id: 'd10', type: 'devinette', emoji: '🤔', theme: 'nature',
    title: 'Je répète tout ce que tu dis',
    content: 'Je répète tout ce que tu dis, mais je suis invisible.\nTu m\'entends dans les montagnes et les tunnels.\nQui suis-je ?',
    answer: 'L\'écho ! 🏔️',
    age: [6, 11],
  },

  /* ══════════════════════════════════════════════════
     PROVERBES
  ══════════════════════════════════════════════════ */
  {
    id: 'pr01', type: 'proverbe', emoji: '📜', theme: 'weather',
    title: 'Après la pluie, le beau temps',
    content: 'Après la pluie, le beau temps.',
    meaning: 'Après les moments difficiles, il y a toujours de meilleurs moments qui arrivent. Ne perds jamais espoir ! 🌈',
    age: [6, 12],
  },
  {
    id: 'pr02', type: 'proverbe', emoji: '📜', theme: 'nature',
    title: 'Les petits ruisseaux font les grandes rivières',
    content: 'Les petits ruisseaux font les grandes rivières.',
    meaning: 'Les petits efforts mis bout à bout donnent de grands résultats. Chaque petit geste compte ! 💧🌊',
    age: [6, 12],
  },
  {
    id: 'pr03', type: 'proverbe', emoji: '📜', theme: 'food',
    title: 'L\'appétit vient en mangeant',
    content: 'L\'appétit vient en mangeant.',
    meaning: 'Plus on fait quelque chose, plus on en a envie. Si tu commences un livre, tu voudras le finir ! 📖',
    age: [7, 12],
  },
  {
    id: 'pr04', type: 'proverbe', emoji: '📜', theme: 'time',
    title: 'Mieux vaut tard que jamais',
    content: 'Mieux vaut tard que jamais.',
    meaning: 'Il vaut mieux faire quelque chose en retard que ne pas le faire du tout. Ce n\'est jamais trop tard pour bien faire ! ⏰',
    age: [6, 12],
  },
  {
    id: 'pr05', type: 'proverbe', emoji: '📜', theme: 'animals',
    title: 'Les chiens ne font pas des chats',
    content: 'Les chiens ne font pas des chats.',
    meaning: 'Les enfants ressemblent souvent à leurs parents. On garde les traits de notre famille ! 🐕🐈',
    age: [7, 12],
  },
  {
    id: 'pr06', type: 'proverbe', emoji: '📜', theme: 'time',
    title: 'Tout vient à point à qui sait attendre',
    content: 'Tout vient à point à qui sait attendre.',
    meaning: 'La patience est récompensée. Les bonnes choses arrivent à ceux qui savent être patients ! ⌛',
    age: [7, 12],
  },
  {
    id: 'pr07', type: 'proverbe', emoji: '📜', theme: 'school',
    title: 'Qui sème le vent récolte la tempête',
    content: 'Qui sème le vent récolte la tempête.',
    meaning: 'Nos actions ont des conséquences. Si on fait de mauvaises choses, on en subira les effets ! 🌪️',
    age: [8, 12],
  },
  {
    id: 'pr08', type: 'proverbe', emoji: '📜', theme: 'animals',
    title: 'Chat échaudé craint l\'eau froide',
    content: 'Chat échaudé craint l\'eau froide.',
    meaning: 'Quelqu\'un qui a été blessé une fois devient très prudent, même là où il n\'y a plus de danger. 🐱💧',
    age: [7, 12],
  },
  {
    id: 'pr09', type: 'proverbe', emoji: '📜', theme: 'nature',
    title: 'Pierre qui roule n\'amasse pas mousse',
    content: 'Pierre qui roule n\'amasse pas mousse.',
    meaning: 'Quelqu\'un qui change souvent d\'avis ou de place ne construit rien de solide. La persévérance est une force ! 🪨',
    age: [8, 12],
  },
  {
    id: 'pr10', type: 'proverbe', emoji: '📜', theme: 'food',
    title: 'Il ne faut pas vendre la peau de l\'ours avant de l\'avoir tué',
    content: 'Il ne faut pas vendre la peau de l\'ours avant de l\'avoir tué.',
    meaning: 'Il ne faut pas se réjouir d\'un succès avant de l\'avoir vraiment obtenu ! Ne compte pas tes poules avant qu\'elles soient écloses. 🐻',
    age: [7, 12],
  },

  /* ══════════════════════════════════════════════════
     POÈMES
  ══════════════════════════════════════════════════ */
  {
    id: 'po01', type: 'poeme', emoji: '🌸', theme: 'nature',
    title: 'Il pleut, il pleut, bergère',
    content: 'Il pleut, il pleut, bergère,\nPresse tes blancs moutons ;\nAllons sous ma chaumière,\nBergère, vite allons.\n\nJ\'entends sur le feuillage\nL\'eau qui tombe à grand bruit ;\nVoici venir l\'orage,\nVoici l\'éclair qui luit.',
    author: 'Fabre d\'Églantine',
    age: [6, 12],
  },
  {
    id: 'po02', type: 'poeme', emoji: '🌸', theme: 'animals',
    title: 'Mon chat',
    content: 'Mon chat ronronne sur mes genoux,\nDoux comme un nuage de soie ;\nIl ferme ses yeux tout roux\nEt s\'endort dans la joie.\n\nQuand je lis mes livres d\'école,\nIl rêve de souris qui volent,\nEt ses moustaches vibrent un peu —\nDe quoi donc rêve-t-il, mon vieux ?',
    author: 'Traditionnel',
    age: [5, 10],
  },
  {
    id: 'po03', type: 'poeme', emoji: '🌸', theme: 'school',
    title: 'Comptine des jours',
    content: 'Lundi matin, papa s\'en va,\nMardi, c\'est l\'école déjà ;\nMercredi, on joue tout le jour,\nJeudi, les amis font retour.\n\nVendredi, on apprend encore,\nSamedi, on sort et on adore,\nDimanche enfin — le beau repos —\nAvant que tout recommence bientôt !',
    author: 'Traditionnel',
    age: [5, 9],
  },
  {
    id: 'po04', type: 'poeme', emoji: '🌸', theme: 'nature',
    title: 'L\'arc-en-ciel',
    content: 'Après l\'averse et les nuages gris,\nVoici le ciel qui se découvre ;\nDe rouge, d\'orange, de vert, de bleueri,\nL\'arc-en-ciel sa beauté nous ouvre.\n\nSept couleurs font un grand sourire\nDu soleil qui dit bonjour ;\nIl suffit de les regarder et de sourire —\nLa pluie devient lumière du jour.',
    author: 'Traditionnel adapté',
    age: [5, 10],
  },
  {
    id: 'po05', type: 'poeme', emoji: '🌸', theme: 'nature',
    title: 'La neige',
    content: 'La neige tombe en silence,\nElle habille les jardins de blanc ;\nLes enfants dansent et avancent,\nEt font un bonhomme rigoland.\n\nCarotte pour nez, boutons pour yeux,\nÉcharpe rouge enroulée autour du cou —\nIl restera là, heureux,\nJusqu\'au retour du soleil doux.',
    author: 'Traditionnel',
    age: [5, 9],
  },
  {
    id: 'po06', type: 'poeme', emoji: '🌸', theme: 'animals',
    title: 'La fourmi',
    content: 'Une petite fourmi\nTravaille tout le jour ;\nElle ne se repose ni\nLe matin ni le tour.\n\nElle porte sur son dos\nDix fois son propre poids —\nQuel courage, quel héros,\nCette fourmi aux longs doigts !',
    author: 'Traditionnel',
    age: [6, 11],
  },
  {
    id: 'po07', type: 'poeme', emoji: '🌸', theme: 'night',
    title: 'La lune et les étoiles',
    content: 'La lune monte dans le ciel bleu nuit,\nElle allume ses lampes d\'argent ;\nLes étoiles scintillent et rient\nEt clignotent doucement.\n\nBonne nuit, dit la lune aux enfants,\nFermez vos yeux, rêvez bien ;\nJe veille sur vous jusqu\'au printemps —\nDors, mon cœur, dors, c\'est bien.',
    author: 'Traditionnel',
    age: [4, 9],
  },
  {
    id: 'po08', type: 'poeme', emoji: '🌸', theme: 'school',
    title: 'Mon livre',
    content: 'Mon livre est un ami fidèle,\nIl voyage avec moi partout ;\nQuand j\'ouvre ses pages si belles,\nJe pars vers des mondes tout doux.\n\nIl me fait rire, parfois pleurer,\nIl me raconte des histoires ;\nDans ses pages j\'aime me cacher\nEt partir à la recherche de la gloire.',
    author: 'Traditionnel adapté',
    age: [6, 12],
  },
  {
    id: 'po09', type: 'poeme', emoji: '🌸', theme: 'food',
    title: 'La gourmandise',
    content: 'J\'aime le chocolat fondu,\nLes crêpes au miel et au citron ;\nJ\'aime les gaufres attendu\nEt les fraises en saison.\n\nMais maman dit : « Mange tes légumes ! »\nEt je fais la grimace un peu —\nPuis je mange, et l\'amertume\nDevient doux dans mes yeux bleus.',
    author: 'Traditionnel',
    age: [5, 10],
  },
  {
    id: 'po10', type: 'poeme', emoji: '🌸', theme: 'nature',
    title: 'Le printemps',
    content: 'Le printemps arrive en dansant,\nIl réveille fleurs et oiseaux ;\nLes abeilles dans les prés en chantant\nFont bourdonner leurs ailes doucement.\n\nLes arbres portent de nouveaux habits,\nVerts, roses, blancs et jaunes ;\nLa nature entière a fleuri —\nVive le printemps ! Vive la saison !',
    author: 'Traditionnel',
    age: [5, 10],
  },

  /* ══════════════════════════════════════════════════
     CONTES COURTS
  ══════════════════════════════════════════════════ */
  {
    id: 'c01', type: 'conte', emoji: '🎭', theme: 'animals',
    title: 'Le Lion qui demanda de l\'aide',
    content: 'Il était une fois un grand lion fier qui régnait sur la savane. Un jour, en marchant la tête haute, il tomba dans un profond trou et se retrouva coincé.\n\nUne petite souris passa par là et s\'arrêta, la tête penchée.\n\n— Tu as besoin d\'aide, grand roi ? demanda-t-elle.\n— Moi ?! rugit le lion. Jamais de la vie ! Je suis le roi des animaux !\n\nLa souris haussa les épaules et continua son chemin.\n\nLe lion attendit toute la journée. Le soir venu, il appela doucement : — Petite souris ? Tu es encore là ?\n— Oui, dit la voix de la souris dans le noir.\n— Je... je crois que j\'aurais besoin d\'un tout petit peu d\'aide, s\'il te plaît.\n\nLa souris appela ses douze amies, et ensemble elles aidèrent le lion à sortir du trou en rongeant les racines.\n\n— Merci, murmura le lion tout rouge. Je n\'aurais pas cru que de si petites créatures pouvaient aider un si grand roi.\n\n— C\'est ça, l\'amitié ! dit la souris en souriant. La taille ne compte pas — c\'est le cœur qui compte ! ❤️',
    moral: 'L\'orgueil ne sert à rien. Tout le monde peut avoir besoin d\'aide, même les plus forts.',
    age: [5, 10],
  },
  {
    id: 'c02', type: 'conte', emoji: '🎭', theme: 'adventure',
    title: 'La Tortue et le Lièvre (version drôle)',
    content: 'Tout le monde connaît l\'histoire de la tortue et du lièvre. Mais personne ne sait ce qui s\'est passé après !\n\nLe lendemain de sa victoire, la tortue était devenue célèbre. Tous les animaux voulaient prendre sa photo et lui serrer la main.\n\nLe lièvre, lui, était rouge de honte. Il s\'entraîna toute la semaine et défia à nouveau la tortue.\n\n— Cette fois, je ne dormirai pas ! promit-il.\n\nLa course commença. Le lièvre fila comme l\'éclair... et tomba dans un trou de marmotte qu\'il n\'avait pas vu tellement il allait vite.\n\nLa tortue passa à côté de lui et dit avec un grand sourire :\n\n— Tu veux de l\'aide, mon ami ? 😊\n\nEt depuis ce jour-là, le lièvre et la tortue devinrent les meilleurs amis du monde. Le lièvre apprit la patience, et la tortue apprit à courir (un tout petit peu) plus vite.',
    moral: 'La vitesse ne sert à rien sans attention. Et un ennemi peut devenir un ami !',
    age: [5, 11],
  },
  {
    id: 'c03', type: 'conte', emoji: '🎭', theme: 'magic',
    title: 'La Fée des Dents trop occupée',
    content: 'La fée des Dents avait un gros problème : elle avait trop de travail. En une seule nuit, 847 enfants avaient perdu une dent dans toute la Belgique !\n\nElle enfila son manteau magique, prit son sac d\'étoiles dorées... et tomba en panne de poudre de fée à mi-chemin.\n\nElle s\'arrêta chez le lutin Émile, le seul ouvert la nuit.\n\n— Une dose de poudre de fée, vite ! dit-elle.\n— Je n\'ai plus que de la poudre de lutin, dit Émile. Ça fait la même chose mais ça sent le chou-fleur.\n\nLa fée n\'avait pas le choix. Elle termina sa tournée avec de la poudre de chou-fleur.\n\nLe lendemain matin, 847 enfants trouvèrent chacun une pièce sous leur oreiller... et leurs chambres sentaient un peu le chou-fleur.\n\nPersonne ne sut jamais pourquoi. 🧚🥦',
    moral: 'Même les fées ont des jours difficiles. L\'important, c\'est de toujours trouver une solution !',
    age: [5, 9],
  },
  {
    id: 'c04', type: 'conte', emoji: '🎭', theme: 'nature',
    title: 'Le Nuage jaloux du Soleil',
    content: 'Il était une fois un petit nuage gris qui n\'aimait pas le soleil. Chaque fois que le soleil brillait, tout le monde criait : « Quel beau temps ! » et personne ne regardait le nuage.\n\n— C\'est injuste, grommelait le nuage. Moi aussi je suis beau !\n\nUn jour, il se plaça devant le soleil pour le cacher. Tout le monde leva les yeux vers lui.\n\n— Oh non, dit une petite fille. Il va pleuvoir.\n\nLe nuage était triste. Il n\'avait pas voulu faire pleuvoir. Il fit tout son possible pour retenir ses larmes... mais une grosse goutte tomba quand même.\n\nEt alors une chose magique arriva : le soleil sortit de derrière lui et, ensemble, ils firent apparaître... un magnifique arc-en-ciel ! 🌈\n\n— Wahou ! crièrent tous les enfants.\n\nDepuis ce jour, le nuage comprit qu\'on est toujours plus beau et plus fort ensemble.',
    moral: 'La jalousie ne sert à rien. Ensemble, on crée de plus belles choses.',
    age: [5, 10],
  },
  {
    id: 'c05', type: 'conte', emoji: '🎭', theme: 'school',
    title: 'Le Robot qui voulait apprendre à rire',
    content: 'Dans une école du futur, il y avait un robot professeur qui s\'appelait Zap-7. Il était très intelligent : il connaissait toutes les tables de multiplication, toutes les capitales du monde et tous les mots du dictionnaire.\n\nMais Zap-7 ne savait pas rire.\n\nUn matin, Théo lui raconta une blague :\n— Zap-7, pourquoi les plongeurs plongent-ils en arrière ?\n— Je ne sais pas, dit Zap-7 en cherchant dans sa base de données.\n— Parce que sinon ils tomberaient dans le bateau !\n\nZap-7 resta silencieux 3 secondes. Puis ses lumières clignotèrent. Puis un drôle de son sortit de lui : « Ha. Ha. Ha. » Très mécanique.\n\nMais Théo éclata de rire — pas à la blague, mais au rire de Zap-7.\n\nEt alors, quelque chose d\'incroyable se produisit : Zap-7 vit Théo rire, et son rire devint... vrai. Un vrai grand rire de robot.\n\nDepuis ce jour, Zap-7 et Théo se racontent des blagues tous les matins. 🤖😂',
    moral: 'Le rire s\'apprend. Et un ami peut nous enseigner les choses les plus importantes.',
    age: [6, 11],
  },
  {
    id: 'c06', type: 'conte', emoji: '🎭', theme: 'magic',
    title: 'La Bibliothèque enchantée',
    content: 'Derrière la vieille école de Bruxelles, il y avait une bibliothèque que peu d\'élèves osaient visiter. On disait qu\'elle était enchantée.\n\nLéa décida d\'y entrer un mercredi pluvieux. À peine avait-elle ouvert la porte qu\'un livre rouge sauta de son étagère et atterrit à ses pieds.\n\n« OUVRE-MOI », disait la couverture.\n\nLéa l\'ouvrit. Et aussitôt, elle se retrouva... dans la forêt de Soignes ! Des arbres immenses l\'entouraient. Un écureuil lui tendit une noisette.\n\n— Tu es dans mon histoire, dit l\'écureuil. Page 47.\n\nLéa passa l\'après-midi à explorer la forêt magique. Quand l\'histoire se termina, elle se retrouva dans la bibliothèque, le livre fermé dans les mains.\n\nSur la couverture, il y avait maintenant un nouveau personnage : une petite fille aux tresses. Léa sourit.\n\nElle était entrée dans le livre. Pour toujours. 📚✨',
    moral: 'Les livres nous emmènent dans des mondes infinis. La lecture, c\'est la plus belle des aventures.',
    age: [6, 12],
  },
  {
    id: 'c07', type: 'conte', emoji: '🎭', theme: 'food',
    title: 'Le Gâteau qui ne voulait pas être mangé',
    content: 'Madame Pâtisserie avait fait le plus beau gâteau de toute sa carrière. Cinq étages, du chocolat partout, des framboises fraîches et des étoiles en sucre.\n\nMais au moment de le couper, le gâteau prit la parole :\n\n— Je refuse d\'être mangé ! J\'ai mis des jours à devenir aussi beau !\n\nMadame Pâtisserie ouvrit des yeux grands comme des assiettes.\n\n— Mais... tu as été créé pour être mangé et rendre les gens heureux.\n— Être heureux ? dit le gâteau. Hm.\n\nIl réfléchit un long moment.\n\n— D\'accord. Mais je veux voir les visages des enfants quand ils me verront.\n\nMadame Pâtisserie appela les enfants de l\'école. Quand ils entrèrent et virent le gâteau, leurs yeux brillèrent comme des étoiles.\n\nEt le gâteau comprit alors que c\'était ça, sa magie : pas d\'être regardé, mais d\'être partagé. 🎂❤️',
    moral: 'Le bonheur se trouve dans ce qu\'on partage, pas dans ce qu\'on garde pour soi.',
    age: [5, 10],
  },
  {
    id: 'c08', type: 'conte', emoji: '🎭', theme: 'nature',
    title: 'L\'arbre qui voulait voyager',
    content: 'Dans un grand parc, il y avait un chêne de 200 ans qui rêvait de voyager. Il regardait les oiseaux partir vers le sud, les feuilles s\'envoler dans le vent, et il soupira.\n\n— Je veux voir la mer, dit-il.\n\nUn merle posa sur sa branche.\n\n— Je reviens d\'Espagne, dit le merle. J\'ai vu la mer, les montagnes, les déserts...\n\n— Tu as de la chance, soupira le chêne.\n\n— De la chance ? dit le merle. Chaque hiver je risque ma vie en voyageant ! Toi, tu restes ici, au chaud, avec tes racines profondes. Les enfants jouent sous tes branches. Les oiseaux nichent dans tes feuilles. Tu es la maison de cent familles !\n\nLe chêne regarda autour de lui. Un écureuil dormait dans son tronc creux. Des enfants grimpaient sur ses branches. Un couple pique-niquait à son ombre.\n\nPour la première fois, le chêne sourit. 🌳',
    moral: 'Le bonheur est souvent là où on est, pas là où on voudrait être.',
    age: [6, 12],
  },
  {
    id: 'c09', type: 'conte', emoji: '🎭', theme: 'animals',
    title: 'Le Pingouin qui voulait voler',
    content: 'Au pôle Sud, un petit pingouin nommé Pablo regardait les albatros planer dans le ciel avec envie.\n\n— Je veux voler ! annonça-t-il un matin.\n\nTous les pingouins éclatèrent de rire.\n\n— Les pingouins ne volent pas, Pablo !\n\nMais Pablo ne voulait pas croire ça. Il grimpa en haut d\'un iceberg, ferma les yeux, et sauta.\n\nIl tomba dans l\'eau avec un SPLATCH retentissant.\n\nMais sous l\'eau... quelque chose d\'étonnant se produisit. Pablo nageait à toute vitesse, virevoltait entre les poissons, plongeait dans le noir des profondeurs et remontait en flèche.\n\nUn phoque qui le regardait dit en s\'approchant :\n— Pablo, tu sais que tu viens de nager à 35 km/h ? Les pingouins sont les meilleurs nageurs du monde !\n\nPablo sortit la tête de l\'eau, le bec grand ouvert.\n\nIl ne volait pas. Mais dans l\'eau, il était libre comme l\'air. 🐧💙',
    moral: 'Chacun a ses propres talents. Cherche ce que TU fais mieux que personne !',
    age: [5, 11],
  },
  {
    id: 'c10', type: 'conte', emoji: '🎭', theme: 'school',
    title: 'Le Crayon magique',
    content: 'Dans la trousse de Zoé, il y avait un crayon ordinaire en apparence... mais pas tout à fait.\n\nUn matin, Zoé dessina un soleil sur sa feuille. Et le soleil se mit à briller pour de vrai sur le papier, tout chaud et tout jaune.\n\nElle dessina un chat. Le chat remua la queue.\n\nElle dessina une maison avec un jardin. Et dans le jardin poussèrent de vraies petites fleurs minuscules.\n\nZoé n\'en revenait pas. Elle dessina toute la journée — des forêts, des océans, des astronautes, des dauphins, des châteaux.\n\nLe soir, sa feuille était un monde entier.\n\nElle la regarda longtemps avant de dormir.\n\nLe lendemain, le crayon était ordinaire à nouveau. Mais Zoé avait compris quelque chose d\'important :\n\nToute la magie était dans ses mains depuis le début. ✏️🌟',
    moral: 'La créativité et l\'imagination sont les plus belles magies. Elles sont en toi !',
    age: [5, 10],
  },

  /* ══════════════════════════════════════════════════
     LE SAIS-TU ? — faits insolites pour enfants
  ══════════════════════════════════════════════════ */

  // — Animaux —
  { id: 'f01', type: 'fait', emoji: '🐙', theme: 'animals', title: 'Le sang bleu',
    content: 'Les pieuvres ont trois cœurs et du sang de couleur bleue !',
    detail: 'Leur sang contient du cuivre (hémocyanine) au lieu du fer, ce qui lui donne cette teinte bleue.', age: [6, 12] },
  { id: 'f02', type: 'fait', emoji: '🦷', theme: 'animals', title: '50 000 dents !',
    content: 'Les dents de requin repoussent toute leur vie. Un requin peut avoir jusqu\'à 50 000 dents !',
    detail: 'Quand une dent tombe, une nouvelle pousse derrière elle, comme un tapis roulant de dents.', age: [6, 12] },
  { id: 'f03', type: 'fait', emoji: '🐘', theme: 'animals', title: 'Jamais de saut',
    content: 'Les éléphants sont les seuls animaux qui ne peuvent pas sauter du tout !',
    detail: 'Leur poids énorme (jusqu\'à 6 tonnes) rend le saut impossible — mais ils nagent très bien.', age: [5, 12] },
  { id: 'f04', type: 'fait', emoji: '🦋', theme: 'animals', title: 'Goûter avec les pieds',
    content: 'Les papillons goûtent leur nourriture… avec leurs pieds !',
    detail: 'Ils ont des capteurs gustatifs sous leurs pattes qui leur permettent de "tester" une fleur avant même de la toucher avec leur bouche.', age: [5, 11] },
  { id: 'f05', type: 'fait', emoji: '🐝', theme: 'animals', title: 'La cuillerée de miel',
    content: 'Une abeille visite 1 500 fleurs pour produire une seule cuillerée de miel !',
    detail: 'Une abeille ouvrière travaille toute sa vie pour fabriquer seulement 1/12 de cuillerée à café de miel.', age: [5, 12] },
  { id: 'f06', type: 'fait', emoji: '🦒', theme: 'animals', title: 'La langue violette',
    content: 'La langue d\'une girafe est violette et mesure environ 50 cm !',
    detail: 'Sa couleur foncée protège contre les coups de soleil — les girafes passent des heures à attraper des feuilles en plein soleil.', age: [5, 11] },
  { id: 'f07', type: 'fait', emoji: '🐬', theme: 'animals', title: 'Dormir à moitié',
    content: 'Les dauphins dorment avec un seul œil ouvert et la moitié du cerveau en éveil !',
    detail: 'C\'est ce qu\'on appelle le sommeil unihémisphérique — cela leur permet de continuer à surveiller les dangers et à respirer.', age: [7, 12] },
  { id: 'f08', type: 'fait', emoji: '🐌', theme: 'animals', title: '3 ans de sommeil',
    content: 'Un escargot peut dormir pendant 3 ans d\'affilée si le temps est trop sec ou trop froid !',
    detail: 'Quand les conditions sont mauvaises, l\'escargot se referme dans sa coquille et entre en hibernation profonde.', age: [6, 12] },
  { id: 'f09', type: 'fait', emoji: '🦈', theme: 'animals', title: 'Plus vieux que les arbres',
    content: 'Les requins existent depuis 450 millions d\'années — bien avant les arbres (il y a 350 millions d\'ans) !',
    detail: 'Les requins ont survécu à 5 extinctions massives. Ils n\'ont presque pas changé car ils sont déjà parfaits pour survivre.', age: [7, 12] },
  { id: 'f10', type: 'fait', emoji: '🐧', theme: 'animals', title: 'Le cadeau en caillou',
    content: 'Les manchots se font la cour en offrant un caillou à l\'élu(e) de leur cœur !',
    detail: 'Pour les manchots empereurs, offrir le bon caillou est une demande en mariage. Le couple peut rester ensemble toute sa vie.', age: [5, 11] },
  { id: 'f11', type: 'fait', emoji: '🦁', theme: 'animals', title: 'Le roi dormeur',
    content: 'Les lions dorment entre 16 et 20 heures par jour !',
    detail: 'Ils se reposent tant que possible pour économiser leur énergie — les grandes chasses sont épuisantes.', age: [5, 11] },
  { id: 'f12', type: 'fait', emoji: '🐸', theme: 'animals', title: 'Boire avec la peau',
    content: 'Les grenouilles ne boivent pas d\'eau — elles l\'absorbent directement à travers leur peau !',
    detail: 'Leur peau est très perméable. C\'est pourquoi elles ont besoin de rester dans des endroits humides.', age: [6, 12] },
  { id: 'f13', type: 'fait', emoji: '🦩', theme: 'animals', title: 'Nés blancs',
    content: 'Les flamants roses naissent blancs ou gris — c\'est leur nourriture qui les rend roses !',
    detail: 'Les algues et crevettes qu\'ils mangent contiennent des pigments appelés caroténoïdes. Sans eux, ils resteraient gris.', age: [6, 12] },
  { id: 'f14', type: 'fait', emoji: '🐋', theme: 'animals', title: 'Un cœur de voiture',
    content: 'Le cœur d\'une baleine bleue est aussi gros qu\'une petite voiture et pèse environ 180 kg !',
    detail: 'La baleine bleue est l\'animal le plus grand ayant jamais existé — plus grand que n\'importe quel dinosaure.', age: [7, 12] },
  { id: 'f15', type: 'fait', emoji: '🦔', theme: 'animals', title: 'Le grand marcheur',
    content: 'Un hérisson peut parcourir jusqu\'à 3 km en une seule nuit à la recherche de nourriture !',
    detail: 'Malgré leur petite taille, les hérissons sont de vrais explorateurs nocturnes.', age: [5, 11] },

  // — Espace & nature —
  { id: 'f16', type: 'fait', emoji: '🌙', theme: 'space', title: 'Empreintes éternelles',
    content: 'Sur la Lune, tes empreintes de pas resteraient là pendant un million d\'années !',
    detail: 'Il n\'y a pas de vent ni d\'eau sur la Lune pour les effacer. Les empreintes des astronautes d\'Apollo sont encore là aujourd\'hui.', age: [6, 12] },
  { id: 'f17', type: 'fait', emoji: '🌳', theme: 'nature', title: 'L\'arbre de 5 000 ans',
    content: 'Le plus vieil arbre du monde a environ 5 000 ans — il s\'appelle Mathusalem !',
    detail: 'C\'est un pin de Bristlecone en Californie. Pour le protéger, son emplacement exact est gardé secret.', age: [6, 12] },
  { id: 'f18', type: 'fait', emoji: '☀️', theme: 'space', title: '8 minutes de lumière',
    content: 'La lumière du Soleil met exactement 8 minutes et 20 secondes pour arriver jusqu\'à nous !',
    detail: 'Si le Soleil s\'éteignait maintenant, on ne le saurait que 8 minutes plus tard. La lumière voyage à 300 000 km par seconde.', age: [7, 12] },
  { id: 'f19', type: 'fait', emoji: '🌍', theme: 'space', title: 'La Terre qui tourne',
    content: 'La Terre tourne à environ 1 670 km/h — même quand tu dors tranquillement !',
    detail: 'On ne le sent pas car tout (l\'air, les bâtiments, nous) se déplace à la même vitesse. C\'est comme dans un avion : tu ne sens pas la vitesse.', age: [7, 12] },
  { id: 'f20', type: 'fait', emoji: '⚡', theme: 'nature', title: 'Plus chaud que le Soleil',
    content: 'Un éclair est 5 fois plus chaud que la surface du Soleil !',
    detail: 'Un éclair peut atteindre 30 000 °C. La surface du Soleil est "seulement" à 5 500 °C. Et tout ça en une fraction de seconde.', age: [7, 12] },
  { id: 'f21', type: 'fait', emoji: '🌊', theme: 'nature', title: 'L\'océan mystérieux',
    content: 'L\'océan couvre 71 % de la Terre mais on en a exploré à peine 20 % !',
    detail: 'Les abysses (les zones profondes) sont si sombres et froides qu\'on les connaît moins bien que la surface de la Lune.', age: [7, 12] },
  { id: 'f22', type: 'fait', emoji: '🪐', theme: 'space', title: 'Saturne flotterait',
    content: 'La planète Saturne est si peu dense qu\'elle flotterait sur l\'eau !',
    detail: 'Saturne est principalement composée d\'hydrogène et d\'hélium, les gaz les plus légers. Sa densité est inférieure à celle de l\'eau.', age: [7, 12] },
  { id: 'f23', type: 'fait', emoji: '❄️', theme: 'nature', title: 'Chaque flocon est unique',
    content: 'Chaque flocon de neige est unique — il n\'en existe pas deux exactement pareils !',
    detail: 'Un flocon se forme autour d\'une minuscule poussière et grandit selon la température et l\'humidité exactes qu\'il rencontre. Chaque voyage est différent.', age: [5, 12] },
  { id: 'f24', type: 'fait', emoji: '🍃', theme: 'nature', title: 'Le poumon de la Terre',
    content: 'Les forêts tropicales produisent 28 % de l\'oxygène de notre planète !',
    detail: 'La forêt amazonienne seule produit 20 % de l\'oxygène mondial. C\'est pourquoi on l\'appelle "le poumon de la Terre".', age: [7, 12] },

  // — Corps humain —
  { id: 'f25', type: 'fait', emoji: '🫀', theme: 'body', title: '100 000 battements',
    content: 'Ton cœur bat environ 100 000 fois par jour, sans jamais s\'arrêter pour se reposer !',
    detail: 'En une vie entière, le cœur bat environ 3 milliards de fois. C\'est le muscle le plus endurant du corps.', age: [6, 12] },
  { id: 'f26', type: 'fait', emoji: '🧠', theme: 'body', title: 'Le cerveau électrique',
    content: 'Ton cerveau génère assez d\'électricité pour allumer une petite ampoule !',
    detail: 'Le cerveau produit environ 12-25 watts. Il représente 2 % du poids du corps mais consomme 20 % de toute l\'énergie !', age: [7, 12] },
  { id: 'f27', type: 'fait', emoji: '🦴', theme: 'body', title: 'Os qui disparaissent',
    content: 'Tu as 206 os dans ton corps — mais les bébés en ont 300 à la naissance !',
    detail: 'En grandissant, de nombreux petits os fusionnent ensemble. C\'est pourquoi les bébés sont si souples.', age: [6, 12] },
  { id: 'f28', type: 'fait', emoji: '👁️', theme: 'body', title: '10 millions de couleurs',
    content: 'Tes yeux peuvent distinguer jusqu\'à 10 millions de couleurs différentes !',
    detail: 'Les chiens ne voient qu\'environ 10 000 couleurs. Les humains ont trois types de cellules pour la couleur dans leurs yeux.', age: [7, 12] },
  { id: 'f29', type: 'fait', emoji: '😂', theme: 'body', title: 'Rire = sport',
    content: 'Rire 100 fois brûle autant de calories que pédaler 10 minutes sur un vélo !',
    detail: 'Le rire fait travailler plus de 400 muscles simultanément. C\'est le meilleur sport sans effort !', age: [6, 12] },
  { id: 'f30', type: 'fait', emoji: '👃', theme: 'body', title: 'Un nez extraordinaire',
    content: 'Ton nez peut reconnaître plus de 1 trillion (1 000 milliards !) d\'odeurs différentes !',
    detail: 'Pendant longtemps on pensait que les humains ne détectaient que 10 000 odeurs. Une étude de 2014 a montré que c\'est bien plus !', age: [8, 12] },

  // — Science & inventions —
  { id: 'f31', type: 'fait', emoji: '💡', theme: 'science', title: '1 000 essais',
    content: 'Thomas Edison a fait plus de 1 000 essais avant d\'inventer l\'ampoule électrique !',
    detail: 'Quand on lui demanda s\'il se sentait découragé par ses échecs, il répondit : "Je n\'ai pas échoué. J\'ai juste trouvé 1 000 façons qui ne fonctionnent pas."', age: [7, 12] },
  { id: 'f32', type: 'fait', emoji: '🌐', theme: 'science', title: 'Le premier message Internet',
    content: 'Le premier message envoyé sur Internet en 1969 était "lo" — le réseau a planté avant la fin du mot "login" !',
    detail: 'Le réseau s\'appelait ARPANET. La première vraie connexion entre deux ordinateurs (à Los Angeles et Stanford) s\'est plantée après seulement 2 lettres.', age: [8, 12] },
  { id: 'f33', type: 'fait', emoji: '🎮', theme: 'science', title: 'Le premier jeu vidéo',
    content: 'Le premier jeu vidéo a été créé en 1958 et c\'était une version de tennis/ping-pong !',
    detail: 'Il s\'appelait "Tennis for Two" et a été créé par un physicien américain nommé William Higinbotham lors d\'une fête.', age: [7, 12] },
  { id: 'f34', type: 'fait', emoji: '🧲', theme: 'science', title: 'L\'aimant coupé en deux',
    content: 'Si tu coupes un aimant en deux, chaque morceau aura un pôle nord ET un pôle sud !',
    detail: 'On ne peut pas avoir un aimant avec seulement un pôle. Les scientifiques cherchent encore un "monopôle magnétique" — il n\'en a jamais été trouvé.', age: [8, 12] },
  { id: 'f35', type: 'fait', emoji: '🚀', theme: 'science', title: '28 000 km/h',
    content: 'Une fusée doit atteindre 28 000 km/h pour rester en orbite autour de la Terre !',
    detail: 'C\'est la "vitesse orbitale". Plus lent et elle tombe, plus rapide et elle s\'échappe dans l\'espace. Les astronautes de l\'ISS font le tour de la Terre en 90 minutes.', age: [8, 12] },
  { id: 'f36', type: 'fait', emoji: '🍕', theme: 'food', title: 'La pizza d\'une reine',
    content: 'La pizza Margherita a été inventée en 1889 pour la reine d\'Italie, Margherita de Savoie !',
    detail: 'Le pizzaiolo Raffaele Esposito a choisi les couleurs du drapeau italien : rouge (tomate), blanc (mozzarella), vert (basilic).', age: [6, 12] },
  { id: 'f37', type: 'fait', emoji: '🍫', theme: 'food', title: 'Le chocolat des guerriers',
    content: 'Les soldats aztèques buvaient du chocolat avant les batailles pour avoir de l\'énergie !',
    detail: 'Mais leur chocolat n\'avait rien à voir avec le nôtre : c\'était amer, pimenté et froid. Le sucre n\'a été ajouté qu\'après l\'arrivée des Espagnols.', age: [7, 12] },
  { id: 'f38', type: 'fait', emoji: '🥕', theme: 'food', title: 'Les carottes violettes',
    content: 'Les carottes étaient violettes ou blanches à l\'origine — les carottes oranges ont été cultivées il y a seulement 400 ans !',
    detail: 'Les Hollandais auraient développé la carotte orange pour honorer la famille royale "Orange-Nassau". Vrai ou légende ? Le débat continue !', age: [7, 12] },
];

export const FUN_TYPES = [
  {
    id: 'blague',
    label: 'Blagues',
    emoji: '😂',
    color: '#f43f5e',
    bg: '#fff1f2',
    gradient: 'linear-gradient(135deg, #f43f5e22, #fb7185aa)',
    desc: 'Fais rire toute la famille !',
    count: () => FUN_ITEMS.filter(i => i.type === 'blague').length,
  },
  {
    id: 'devinette',
    label: 'Devinettes',
    emoji: '🤔',
    color: '#8b5cf6',
    bg: '#f5f3ff',
    gradient: 'linear-gradient(135deg, #8b5cf622, #a78bfaaa)',
    desc: 'Devine si tu peux !',
    count: () => FUN_ITEMS.filter(i => i.type === 'devinette').length,
  },
  {
    id: 'proverbe',
    label: 'Proverbes',
    emoji: '📜',
    color: '#f59e0b',
    bg: '#fffbeb',
    gradient: 'linear-gradient(135deg, #f59e0b22, #fbbf24aa)',
    desc: 'La sagesse de nos ancêtres',
    count: () => FUN_ITEMS.filter(i => i.type === 'proverbe').length,
  },
  {
    id: 'poeme',
    label: 'Poèmes',
    emoji: '🌸',
    color: '#ec4899',
    bg: '#fdf2f8',
    gradient: 'linear-gradient(135deg, #ec489922, #f472b6aa)',
    desc: 'La beauté des mots en rimes',
    count: () => FUN_ITEMS.filter(i => i.type === 'poeme').length,
  },
  {
    id: 'conte',
    label: 'Contes',
    emoji: '🎭',
    color: '#06b6d4',
    bg: '#ecfeff',
    gradient: 'linear-gradient(135deg, #06b6d422, #22d3eeaa)',
    desc: 'Des histoires pleines de magie',
    count: () => FUN_ITEMS.filter(i => i.type === 'conte').length,
  },
  {
    id: 'fait',
    label: 'Le sais-tu ?',
    emoji: '🌍',
    color: '#10b981',
    bg: '#ecfdf5',
    gradient: 'linear-gradient(135deg, #10b98122, #34d399aa)',
    desc: 'Des faits incroyables sur le monde !',
    count: () => FUN_ITEMS.filter(i => i.type === 'fait').length,
  },
];
