import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade2Modules = [
  createModule({
    id: 'math-g2-numbers',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'numbers',
    domainLabel: 'Nombres',
    title: 'Compter, lire et construire',
    summary: 'Compter, lire, construire et comparer des nombres simples.',
    goal: 'Comprendre les dizaines et les unites avant de calculer.',
    demo: 'Une demonstration montre comment construire un nombre avec dizaines et unites.',
    guidedActivityIds: ['build-number', 'place-value'],
    independentActivityIds: ['generated-comparison-p2'],
    challengeActivityId: 'number-line',
    examActivityId: 'place-value',
    suggestedReviewIds: ['build-number']
  }),
  createModule({
    id: 'math-g2-addition',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'addition',
    domainLabel: 'Addition',
    title: 'Additions et bonds',
    summary: 'Additionner avec des nombres petits puis moyens.',
    goal: 'Passer du comptage a la reponse autonome.',
    demo: 'On montre d abord comment avancer sur une ligne numerique.',
    guidedActivityIds: ['generated-addition-p2', 'number-line'],
    independentActivityIds: ['generated-addition-p2'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'generated-addition-p2',
    suggestedReviewIds: ['number-line']
  }),
  createModule({
    id: 'math-g2-subtraction',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'subtraction',
    domainLabel: 'Soustraction',
    title: 'Soustraire et reculer',
    summary: 'Soustraire en reculant puis choisir la bonne operation.',
    goal: 'Rendre la soustraction claire et rassurante.',
    demo: 'Une demonstration montre comment compter en arriere pas a pas.',
    guidedActivityIds: ['generated-subtraction-p2', 'number-line'],
    independentActivityIds: ['generated-subtraction-p2'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'generated-subtraction-p2',
    suggestedReviewIds: ['number-line']
  }),
  createModule({
    id: 'math-g2-problems',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'problems',
    domainLabel: 'Problemes',
    title: 'Problemes simples du quotidien',
    summary: 'Lire une situation, choisir l operation et donner la bonne reponse.',
    goal: 'Relier les calculs a la vie de tous les jours.',
    demo: 'On isole d abord les nombres utiles avant de repondre.',
    guidedActivityIds: ['word-problems', 'generated-word-problems'],
    independentActivityIds: ['money-simple'],
    challengeActivityId: 'word-problems',
    examActivityId: 'generated-word-problems',
    suggestedReviewIds: ['generated-addition-p2']
  }),
  createModule({
    id: 'math-g2-multiplication',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'multiplication',
    domainLabel: 'Introduction a la multiplication',
    title: 'Les premiers paquets egaux',
    summary: 'Commencer avec la table du 2 puis reconnaitre des groupes egaux.',
    goal: 'Preparer la multiplication avant le travail plus rapide.',
    demo: 'Une demonstration montre comment la table avance de deux en deux.',
    guidedActivityIds: ['multiplication-table-2', 'multiplication-table-5'],
    independentActivityIds: ['multiplication-table-10'],
    challengeActivityId: 'multiplication-table-2',
    examActivityId: 'multiplication-table-5',
    suggestedReviewIds: ['multiplication-table-2']
  }),
  createModule({
    id: 'math-g2-money-time',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'money-time',
    domainLabel: 'Monnaie et heure',
    title: 'Payer et lire l heure',
    summary: 'Travailler la monnaie simple et les heures entieres.',
    goal: 'Donner des reperes pratiques pour la vie quotidienne.',
    demo: 'On montre d abord comment lire une somme puis une horloge simple.',
    guidedActivityIds: ['money-simple', 'read-time-p2'],
    independentActivityIds: ['money-simple'],
    challengeActivityId: 'read-time-p2',
    examActivityId: 'money-simple',
    suggestedReviewIds: ['read-time-p2']
  }),
  createModule({
    id: 'math-g2-geometry',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'geometry',
    domainLabel: 'Geometrie',
    title: 'Figures, symetrie et motifs',
    summary: 'Reconnaitre des formes, une symetrie simple et des suites.',
    goal: 'Observer, comparer et raisonner avec des images simples.',
    demo: 'Une demonstration montre comment reconnaitre une forme ou un axe de symetrie.',
    guidedActivityIds: ['shapes-symmetry-p2', 'generated-logic-sequences'],
    independentActivityIds: ['generated-comparison-p2'],
    challengeActivityId: 'shapes-symmetry-p2',
    examActivityId: 'generated-logic-sequences',
    suggestedReviewIds: ['shapes-symmetry-p2']
  })
];
