import { createModule } from '../../curriculum/moduleTemplate.js';

export const mathematicsGrade2Modules = [
  createModule({
    id: 'math-g2-place-value',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'place-value',
    domainLabel: 'Valeur positionnelle',
    title: 'Construire et lire les nombres',
    summary: 'Compter, lire et decomposer des nombres a deux chiffres.',
    goal: 'Comprendre dizaines et unites avant de comparer ou calculer.',
    demo: 'Une demonstration montre comment construire un nombre avec dizaines et unites.',
    guidedActivityIds: ['build-number', 'place-value'],
    independentActivityIds: ['generated-comparison-p2'],
    challengeActivityId: 'generated-classification-p2',
    examActivityId: 'place-value',
    suggestedReviewIds: ['build-number'],
    missionTitle: 'Mission nombres P2',
    missionSummary: 'Lire, construire et comparer des nombres simples.',
    levelTitles: {
      'build-number': 'Construire un nombre',
      'place-value': 'Lire dizaines et unites',
      'generated-comparison-p2': 'Comparer deux nombres',
      'generated-classification-p2': 'Classer des nombres'
    }
  }),
  createModule({
    id: 'math-g2-addition',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'addition',
    domainLabel: 'Additions',
    title: 'Ajouter et calculer mentalement',
    summary: 'Faire des additions simples et gagner en rapidite.',
    goal: 'Passer du comptage a des automatismes utiles.',
    demo: 'On montre d abord comment avancer sur une ligne numerique.',
    guidedActivityIds: ['generated-addition-p2', 'number-line'],
    independentActivityIds: ['generated-mental-math-p2'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'generated-addition-p2',
    suggestedReviewIds: ['number-line'],
    missionTitle: 'Mission additions P2',
    missionSummary: 'Addition, ligne numerique et calcul mental de base.'
  }),
  createModule({
    id: 'math-g2-subtraction',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'subtraction',
    domainLabel: 'Soustractions',
    title: 'Retirer, reculer et verifier',
    summary: 'Soustraire avec appui visuel puis choisir la bonne reponse.',
    goal: 'Rendre la soustraction lisible et rassurante.',
    demo: 'Une demonstration montre comment compter en arriere pas a pas.',
    guidedActivityIds: ['generated-subtraction-p2', 'number-line'],
    independentActivityIds: ['generated-mental-math-p2'],
    challengeActivityId: 'generated-word-problems',
    examActivityId: 'generated-subtraction-p2',
    suggestedReviewIds: ['number-line'],
    missionTitle: 'Mission soustractions P2',
    missionSummary: 'Reculer, verifier et comprendre ce que lon retire.'
  }),
  createModule({
    id: 'math-g2-patterns',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'patterns',
    domainLabel: 'Suites et motifs',
    title: 'Suites, motifs et classements',
    summary: 'Observer une regle, continuer une suite et classer.',
    goal: 'Developper une premiere logique mathematique.',
    demo: 'Une demonstration montre comment chercher la regle qui se repete.',
    guidedActivityIds: ['generated-patterns-p2', 'generated-logic-sequences'],
    independentActivityIds: ['generated-classification-p2'],
    challengeActivityId: 'shapes-symmetry-p2',
    examActivityId: 'generated-patterns-p2',
    suggestedReviewIds: ['generated-logic-sequences'],
    missionTitle: 'Mission suites P2',
    missionSummary: 'Chercher une regle simple, classer et continuer un motif.'
  }),
  createModule({
    id: 'math-g2-groups-sharing',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'multiplication-division',
    domainLabel: 'Groupes et partages',
    title: 'Groupes egaux et partages simples',
    summary: 'Decouvrir multiplication et division avec images mentales tres simples.',
    goal: 'Comprendre d abord les groupes egaux et les partages avant les automatismes.',
    demo: 'Une demonstration montre des paquets egaux puis un partage entre plusieurs enfants.',
    guidedActivityIds: ['generated-multiplication-p2', 'generated-division-p2'],
    independentActivityIds: ['multiplication-table-2'],
    challengeActivityId: 'word-problems',
    examActivityId: 'generated-division-p2',
    suggestedReviewIds: ['generated-multiplication-p2'],
    missionTitle: 'Mission groupes et partages P2',
    missionSummary: 'Observer des paquets egaux, partager et faire le lien avec les premieres tables.'
  }),
  createModule({
    id: 'math-g2-tables-foundations',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'tables-foundations',
    domainLabel: 'Tables de base',
    title: 'Tables 2 a 5',
    summary: 'Jouer les premieres tables de multiplication et de division utiles au primaire.',
    goal: 'Rendre visibles et jouables les premieres tables de facon progressive.',
    demo: 'Une demonstration montre comment une multiplication et sa division racontent la meme histoire.',
    guidedActivityIds: ['multiplication-table-2', 'multiplication-table-3', 'division-table-2'],
    independentActivityIds: ['multiplication-table-4', 'division-table-3'],
    challengeActivityId: 'multiplication-table-5',
    examActivityId: 'division-table-5',
    suggestedReviewIds: ['division-table-4'],
    missionTitle: 'Mission tables de base P2',
    missionSummary: 'Premieres tables pour multiplier et partager sans les cacher dans le catalogue.'
  }),
  createModule({
    id: 'math-g2-time-shapes',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'time-shapes',
    domainLabel: 'Heure et formes',
    title: 'Lire l heure et observer les figures',
    summary: 'Deux ateliers utiles du quotidien qui etaient jouables mais peu visibles.',
    goal: 'Faire exister heure, formes et symetrie dans le parcours principal.',
    demo: 'Une demonstration montre comment lire une heure simple puis reconnaitre une forme.',
    guidedActivityIds: ['read-time-p2', 'shapes-symmetry-p2'],
    independentActivityIds: ['money-simple'],
    challengeActivityId: 'read-time-p2',
    examActivityId: 'shapes-symmetry-p2',
    suggestedReviewIds: ['read-time-p2'],
    missionTitle: 'Mission heure et formes P2',
    missionSummary: 'Lire l heure, reconnaitre des figures et travailler la symetrie simple.'
  }),
  createModule({
    id: 'math-g2-problems',
    subjectId: 'mathematics',
    gradeId: 'P2',
    domainId: 'problems',
    domainLabel: 'Problemes',
    title: 'Petits problemes du quotidien',
    summary: 'Lire une situation courte et choisir l operation utile.',
    goal: 'Relier les calculs a la vie de tous les jours.',
    demo: 'On isole d abord les nombres utiles avant de repondre.',
    guidedActivityIds: ['word-problems', 'generated-word-problems'],
    independentActivityIds: ['money-simple'],
    challengeActivityId: 'money-simple',
    examActivityId: 'generated-word-problems',
    suggestedReviewIds: ['generated-addition-p2'],
    missionTitle: 'Mission problemes P2',
    missionSummary: 'Resoudre des situations simples avec addition, soustraction ou comparaison.'
  })
];
